import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function app(){
 const mem=new Map(),session=new Map(),saves=new Map(),handlers={};
 const storage=m=>({getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)});
 const ctx={window:{},localStorage:storage(mem),sessionStorage:storage(session),document:{addEventListener:(k,v)=>handlers[k]=v},location:{hash:''},Date,URL,Math,FormData:class{constructor(f){this.v=f.data||{};}forEach(cb){Object.entries(this.v).forEach(([k,v])=>cb(v,k));}}};
 const esc=x=>String(x??'').replaceAll('<','&lt;').replaceAll('"','&quot;');
 const ui={esc,read:(k,f,st)=>JSON.parse((st||ctx.localStorage).getItem(k)||'null')||f,write:(k,v,st)=>{(st||ctx.localStorage).setItem(k,JSON.stringify(v));return true;},section:(a,b)=>a+b,link:(a,b)=>`<a href="${b}">${a}</a>`,button:(a,b)=>`<button ${b}>${a}</button>`,input:(k,t)=>`<label>${t}<input name="${k}"/></label>`,select:(k,t,v)=>`<label>${t}<select name="${k}">${v.join('|')}</select></label>`,list:a=>a.join(' '),notice:t=>ctx.notice=t,ask:(s,x)=>{ctx.ai=x;return x;}};
 ctx.window.LivonServices={ui,all:()=>ctx.window.LivonLifeData.stages.flatMap(x=>x.services)};ctx.window.LivonPlatform={listSaves:()=>[...saves.values()],saveItem:x=>saves.set(x.id,x)};ctx.window.LivonTodayData={contents:[]};
 vm.createContext(ctx);for(const f of ['life-data.js','service-teen-data.js','service-tools.js','service-family-data.js','service-family.js'])vm.runInContext(readFileSync(new URL('../../livon/'+f,import.meta.url),'utf8'),ctx);
 const host={html:'',querySelector:()=>null,contains:()=>true};
 function open(n){const s=ctx.window.LivonServices.all().find(x=>x.id==='service-30-'+String(n).padStart(2,'0'));ctx.location.hash='#life-service-'+s.id;host.html=ctx.window.LivonFamily.render(s,[s.id]);ctx.window.LivonFamily.mount(s,host);return s;}
 return {ctx,mem,session,saves,handlers,host,open,T:ctx.window.LivonServiceTools,F:ctx.window.LivonFamily,D:ctx.window.LivonFamilyData};
}
test('all 15 stage-30 services have unique dedicated views, action CTAs, related links, existing storage',()=>{const a=app(),rows=a.ctx.window.LivonServices.all().filter(x=>x.lifeStage==='30');assert.equal(rows.length,15);for(let n=1;n<=15;n++){const s=a.open(n);assert.match(s.detail,/^family-/);assert.ok(!s.cta.includes('관련 서비스'));assert.match(a.host.html,/data-family-form/);assert.match(a.host.html,/함께 준비하면 좋은 서비스/);}assert.equal(rows[7].cta,'결혼 준비 시작하기');assert.equal(rows[8].cta,'가족 일정 관리하기');});
test('household calculator includes every group and handles deficit and zero income',()=>{const {T,D}=app(),b=T.budget({b0_0:'4000000',b0_1:'2000000',b1_0:'1000000',b2_0:'800000',b3_0:'500000',b3_1:'1000000'},D.budgetGroups);assert.equal(b.income,6000000);assert.equal(b.balance,2700000);assert.equal(b.saving,1500000);assert.equal(b.rate,25);assert.equal(T.budget({},D.budgetGroups).rate,null);assert.equal(T.budget({b1_0:100},D.budgetGroups).balance,-100);for(const v of [-1,'abc',Infinity,1e12])assert.throws(()=>T.budget({b0_0:v},D.budgetGroups));});
test('calendar validates data, bounds recurrence and handles month ends without overflow',()=>{const {T}=app(),v={title:'Fixture event',date:'2027-01-31',repeat:'매월',count:'3',members:'나, 배우자'};const rows=T.calendar(v,'fixture');assert.deepEqual(Array.from(rows,x=>x.date),['2027-01-31','2027-02-28','2027-03-31']);assert.equal(rows[0].familyMembers.length,2);assert.equal(T.calendar({...v,date:'2028-01-31'},'fixture')[1].date,'2028-02-29');assert.throws(()=>T.calendar({...v,count:13},'x'));assert.throws(()=>T.calendar({...v,title:''},'x'));assert.throws(()=>T.calendar({...v,date:'2026-02-30'},'x'));});
test('shared My Life upsert preserves unrelated records and updates rather than duplicates',()=>{const {T}=app(),s=T.read();s.events.push({id:'old',title:'Existing'});const rows=T.calendar({title:'Fixture',date:'2026-09-27',repeat:'매주',count:'2'},'family-test');for(let pass=0;pass<2;pass++)rows.forEach(x=>T.upsert(s.events,x));T.write(s);assert.equal(T.read().events.length,3);assert.equal(T.read().events.find(x=>x.id==='old').title,'Existing');});
test('shared bookmarks save and restore conditions using the existing service ID',()=>{const a=app(),s=a.open(1);a.T.save(s,{region:'서울',deposit:'1000000'});assert.equal(a.saves.size,1);assert.equal(a.saves.get('life-service:'+s.id).data.region,'서울');a.T.save(s,{region:'부산'});assert.equal(a.saves.size,1);a.session.clear();assert.equal(a.T.load(s).region,'부산');});
test('external source states and verification gate exclude fake or malformed records',()=>{const {T,D}=app();for(const f of Object.values(D.feeds)){assert.equal(T.source(f,{}).state,'notConnected');assert.equal(f.items.length,0);}const valid={id:'fixture',title:'Fixture',sourceUrl:'https://example.org/',lastVerifiedAt:'2026-09-27',region:'서울'};assert.equal(T.source({state:'ready',items:[valid,{...valid,id:'bad',sourceUrl:'javascript:alert(1)'}]},{region:'서울'}).items.length,1);assert.equal(T.source({state:'ready',items:[valid]},{region:'부산'}).state,'empty');assert.equal(T.source({state:'error',items:[]},{}).state,'error');});
test('checklist save preserves other checklists and repeated save produces one item',()=>{const a=app();a.mem.set('livon.mlStore.v1',JSON.stringify({checklists:[{id:'unrelated',items:[]}]}));const s=a.open(4);a.F.save();a.F.save();const store=JSON.parse(a.mem.get('livon.mlStore.v1'));assert.equal(store.checklists.length,2);assert.equal(store.checklists.find(x=>x.id==='service-checklist:'+s.id).items.length,6);});
test('finance AI includes only calculated real input and the no-fabrication instruction',()=>{const a=app(),s=a.ctx.window.LivonServices.all().find(x=>x.id==='service-30-07');a.T.save(s,{b0_0:'123000',b1_0:'23000'});a.open(7);a.F.ask();assert.match(a.ctx.ai,/123000/);assert.match(a.ctx.ai,/연결된 것으로 가정하지/);assert.equal(a.ctx.location.hash,'#life-service-service-30-07');});
