import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function app(){
 const mem=new Map(),saves=new Map(), handlers={}, ctx={window:{},localStorage:{getItem:k=>mem.get(k),setItem:(k,v)=>mem.set(k,v)},sessionStorage:{getItem:()=>null,setItem(){}},document:{addEventListener:(k,v)=>handlers[k]=v},location:{hash:'#life-service-service-10-07'},Date,URL,Math};
 const ui={esc:x=>String(x??'').replaceAll('<','&lt;'),read:(k,f)=>JSON.parse(mem.get(k)||'null')||f,write:(k,v)=>{mem.set(k,JSON.stringify(v));return true;},section:(a,b)=>a+b,link:(a,b)=>a+b,button:a=>a,input:(a,b)=>b,select:(a,b)=>b,notice(){},ask:(s,x)=>x};
 ctx.window.LivonServices={ui};ctx.window.LivonPlatform={listSaves:()=>[...saves.values()],saveItem:x=>saves.set(x.id,x)};
 vm.createContext(ctx);for(const f of ['life-data.js','opportunities-data.js','service-teen-data.js','service-teen.js'])vm.runInContext(readFileSync(new URL('../../livon/'+f,import.meta.url),'utf8'),ctx);
 return {...ctx,T:ctx.window.LivonTeen,O:ctx.window.LivonOpportunities,mem,saves};
}
const base=()=>({transactions:[{id:'existing',kind:'expense',date:'2026-09-26',amount:9999}],goals:[],events:[],teenAllowance:{months:{}}});
const row=(extra={})=>({id:'fixture-only',title:'TEST fixture',type:'experience',category:'과학 · 연구',source:'Test official source',sourceUrl:'https://example.org/program',lastVerifiedAt:'2026-09-26',targetAge:[13,18],targetGrade:['중학생'],region:'서울',district:'종로구',price:0,mode:'오프라인',startDate:'2026-10-02',endDate:'2026-10-03',status:'접수 중',...extra});
test('all 12 teen cards have dedicated details; remaining 6 have exact action labels',()=>{const a=app(),rows=a.window.LivonLifeData.stages.find(x=>x.id==='10').services;assert.equal(rows.length,12);assert.ok(rows.every(x=>x.detail!=='standard'));const labels=['직업 체험 찾기','공모전 찾기','활동 찾기','지역 프로그램 찾기','용돈 관리 시작하기','상담기관 찾기'];rows.slice(6).forEach((s,i)=>{assert.equal(s.cta,labels[i]);assert.ok(a.T.render(s,[s.id]).length>200);});});
test('shared opportunities are empty by default and reject unverified or adult-only data',()=>{const {O}=app();assert.equal(O.query({}).length,0);O.replace([row(),row({id:'bad',sourceUrl:'javascript:alert(1)'}),row({id:'missing',lastVerifiedAt:''}),row({id:'adult',targetAge:[20,30]})]);assert.equal(O.query({}).length,1);assert.equal(O.validDate('2026-02-30'),false);});
test('opportunity filters apply category, region, dates, age, grade, cost, type and mode',()=>{const {O}=app();O.replace([row()]);assert.equal(O.query({type:'experience',age:'15',grade:'중학생',date:'2026-10-03',cost:'무료',region:'서울',district:'종로구',mode:'오프라인'}).length,1);for(const f of [{type:'camp'},{age:'19'},{grade:'고등학생'},{date:'2026-10-04'},{cost:'유료'},{region:'부산'},{mode:'온라인'},{category:'IT · 개발'}])assert.equal(O.query(f).length,0);});
test('monthly income upsert prevents duplicates, expenses and goal compute without double counting savings',()=>{const {T}=app(),s=base(),now=new Date('2026-09-26T12:00:00');const income={month:'2026-09',regular:'100000',extra:'10000',other:'5000',saving:'20000'};T.applyMoney(s,'income',income,now);T.applyMoney(s,'income',income,now);assert.equal(s.transactions.length,4);T.applyMoney(s,'expense',{amount:'5000',category:'간식',date:'2026-09-26',memo:'test'},now);T.applyMoney(s,'goal',{title:'테스트 목표',target:'100000',saved:'50000',due:'2026-12-01'},now);T.applyMoney(s,'goal',{title:'테스트 목표 수정',target:'100000',saved:'60000',due:'2026-12-01'},now);const b=T.summary(s,'2026-09','2026-09-26');assert.equal(b.income,115000);assert.equal(b.spent,5000);assert.equal(b.remaining,90000);assert.equal(b.week,5000);assert.equal(b.top,'간식');assert.equal(s.goals.length,1);assert.equal(s.goals[0].progress,60);assert.equal(s.transactions.find(x=>x.id==='existing').amount,9999);});
test('money validation rejects invalid input without partial mutation',()=>{const {T}=app();for(const value of ['-1','NaN','0.5','100000001']){const s=base();assert.throws(()=>T.applyMoney(s,'income',{month:'2026-09',regular:'1000',extra:value},new Date()));assert.equal(s.transactions.length,1);}assert.throws(()=>T.applyMoney(base(),'expense',{amount:'1',category:'간식',date:'2099-01-01'},new Date()));});
test('weekly expenses span month boundary, ignore unrelated transactions, and month changes isolate income',()=>{const {T}=app(),s=base();T.applyMoney(s,'expense',{amount:'3000',category:'교통',date:'2026-08-31'},new Date('2026-09-01T12:00:00'));assert.equal(T.summary(s,'2026-09','2026-09-01').week,3000);assert.equal(T.summary(s,'2026-09','2026-09-01').spent,0);});
test('calendar upsert preserves existing events and uses competition deadline',()=>{const a=app();a.localStorage.setItem('livon.mlStore.v1',JSON.stringify({events:[{id:'existing'}]}));const x=row({type:'competition',applicationEnd:'2026-10-01'});a.T.addCalendar(x);a.T.addCalendar(x);const s=JSON.parse(a.mem.get('livon.mlStore.v1'));assert.equal(s.events.length,2);assert.equal(s.events[1].date,'2026-10-01');assert.equal(a.T.addCalendar(row({startDate:''})),false);});
test('missing item route recovers, official records render source, and no unverified item enters AI',()=>{const a=app(),s=a.window.LivonLifeData.stages[0].services.find(x=>x.id==='service-10-07');assert.match(a.T.render(s,[s.id,'item','missing']),/항목을 찾을 수 없습니다/);a.O.replace([row()]);assert.match(a.T.render(s,[s.id,'item','fixture-only']),/Test official source/);a.T.mount(s,{querySelector:()=>null});assert.match(a.T.ask(),/공식 출처에서 확인된 항목/);});
