window.LivonExploreData = {
  checkedAt: "2026-09-25",
  suggest: [
    "세무사", "이사", "영어 강사", "청소", "인테리어",
    "가족 상담", "원데이 클래스", "주거 서비스", "진로 상담", "도서관"
  ],
  regions: ["전국", "서울", "경기", "인천", "부산", "대구", "광주", "대전", "온라인"],
  categories: [
    { id: "experts", num: "01", title: "전문가", desc: "교육·진로·금융·법률·주거·가족·건강·취미 전문가", type: "expert" },
    { id: "services", num: "02", title: "생활 서비스", desc: "이사·청소·정리수납·수리·생활 지원", type: "service" },
    { id: "education", num: "03", title: "교육·클래스", desc: "직업교육·자격증·평생교육·취미 강좌", type: "program" },
    { id: "local", num: "04", title: "지역 생활", desc: "도서관·문화시설·공공·복지·지역 프로그램", type: "place" },
    { id: "housing", num: "05", title: "주거·공간", desc: "주거 정보·이사·인테리어·공간 관련 서비스", type: "service" },
    { id: "family", num: "06", title: "가족·돌봄", desc: "육아·가족 상담·복지·시니어 생활 지원", type: "service" },
    { id: "health", num: "07", title: "건강·웰니스", desc: "의료기관 정보·운동·심리·건강 프로그램", type: "service" },
    { id: "career", num: "08", title: "커리어·취업", desc: "취업 지원·직업교육·경력 개발·재취업", type: "expert" },
    { id: "leisure", num: "09", title: "취미·여가", desc: "원데이 클래스·문화·스포츠·지역 체험", type: "program" },
    { id: "products", num: "10", title: "생활 상품", desc: "가구·가전·생활용품 — 외부 판매처 연결", type: "product" }
  ],
  statusLabel: {
    link: "공식 연결",
    info: "정보 안내",
    guide: "가이드",
    partner_pending: "파트너 등록 예정"
  },
  items: [
    {
      id: "ex-career24",
      type: "expert",
      categoryIds: ["experts", "career"],
      subfield: "취업·커리어",
      title: "고용24 취업 지원",
      provider: "고용노동부 · 고용24",
      blurb: "구직·직업훈련·일자리 정보를 공식 포털에서 확인합니다.",
      body: "고용24는 구인구직, 직업훈련, 취업 지원 서비스를 제공하는 공식 포털입니다. LIVON은 개별 상담사 프로필을 임의로 만들지 않으며, 상담·신청은 공식 페이지에서 진행합니다.",
      img: "/livon/assets/topics/career.jpg",
      region: "전국",
      mode: "both",
      visit: false,
      priceType: "varies",
      priceLabel: "서비스별 상이 · 공식 안내 확인",
      audience: "구직자 · 이직 준비자 · 재취업",
      hours: "온라인 상시 · 센터별 상이",
      address: "",
      credentials: { status: "verified", note: "공공 고용서비스 포털" },
      officialUrl: "https://www.work24.go.kr/",
      source: "고용24",
      checkedAt: "2026-09-25",
      tags: ["취업", "이력서", "직업교육", "재취업"],
      layout: "expert",
      compare: { field: "취업 지원", range: "전국", mode: "온·오프라인", price: "서비스별", cred: "공공 포털" }
    },
    {
      id: "ex-qnet",
      type: "program",
      categoryIds: ["education", "career", "experts"],
      subfield: "자격증",
      title: "큐넷 국가기술자격 안내",
      provider: "한국산업인력공단",
      blurb: "국가기술자격 시험·일정·원서접수를 공식 사이트에서 확인합니다.",
      body: "자격 시험 일정·응시료·원서접수는 변경될 수 있습니다. LIVON에 표시된 정보는 안내이며, 실제 접수·결과는 큐넷에서 확인하세요.",
      img: "/livon/assets/topics/study.jpg",
      region: "전국",
      mode: "both",
      visit: false,
      priceType: "varies",
      priceLabel: "종목별 응시료 · 공식 확인",
      audience: "자격 취득 희망자",
      hours: "시험·접수 일정별",
      credentials: { status: "verified", note: "국가기술자격 공식" },
      officialUrl: "https://www.q-net.or.kr/",
      source: "큐넷",
      checkedAt: "2026-09-25",
      tags: ["자격증", "직업교육", "취업"],
      layout: "program",
      compare: { field: "자격 시험", range: "전국", mode: "온·오프라인", price: "종목별", cred: "국가자격" }
    },
    {
      id: "ex-hrdkorea",
      type: "program",
      categoryIds: ["education", "career"],
      subfield: "직업교육",
      title: "직업훈련 · HRD-Net",
      provider: "한국산업인력공단",
      blurb: "국민내일배움카드·직업훈련 과정을 공식 포털에서 검색합니다.",
      body: "훈련 과정·수강료·지원 조건은 과정별로 다릅니다. 허위 수강료나 임의 일정을 표시하지 않으며, 신청은 HRD-Net에서 진행합니다.",
      img: "/livon/assets/topics/career.jpg",
      region: "전국",
      mode: "both",
      visit: false,
      priceType: "varies",
      priceLabel: "과정·지원 대상별 상이",
      audience: "구직·재직·경력 전환",
      credentials: { status: "verified", note: "공공 직업훈련 포털" },
      officialUrl: "https://www.hrd.go.kr/",
      source: "HRD-Net",
      checkedAt: "2026-09-25",
      tags: ["직업교육", "내일배움카드", "경력 전환"],
      layout: "program",
      compare: { field: "직업훈련", range: "전국", mode: "온·오프라인", price: "지원 가능", cred: "공공" }
    },
    {
      id: "ex-nts",
      type: "expert",
      categoryIds: ["experts"],
      subfield: "금융·세무·법률",
      title: "국세청 홈택스 · 세무 안내",
      provider: "국세청",
      blurb: "세금 신고·증명·세무 상담 안내는 공식 홈택스에서 확인합니다.",
      body: "개인 세무사 프로필은 LIVON에 임의 등록되어 있지 않습니다. 세무 상담이 필요하면 홈택스 안내 또는 자격 확인된 세무사를 공식 경로로 찾아보세요. 미확인 자격을 검증된 것처럼 표시하지 않습니다.",
      img: "/livon/assets/topics/finance.jpg",
      region: "전국",
      mode: "online",
      visit: false,
      priceType: "free",
      priceLabel: "공공 안내 무료 · 개별 세무사 상담은 별도",
      audience: "납세자 일반",
      credentials: { status: "verified", note: "공공 세무 포털 · 개별 세무사 아님" },
      officialUrl: "https://www.hometax.go.kr/",
      source: "국세청 홈택스",
      checkedAt: "2026-09-25",
      tags: ["세무사", "세금", "재무"],
      layout: "expert",
      compare: { field: "세무 안내", range: "전국", mode: "온라인", price: "공공 무료", cred: "공공" }
    },
    {
      id: "ex-korea-bar",
      type: "guide",
      categoryIds: ["experts"],
      subfield: "금융·세무·법률",
      title: "대한변호사협회 변호사 검색 안내",
      provider: "대한변호사협회",
      blurb: "변호사 검색·법률 상담은 협회·공식 채널에서 확인합니다.",
      body: "법률 자문은 자격이 확인된 변호사에게 받아야 합니다. LIVON은 가짜 변호사 프로필을 만들지 않으며, 협회 공식 안내로 연결합니다.",
      img: "/livon/assets/topics/public-service.jpg",
      region: "전국",
      mode: "both",
      visit: false,
      priceType: "varies",
      priceLabel: "상담 비용은 변호사별 · 공식 확인",
      audience: "법률 상담이 필요한 경우",
      credentials: { status: "n/a", note: "개별 변호사 자격은 협회·공식 경로에서 확인" },
      officialUrl: "https://www.koreanbar.or.kr/",
      source: "대한변호사협회",
      checkedAt: "2026-09-25",
      tags: ["변호사", "법률"],
      layout: "expert",
      compare: { field: "법률 안내", range: "전국", mode: "온·오프라인", price: "개별", cred: "협회 안내" }
    },
    {
      id: "ex-molit-housing",
      type: "guide",
      categoryIds: ["housing", "services"],
      subfield: "주거 정보",
      title: "마이홈 포털 · 주거 지원 정보",
      layout: "benefit",
      eligibility: "무주택·소득 기준 등 공식 조건",
      benefitAmount: "지원·상품별 상이",
      applyPeriod: "공고·상시 병행",
      documents: "공고별 안내",
      applyHow: "마이홈·관련 기관 공식 신청",
      supportDetail: "공공임대·주거급여·청약 등 주거 지원 정보",
      provider: "국토교통부 · 마이홈",
      blurb: "공공임대·주거급여·청약 등 주거 지원 정보를 공식에서 확인합니다.",
      body: "실제 매물·가격 DB는 LIVON에 연결되어 있지 않습니다. 허위 매물·임의 시세를 표시하지 않으며, 신청·조회는 마이홈에서 진행합니다.",
      img: "/livon/assets/topics/housing.jpg",
      region: "전국",
      mode: "online",
      visit: false,
      priceType: "varies",
      priceLabel: "지원·상품별 상이 · 매물 미연동",
      audience: "무주택·주거 지원 대상",
      credentials: { status: "verified", note: "공공 주거 정보 포털" },
      officialUrl: "https://www.myhome.go.kr/",
      source: "마이홈",
      checkedAt: "2026-09-25",
      tags: ["주거", "이사", "독립", "임대"],
      layout: "service",
      compare: { field: "주거 지원", range: "전국", mode: "온라인", price: "지원별", cred: "공공" }
    },
    {
      id: "ex-khfc",
      type: "guide",
      categoryIds: ["housing"],
      subfield: "주거 정보",
      title: "주택금융공사 보금자리론 안내",
      provider: "한국주택금융공사",
      blurb: "주택 구입·전세 자금 관련 공식 상품 안내입니다.",
      body: "대출 한도·금리·자격은 상품·시점에 따라 달라집니다. LIVON은 확정 금리·한도를 임의로 표시하지 않습니다.",
      img: "/livon/assets/topics/finance.jpg",
      region: "전국",
      mode: "online",
      visit: false,
      priceType: "varies",
      priceLabel: "금리·한도 공식 확인",
      audience: "주택 구입·전세 준비",
      credentials: { status: "verified", note: "공공 금융기관 안내" },
      officialUrl: "https://www.hf.go.kr/",
      source: "한국주택금융공사",
      checkedAt: "2026-09-25",
      tags: ["주거", "금융", "독립"],
      layout: "service",
      compare: { field: "주택금융", range: "전국", mode: "온라인", price: "상품별", cred: "공공" }
    },
    {
      id: "ex-move-guide",
      type: "service",
      categoryIds: ["services", "housing"],
      subfield: "이사",
      title: "이사·입주 준비 가이드",
      provider: "LIVON 생활 가이드",
      blurb: "이사 체크리스트와 견적 비교 시 확인할 항목을 정리했습니다.",
      body: "이사업체 개별 견적·확정 가격은 연동되어 있지 않습니다. 견적은 작업 범위·거리·날짜에 따라 달라지므로 ‘확정 가격’처럼 표시하지 않습니다. 관심 업체를 저장하고 내 생활의 이사 프로젝트에 연결할 수 있습니다.",
      img: "/livon/assets/topics/moving.jpg",
      region: "전국",
      mode: "offline",
      visit: true,
      priceType: "quote",
      priceLabel: "견적 방식 · 업체별 상이",
      audience: "이사·독립 준비",
      credentials: { status: "n/a", note: "가이드 콘텐츠 · 개별 업체 미등록" },
      officialUrl: "",
      source: "LIVON",
      checkedAt: "2026-09-25",
      tags: ["이사", "청소", "주거", "독립"],
      layout: "service",
      compare: { field: "이사", range: "전국", mode: "방문", price: "견적", cred: "가이드" },
      links: { lifeNow: "#ml-panel", lifeGoto: "projects" }
    },
    {
      id: "ex-clean-guide",
      type: "service",
      categoryIds: ["services", "housing"],
      subfield: "청소",
      title: "입주·생활 청소 이용 가이드",
      provider: "LIVON 생활 가이드",
      blurb: "청소 범위·자재·시간 단위 견적 확인 포인트를 안내합니다.",
      body: "등록된 청소 업체가 아직 없습니다. 가짜 업체·가격을 표시하지 않으며, 관심 키워드를 저장해 두었다가 파트너 연동 후 이어갈 수 있습니다.",
      img: "/livon/assets/topics/cleaning.jpg",
      region: "전국",
      mode: "offline",
      visit: true,
      priceType: "quote",
      priceLabel: "견적 방식 · 면적·범위별",
      audience: "입주·정기 청소",
      credentials: { status: "n/a", note: "가이드 · 업체 미등록" },
      officialUrl: "",
      source: "LIVON",
      checkedAt: "2026-09-25",
      tags: ["청소", "이사", "주거"],
      layout: "service",
      compare: { field: "청소", range: "전국", mode: "방문", price: "견적", cred: "가이드" }
    },
    {
      id: "ex-nl",
      type: "place",
      categoryIds: ["local", "education", "leisure"],
      subfield: "도서관",
      title: "국립중앙도서관",
      provider: "국립중앙도서관",
      blurb: "열람·디지털 자료·문화 프로그램을 공식 안내에서 확인합니다.",
      body: "이용 조건·좌석·프로그램은 변경될 수 있습니다. 지도·길찾기는 공식 주소 기준으로 연결하며, 허위 핀을 표시하지 않습니다.",
      img: "/livon/assets/topics/library.jpg",
      region: "서울",
      mode: "offline",
      visit: false,
      priceType: "free",
      priceLabel: "기본 열람 무료 · 일부 유료",
      audience: "일반 · 연구 · 학습",
      hours: "관별·요일별 상이",
      address: "서울 서초구 반포대로 201",
      mapQuery: "국립중앙도서관",
      credentials: { status: "verified", note: "국립 도서관" },
      officialUrl: "https://www.nl.go.kr/",
      source: "국립중앙도서관",
      checkedAt: "2026-09-25",
      tags: ["도서관", "교육", "지역 생활"],
      layout: "place",
      compare: { field: "도서관", range: "서울", mode: "오프라인", price: "무료~", cred: "공공" }
    },
    {
      id: "ex-mmca",
      type: "place",
      categoryIds: ["local", "leisure", "education"],
      subfield: "박물관·미술관",
      title: "국립현대미술관",
      provider: "국립현대미술관",
      blurb: "전시·교육·관람 안내는 관별 공식 사이트에서 확인합니다.",
      body: "현재 전시·입장료·예약 여부는 공식 사이트 기준입니다. 임의 전시 일정·가격을 고정 표시하지 않습니다.",
      img: "/livon/assets/topics/museum.jpg",
      region: "서울",
      mode: "offline",
      visit: false,
      priceType: "varies",
      priceLabel: "전시·프로그램별 상이",
      audience: "일반 · 가족 · 학생",
      hours: "관별 상이",
      address: "관별 상이 (공식 안내)",
      mapQuery: "국립현대미술관 서울",
      credentials: { status: "verified", note: "국립 미술관" },
      officialUrl: "https://www.mmca.go.kr/",
      source: "국립현대미술관",
      checkedAt: "2026-09-25",
      tags: ["전시", "문화", "여가"],
      layout: "place",
      compare: { field: "미술관", range: "서울", mode: "오프라인", price: "전시별", cred: "공공" }
    },
    {
      id: "ex-seoul-library",
      type: "place",
      categoryIds: ["local"],
      subfield: "도서관",
      title: "서울도서관",
      provider: "서울특별시",
      blurb: "시민 도서관 이용·행사 정보를 공식에서 확인합니다.",
      body: "운영 시간·휴관일은 변경될 수 있습니다. 위치는 공식 안내의 주소를 기준으로 합니다.",
      img: "/livon/assets/topics/library.jpg",
      region: "서울",
      mode: "offline",
      visit: false,
      priceType: "free",
      priceLabel: "기본 이용 무료",
      audience: "서울 시민 · 방문자",
      hours: "요일별 상이",
      address: "서울 중구 세종대로 110",
      mapQuery: "서울도서관",
      credentials: { status: "verified", note: "시립 도서관" },
      officialUrl: "https://lib.seoul.go.kr/",
      source: "서울도서관",
      checkedAt: "2026-09-25",
      tags: ["도서관", "지역 생활"],
      layout: "place",
      compare: { field: "도서관", range: "서울", mode: "오프라인", price: "무료", cred: "공공" }
    },
    {
      id: "ex-lifelong",
      type: "program",
      categoryIds: ["education", "leisure", "career"],
      subfield: "평생교육",
      title: "국가평생교육진흥원 · 평생교육 안내",
      provider: "국가평생교육진흥원",
      blurb: "평생학습·성인 문해·학점은행 등 공식 안내입니다.",
      body: "개별 강좌 수강료·일정을 임의로 나열하지 않습니다. 과정 검색·신청은 공식 포털에서 확인하세요.",
      img: "/livon/assets/topics/study.jpg",
      region: "전국",
      mode: "both",
      visit: false,
      priceType: "varies",
      priceLabel: "과정별 상이",
      audience: "성인 · 시니어 · 재학습",
      credentials: { status: "verified", note: "공공 평생교육" },
      officialUrl: "https://www.nile.or.kr/",
      source: "국가평생교육진흥원",
      checkedAt: "2026-09-25",
      tags: ["평생교육", "시니어", "취미", "디지털 교육"],
      layout: "program",
      compare: { field: "평생교육", range: "전국", mode: "온·오프라인", price: "과정별", cred: "공공" }
    },
    {
      id: "ex-allilearn",
      type: "program",
      categoryIds: ["education", "leisure"],
      subfield: "평생교육",
      title: "늘배움 포털",
      provider: "국가평생교육진흥원",
      blurb: "지역·온라인 평생학습 강좌를 공식에서 검색합니다.",
      body: "강좌 정보·신청은 늘배움에서 확인합니다. LIVON에 없는 강좌를 가짜로 생성하지 않습니다.",
      img: "/livon/assets/topics/study.jpg",
      region: "전국",
      mode: "both",
      visit: false,
      priceType: "varies",
      priceLabel: "강좌별 · 공식 확인",
      audience: "일반 · 시니어",
      credentials: { status: "verified", note: "공공 학습 포털" },
      officialUrl: "https://www.lifelongedu.go.kr/",
      source: "늘배움",
      checkedAt: "2026-09-25",
      tags: ["원데이 클래스", "취미", "평생교육", "외국어"],
      layout: "program",
      compare: { field: "학습 강좌", range: "전국", mode: "온·오프라인", price: "강좌별", cred: "공공" }
    },
    {
      id: "ex-bokjiro",
      type: "service",
      categoryIds: ["family", "health", "services"],
      subfield: "복지",
      title: "복지로 · 복지 서비스 안내",
      layout: "benefit",
      eligibility: "가구·소득·생애주기 등 공식 조건",
      benefitAmount: "서비스별 상이",
      applyPeriod: "상시·제도별",
      documents: "신분증·소득·가족관계 등 제도별",
      applyHow: "복지로에서 자격 확인 후 신청",
      supportDetail: "생애주기별 복지 혜택·신청 안내",
      provider: "보건복지부 · 복지로",
      blurb: "생애주기별 복지 혜택·신청 안내를 공식에서 확인합니다.",
      body: "자격·신청은 개인 상황에 따라 다릅니다. LIVON은 수급을 보장하지 않으며, 조회·신청은 복지로에서 진행합니다.",
      img: "/livon/assets/topics/family.jpg",
      region: "전국",
      mode: "online",
      visit: false,
      priceType: "free",
      priceLabel: "공공 안내 무료",
      audience: "가족 · 육아 · 시니어 · 저소득 등",
      credentials: { status: "verified", note: "공공 복지 포털" },
      officialUrl: "https://www.bokjiro.go.kr/",
      source: "복지로",
      checkedAt: "2026-09-25",
      tags: ["가족", "육아", "돌봄", "복지"],
      layout: "service",
      compare: { field: "복지 안내", range: "전국", mode: "온라인", price: "공공", cred: "공공" }
    },
    {
      id: "ex-childcare",
      type: "service",
      categoryIds: ["family"],
      subfield: "육아",
      title: "아이사랑 · 보육 정보",
      provider: "보건복지부 · 아이사랑",
      blurb: "어린이집·보육료 지원 등 공식 보육 정보입니다.",
      body: "개별 어린이집 평가·대기 현황은 공식 서비스에서 확인하세요. 허위 후기·임의 대기 정보를 표시하지 않습니다.",
      img: "/livon/assets/topics/childcare.jpg",
      region: "전국",
      mode: "both",
      visit: false,
      priceType: "varies",
      priceLabel: "지원·시설별 상이",
      audience: "영유아 가구",
      credentials: { status: "verified", note: "공공 보육 정보" },
      officialUrl: "https://www.childcare.go.kr/",
      source: "아이사랑",
      checkedAt: "2026-09-25",
      tags: ["육아", "가족", "돌봄"],
      layout: "service",
      compare: { field: "보육", range: "전국", mode: "온·오프라인", price: "지원별", cred: "공공" }
    },
    {
      id: "ex-ongil",
      type: "service",
      categoryIds: ["family", "health", "services"],
      subfield: "시니어 돌봄",
      title: "Ongil · 시니어 생활·돌봄",
      provider: "Newon · Ongil",
      blurb: "시니어 생활·돌봄 특화 서비스는 Ongil에서 확인합니다.",
      body: "LIVON과 Ongil은 역할이 다릅니다. 데이터가 자동 공유되는 것처럼 표시하지 않으며, 전문 돌봄은 Ongil로 연결합니다.",
      img: "/livon/assets/topics/senior.jpg",
      region: "전국",
      mode: "both",
      visit: true,
      priceType: "varies",
      priceLabel: "서비스별 · Ongil 안내",
      audience: "시니어 · 가족 돌봄",
      credentials: { status: "verified", note: "Newon Ongil 서비스" },
      officialUrl: "/ongil-start/#care",
      source: "Ongil",
      checkedAt: "2026-09-25",
      tags: ["시니어", "돌봄", "가족"],
      layout: "service",
      compare: { field: "시니어 돌봄", range: "전국", mode: "온·오프라인", price: "서비스별", cred: "Ongil" }
    },
    {
      id: "ex-nhis",
      type: "guide",
      categoryIds: ["health"],
      subfield: "의료기관 정보",
      title: "국민건강보험 · 건강검진 안내",
      provider: "국민건강보험공단",
      blurb: "건강검진·의료비 관련 공식 안내입니다.",
      body: "의료 진단·치료 효과를 보장하지 않습니다. 병원 예약·검진 일정은 공식·의료기관에서 확인하세요.",
      img: "/livon/assets/topics/fitness.jpg",
      region: "전국",
      mode: "both",
      visit: false,
      priceType: "varies",
      priceLabel: "검진·급여 기준 공식 확인",
      audience: "건강보험 가입자",
      credentials: { status: "verified", note: "공공 건강보험" },
      officialUrl: "https://www.nhis.or.kr/",
      source: "국민건강보험공단",
      checkedAt: "2026-09-25",
      tags: ["건강검진", "의료", "건강"],
      layout: "service",
      compare: { field: "건강검진", range: "전국", mode: "온·오프라인", price: "급여별", cred: "공공" }
    },
    {
      id: "ex-nimh",
      type: "guide",
      categoryIds: ["health", "experts"],
      subfield: "심리상담",
      title: "정신건강 상담 · 공식 안내",
      provider: "보건복지부 · 정신건강사업",
      blurb: "정신건강 상담·위기 대응 안내는 공식 채널을 우선합니다.",
      body: "미확인 상담사 프로필을 검증된 것처럼 표시하지 않습니다. 응급 상황에서는 지역 정신건강복지센터·응급 전화를 이용하세요.",
      img: "/livon/assets/topics/fitness.jpg",
      region: "전국",
      mode: "both",
      visit: false,
      priceType: "varies",
      priceLabel: "기관·상담별 상이",
      audience: "심리·정신건강 지원이 필요한 경우",
      credentials: { status: "n/a", note: "공공 안내 · 개별 상담사 미등록" },
      officialUrl: "https://www.mentalhealth.go.kr/",
      source: "정신건강사업",
      checkedAt: "2026-09-25",
      tags: ["심리 상담", "건강", "가족"],
      layout: "expert",
      compare: { field: "심리 안내", range: "전국", mode: "온·오프라인", price: "기관별", cred: "공공 안내" }
    },
    {
      id: "ex-sports",
      type: "place",
      categoryIds: ["health", "leisure", "local"],
      subfield: "운동시설",
      title: "국민체육진흥공단 · 스포츠 정보",
      provider: "국민체육진흥공단",
      blurb: "생활체육·시설·프로그램 정보를 공식에서 확인합니다.",
      body: "개별 헬스장·강사 예약은 연동되어 있지 않습니다. 시설·프로그램은 공식 안내를 기준으로 합니다.",
      img: "/livon/assets/topics/fitness.jpg",
      region: "전국",
      mode: "both",
      visit: false,
      priceType: "varies",
      priceLabel: "시설·프로그램별",
      audience: "운동 · 생활체육",
      credentials: { status: "verified", note: "공공 체육 기관" },
      officialUrl: "https://www.kspo.or.kr/",
      source: "국민체육진흥공단",
      checkedAt: "2026-09-25",
      tags: ["운동", "건강", "스포츠"],
      layout: "place",
      compare: { field: "생활체육", range: "전국", mode: "온·오프라인", price: "시설별", cred: "공공" }
    },
    {
      id: "ex-youth",
      type: "guide",
      categoryIds: ["career", "education", "experts"],
      subfield: "진로 상담",
      title: "온통청년 · 청년 정책 포털",
      provider: "국무조정실 · 온통청년",
      blurb: "청년 일자리·주거·교육·생활 정책을 공식에서 검색합니다.",
      body: "자격·신청 기간은 정책별로 다릅니다. 허위 혜택을 보장하지 않습니다.",
      img: "/livon/assets/topics/twenties.jpg",
      region: "전국",
      mode: "online",
      visit: false,
      priceType: "free",
      priceLabel: "공공 안내 무료",
      audience: "청년",
      credentials: { status: "verified", note: "공공 청년 정책" },
      officialUrl: "https://www.youthcenter.go.kr/",
      source: "온통청년",
      checkedAt: "2026-09-25",
      tags: ["진로", "취업", "주거", "청년"],
      layout: "expert",
      compare: { field: "청년 정책", range: "전국", mode: "온라인", price: "공공", cred: "공공" }
    },
    {
      id: "ex-worknet-job",
      type: "program",
      categoryIds: ["career", "education"],
      subfield: "재취업",
      title: "직업심리검사 · 진로 안내",
      provider: "고용24 / 워크넷 연계 안내",
      blurb: "진로·적성 검사는 공식 고용 서비스에서 이용합니다.",
      body: "검사 결과 해석은 참고용이며, 개별 전문가 상담과는 구분됩니다.",
      img: "/livon/assets/topics/career.jpg",
      region: "전국",
      mode: "online",
      visit: false,
      priceType: "free",
      priceLabel: "공공 서비스 · 공식 확인",
      audience: "진로·이직 준비",
      credentials: { status: "verified", note: "공공 고용서비스" },
      officialUrl: "https://www.work24.go.kr/",
      source: "고용24",
      checkedAt: "2026-09-25",
      tags: ["진로 상담", "취업", "적성"],
      layout: "program",
      compare: { field: "진로 검사", range: "전국", mode: "온라인", price: "공공", cred: "공공" }
    },
    {
      id: "ex-culture",
      type: "place",
      categoryIds: ["leisure", "local"],
      subfield: "문화시설",
      title: "문화포털 · 공연·전시 정보",
      provider: "문화체육관광부 · 문화포털",
      blurb: "공연·전시·축제 정보를 공식 문화포털에서 확인합니다.",
      body: "개별 티켓 재고·가격은 LIVON에 연동되지 않습니다. 예매는 공식·주최 측에서 진행하세요.",
      img: "/livon/assets/topics/museum.jpg",
      region: "전국",
      mode: "both",
      visit: false,
      priceType: "varies",
      priceLabel: "행사별 · 공식 예매",
      audience: "일반 · 가족",
      credentials: { status: "verified", note: "공공 문화 정보" },
      officialUrl: "https://www.culture.go.kr/",
      source: "문화포털",
      checkedAt: "2026-09-25",
      tags: ["공연", "전시", "여가", "여행"],
      layout: "place",
      compare: { field: "문화 정보", range: "전국", mode: "온·오프라인", price: "행사별", cred: "공공" }
    },
    {
      id: "ex-tour",
      type: "place",
      categoryIds: ["leisure", "local"],
      subfield: "여행 프로그램",
      title: "대한민국 구석구석",
      provider: "한국관광공사",
      blurb: "지역 여행·체험 코스를 공식 관광 정보에서 확인합니다.",
      body: "숙박·입장료는 시점별로 달라집니다. 임의 패키지 가격을 표시하지 않습니다.",
      img: "/livon/assets/topics/travel.jpg",
      region: "전국",
      mode: "offline",
      visit: false,
      priceType: "varies",
      priceLabel: "여행지·시즌별",
      audience: "여행 · 가족 · 혼자",
      credentials: { status: "verified", note: "공공 관광 정보" },
      officialUrl: "https://korean.visitkorea.or.kr/",
      source: "한국관광공사",
      checkedAt: "2026-09-25",
      tags: ["여행", "여가", "지역"],
      layout: "place",
      compare: { field: "여행 정보", range: "전국", mode: "오프라인", price: "시즌별", cred: "공공" }
    },
    {
      id: "ex-product-guide",
      type: "product",
      categoryIds: ["products", "housing"],
      subfield: "가구",
      title: "생활 상품 · 외부 판매처 연결 안내",
      provider: "LIVON",
      blurb: "가구·가전·생활용품은 확인된 외부 판매처로 연결합니다.",
      body: "직접 결제·배송·재고 시스템이 없습니다. 허위 가격·재고를 표시하지 않으며, 구매는 판매처에서 진행합니다.",
      img: "/livon/assets/topics/declutter.jpg",
      region: "온라인",
      mode: "online",
      visit: false,
      priceType: "external",
      priceLabel: "판매처에서 확인 · 확인일 기준 미연동",
      audience: "자취·주거·생활",
      credentials: { status: "n/a", note: "상품 DB 미연동" },
      officialUrl: "",
      source: "LIVON",
      checkedAt: "2026-09-25",
      tags: ["가구", "가전", "생활용품"],
      layout: "product",
      compare: { field: "생활 상품", range: "온라인", mode: "온라인", price: "외부", cred: "미연동" }
    },
    {
      id: "ex-interior-guide",
      type: "service",
      categoryIds: ["housing", "services", "experts"],
      subfield: "인테리어",
      title: "인테리어·정리수납 준비 가이드",
      provider: "LIVON 생활 가이드",
      blurb: "견적·계약 시 확인할 범위·일정·자재 포인트를 정리했습니다.",
      body: "등록된 인테리어 업체·공인중개사 개인 프로필은 아직 없습니다. 파트너 검수 후 등록될 예정입니다.",
      img: "/livon/assets/topics/declutter.jpg",
      region: "전국",
      mode: "offline",
      visit: true,
      priceType: "quote",
      priceLabel: "견적 방식",
      audience: "이사·리모델링",
      credentials: { status: "n/a", note: "가이드 · 업체 미등록" },
      officialUrl: "",
      source: "LIVON",
      checkedAt: "2026-09-25",
      tags: ["인테리어", "정리수납", "주거"],
      layout: "service",
      compare: { field: "인테리어", range: "전국", mode: "방문", price: "견적", cred: "가이드" }
    },
    {
      id: "ex-senior-job",
      type: "program",
      categoryIds: ["career", "family"],
      subfield: "시니어 일자리",
      title: "노인일자리 · 시니어 취업 안내",
      provider: "한국노인인력개발원 연계 안내",
      blurb: "시니어 일자리·사회활동 지원 정보를 공식 경로로 안내합니다.",
      body: "개별 일자리 매칭 결과를 임의로 표시하지 않습니다. 신청·상담은 공식·지자체 창구를 이용하세요.",
      img: "/livon/assets/topics/senior.jpg",
      region: "전국",
      mode: "both",
      visit: false,
      priceType: "free",
      priceLabel: "공공 안내",
      audience: "시니어 · 재취업",
      credentials: { status: "verified", note: "공공 시니어 일자리 안내" },
      officialUrl: "https://www.kordi.or.kr/",
      source: "한국노인인력개발원",
      checkedAt: "2026-09-25",
      tags: ["시니어", "재취업", "일자리"],
      layout: "program",
      compare: { field: "시니어 일자리", range: "전국", mode: "온·오프라인", price: "공공", cred: "공공" }
    },
    {
      id: "ex-english-guide",
      type: "guide",
      categoryIds: ["education", "experts", "leisure"],
      subfield: "외국어",
      title: "외국어·영어 학습 탐색 가이드",
      provider: "LIVON",
      blurb: "영어 강사·학원·온라인 클래스 선택 시 확인할 기준을 안내합니다.",
      body: "개별 영어 강사 프로필·수강료는 등록되어 있지 않습니다. ‘영어 강사’ 검색 시 관련 교육 포털·가이드를 보여 드립니다.",
      img: "/livon/assets/topics/study.jpg",
      region: "전국",
      mode: "both",
      visit: false,
      priceType: "varies",
      priceLabel: "강사·기관별 · 미연동",
      audience: "외국어 학습",
      credentials: { status: "n/a", note: "가이드 · 강사 미등록" },
      officialUrl: "https://www.lifelongedu.go.kr/",
      source: "LIVON / 늘배움 연결",
      checkedAt: "2026-09-25",
      tags: ["영어 강사", "외국어", "교육"],
      layout: "program",
      compare: { field: "외국어", range: "전국", mode: "온·오프라인", price: "미연동", cred: "가이드" }
    }
  ]
};
