/*
 * LIVON Help content — structured data only (no markup, no DOM). Rendered by help-page.js.
 *
 * Help describes what LIVON does TODAY. `facts` holds every number and connection state the articles rely on;
 * tests/livon/help.test.mjs compares each fact with the code, so a feature change makes the tests fail until the
 * Help is updated. Article text refers to numbers through {lifeStages} · {topics} · {postTypes} · {lifeEvents}.
 *
 * article: { id (stable, used in links: #help/a/{id}), cat, title, short, body[], steps[], note, related[], feature[label, href],
 *            kw[], v (CODE_VERIFIED | DOC_VERIFIED | PRODUCT_POLICY — internal, never shown), hf (source inventory id), popular,
 *            ts { symptom, causes[], fixes[] } for troubleshooting }
 * Support: there is no inquiry, ticket or e-mail backend. Help content is bundled with the page and works offline.
 */
(function (root) {
  "use strict";

  var facts = {
    lifeStages: 7, topics: 228, postTypes: 6, lifeEvents: 34,
    account: "NOT_CONNECTED",            /* no sign-up, no login, no NEWON+ link */
    sync: "NOT_CONNECTED",               /* nothing is synced between devices */
    personalization: "LOCAL_RULE_BASED", /* rules in the browser, no AI */
    communityPosts: "LOCAL",             /* posts exist only in the browser that wrote them */
    follow: "ACCOUNT_REQUIRED",          /* following needs accounts: not available */
    reports: "LOCAL_ONLY",               /* a report is a record in this browser, not sent anywhere */
    ai: "NOT_CONNECTED",                 /* no AI server is configured for this site (livon-api-config.js) */
    liveData: "NOT_CONNECTED",           /* the source default: no data server origin. A build that sets LIVON_API_ORIGIN may
                                            receive public data; help-page.js then reports what this browser actually received */
    support: "NOT_CONNECTED",            /* no inquiry / ticket backend */
    help: "READY"
  };

  var categories = [
    { id: "start", label: "시작하기", desc: "회원가입 없이 쓰는 방법과 LIVON의 구성" },
    { id: "data", label: "저장·데이터", desc: "내 정보가 어디에 있고, 언제 사라질 수 있는지" },
    { id: "personalization", label: "맞춤 설정", desc: "연령대·관심 분야·Life Event와 추천" },
    { id: "life-stage", label: "라이프 스테이지", desc: "연령대별 주제와 Life Event" },
    { id: "today", label: "오늘의 발견", desc: "오늘 볼 만한 정보와 맞춤 순서" },
    { id: "my-life", label: "내 생활", desc: "저장, 할 일, 목표, 기록" },
    { id: "explore", label: "탐색·검색", desc: "찾는 방법과 공식 출처 표시" },
    { id: "community", label: "커뮤니티", desc: "글, 댓글, 신고, 팔로잉" },
    { id: "ai", label: "LIVON AI", desc: "연결 상태와 정보 사용 방식" },
    { id: "troubleshooting", label: "문제 해결", desc: "증상별로 이유와 해결 방법 확인" }
  ];

  var articles = [
    /* ───────── 시작하기 ───────── */
    { id: "no-signup", cat: "start", hf: "HF-1", popular: true, v: "CODE_VERIFIED",
      title: "회원가입 없이 왜 쓸 수 있나요?",
      short: "LIVON은 지금 계정 없이 쓰는 서비스예요. 고른 설정과 저장한 내용은 서버가 아니라 이 브라우저에 보관돼요.",
      body: ["가입이나 로그인 절차가 없고, 이름·연락처 같은 개인정보도 묻지 않아요.", "대신 저장한 내용은 지금 쓰는 기기의 이 브라우저에만 있어요. 다른 기기에서는 보이지 않고, 브라우저 데이터를 지우면 함께 사라질 수 있어요."],
      related: ["local-data-storage", "account-status", "other-device"], feature: ["LIVON 홈", "#livon-home"],
      kw: ["가입", "로그인", "계정", "익명", "무료", "아이디", "비밀번호"] },
    { id: "what-is-livon", cat: "start", v: "CODE_VERIFIED",
      title: "LIVON은 어떤 서비스인가요?",
      short: "삶의 단계와 상황에 맞는 정보·서비스·할 일을 한곳에서 찾고 관리하는 서비스예요.",
      body: ["메뉴는 일곱 가지예요. 홈, 라이프 스테이지(연령대별 주제), 오늘의 발견(오늘 볼 만한 정보), 내 생활(저장·할 일·목표·기록), 탐색(검색과 분야별 찾기), 커뮤니티(글과 댓글), LIVON AI예요.", "어느 메뉴든 가입 없이 바로 쓸 수 있어요. 맞춤 설정을 하지 않아도 모든 메뉴가 열려 있어요."],
      related: ["no-signup", "what-is-life-stage", "what-is-my-life"], feature: ["LIVON 홈", "#livon-home"],
      kw: ["소개", "메뉴", "기능", "무엇", "서비스"] },
    { id: "account-status", cat: "start", v: "CODE_VERIFIED",
      title: "로그인이나 NEWON+ 계정은 쓸 수 있나요?",
      short: "아직 쓸 수 없어요. 지금 LIVON에는 로그인도, NEWON+ 계정 연결도 없어요.",
      body: ["그래서 계정으로 내용을 불러오거나 여러 기기에서 같은 내용을 보는 기능도 없어요.", "계정 기능이 언제 열릴지는 정해진 바가 없어요. 열리더라도 이 기기의 내용이 사용자 동의 없이 서버로 올라가지는 않아요."],
      related: ["no-signup", "other-device", "future-account"], feature: ["서비스 상태", "#help/status"],
      kw: ["로그인", "계정", "NEWON+", "뉴온", "회원가입", "동기화", "아이디", "비밀번호", "로그아웃", "login", "account"] },
    { id: "contact-support", cat: "start", v: "CODE_VERIFIED",
      title: "문의는 어디로 보내나요?",
      short: "지금은 LIVON 안에서 문의를 보내는 기능이 없어요. 문의 접수 창구가 아직 연결되지 않았어요.",
      body: ["이 도움말은 기기 안에 들어 있는 안내라서, 검색하거나 읽은 내용이 어디로도 전송되지 않아요.", "궁금한 점은 도움말 검색과 문제 해결에서 먼저 찾아 주세요. 문의 기능이 생기면 이 자리에 안내할게요."],
      related: ["ts-search-no-result", "community-report", "no-signup"], feature: ["문제 해결", "#help/c/troubleshooting"],
      kw: ["문의", "고객센터", "연락", "상담", "이메일", "전화", "지원", "티켓", "support"] },

    /* ───────── 저장·데이터 ───────── */
    { id: "local-data-storage", cat: "data", hf: "HF-2", popular: true, v: "CODE_VERIFIED",
      title: "내 정보는 어디에 저장되나요?",
      short: "지금 쓰는 기기의 이 브라우저 안에 저장돼요. LIVON 서버에는 저장되지 않아요.",
      body: ["맞춤 설정, 저장한 항목, 할 일·목표·기록, 커뮤니티 글과 댓글, LIVON AI 대화 기록이 모두 여기에 해당해요.", "같은 기기라도 다른 브라우저(예: 크롬과 사파리)는 저장 공간이 달라서 서로 보이지 않아요. 시크릿·사생활 보호 창은 창을 닫으면 내용이 지워져요."],
      related: ["what-is-stored", "other-device", "clear-browser-data"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["저장", "위치", "기기", "브라우저", "서버", "보관", "어디", "localStorage", "데이터"] },
    { id: "what-is-stored", cat: "data", v: "CODE_VERIFIED",
      title: "이 기기에 저장되는 것과 서버에 저장되지 않는 것",
      short: "LIVON에서 직접 고르거나 쓴 내용은 전부 이 브라우저에 있고, 서버에는 아무것도 보관하지 않아요.",
      body: ["이 브라우저에 저장되는 것: 맞춤 설정(연령대·관심 분야·Life Event), 저장한 항목, 내 생활의 일정·할 일·목표·기록, 체크리스트 진행 상태, 커뮤니티 글·댓글·공감·신고 기록, 최근 본 항목, LIVON AI 대화 기록.", "서버에 저장되지 않는 것: 위의 모든 내용. LIVON은 지금 사용자 정보를 받아 두는 서버가 없어요.", "보내는 경우는 두 가지예요. LIVON AI가 연결된 환경에서 질문을 보내면, 그 질문과 함께 보낸 내용은 답변을 만들기 위해 AI 서버로 전달돼요.", "데이터 서버가 연결된 환경에서 탐색으로 장소나 훈련 과정을 검색하면, 검색어가 그 정보를 받아 오기 위해 데이터 서버로 전달돼요. ‘내 위치 기준으로 찾기’를 눌렀을 때만 약 100m 단위로 줄인 위치가 함께 가고, 저장되지 않아요."],
      related: ["local-data-storage", "ai-what-it-uses", "clear-browser-data"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["저장", "서버", "목록", "무엇", "개인정보", "수집", "데이터"] },
    { id: "other-device", cat: "data", hf: "HF-3", popular: true, v: "CODE_VERIFIED",
      title: "다른 기기에서는 왜 안 보이나요?",
      short: "내용이 기기마다 따로 저장되고, 기기 사이에 옮겨 주는 동기화가 없기 때문이에요.",
      body: ["휴대폰에서 저장한 내용은 휴대폰의 그 브라우저에만 있어요. 컴퓨터에서 열면 처음 쓰는 상태로 보여요.", "계정이 없어서 자동으로 맞춰 주는 방법이 지금은 없어요."],
      related: ["local-data-storage", "move-device", "account-status"], feature: ["서비스 상태", "#help/status"],
      kw: ["다른 기기", "휴대폰", "컴퓨터", "PC", "동기화", "연동", "안 보여", "태블릿"] },
    { id: "clear-browser-data", cat: "data", hf: "HF-4", popular: true, v: "CODE_VERIFIED",
      title: "브라우저 기록을 지우면 어떻게 되나요?",
      short: "‘쿠키 및 사이트 데이터’를 지우면 LIVON에 저장한 내용도 함께 지워져요. 되돌릴 수 없어요.",
      body: ["방문 기록이나 캐시만 지우는 것은 영향이 없어요. 사이트 데이터(저장 공간)를 지울 때 사라져요.", "브라우저를 새로 설치하거나 기기를 초기화해도 마찬가지예요. 서버에 사본이 없어서 다시 불러올 수 없어요."],
      note: "내 생활의 일정·할 일·목표·루틴·기록은 내 생활 › 설정에서 JSON 파일로 내려받아 둘 수 있어요(다시 불러오는 기능은 아직 없어요). 저장한 항목, 커뮤니티 글, 맞춤 설정은 파일로 내보내는 기능이 없으니 꼭 남겨야 하는 내용은 따로 적어 두는 것이 안전해요.",
      related: ["local-data-storage", "ts-data-disappeared", "move-device"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["삭제", "기록 삭제", "쿠키", "캐시", "사이트 데이터", "초기화", "지우기", "복구"] },
    { id: "storage-blocked", cat: "data", hf: "HF-5", v: "CODE_VERIFIED",
      title: "‘저장이 막혀 있어요’ 안내는 무슨 뜻인가요?",
      short: "브라우저 설정 때문에 LIVON이 내용을 보관할 수 없다는 뜻이에요. 쓰는 동안에는 동작하지만 창을 닫으면 사라져요.",
      body: ["쿠키·사이트 데이터를 차단했거나, 일부 앱 안의 브라우저처럼 저장을 허용하지 않는 환경에서 나타나요.", "이때 LIVON은 내용을 창이 열려 있는 동안만 기억해요. 기능이 멈추지는 않아요."],
      steps: ["브라우저 설정에서 쿠키·사이트 데이터 차단을 해제해요.", "사생활 보호(시크릿) 창이면 일반 창에서 다시 열어요.", "앱 안에서 열었다면 기본 브라우저로 열어 보세요."],
      related: ["ts-cannot-save", "local-data-storage", "clear-browser-data"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["저장 차단", "막혀", "쿠키 차단", "시크릿", "사생활 보호", "창을 닫으면", "임시"] },
    { id: "move-device", cat: "data", v: "CODE_VERIFIED",
      title: "다른 기기로 내용을 옮길 수 있나요?",
      short: "아직 옮길 수 없어요. 자동으로 옮기는 기능도, 파일을 다시 불러오는 기능도 지금은 없어요.",
      body: ["내 생활 › 설정의 ‘내 생활 데이터 내보내기’로 일정·할 일·목표·루틴·기록을 JSON 파일로 내려받아 보관할 수는 있어요. 그 파일을 LIVON으로 다시 불러오는 기능은 아직 없어요.", "새 기기에서는 맞춤 설정을 다시 고르고, 필요한 항목을 다시 저장해야 해요.", "커뮤니티 글은 쓴 기기의 브라우저에만 남아요."],
      related: ["other-device", "future-account", "clear-browser-data"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["옮기기", "이동", "백업", "내보내기", "가져오기", "기기 변경", "새 폰"] },
    { id: "future-account", cat: "data", v: "PRODUCT_POLICY",
      title: "나중에 계정이 생기면 지금 내용은 어떻게 되나요?",
      short: "정해진 일정은 없어요. 계정 기능이 생기더라도 이 기기의 내용이 동의 없이 서버로 올라가지 않아요.",
      body: ["계정에 옮길지는 그때 사용자가 직접 고르게 돼요. 고르지 않으면 지금처럼 이 기기에만 남아요.", "커뮤니티 글과 LIVON AI 대화는 계정으로 자동 이전되는 대상이 아니에요."],
      related: ["account-status", "local-data-storage", "move-device"], feature: ["서비스 상태", "#help/status"],
      kw: ["계정", "나중", "향후", "연동", "이전", "업로드", "NEWON+"] },
    { id: "save-items", cat: "data", v: "CODE_VERIFIED",
      title: "‘저장’은 어떻게 동작하나요?",
      short: "주제·정보·커뮤니티 글의 ‘저장’을 누르면 내 생활 › 저장에 모여요. 이 브라우저에만 보관돼요.",
      body: ["저장을 처음 누르면 ‘이 기기에 저장됩니다’라는 확인 창이 떠요. 확인하면 창을 닫을 때까지는 다시 묻지 않고 바로 저장돼요.", "어느 메뉴에서 저장했든 같은 저장함에 모이고, 다시 누르면 저장이 해제돼요."],
      related: ["local-data-storage", "what-is-my-life", "ts-cannot-save"], feature: ["내 생활 › 저장", "#ml-saved"],
      kw: ["저장", "북마크", "저장함", "보관", "저장한 글", "찜"] },

    /* ───────── 맞춤 설정 ───────── */
    { id: "why-ask-profile", cat: "personalization", hf: "HF-6", v: "CODE_VERIFIED",
      title: "연령대·관심 분야·Life Event는 왜 묻나요?",
      short: "관련 있는 정보를 먼저 보여 주려고 물어요. 세 가지 모두 선택 사항이고, 이 기기 안에서 순서를 정하는 데만 써요.",
      body: ["연령대는 10대부터 70대 이상까지 {lifeStages}개 중 하나, 관심 분야는 여러 개, Life Event는 지금 준비하거나 겪는 일을 고르는 거예요.", "생년월일·이름·연락처·주소·소득 같은 정보는 묻지 않아요. 고르지 않아도 모든 메뉴를 그대로 쓸 수 있어요."],
      related: ["personalization-storage", "how-recommendation-works", "onboarding-skip"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["연령대", "나이", "관심 분야", "관심사", "Life Event", "라이프 이벤트", "왜", "개인정보", "맞춤"] },
    { id: "personalization-storage", cat: "personalization", hf: "HF-7", popular: true, v: "CODE_VERIFIED",
      title: "맞춤 설정은 어디에 저장되나요?",
      short: "고른 연령대·관심 분야·Life Event는 이 브라우저에만 저장돼요. 서버로 보내지 않아요.",
      body: ["다른 기기나 다른 브라우저에서는 보이지 않아요. 그곳에서는 다시 고르면 돼요.", "브라우저의 사이트 데이터를 지우면 맞춤 설정도 함께 지워져요."],
      related: ["local-data-storage", "change-preferences", "personalization-reset"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["맞춤 설정", "저장 위치", "관심 설정", "연령대", "기기", "개인화"] },
    { id: "onboarding-restart", cat: "personalization", hf: "HF-8", v: "CODE_VERIFIED",
      title: "맞춤 설정을 처음부터 다시 하려면?",
      short: "내 생활 › 설정의 ‘맞춤 설정 다시 하기’를 누르면 처음 화면과 같은 순서로 다시 고를 수 있어요.",
      steps: ["내 생활 메뉴에서 ‘설정’을 열어요.", "‘맞춤 설정’ 영역에서 ‘맞춤 설정 다시 하기’를 눌러요.", "연령대 → 관심 분야 → Life Event → 미리보기 순서로 고르고 ‘이대로 시작하기’를 눌러요."],
      note: "항목 하나만 바꾸고 싶으면 각 항목 옆의 ‘변경’을 누르면 돼요.",
      related: ["change-preferences", "onboarding-skip", "ts-onboarding-not-showing"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["온보딩", "다시 설정", "다시 하기", "재설정", "처음부터", "시작 설정"] },
    { id: "personalization-reset", cat: "personalization", hf: "HF-9", popular: true, v: "CODE_VERIFIED",
      title: "맞춤 설정을 초기화하면 무엇이 지워지나요?",
      short: "연령대·관심 분야·Life Event 세 가지만 지워져요. 저장한 항목, 할 일, 목표, 기록, 커뮤니티 글은 그대로예요.",
      body: ["초기화하면 화면이 기본 순서로 돌아가요. 숨겨지거나 막히는 기능은 없어요.", "초기화한 뒤에도 원하면 언제든 다시 고를 수 있어요."],
      related: ["my-life-reset-scope", "onboarding-restart", "community-reset"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["초기화", "삭제", "지우기", "리셋", "맞춤 설정", "지워지나요"] },
    { id: "recommendation-reason", cat: "personalization", hf: "HF-10", v: "CODE_VERIFIED",
      title: "‘선택한 ‘첫 취업’ 관련’ 같은 문구는 무슨 뜻인가요?",
      short: "그 항목을 먼저 보여 준 이유예요. 내가 고른 설정 가운데 무엇과 맞았는지를 그대로 알려 줘요.",
      body: ["‘선택한 ‘○○’ 관련’은 고른 Life Event와, ‘20대 주제’는 고른 연령대와, ‘관심사 ‘○○’’는 고른 관심 분야와 맞았다는 뜻이에요.", "인기나 조회 수, 다른 사람의 이용 기록은 이유로 쓰지 않아요."],
      related: ["how-recommendation-works", "recommendation-ai", "ts-recommendation-off"], feature: ["LIVON 홈", "#livon-home"],
      kw: ["추천 이유", "문구", "관련", "왜 보여", "이유"] },
    { id: "life-event-no-guide", cat: "personalization", hf: "HF-11", v: "CODE_VERIFIED",
      title: "고른 Life Event에 안내가 없다고 나와요",
      short: "그 Life Event에 연결된 안내가 아직 충분하지 않을 수 있어요. 이때는 다른 선택에 맞는 정보를 먼저 보여 줘요.",
      body: ["Life Event마다, 또 연령대마다 준비된 안내의 양이 달라요. 프리랜서, 차량 구매, 해외생활, 장기여행처럼 아직 연결된 안내가 없는 것도 있어요.", "없는 안내를 있는 것처럼 채워 넣지 않아요. 탐색에서 직접 검색하면 관련 정보를 찾을 수 있어요."],
      related: ["what-is-life-event", "how-recommendation-works", "explore-search"], feature: ["탐색", "#explore"],
      kw: ["Life Event", "라이프 이벤트", "안내 없음", "준비 중", "프리랜서", "차량", "해외생활", "장기여행"] },
    { id: "other-life-stages", cat: "personalization", hf: "HF-12", v: "CODE_VERIFIED",
      title: "연령대를 고르면 다른 연령대 정보는 못 보나요?",
      short: "볼 수 있어요. 연령대는 먼저 보여 줄 순서만 바꾸고, 다른 연령대의 주제를 숨기지 않아요.",
      body: ["라이프 스테이지 메뉴에서 10대부터 70대 이상까지 어느 연령대든 열어 볼 수 있어요.", "다만 추천 영역에는 다른 연령대를 위한 정보를 올리지 않아요. 예를 들어 70대 이상을 고르면 보육 안내는 추천에 나오지 않아요."],
      related: ["what-is-life-stage", "how-recommendation-works", "change-preferences"], feature: ["라이프 스테이지", "#life"],
      kw: ["다른 연령대", "나이", "70대", "30대", "숨김", "제한", "부모님", "육아"] },
    { id: "recommendation-ai", cat: "personalization", hf: "HF-13", popular: true, v: "CODE_VERIFIED",
      title: "추천에 AI가 쓰이나요?",
      short: "아니요. 추천은 정해진 규칙으로 이 기기 안에서 계산해요. AI도, 서버도 쓰지 않아요.",
      body: ["규칙은 단순해요. 고른 Life Event와 맞으면 가장 먼저, 그다음 연령대, 그다음 관심 분야 순으로 올려요.", "LIVON AI는 별도의 메뉴이고, 추천 순서를 정하는 데 관여하지 않아요."],
      related: ["how-recommendation-works", "recommendation-reason", "ai-status"], feature: ["LIVON 홈", "#livon-home"],
      kw: ["AI", "인공지능", "추천", "알고리즘", "개인화", "자동"] },
    { id: "how-recommendation-works", cat: "personalization", v: "CODE_VERIFIED",
      title: "추천은 어떻게 정해지나요?",
      short: "내가 고른 Life Event, 연령대, 관심 분야와 맞는 정보를 그 순서대로 먼저 보여 줘요.",
      body: ["Life Event와 맞는 정보가 가장 앞에 오고, 다음이 연령대, 다음이 관심 분야예요. 여러 가지가 겹치면 더 앞에 와요.", "아무것도 고르지 않으면 추천 없이 기본 순서로 보여요. 추천은 순서만 바꾸고 어떤 정보도 숨기지 않아요."],
      related: ["recommendation-reason", "recommendation-ai", "ts-recommendation-off"], feature: ["LIVON 홈", "#livon-home"],
      kw: ["추천", "순서", "기준", "맞춤", "개인화", "어떻게"] },
    { id: "onboarding-skip", cat: "personalization", v: "CODE_VERIFIED",
      title: "‘나중에 할게요’를 누르면 어떻게 되나요?",
      short: "맞춤 설정 없이 바로 쓸 수 있어요. 건너뛰어도 막히는 기능은 없고, 안내도 다시 뜨지 않아요.",
      body: ["화면은 기본 순서로 보여요. ‘먼저 둘러보기’도 같은 뜻이에요.", "나중에 하고 싶어지면 내 생활 › 설정에서 시작할 수 있어요."],
      related: ["onboarding-restart", "ts-onboarding-not-showing", "why-ask-profile"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["나중에", "건너뛰기", "스킵", "둘러보기", "온보딩", "제한"] },
    { id: "onboarding-resume", cat: "personalization", v: "CODE_VERIFIED",
      title: "고르다가 닫았어요. 이어서 할 수 있나요?",
      short: "네. 닫기(×)나 Esc로 닫으면 고르던 내용이 남아 있어서 ‘이어서 하기’로 계속할 수 있어요.",
      body: ["다음에 LIVON을 열면 ‘맞춤 설정을 이어서 할까요?’ 안내가 보여요. ‘그만두기’를 누르면 더 묻지 않아요.", "‘이대로 시작하기’를 누르기 전까지는 고른 내용이 화면에 반영되지 않아요."],
      related: ["onboarding-restart", "onboarding-skip", "personalization-storage"], feature: ["LIVON 홈", "#livon-home"],
      kw: ["이어서", "중간", "닫기", "계속", "온보딩", "재개"] },
    { id: "change-preferences", cat: "personalization", v: "CODE_VERIFIED",
      title: "맞춤 설정은 어디서 바꾸나요?",
      short: "내 생활 › 설정에서 연령대, 관심 분야, Life Event를 각각 ‘변경’으로 바꿀 수 있어요.",
      steps: ["내 생활 메뉴에서 ‘설정’을 열어요.", "바꾸려는 항목 옆의 ‘변경’을 눌러요.", "새로 고른 뒤 ‘이대로 시작하기’를 누르면 바로 반영돼요."],
      note: "바꾸다가 ‘바꾸지 않고 닫기’를 누르면 이전 설정이 그대로 유지돼요.",
      related: ["onboarding-restart", "personalization-reset", "personalization-storage"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["변경", "수정", "바꾸기", "설정", "연령대 변경", "관심사 변경"] },
    { id: "what-is-life-event", cat: "personalization", v: "CODE_VERIFIED",
      title: "Life Event가 무엇인가요?",
      short: "첫 취업, 독립, 육아, 은퇴 준비처럼 지금 준비하거나 겪고 있는 일이에요. 고르면 그 일과 관련된 정보를 먼저 보여 줘요.",
      body: ["모두 {lifeEvents}가지가 있고, 고른 연령대에 해당하는 것을 먼저 보여 줘요. 한 번에 8개까지 고를 수 있어요.", "커뮤니티 글에도 Life Event를 붙일 수 있어서, 같은 일을 겪는 글을 찾기 쉬워요."],
      related: ["life-event-no-guide", "why-ask-profile", "what-is-life-stage"], feature: ["라이프 스테이지", "#life"],
      kw: ["Life Event", "라이프 이벤트", "생애 사건", "첫 취업", "독립", "육아", "은퇴"] },

    /* ───────── 라이프 스테이지 ───────── */
    { id: "what-is-life-stage", cat: "life-stage", popular: true, v: "CODE_VERIFIED",
      title: "라이프 스테이지가 무엇인가요?",
      short: "10대부터 70대 이상까지 {lifeStages}개 연령대로 나눠, 그 시기에 필요한 주제를 모아 둔 메뉴예요.",
      body: ["전체 주제는 {topics}개예요. 진로, 주거, 돈, 건강, 가족처럼 그 연령대에서 자주 마주치는 일로 이루어져 있어요.", "어느 연령대든 자유롭게 열어 볼 수 있어요. 내 연령대를 골라 두면 그 연령대부터 보여요."],
      related: ["life-stage-topics", "other-life-stages", "what-is-life-event"], feature: ["라이프 스테이지", "#life"],
      kw: ["라이프 스테이지", "Life Stage", "연령대", "나이", "10대", "20대", "30대", "40대", "50대", "60대", "70대", "주제"] },
    { id: "life-stage-topics", cat: "life-stage", v: "CODE_VERIFIED",
      title: "주제 페이지에서는 무엇을 볼 수 있나요?",
      short: "주제의 요약, 단계별 체크리스트, 그리고 연결된 정책·서비스·교육 정보를 볼 수 있어요.",
      body: ["체크리스트에 표시한 진행 상태는 이 브라우저에 저장돼요.", "주제는 저장하거나 내 생활의 할 일로 보낼 수 있어요. 정책과 지원 내용은 바뀔 수 있으니 신청 전에 공식 사이트에서 확인해 주세요."],
      related: ["what-is-life-stage", "save-items", "official-badge"], feature: ["라이프 스테이지", "#life"],
      kw: ["주제", "체크리스트", "정책", "가이드", "토픽", "진행"] },

    /* ───────── 오늘의 발견 ───────── */
    { id: "what-is-today", cat: "today", v: "CODE_VERIFIED",
      title: "오늘의 발견은 무엇인가요?",
      short: "가 볼 만한 장소, 체험, 배움, 계절 이야기처럼 일상에서 해 볼 만한 것을 모아 보여 주는 메뉴예요.",
      body: ["맨 위 ‘내 오늘’에는 내 생활에 직접 기록한 오늘의 할 일·일정·루틴과 앞으로 7일의 일정·마감이 모여요. 여기서 체크하면 내 생활에도 바로 반영되고, 이 내용은 이 기기에만 있어요.", "LIVON이 정리해 둔 항목을 보여 줘요. 실시간 행사 일정이나 현재 가격을 자동으로 가져오지는 않아요.", "지역, 가격, 날짜를 LIVON이 짐작해서 채우지 않아요. 정보가 없으면 ‘공식에서 확인’처럼 그대로 표시해요."],
      related: ["today-personalization", "official-badge", "live-data"], feature: ["오늘의 발견", "#today"],
      kw: ["오늘의 발견", "Today", "투데이", "장소", "체험", "계절", "추천", "내 오늘", "오늘 할 일"] },
    { id: "today-personalization", cat: "today", v: "CODE_VERIFIED",
      title: "맞춤 설정이 오늘의 발견에 어떤 영향을 주나요?",
      short: "‘맞춤’ 영역의 순서에만 영향을 줘요. 나머지 영역은 누구에게나 같은 순서로 보여요.",
      body: ["맞춤 영역은 고른 연령대, 관심 분야, Life Event와 저장하거나 최근에 본 항목을 참고해요.", "모든 항목이 개인화되는 것은 아니에요. 장소·계절·이야기 같은 영역은 맞춤 설정과 상관없이 같아요."],
      related: ["what-is-today", "how-recommendation-works", "ts-recommendation-off"], feature: ["오늘의 발견", "#today"],
      kw: ["오늘의 발견", "맞춤", "개인화", "순서", "영향"] },

    /* ───────── 내 생활 ───────── */
    { id: "what-is-my-life", cat: "my-life", popular: true, v: "CODE_VERIFIED",
      title: "내 생활에서는 무엇을 할 수 있나요?",
      short: "저장한 항목을 모아 보고, 일정·할 일·목표·기록과 루틴을 직접 관리하고, 관심사와 맞춤 설정을 바꿀 수 있어요.",
      body: ["라이프 스테이지 주제나 오늘의 발견에서 ‘할 일로 보내기’를 누르면 내 생활의 할 일에 들어와요.", "‘내 생활에서 찾기’는 이 기기의 내 생활 항목만 찾아요. LIVON 통합 검색에는 내 생활 내용이 들어가지 않아요.", "모든 내용은 이 브라우저에 저장돼요. 가족 연결(Family Space)처럼 다른 사람이나 서버가 필요한 기능은 준비 중이에요."],
      related: ["save-items", "my-life-reset-scope", "local-data-storage"], feature: ["내 생활", "#life-now"],
      kw: ["내 생활", "할 일", "목표", "기록", "일정", "저장", "관심사", "마이"] },
    { id: "my-life-reset-scope", cat: "my-life", v: "CODE_VERIFIED",
      title: "초기화·삭제 버튼마다 지워지는 범위가 다른가요?",
      short: "네. 각각 자기 영역만 지우고 다른 영역은 건드리지 않아요.",
      body: ["맞춤 설정 초기화: 연령대·관심 분야·Life Event만 지워요. 저장한 항목, 할 일, 목표, 기록, 커뮤니티 글은 남아요.", "커뮤니티 기록 지우기: 커뮤니티 글·댓글·공감·신고 기록·표시 이름을 지워요. 맞춤 설정과 내 생활은 남아요.", "내 생활 데이터 전체 삭제: 내 생활 › 설정에서 일정·할 일·목표·루틴·체크리스트·기록·생활비·예산·건강 기록을 한꺼번에 지워요. 저장한 항목, 커뮤니티 글, 맞춤 설정, 관심사, LIVON AI 대화는 남아요. 두 번 확인한 뒤에 지워요.", "항목 하나만 지우려면 그 항목의 ‘삭제’를 눌러요."],
      note: "삭제와 초기화는 되돌릴 수 없어요. 누르면 한 번 더 확인해요.",
      related: ["personalization-reset", "community-reset", "what-is-my-life"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["초기화", "전체 삭제", "삭제 범위", "지우기", "내 생활 삭제"] },

    /* ───────── 탐색·검색 ───────── */
    { id: "explore-search", cat: "explore", popular: true, v: "CODE_VERIFIED",
      title: "탐색에서는 무엇을 찾을 수 있나요?",
      short: "라이프 스테이지 주제, 오늘의 발견, 서비스, 정책·지원과 공식 기관, 교육, 장소, 그리고 이 기기에 쓴 커뮤니티 공개 글을 한 번에 찾아요.",
      body: ["검색어를 넣거나 분야를 골라 찾고, 결과에서 유형과 분야로 좁힐 수 있어요.", "행사 일정은 아직 준비 중이에요. 항목을 누르면 상세 화면에서 내용과 공식 사이트 링크를 볼 수 있어요."],
      related: ["search-difference", "official-badge", "ts-search-no-result"], feature: ["탐색", "#explore"],
      kw: ["탐색", "검색", "찾기", "정책", "서비스", "교육", "장소", "분야", "필터", "상세"] },
    { id: "official-badge", cat: "explore", v: "CODE_VERIFIED",
      title: "‘공식 출처’ 표시는 무슨 뜻인가요?",
      short: "그 정보의 출처가 정부·공공기관 같은 공식 기관의 사이트라는 뜻이에요.",
      body: ["LIVON이 내용을 보증하거나 신청을 대신해 준다는 뜻은 아니에요. 지원 대상, 금액, 기간은 바뀔 수 있어요.", "신청하기 전에는 ‘공식 사이트’ 링크로 들어가 최신 내용을 확인해 주세요."],
      related: ["explore-search", "live-data", "life-stage-topics"], feature: ["탐색", "#explore"],
      kw: ["공식", "출처", "기관", "정부", "공공", "신뢰", "정책", "배지"] },
    { id: "search-difference", cat: "explore", v: "CODE_VERIFIED",
      title: "전체 검색과 커뮤니티 검색은 어떻게 다른가요?",
      short: "전체 검색(탐색)은 LIVON의 모든 정보에서, 커뮤니티 검색은 이 기기에 있는 커뮤니티 글에서만 찾아요.",
      body: ["탐색 검색 결과에는 커뮤니티의 공개 글도 함께 나와요. 임시 저장 글과 비공개 글은 나오지 않아요.", "커뮤니티 검색은 제목, 본문, 태그, 글 유형, 연령대, Life Event로 찾고 띄어쓰기와 영문 대소문자를 구분하지 않아요."],
      related: ["explore-search", "community-search-filter", "ts-search-no-result"], feature: ["탐색", "#explore"],
      kw: ["검색", "전체 검색", "커뮤니티 검색", "차이", "찾기"] },
    { id: "live-data", cat: "explore", v: "CODE_VERIFIED",
      title: "실시간 공공 데이터가 연결되어 있나요?",
      short: "데이터 서버가 연결되어 응답할 때만, 일부 영역에서 보여요. 그 밖의 정보는 LIVON이 정리해 둔 안내와 공식 사이트 링크예요.",
      body: ["평생학습 강좌, 마을세무사, 주변 장소, 직업훈련 과정처럼 공공기관이 공개한 데이터는 데이터 서버가 연결되어야 보여요. 연결되지 않았거나 응답이 없으면 그 부분은 준비 중으로 표시되고, 정리해 둔 안내만 보여요.", "받아 온 데이터에도 모집 기간, 잔여 인원, 현재 가격처럼 자주 바뀌는 값이 있어요. 신청하기 전에는 공식 사이트에서 확인해야 해요.", "지금 이 브라우저에서 받아 온 공공 데이터가 있는지는 ‘서비스 상태’에서 볼 수 있어요."],
      related: ["official-badge", "what-is-today", "explore-search"], feature: ["서비스 상태", "#help/status"],
      kw: ["공공 데이터", "실시간", "연결", "데이터", "API", "최신", "행사", "장소"] },

    /* ───────── 커뮤니티 ───────── */
    { id: "community-post-storage", cat: "community", hf: "HF-14", popular: true, v: "CODE_VERIFIED",
      title: "내가 쓴 글은 어디에 저장되나요?",
      short: "글, 댓글, 공감은 이 브라우저에만 저장돼요. 서버에 올라가지 않고, 다른 사람에게 보이지 않아요.",
      body: ["지금 커뮤니티는 서버가 연결되지 않은 상태예요. 그래서 내가 쓴 글은 나만 볼 수 있어요.", "브라우저의 사이트 데이터를 지우면 글도 함께 지워져요."],
      related: ["community-no-other-posts", "local-data-storage", "community-share-link"], feature: ["커뮤니티", "#community"],
      kw: ["글", "게시글", "저장", "커뮤니티", "어디", "공개", "서버"] },
    { id: "community-no-other-posts", cat: "community", hf: "HF-15", v: "CODE_VERIFIED",
      title: "다른 사람 글은 왜 없나요?",
      short: "커뮤니티 서버가 아직 연결되지 않아서예요. 지금은 이 기기에서 쓴 글만 보여요.",
      body: ["보기용으로 만든 가짜 글이나 가짜 사용자는 넣지 않았어요. 그래서 처음에는 피드가 비어 있어요.", "커뮤니티 그룹과 챌린지 목록은 LIVON이 준비해 둔 것이고, 회원 수는 표시하지 않아요."],
      related: ["community-post-storage", "community-following", "ts-community-post-missing"], feature: ["커뮤니티", "#community"],
      kw: ["다른 사람", "글 없음", "비어", "피드", "사용자", "회원"] },
    { id: "community-following", cat: "community", hf: "HF-16", popular: true, v: "CODE_VERIFIED",
      title: "팔로잉은 왜 비어 있나요?",
      short: "팔로우는 계정이 있어야 하는 기능인데, 지금은 계정이 없어서 쓸 수 없어요.",
      body: ["팔로우할 다른 사용자가 없기 때문에 팔로잉 탭에는 글이 나오지 않아요. 가짜 팔로우 목록도 만들지 않아요.", "지금은 ‘최신’이나 ‘For You’ 탭, 주제 필터로 글을 볼 수 있어요."],
      related: ["community-no-other-posts", "account-status", "community-for-you"], feature: ["커뮤니티 피드", "#cm-home"],
      kw: ["팔로잉", "팔로우", "팔로워", "follow", "구독", "비어"] },
    { id: "community-report", cat: "community", hf: "HF-17", popular: true, v: "CODE_VERIFIED",
      title: "신고하면 운영자에게 전달되나요?",
      short: "아니요. 지금 신고는 이 브라우저에만 기록돼요. 운영자나 서버로 전송되지 않아요.",
      body: ["신고를 받아 검토하는 서버가 아직 연결되지 않았어요. 그래서 신고해도 글이 가려지거나 조치되지 않아요.", "남긴 신고는 커뮤니티 › 나의 활동의 ‘신고 기록’에서 볼 수 있어요. 기록에는 대상, 사유, 시간만 남아요."],
      related: ["community-report-duplicate", "ts-report-not-sent", "community-guidelines"], feature: ["커뮤니티 › 나의 활동", "#cm-mine"],
      kw: ["신고", "report", "운영자", "전달", "접수", "검토", "스팸"] },
    { id: "community-report-duplicate", cat: "community", hf: "HF-18", v: "CODE_VERIFIED",
      title: "같은 글을 두 번 신고할 수 있나요?",
      short: "같은 글을 같은 사유로는 한 번만 기록돼요. 다른 사유로는 다시 신고할 수 있어요.",
      body: ["사유는 스팸, 부적절한 콘텐츠, 괴롭힘/비방, 잘못된 정보, 기타 다섯 가지예요.", "이미 기록한 사유를 다시 고르면 ‘같은 사유로 이미 기록한 신고예요’라고 알려 줘요."],
      related: ["community-report", "ts-report-not-sent", "community-guidelines"], feature: ["커뮤니티", "#community"],
      kw: ["신고", "중복", "두 번", "사유", "다시"] },
    { id: "community-autosave", cat: "community", hf: "HF-19", v: "CODE_VERIFIED",
      title: "쓰다가 닫은 글은 어떻게 되나요?",
      short: "새 글을 쓰는 동안에는 내용이 자동으로 보관돼요. 글쓰기를 다시 열면 그대로 불러와요.",
      body: ["불러온 내용이 필요 없으면 ‘지우고 새로 쓰기’를 누르면 돼요. 글을 게시하면 보관된 내용은 비워져요.", "이미 게시한 글을 수정하다가 닫으면 자동 보관되지 않아요. 이때는 닫기 전에 한 번 더 물어봐요."],
      related: ["community-draft-vs-autosave", "community-post-storage", "storage-blocked"], feature: ["커뮤니티 글쓰기", "#cm-write"],
      kw: ["자동 보관", "쓰다가", "닫기", "복원", "글쓰기", "임시", "사라졌"] },
    { id: "community-draft-vs-autosave", cat: "community", hf: "HF-20", v: "CODE_VERIFIED",
      title: "임시 저장과 자동 보관은 무엇이 다른가요?",
      short: "자동 보관은 쓰던 글 한 편을 알아서 기억하는 것이고, 임시 저장은 내가 눌러서 여러 편을 따로 보관하는 거예요.",
      body: ["자동 보관: 새 글을 쓰는 동안 자동으로 한 편만 보관돼요. 글쓰기를 열면 바로 이어 쓸 수 있어요.", "임시 저장: ‘임시 저장’ 버튼을 누르면 나의 활동 › 임시 저장 글에 쌓여요. 거기서 골라 이어 쓸 수 있어요.", "둘 다 피드와 검색에는 나오지 않아요."],
      related: ["community-autosave", "community-post-storage", "community-search-filter"], feature: ["커뮤니티 › 나의 활동", "#cm-mine"],
      kw: ["임시 저장", "자동 보관", "차이", "초안", "드래프트", "draft"] },
    { id: "community-delete-post", cat: "community", hf: "HF-21", v: "CODE_VERIFIED",
      title: "글을 삭제하면 댓글과 저장은 어떻게 되나요?",
      short: "글과 함께 그 글의 댓글, 공감, 저장 표시가 모두 지워져요. 되돌릴 수 없어요.",
      body: ["피드와 검색에서도 바로 사라져요. 그 글에 남긴 신고 기록은 ‘삭제된 글’로 표시되어 남아요.", "내가 쓴 글만 수정하거나 삭제할 수 있어요."],
      related: ["community-post-storage", "community-comments", "community-reset"], feature: ["커뮤니티", "#community"],
      kw: ["삭제", "글 삭제", "댓글", "저장", "지우기", "복구"] },
    { id: "community-reaction-count", cat: "community", hf: "HF-22", v: "CODE_VERIFIED",
      title: "공감 수는 왜 안 보이나요?",
      short: "지금은 이 기기에서 누른 공감만 있어서, 숫자 대신 ‘공감했어요’ 여부만 보여 줘요.",
      body: ["다른 사람의 공감이 모이지 않는 상태에서 숫자를 보여 주면 사실과 다르기 때문이에요. 조회 수나 팔로워 수도 같은 이유로 표시하지 않아요."],
      related: ["community-no-other-posts", "community-comments", "community-post-storage"], feature: ["커뮤니티", "#community"],
      kw: ["공감", "좋아요", "숫자", "카운트", "조회 수", "like"] },
    { id: "community-for-you", cat: "community", hf: "HF-23", v: "CODE_VERIFIED",
      title: "For You 순서는 어떻게 정해지나요?",
      short: "맞춤 설정에 맞는 글을 먼저 보여 줘요. 맞춤 설정이 없으면 최신순과 같아요.",
      body: ["내가 고른 Life Event가 붙은 글이 가장 앞에 오고, 다음이 같은 연령대의 글, 다음이 관심 분야와 맞는 글이에요. 먼저 올라온 글에는 이유가 한 줄로 표시돼요.", "다른 연령대를 위해 쓴 글은 위로 올리지 않아요. 그래도 ‘최신’ 탭에서는 모두 볼 수 있어요. AI는 쓰지 않아요."],
      related: ["how-recommendation-works", "recommendation-reason", "community-following"], feature: ["커뮤니티 피드", "#cm-home"],
      kw: ["For You", "포유", "순서", "추천", "피드", "맞춤", "최신"] },
    { id: "community-share-link", cat: "community", hf: "HF-24", v: "CODE_VERIFIED",
      title: "글 링크를 보냈는데 상대가 열 수 없대요",
      short: "글이 내 브라우저에만 있어서, 다른 사람의 기기에서는 그 링크로 글을 열 수 없어요.",
      body: ["상대 화면에는 ‘글을 찾을 수 없습니다’가 보여요. 오류가 아니라 지금 구조에서 나오는 정상 동작이에요.", "내용을 전하려면 글의 내용을 복사해서 직접 보내 주세요."],
      related: ["community-post-storage", "ts-community-link", "other-device"], feature: ["커뮤니티", "#community"],
      kw: ["링크", "공유", "주소", "URL", "안 열려", "찾을 수 없습니다", "상대"] },
    { id: "community-guidelines", cat: "community", hf: "HF-25", v: "CODE_VERIFIED",
      title: "커뮤니티에 쓰면 안 되는 내용이 있나요?",
      short: "서로 존중하고, 개인정보와 스팸·불법·유해한 내용은 올리지 않는 것이 기본이에요.",
      body: ["실명, 전화번호, 이메일, 주소, 계좌처럼 나나 다른 사람을 알아볼 수 있는 정보는 적지 않는 것이 좋아요. 건강이나 돈처럼 민감한 이야기는 필요한 만큼만 적어 주세요.", "경험과 사실을 구분해서 쓰고, 건강·돈·법률 판단은 전문가와 확인해 주세요. 전체 가이드는 커뮤니티 › 안전에 있어요."],
      related: ["community-display-name", "community-report", "community-post-types"], feature: ["커뮤니티 가이드", "#cm-safe"],
      kw: ["가이드", "규칙", "금지", "개인정보", "실명", "전화번호", "이메일", "주소", "스팸", "프라이버시"] },
    { id: "community-display-name", cat: "community", hf: "HF-26", v: "CODE_VERIFIED",
      title: "표시 이름은 실명인가요?",
      short: "아니요. 이 기기에서 쓰는 별명이에요. 처음에는 ‘나’로 되어 있고 계정이 아니에요.",
      body: ["커뮤니티 › 나의 활동에서 20자 이내로 바꿀 수 있어요. 새로 쓰는 글부터 바뀐 이름이 표시돼요.", "실명이나 연락처는 이름으로 쓰지 않는 것이 좋아요. 프로필 사진과 팔로워 기능은 아직 없어요."],
      related: ["community-guidelines", "account-status", "community-following"], feature: ["커뮤니티 › 나의 활동", "#cm-mine"],
      kw: ["표시 이름", "닉네임", "별명", "실명", "프로필", "이름"] },
    { id: "community-reset", cat: "community", hf: "HF-27", v: "CODE_VERIFIED",
      title: "커뮤니티 기록을 지우면 맞춤 설정도 지워지나요?",
      short: "아니요. 커뮤니티 기록만 지워지고 맞춤 설정과 내 생활의 다른 내용은 그대로 남아요.",
      body: ["‘이 기기의 커뮤니티 기록 지우기’는 글, 댓글, 공감, 신고 기록, 커뮤니티 가입, 표시 이름을 지워요.", "반대로 맞춤 설정을 초기화해도 커뮤니티 글은 지워지지 않아요."],
      related: ["my-life-reset-scope", "personalization-reset", "community-delete-post"], feature: ["커뮤니티 › 나의 활동", "#cm-mine"],
      kw: ["커뮤니티 기록", "지우기", "초기화", "삭제", "맞춤 설정"] },
    { id: "community-related-info", cat: "community", hf: "HF-28", v: "CODE_VERIFIED",
      title: "글 아래 ‘관련 LIVON 정보’는 어떻게 고르나요?",
      short: "글을 쓸 때 고른 ‘관련 주제’와 ‘Life Event’에 실제로 연결된 정보만 보여 줘요.",
      body: ["주제를 골랐다면 그 주제와, 그 주제에 연결된 가이드·정책·서비스·교육이 나와요. Life Event를 골랐다면 그 일을 다룬 주제가 나와요.", "글의 내용을 읽고 짐작해서 붙이지 않아요. 둘 다 고르지 않은 글에는 연결된 정보가 없다고 표시돼요."],
      related: ["community-post-types", "what-is-life-event", "life-stage-topics"], feature: ["커뮤니티", "#community"],
      kw: ["관련 정보", "관련 LIVON 정보", "연결", "주제", "Life Event"] },
    { id: "community-post-types", cat: "community", v: "CODE_VERIFIED",
      title: "글 유형 여섯 가지는 어떻게 다른가요?",
      short: "질문, 경험 공유, 생활 정보, 후기, 생활 팁, 일상 이야기 {postTypes}가지예요. 글의 성격에 맞게 고르면 돼요.",
      body: ["질문은 궁금한 것을 물을 때, 경험 공유는 겪은 일을 나눌 때, 생활 정보는 알아 둘 내용을 전할 때 써요.", "후기는 써 보거나 다녀온 소감, 생활 팁은 짧은 요령, 일상 이야기는 가벼운 이야기에 어울려요.", "글에는 제목과 본문이 꼭 필요해요. 분야, 연령대, Life Event, 관련 주제, 태그는 선택이에요."],
      related: ["community-comments", "community-search-filter", "community-guidelines"], feature: ["커뮤니티 글쓰기", "#cm-write"],
      kw: ["글 유형", "질문", "경험", "정보", "후기", "팁", "일상", "글쓰기", "게시글", "작성"] },
    { id: "community-comments", cat: "community", v: "CODE_VERIFIED",
      title: "댓글·답글·공감·저장은 어떻게 쓰나요?",
      short: "글 아래에서 댓글을 쓰고, 댓글에는 답글을 한 단계까지 달 수 있어요. 공감과 저장은 누르면 켜지고 다시 누르면 꺼져요.",
      body: ["내가 쓴 댓글은 수정하고 삭제할 수 있어요. 답글이 달린 댓글을 지우면 ‘삭제된 댓글입니다’로 남아요.", "저장한 글은 내 생활 › 저장과 커뮤니티 › 나의 활동에서 볼 수 있어요. 모두 이 브라우저에만 저장돼요."],
      related: ["community-reaction-count", "save-items", "community-delete-post"], feature: ["커뮤니티", "#community"],
      kw: ["댓글", "답글", "공감", "저장", "저장한 글", "수정", "삭제", "comment"] },
    { id: "community-search-filter", cat: "community", v: "CODE_VERIFIED",
      title: "커뮤니티에서 글을 어떻게 찾나요?",
      short: "피드 위의 검색창에 검색어를 넣거나, 주제·글 유형·연령대·Life Event 필터로 좁혀요.",
      body: ["검색과 필터는 함께 쓸 수 있어요. ‘필터 초기화’를 누르면 처음 상태로 돌아가요.", "임시 저장 글과 비공개 글은 검색과 피드에 나오지 않아요."],
      related: ["search-difference", "community-for-you", "ts-community-post-missing"], feature: ["커뮤니티 피드", "#cm-home"],
      kw: ["검색", "필터", "찾기", "글 유형", "연령대", "Life Event", "커뮤니티"] },

    /* ───────── LIVON AI ───────── */
    { id: "ai-status", cat: "ai", popular: true, v: "CODE_VERIFIED",
      title: "LIVON AI는 지금 사용할 수 있나요?",
      short: "아직 답변을 받을 수 없어요. LIVON AI는 AI 서버에 연결되어야 동작하는데, 지금은 연결되어 있지 않아요.",
      body: ["LIVON AI 화면 위쪽에 연결 상태가 표시돼요. ‘연결 확인 불가’나 ‘연결 미완료’로 보이면 질문을 보내도 답변이 오지 않아요.", "연결되지 않은 동안 가짜 답변을 만들어 보여 주지 않아요. 질문을 보내면 연결되지 않았다는 안내가 그대로 표시돼요."],
      related: ["ts-ai-not-working", "ai-what-it-uses", "recommendation-ai"], feature: ["LIVON AI", "#livon-ai"],
      kw: ["AI", "LIVON AI", "인공지능", "챗봇", "사용", "연결", "답변", "준비 중"] },
    { id: "ai-what-it-uses", cat: "ai", v: "CODE_VERIFIED",
      title: "LIVON AI는 어떤 정보를 사용하나요?",
      short: "보낸 질문, 직접 가져온 화면 맥락, 관련 LIVON 정보 몇 건, 최근 대화만 사용해요. 연결된 뒤에 적용되는 방식이에요.",
      body: ["다른 화면에서 ‘LIVON AI에게 물어보기’로 넘어오면 그 화면의 제목과 요약이 ‘참고 중’으로 붙어요. ×를 누르면 빼고 보낼 수 있어요.", "내 생활의 기록이나 커뮤니티 글을 자동으로 붙여 보내지 않아요. 대화 기록은 이 브라우저에 저장돼요."],
      related: ["ai-personalization", "ai-status", "what-is-stored"], feature: ["LIVON AI", "#livon-ai"],
      kw: ["AI", "정보", "전송", "맥락", "대화", "개인정보", "참고"] },
    { id: "ai-save-to-my-life", cat: "ai", v: "CODE_VERIFIED",
      title: "AI가 내 생활에 자동으로 저장하나요?",
      short: "아니요. AI가 제안한 계획은 미리 보고, 넣을 항목을 고르고, 승인해야만 내 생활에 들어가요.",
      body: ["승인하지 않으면 아무것도 저장되지 않아요. 이미 있는 할 일과 같은 항목은 중복으로 넣지 않아요."],
      related: ["ai-what-it-uses", "what-is-my-life", "ai-status"], feature: ["LIVON AI", "#livon-ai"],
      kw: ["AI", "자동 저장", "승인", "계획", "할 일", "내 생활"] },
    { id: "ai-personalization", cat: "ai", v: "CODE_VERIFIED",
      title: "맞춤 설정이 AI로 전송되나요?",
      short: "아니요. 처음 설정에서 고른 연령대·관심 분야·Life Event는 AI로 자동 전송되지 않아요.",
      body: ["LIVON AI에는 별도의 ‘개인화 설정’이 있어요. 거기에 직접 적은 연령대·관심사·지역·목표만, ‘개인화 사용’이 켜져 있을 때 질문과 함께 보내요.", "아무것도 적지 않았다면 그런 정보 없이 질문만 보내요."],
      related: ["ai-what-it-uses", "personalization-storage", "recommendation-ai"], feature: ["LIVON AI", "#livon-ai"],
      kw: ["AI", "맞춤 설정", "전송", "개인화", "개인정보", "연령대"] },

    /* ───────── 문제 해결 ───────── */
    { id: "ts-cannot-save", cat: "troubleshooting", popular: true, v: "CODE_VERIFIED",
      title: "저장이 안 돼요",
      short: "브라우저가 저장을 막고 있거나 저장 공간이 가득 찼을 수 있어요.",
      ts: { symptom: "저장을 눌러도 남지 않거나, 새로고침하면 사라져요.",
        causes: ["쿠키·사이트 데이터가 차단되어 있어요.", "사생활 보호(시크릿) 창을 쓰고 있어요.", "이미지가 큰 커뮤니티 글 때문에 저장 공간이 가득 찼어요.", "처음 저장할 때 뜨는 확인 창에서 ‘취소’를 눌렀어요."],
        fixes: ["브라우저 설정에서 이 사이트의 쿠키·사이트 데이터를 허용해요.", "일반 창에서 다시 열어요.", "‘저장 공간이 부족해 저장하지 못했습니다’가 보이면 이미지가 큰 글을 정리해요.", "저장을 다시 누르고 ‘이 기기에 저장’을 선택해요."] },
      related: ["storage-blocked", "save-items", "ts-data-disappeared"], feature: ["내 생활 › 저장", "#ml-saved"],
      kw: ["저장 안됨", "저장이 안 돼요", "저장 오류", "안 남아", "저장 실패"] },
    { id: "ts-data-disappeared", cat: "troubleshooting", popular: true, v: "CODE_VERIFIED",
      title: "저장한 내용이 사라졌어요",
      short: "대부분 브라우저의 사이트 데이터가 지워졌거나, 다른 브라우저·다른 기기로 보고 있는 경우예요.",
      ts: { symptom: "어제까지 있던 저장 항목, 할 일, 글, 맞춤 설정이 보이지 않아요.",
        causes: ["브라우저의 쿠키·사이트 데이터를 지웠어요(자동 삭제 설정 포함).", "다른 브라우저나 다른 기기로 접속했어요.", "사생활 보호 창에서 썼던 내용이에요.", "초기화나 삭제 버튼을 눌렀어요."],
        fixes: ["전에 쓰던 기기와 브라우저로 다시 열어 봐요.", "브라우저의 ‘종료 시 사이트 데이터 삭제’ 설정을 꺼요.", "서버에 사본이 없어서 지워진 내용은 복구할 수 없어요."] },
      related: ["clear-browser-data", "other-device", "storage-blocked"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["사라졌어요", "없어졌어요", "글이 사라졌어요", "날아갔", "복구", "안 보여요", "삭제됨"] },
    { id: "ts-other-device", cat: "troubleshooting", v: "CODE_VERIFIED",
      title: "다른 기기에서 내용이 안 보여요",
      short: "정상이에요. 내용은 기기마다 따로 저장되고, 기기 사이의 동기화는 아직 없어요.",
      ts: { symptom: "휴대폰에서 저장한 내용이 컴퓨터에서 보이지 않아요.",
        causes: ["LIVON은 내용을 서버가 아니라 각 브라우저에 저장해요.", "계정이 없어 기기를 서로 연결할 수 없어요."],
        fixes: ["내용을 저장했던 기기와 브라우저에서 확인해요.", "새 기기에서는 맞춤 설정을 다시 골라요.", "기기 사이에 내용을 옮기는 방법은 아직 없어요."] },
      related: ["other-device", "move-device", "account-status"], feature: ["서비스 상태", "#help/status"],
      kw: ["다른 기기", "안 보여요", "동기화", "휴대폰", "컴퓨터"] },
    { id: "ts-recommendation-off", cat: "troubleshooting", v: "CODE_VERIFIED",
      title: "추천이 나와 맞지 않아요",
      short: "추천은 고른 맞춤 설정만 보고 정해요. 설정을 바꾸면 바로 달라져요.",
      ts: { symptom: "관심 없는 주제가 먼저 나오거나, 추천이 전혀 보이지 않아요.",
        causes: ["맞춤 설정을 하지 않았거나 일부만 골랐어요.", "예전에 고른 연령대나 Life Event가 그대로예요.", "고른 Life Event에 연결된 안내가 아직 적어요."],
        fixes: ["내 생활 › 설정에서 연령대·관심 분야·Life Event를 확인하고 ‘변경’으로 바꿔요.", "추천 옆의 이유 문구를 보면 무엇 때문에 나온 것인지 알 수 있어요.", "추천이 필요 없으면 ‘맞춤 설정 초기화’로 기본 순서로 돌아가요."] },
      related: ["how-recommendation-works", "change-preferences", "life-event-no-guide"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["추천 이상", "안 맞아요", "엉뚱", "추천 안 나와", "맞춤"] },
    { id: "ts-onboarding-not-showing", cat: "troubleshooting", v: "CODE_VERIFIED",
      title: "처음 설정 안내가 다시 안 떠요",
      short: "한 번 마쳤거나 ‘나중에 할게요’를 누르면 안내가 다시 뜨지 않아요. 설정에서 직접 열 수 있어요.",
      ts: { symptom: "처음에 보이던 ‘나에게 맞게 시작하기’ 안내가 보이지 않아요.",
        causes: ["맞춤 설정을 이미 마쳤어요.", "‘나중에 할게요’, ‘먼저 둘러보기’, ‘그만두기’ 중 하나를 눌렀어요.", "맞춤 설정을 초기화했어요(초기화 뒤에도 다시 묻지 않아요)."],
        fixes: ["내 생활 › 설정 › ‘맞춤 설정 다시 하기’를 눌러요.", "항목 하나만 바꾸려면 같은 화면에서 ‘변경’을 눌러요."] },
      related: ["onboarding-restart", "onboarding-skip", "change-preferences"], feature: ["내 생활 › 설정", "#ml-settings"],
      kw: ["온보딩", "안 떠요", "안내 없음", "다시 설정", "시작하기"] },
    { id: "ts-community-post-missing", cat: "troubleshooting", v: "CODE_VERIFIED",
      title: "커뮤니티 글이 안 보여요",
      short: "필터나 검색어가 걸려 있거나, 임시 저장·비공개 글이거나, 다른 기기에서 쓴 글일 수 있어요.",
      ts: { symptom: "방금 쓴 글이나 전에 쓴 글이 피드에 나오지 않아요.",
        causes: ["주제·유형·연령대·Life Event 필터나 검색어가 적용되어 있어요.", "‘팔로잉’ 탭을 보고 있어요(지금은 항상 비어 있어요).", "글이 임시 저장 상태이거나 비공개예요.", "다른 기기나 다른 브라우저에서 쓴 글이에요."],
        fixes: ["‘필터 초기화’를 누르고 ‘최신’ 탭을 확인해요.", "커뮤니티 › 나의 활동에서 ‘내가 작성한 글’과 ‘임시 저장 글’을 확인해요.", "글을 쓴 기기와 브라우저에서 열어 봐요."] },
      related: ["community-post-storage", "community-search-filter", "community-following"], feature: ["커뮤니티 › 나의 활동", "#cm-mine"],
      kw: ["글이 안 보여요", "글 없음", "피드", "게시글", "사라졌"] },
    { id: "ts-community-link", cat: "troubleshooting", v: "CODE_VERIFIED",
      title: "보낸 커뮤니티 링크가 안 열려요",
      short: "글이 보낸 사람의 브라우저에만 있어서, 받은 사람은 그 글을 열 수 없어요.",
      ts: { symptom: "링크를 열면 ‘글을 찾을 수 없습니다’가 보여요.",
        causes: ["커뮤니티 글은 서버가 아니라 글쓴이의 브라우저에만 저장돼요.", "글이 삭제되었어요."],
        fixes: ["전하려는 내용을 복사해서 메시지로 직접 보내요.", "같은 기기·같은 브라우저에서는 링크가 정상적으로 열려요."] },
      related: ["community-share-link", "community-post-storage", "other-device"], feature: ["커뮤니티", "#community"],
      kw: ["링크", "안 열려요", "찾을 수 없습니다", "공유", "주소"] },
    { id: "ts-following-empty", cat: "troubleshooting", v: "CODE_VERIFIED",
      title: "팔로잉이 비어 있어요",
      short: "정상이에요. 팔로우는 계정이 필요한 기능이라 지금은 쓸 수 없어요.",
      ts: { symptom: "팔로잉 탭에 글이 하나도 없고 팔로우 버튼도 보이지 않아요.",
        causes: ["계정과 커뮤니티 서버가 연결되지 않아 팔로우할 다른 사용자가 없어요."],
        fixes: ["‘최신’ 또는 ‘For You’ 탭에서 글을 봐요.", "주제 필터로 관심 있는 글을 좁혀 봐요."] },
      related: ["community-following", "community-no-other-posts", "account-status"], feature: ["커뮤니티 피드", "#cm-home"],
      kw: ["팔로잉", "팔로우", "비어", "follow", "없어요"] },
    { id: "ts-report-not-sent", cat: "troubleshooting", v: "CODE_VERIFIED",
      title: "신고가 전송되지 않아요",
      short: "지금 신고는 전송되는 기능이 아니라 이 브라우저에 기록만 하는 기능이에요.",
      ts: { symptom: "신고했는데 글이 그대로 있고 결과 안내도 없어요.",
        causes: ["신고를 받는 서버가 아직 연결되지 않았어요.", "같은 사유로 이미 신고한 글이라 새로 기록되지 않았어요."],
        fixes: ["커뮤니티 › 나의 활동 › ‘신고 기록’에서 기록된 내용을 확인해요.", "지금 커뮤니티에는 이 기기에서 쓴 글만 있어서, 불편한 글은 직접 삭제할 수 있어요."] },
      related: ["community-report", "community-report-duplicate", "community-delete-post"], feature: ["커뮤니티 › 나의 활동", "#cm-mine"],
      kw: ["신고", "전송", "접수", "처리", "안 돼요", "report"] },
    { id: "ts-ai-not-working", cat: "troubleshooting", popular: true, v: "CODE_VERIFIED",
      title: "AI가 동작하지 않아요",
      short: "LIVON AI 서버가 연결되지 않아 답변을 받을 수 없는 상태예요. 기기나 브라우저의 문제가 아니에요.",
      ts: { symptom: "질문을 보내면 ‘연결되어 있지 않습니다’ 같은 안내가 나오거나 상태가 ‘연결 확인 불가’로 보여요.",
        causes: ["이 사이트에 AI 서버가 아직 연결되지 않았어요.", "인터넷 연결이 끊겨 있어요(연결된 환경에서도 답변을 받으려면 인터넷이 필요해요)."],
        fixes: ["LIVON AI 화면 위쪽의 연결 상태를 확인해요.", "연결 전까지는 탐색 검색이나 라이프 스테이지 주제에서 정보를 찾아 주세요."] },
      related: ["ai-status", "explore-search", "ai-what-it-uses"], feature: ["LIVON AI", "#livon-ai"],
      kw: ["AI 안됨", "AI 오류", "답변 없음", "동작하지", "연결 확인 불가", "AI가 안 돼요"] },
    { id: "ts-search-no-result", cat: "troubleshooting", v: "CODE_VERIFIED",
      title: "검색 결과가 없어요",
      short: "검색어를 짧게 바꾸거나 다른 표현으로 다시 찾아보세요. LIVON에 아직 없는 정보일 수도 있어요.",
      ts: { symptom: "탐색, 커뮤니티, 도움말에서 검색해도 결과가 나오지 않아요.",
        causes: ["검색어가 길거나 문장으로 되어 있어요.", "필터가 함께 걸려 있어요.", "커뮤니티는 이 기기에서 쓴 글만 검색돼요.", "아직 준비되지 않은 정보예요."],
        fixes: ["핵심 단어 한두 개로 줄여요(예: ‘전세 계약’).", "필터를 초기화해요.", "분야나 카테고리로 둘러봐요.", "없는 결과를 대신 만들어 보여 주지는 않아요."] },
      related: ["explore-search", "search-difference", "contact-support"], feature: ["탐색", "#explore"],
      kw: ["검색 안됨", "결과 없음", "검색 결과", "못 찾", "검색이 안 돼요"] }
  ];

  /* words that mean the same thing in a help search (each group is expanded both ways) */
  var synonyms = [
    ["계정", "로그인", "회원가입", "가입", "NEWON+", "뉴온", "아이디", "비밀번호", "로그아웃", "account", "login"],
    ["저장", "보관", "세이브", "save"],
    ["기기", "디바이스", "휴대폰", "핸드폰", "폰", "컴퓨터", "PC", "노트북", "태블릿", "브라우저"],
    ["삭제", "초기화", "지우기", "지워", "리셋", "reset", "제거", "없애"],
    ["추천", "맞춤", "개인화", "personalization"],
    ["나이", "연령", "연령대", "라이프 스테이지", "Life Stage", "세대"],
    ["글쓰기", "게시글", "글", "포스트", "post", "작성", "커뮤니티"],
    ["신고", "report", "리포트"],
    ["AI", "인공지능", "LIVON AI", "챗봇", "에이아이"],
    ["찾기", "검색", "탐색", "search"],
    ["관심사", "관심 분야", "관심"],
    ["Life Event", "라이프 이벤트", "생애 사건", "인생 이벤트"],
    ["팔로우", "팔로잉", "팔로워", "follow", "following", "구독"],
    ["공감", "좋아요", "like", "하트"],
    ["댓글", "답글", "코멘트", "comment", "reply"],
    ["링크", "주소", "URL", "공유"],
    ["온보딩", "시작 설정", "처음 설정", "다시 설정", "onboarding"],
    ["사라졌", "없어졌", "날아갔", "안 보여", "안보여"],
    ["동기화", "연동", "sync", "다른 기기"],
    ["정책", "지원", "제도", "복지"],
    ["공식", "출처", "기관", "정부", "공공"],
    ["할 일", "할일", "todo", "투두", "체크리스트"],
    ["목표", "goal"],
    ["기록", "일기", "저널", "journal"],
    ["개인정보", "프라이버시", "privacy", "실명"],
    ["문의", "고객센터", "연락", "상담", "support"],
    ["오류", "에러", "error", "안됨", "안돼요", "안 돼요", "동작하지", "고장"],
    ["임시 저장", "초안", "드래프트", "draft"],
    ["백업", "내보내기", "export"]
  ];

  /* what can be used today. `fact` ties each row to facts above (and through the tests, to the code). */
  var status = [
    { id: "core", label: "LIVON 기본 기능", state: "available", text: "홈, 라이프 스테이지, 오늘의 발견, 내 생활, 탐색을 가입 없이 쓸 수 있어요.", fact: "help", article: "what-is-livon" },
    { id: "personalization", label: "맞춤 설정", state: "local", text: "이 기기 안에서 규칙으로 계산해요. 서버와 AI를 쓰지 않아요.", fact: "personalization", article: "how-recommendation-works" },
    { id: "storage", label: "저장·내 생활", state: "local", text: "이 브라우저에만 저장돼요.", fact: "sync", article: "local-data-storage" },
    { id: "community", label: "커뮤니티 글·댓글", state: "local", text: "이 기기에서 쓴 글만 보여요. 다른 사람과 공유되지 않아요.", fact: "communityPosts", article: "community-post-storage" },
    { id: "follow", label: "커뮤니티 팔로우", state: "off", text: "계정이 필요해서 아직 쓸 수 없어요.", fact: "follow", article: "community-following" },
    { id: "reports", label: "커뮤니티 신고", state: "local", text: "이 브라우저에 기록만 해요. 운영자에게 전송되지 않아요.", fact: "reports", article: "community-report" },
    { id: "ai", label: "LIVON AI", state: "off", text: "AI 서버가 연결되지 않아 답변을 받을 수 없어요.", fact: "ai", article: "ai-status" },
    { id: "live-data", label: "실시간 공공 데이터", state: "off", text: "아직 연결되지 않았어요. 정리해 둔 안내와 공식 링크를 보여 줘요.", fact: "liveData", article: "live-data" },
    { id: "account", label: "계정·기기 간 동기화", state: "off", text: "로그인과 NEWON+ 연결이 없고, 기기 사이에 내용이 옮겨지지 않아요.", fact: "account", article: "account-status" },
    { id: "support", label: "문의 접수", state: "off", text: "문의를 보내는 창구가 아직 연결되지 않았어요.", fact: "support", article: "contact-support" }
  ];
  var statusLabel = { available: "사용 가능", local: "이 기기에서만", off: "아직 연결 안 됨" };

  /* where a screen links into Help (contextual entries). The same ids are used by the screens. */
  var contextual = [
    { screen: "onboarding", article: "personalization-storage" },
    { screen: "onboarding-storage-blocked", article: "storage-blocked" },
    { screen: "my-life-settings", article: "personalization-reset" },
    { screen: "community-following", article: "community-following" },
    { screen: "community-report", article: "community-report" },
    { screen: "community-reset", article: "community-reset" },
    { screen: "ai-status", article: "ai-status" },
    { screen: "save-confirm", article: "local-data-storage" }
  ];

  /* Articles that also get a static, indexable page (/livon/help/{id}/), generated from this same file by
     scripts/livon-seo-build.mjs. These answer questions people ask before or while using LIVON. The others explain a
     button or a state inside the app and stay in the interactive Help only. */
  var seoIndexable = [
    "no-signup", "what-is-livon", "account-status",
    "local-data-storage", "what-is-stored", "other-device", "clear-browser-data", "storage-blocked", "move-device", "save-items",
    "why-ask-profile", "personalization-storage", "how-recommendation-works", "recommendation-ai", "other-life-stages", "what-is-life-event", "personalization-reset", "onboarding-skip",
    "what-is-life-stage", "life-stage-topics", "what-is-today", "what-is-my-life",
    "explore-search", "official-badge", "live-data",
    "community-post-storage", "community-no-other-posts", "community-following", "community-report", "community-guidelines", "community-post-types", "community-for-you",
    "ai-status", "ai-what-it-uses", "ai-personalization",
    "ts-cannot-save", "ts-data-disappeared", "ts-other-device", "ts-ai-not-working"
  ];

  root.LivonHelpData = { version: 1, facts: facts, categories: categories, articles: articles, synonyms: synonyms, status: status, statusLabel: statusLabel, contextual: contextual, seoIndexable: seoIndexable };
})(typeof window !== "undefined" ? window : globalThis);
