(function(){
 var U=window.LivonServices.ui,T=window.LivonServiceTools,D=window.LivonFamilyData,e=U.esc;
 var current,host,kind,parts=[],state={},selected=null;
 function action(label,name,primary){return U.button(label,'data-family-action="'+name+'"',primary);}
 function href(n){return '#life-service-service-30-'+String(n).padStart(2,'0');}
 function field(f){var k=f[0],title=f[1],type=f[2];return Array.isArray(type)?U.select(k,title,type):U.input(k,title,type,type==='number'?'min="0" max="100000000000" step="any"':type==='date'?'':'maxlength="500"');}
 function fields(list){return list.map(field).join('');}
 function section(title,html){return U.section(title,html);}
 function form(html,label){return '<form class="lv-ls-form lv-family-form" data-family-form>'+html+'<button type="submit" class="lv-life-btn lv-life-btn--dark">'+e(label||'선택한 조건 확인')+'</button></form><div data-family-result aria-live="polite"></div>';}
 function group(title,html){return '<fieldset class="lv-youth-budget-group"><legend>'+e(title)+'</legend>'+html+'</fieldset>';}
 function controls(){return fields(D.fields[kind]||[]);}
 function related(){return section('함께 준비하면 좋은 서비스','<div class="lv-family-related">'+(D.related[kind]||[]).map(function(n){var s=window.LivonServices.all().find(function(x){return x.id==='service-30-'+String(n).padStart(2,'0');});return U.link(s.name+' →',href(n));}).join('')+'</div>');}
 function quick(){return '<div class="lv-family-quick">'+action('내 생활에 저장','save')+U.button('공유','data-ls-share="'+current.id+'"')+action('AI에게 물어보기','ai')+'</div>';}
 function collect(){var f=host&&host.querySelector('[data-family-form]');if(f){new FormData(f).forEach(function(v,k){state[k]=String(v).slice(0,1500);});f.querySelectorAll('input[type="checkbox"]').forEach(function(c){state[c.name]=c.checked;});state.updatedAt=Date.now();T.draft(current,state);}return state;}
 function result(html){var n=host.querySelector('[data-family-result]');if(n)n.innerHTML=html;}
 function labels(){var out={};(D.fields[kind]||[]).forEach(function(f){out[f[0]]=f[1];});return out;}
 function summary(){var l=labels();return '<dl class="lv-teen-detail">'+Object.keys(l).filter(function(k){return state[k]!==undefined&&state[k]!=='';}).map(function(k){return '<div><dt>'+e(l[k])+'</dt><dd>'+e(state[k])+'</dd></div>';}).join('')+'</dl>';}
 function saved(){try{collect();if(kind==='finance')return financeSave(false);if(kind==='calendar')return calendarSave();if(kind==='wellness')return routineSave();if(D.checks[kind]&&!D.feeds[kind])return checklistSave();if(kind==='products')productResult();T.save(current,state);}catch(err){U.notice(err.message);}}
 function explore(q,type){collect();window.LivonExplore.openResults(q,{type:type||'',categoryId:'',region:state.region==='전체'?'':state.region||''});}
 function tabs(names){return '<nav class="lv-youth-tabs" aria-label="상세 분야">'+names.map(function(n,i){return '<a href="#life-service-'+current.id+'/'+i+'" class="lv-life-btn lv-life-btn--'+(String(i)===(parts[1]||'0')?'dark':'outline')+'"'+(String(i)===(parts[1]||'0')?' aria-current="page"':'')+'>'+e(n)+'</a>';}).join('')+'</nav>';}
 function checkRows(){var rows=[];Object.keys(D.checks[kind]||{}).forEach(function(g){D.checks[kind][g].forEach(function(text,i){rows.push({key:g+'-'+i,group:g,text:text});});});return rows;}
 function checklist(){var groups=Object.keys(D.checks[kind]||{}),tab=groups[Number(parts[1]||0)]||groups[0];return (groups.length>1?tabs(groups):'')+'<div class="lv-family-checks">'+checkRows().filter(function(x){return groups.length===1||x.group===tab;}).map(function(x){var key=x.key;return '<fieldset class="lv-family-task"><legend>'+e(x.text)+'</legend><label class="lv-family-check"><input type="checkbox" name="done_'+e(key)+'" />완료</label>'+field(['due_'+key,'예정일','date'])+(kind==='wedding'?field(['estimate_'+key,'예상 비용 (원)','number'])+field(['actual_'+key,'실제 비용 (원)','number']):'')+field(['note_'+key,'메모','text'])+'</fieldset>';}).join('')+'</div>';}
 function checklistSave(){collect();var s=T.read(),id='service-checklist:'+current.id,old=s.checklists.find(function(x){return x.id===id;}),rows=checkRows().map(function(x){return {id:x.key,text:x.group+' · '+x.text,done:!!state['done_'+x.key],due:state['due_'+x.key]||'',note:state['note_'+x.key]||'',estimate:T.amount(state['estimate_'+x.key]),actual:T.amount(state['actual_'+x.key])};});T.upsert(s.checklists,{id:id,title:current.name,desc:'라이프 스테이지 · 30대',items:rows,createdAt:old?old.createdAt:Date.now(),updatedAt:Date.now()});if(T.write(s))T.save(current,state);}
 function finance(){return section('이번 달 가계 계획','<p>각 항목은 한 달 기준입니다. 목표별 금액은 매달 저축할 금액이며 금융상품을 추천하지 않습니다.</p>'+form(D.budgetGroups.map(function(g,i){return group(g[0],g[1].map(function(label,j){return field(['b'+i+'_'+j,label+' (원)','number']);}).join(''));}).join(''),'가계 계획 계산'))+action('내 생활에 저장','finance-save',true)+action('저축 목표 만들기','goals');}
 function budgetResult(){var b=T.budget(state,D.budgetGroups),total=b.fixed+b.variable+b.saving,segments=[['고정비',b.fixed],['생활비',b.variable],['목표 저축',b.saving]];result(section('이번 달 가계 계획','<dl class="lv-youth-summary">'+[['총수입',b.income],['고정비',b.fixed],['변동비',b.variable],['예상 잔액',b.balance],['목표 저축',b.saving]].map(function(x){return '<div><dt>'+x[0]+'</dt><dd>'+x[1].toLocaleString('ko-KR')+'<small>원</small></dd></div>';}).join('')+'<div><dt>저축률</dt><dd>'+(b.rate===null?'계산 불가':b.rate.toFixed(1)+'%')+'</dd></div></dl><div class="lv-family-breakdown" aria-label="계획한 지출 및 저축 비중">'+segments.map(function(x){return '<div><span>'+x[0]+'</span><meter min="0" max="'+(total||1)+'" value="'+x[1]+'"></meter><strong>'+ (total?Math.round(x[1]/total*100):0)+'%</strong></div>';}).join('')+'</div><p>'+(b.balance<0?'계획한 지출·저축이 수입보다 많습니다. 금액을 조정해 주세요.':'사용자가 입력한 월 계획이며 실제 거래 내역과는 다릅니다.')+'</p>'));return b;}
 function weddingResult(){var rows=checkRows(),estimate=0,actual=0;rows.forEach(function(x){estimate+=T.amount(state['estimate_'+x.key]);actual+=T.amount(state['actual_'+x.key]);});result(section('결혼 준비 예산',U.list(['전체 예산: '+T.amount(state.budget).toLocaleString()+'원','예상 비용 합계: '+estimate.toLocaleString()+'원','실제 비용 합계: '+actual.toLocaleString()+'원','전체 예산 대비 실제 잔액: '+(T.amount(state.budget)-actual).toLocaleString()+'원'])+'<p>입력하지 않은 업체 가격은 합계에 포함하지 않습니다.</p>'+action('예산 저장','save')+action('예정일을 일정에 추가','wedding-calendar')));}
 function products(){return section('직접 확인한 육아용품 비교','<p>제품명과 공식 페이지에서 확인한 정보를 직접 입력하세요. 확인하지 않은 가격·재고·후기는 만들지 않습니다.</p>'+form(controls()+[0,1,2].map(function(i){return group('제품 '+(i+1),U.input('p'+i,'제품명','text','maxlength="150"'+(i<2?' required':''))+['가격','크기','무게','사용 연령','주요 기능','설치','휴대성','관리 방법'].map(function(t,j){return field(['p'+i+'_'+j,t,'text']);}).join(''));}).join(''),'비교하기'))+action('비교 목록 저장','save')+action('상품 탐색','commerce');}
 function productResult(){var rows=[0,1,2].filter(function(i){return state['p'+i]&&state['p'+i].trim();});if(rows.length<2)throw Error('비교할 제품을 2개 이상 입력해 주세요.');result('<div class="lv-youth-compare">'+rows.map(function(i){return '<article class="lv-life-svc"><h4>'+e(state['p'+i])+'</h4><dl>'+['가격','크기','무게','사용 연령','주요 기능','설치','휴대성','관리 방법'].map(function(t,j){return '<dt>'+t+'</dt><dd>'+e(state['p'+i+'_'+j]||'미입력')+'</dd>';}).join('')+'</dl></article>';}).join('')+'</div>');}
 function calendar(){return section('가족의 일정을 한곳에서','<p>일정은 이 브라우저의 내 생활에 저장됩니다. 가족 초대·계정 동기화·알림 발송은 아직 연결되지 않았습니다. 반복은 최대 12회까지 실제 일정으로 생성합니다.</p>'+form(fields([['title','제목','text'],['date','날짜','date'],['time','시간','time'],['members','참여 가족 · 쉼표로 구분','text'],['place','장소','text'],['category','일정 종류',['가족','아이','병원','학교/어린이집','기념일','여행','생활','기타']],['reminder','알림 희망 · 메모만 저장',['없음','5분 전','30분 전','하루 전']],['repeat','반복',['없음','매주','매월']],['count','반복 횟수 · 최대 12회','number'],['note','메모','text']]),'일정 저장')+action('새 일정 작성','new-event'))+section('내 가족 일정','<div class="lv-life-svc__acts">'+['오늘','주간','월간'].map(function(v){return action(v,'view-'+v);}).join('')+'</div><label>확인할 기준 날짜<input type="date" data-family-calendar-date value="'+e(state.viewDate||T.day(new Date()))+'" /></label><div data-family-calendar aria-live="polite"></div>');}
 function calendarList(){var n=host.querySelector('[data-family-calendar]');if(!n)return;var date=state.viewDate||T.day(new Date()),view=state.view||'월간',d=new Date(date+'T12:00:00'),start=date,end=date;if(view==='월간'){start=date.slice(0,7)+'-01';end=date.slice(0,7)+'-31';}if(view==='주간'){d.setDate(d.getDate()-(d.getDay()+6)%7);start=T.day(d);d.setDate(d.getDate()+6);end=T.day(d);}var rows=T.read().events.filter(function(x){return (x.source==='life-stage-30'||x.id.indexOf('family-')===0)&&x.date>=start&&x.date<=end;}).sort(function(a,b){return (a.date+a.start).localeCompare(b.date+b.start);});n.innerHTML='<p>'+e(view+' · '+start+' ~ '+end)+'</p>'+(rows.length?'<ul class="lv-teen-ledger">'+rows.map(function(x){return '<li><div><strong>'+e(x.title)+'</strong><span>'+e(x.date+' '+(x.start||'종일')+' · '+(x.familyMembers||[]).join(', '))+'</span></div>'+U.button('수정','data-family-edit="'+e(x.id)+'"')+'</li>';}).join('')+'</ul>':T.status('empty','가족 일정'))+U.link('내 생활 달력에서 관리','#ml-calendar');}
 function wellness(){var start=state.week||T.day((function(){var d=new Date();d.setDate(d.getDate()-(d.getDay()+6)%7);return d;})());return section('생활 속 작은 루틴','<p>질환 치료나 처방을 위한 도구가 아닙니다. 운동과 식사, 생활 습관을 직접 기록하세요.</p>'+form(controls()+field(['week','기록 주의 시작일','date'])+'<div class="lv-family-week">'+['월','화','수','목','금','토','일'].map(function(day,i){return '<details'+(i===0?' open':'')+'><summary>'+day+'요일 기록</summary><div class="lv-family-task"><label><input type="checkbox" name="exercise'+i+'" />운동 완료</label><label><input type="checkbox" name="habit'+i+'" />생활 습관 완료</label>'+['아침','점심','저녁','간식','물'].map(function(t,j){return field(['meal'+i+'_'+j,t,'text']);}).join('')+'</div></details>';}).join('')+'</div>','루틴 저장'))+action('내 생활에 추가','routine-save')+action('관련 활동 찾기','activities');}
 function sourceDetail(x){return section(x.title,'<dl class="lv-teen-detail">'+[['소개','description'],['대상','target'],['주소','address'],['운영시간','hours'],['일정','date'],['비용','price'],['제공 서비스','services'],['문의 방법','contact'],['출처','source'],['마지막 확인','lastVerifiedAt']].map(function(pair){return '<div><dt>'+pair[0]+'</dt><dd>'+e(x[pair[1]]===undefined?'공식 정보 확인 필요':x[pair[1]])+'</dd></div>';}).join('')+'</dl>'+U.link('공식 정보 확인',x.sourceUrl,true)+action('이 항목 저장','source-save')+(T.date(x.date)?action('일정 추가','source-calendar'):''));}
 function sourceResults(){var n=host.querySelector('[data-family-source]');if(!n)return;var feed=T.source(D.feeds[kind],state);n.innerHTML=T.status(feed.state,current.name)+(feed.items.length?'<div class="lv-ls-results">'+feed.items.map(function(x){return '<article class="lv-life-svc"><h4>'+e(x.title)+'</h4><p>'+e(x.description||'')+'</p><p>출처: '+e(x.source||x.sourceUrl)+' · '+e(x.lastVerifiedAt)+'</p>'+U.link('상세 정보','#life-service-'+current.id+'/item/'+x.id,true)+'</article>';}).join('')+'</div>':'');}
 function sourceView(){var src=D.sources[kind];return section(kind==='health'?'공식 기준을 먼저 확인하세요.':kind==='childcare'?'아이의 단계에 맞는 정보':'조건에 맞는 정보 찾기',form(controls(),'조건 확인'))+section('공식 정보',''+'<p>'+(kind==='health'?'검진 대상·주기·검사항목은 현재 조회할 수 없습니다. 공단에서 본인의 대상 여부와 최신 기준을 확인해 주세요.':'선택한 단계·분야의 공식 자료를 확인해 보세요. 개별 프로그램이나 시설 정보는 아직 연결되지 않았습니다.')+'</p>'+U.link(src[0],src[1],true)+'<p class="lv-teen-caption">출처: '+e(src[0])+' · 연결 확인 2026-09-27</p>'+(kind==='childcare'?action('확인 체크리스트 만들기','checklist'):kind==='health'?action('검진 일정 직접 추가','health-calendar')+U.link('검진기관 공식 확인',src[1]):'')+'<div data-family-source></div>');}
 function experience(){return section('함께할 경험을 찾아보세요.',form(controls(),'관련 콘텐츠 보기'))+'<p>오늘의 발견과 같은 콘텐츠를 사용합니다. 날짜·가족 연령·예산·이동시간·숙박은 아직 실시간 조회할 수 없어 검색 메모로 저장하며 결과에는 적용하지 않습니다.</p>';
 }
 function experienceResult(){var rows=((window.LivonTodayData||{}).contents||[]).filter(function(x){var text=[x.title,x.blurb,(x.tags||[]).join(' ')].join(' ');return /가족|아이|키즈|체험|여행|자연|공원|전시|공연/.test(text)&&(!state.category||state.category==='전체'||text.includes(state.category))&&(!state.region||state.region==='전체'||x.region===state.region)&&(!state.place||state.place==='전체'||x.indoorOutdoor===state.place);});result('<p>선택 조건 중 분야·지역·실내/야외를 적용한 등록 콘텐츠입니다. 실제 날짜·이용 대상·가격은 공식 정보에서 확인하세요.</p><div class="lv-ls-results">'+rows.slice(0,12).map(function(x){return '<article class="lv-life-svc"><img class="lv-youth-image" src="'+e(x.img)+'" alt="'+e(x.alt||'')+'" loading="lazy"/><h4>'+e(x.title)+'</h4><p>'+e(x.blurb)+'</p>'+U.link('오늘의 발견에서 보기','#td-item-'+x.id,true)+U.button('관심 저장','data-family-content="'+e(x.id)+'"')+U.link('가족 일정 직접 추가',href(9))+'</article>';}).join('')+'</div>'+(rows.length?'':T.status('empty','등록 콘텐츠')));}
 function render(s,p){current=s;parts=p;kind=s.detail.replace('family-','');state=T.load(s);selected=null;
  var old=T.read().checklists.find(function(x){return x.id==='service-checklist:'+s.id;});if(old&&(!state.updatedAt||old.updatedAt>state.updatedAt)){old.items.forEach(function(x){state['done_'+x.id]=x.done;['due','note','estimate','actual'].forEach(function(k){if(x[k]!==undefined)state[k+'_'+x.id]=String(x[k]);});});}
  if(kind==='wellness'&&state.week){var routine=T.read().checklists.find(function(x){return x.id==='family-routine-'+state.week;});if(routine&&(!state.updatedAt||routine.updatedAt>state.updatedAt))routine.items.forEach(function(x){state[x.id]=x.done;});}
  var body='';
  if(kind==='finance')body=finance();else if(kind==='products')body=products();else if(kind==='calendar')body=calendar();else if(kind==='wellness')body=wellness();else if(D.feeds[kind])body=sourceView();else if(kind==='experience')body=experience();else if(D.checks[kind])body=section(kind==='career'?'커리어 전환 로드맵':kind==='wedding'?'함께 준비하는 결혼':'이사부터 공간 준비까지',form(controls()+checklist(),kind==='career'?'로드맵 저장':'체크리스트 저장'))+'<div class="lv-life-svc__acts">'+(kind==='career'?action('교육 찾기','education')+U.link('채용 정보 보기','#life-service-service-20-06')+U.link('멘토 찾기',href(5)):kind==='moving'?U.link('생활 서비스 찾기',href(14))+action('가구·가전 찾기','commerce'):'')+'</div>';else body=section(kind==='housing'?'나에게 맞는 주거 조건':kind==='mentor'?'어떤 도움이 필요한가요?':'생활에 필요한 도움',form(controls(),kind==='mentor'?'전문가 탐색':kind==='home'?'생활 서비스 탐색':'주거 조건 정리'))+'<p>입력한 조건을 정리하고 기존 탐색으로 연결합니다. 실제 매물·업체·가격·예약 정보는 만들어 제공하지 않습니다.</p>'+(kind==='housing'?action('주거 서비스 탐색','housing'):'');
  if(parts[1]==='item'&&D.feeds[kind]){var record=T.source(D.feeds[kind],{}).items.find(function(x){return x.id===parts[2];});selected=record||null;body=record?sourceDetail(record):section('정보를 찾을 수 없습니다.',U.link('검색으로 돌아가기','#life-service-'+s.id));}
  return quick()+body+related();
 }
 function mount(s,node){host=node;var f=host.querySelector('[data-family-form]');if(f){if(kind==='wellness'&&!state.week){var d=new Date();d.setDate(d.getDate()-(d.getDay()+6)%7);state.week=T.day(d);}Object.keys(state).forEach(function(k){var c=f.elements.namedItem(k);if(c){if(c.type==='checkbox')c.checked=!!state[k];else if(typeof state[k]!=='object')c.value=state[k];}});}if(kind==='finance'&&state.calculated)budgetResult();if(kind==='wedding')weddingResult();if(kind==='products'&&state.p0&&state.p1)productResult();if(kind==='experience')experienceResult();if(kind==='calendar')calendarList();if(D.feeds[kind])sourceResults();}
 function ask(){collect();var data=selected?{검증된정보:selected}:{},l=labels();Object.keys(l).forEach(function(k){if(state[k])data[l[k]]=state[k];});if(kind==='finance')data['가계 계획']=T.budget(state,D.budgetGroups);if(kind==='wedding'||kind==='career'||kind==='moving')data['완료 항목']=checkRows().filter(function(x){return state['done_'+x.key];}).map(function(x){return x.text;});if(kind==='products')data['직접 입력한 비교']=state;if(kind==='wellness')data['주간 생활 기록']=state;if(kind==='calendar')data={제목:state.title,날짜:state.date,시간:state.time,반복:state.repeat};return U.ask(current,'사용자가 직접 입력한 조건/계획입니다. 실제 매물·기관·프로그램·예약을 연결된 것으로 가정하지 마세요. 의료 진단·개인 처방·금융상품 추천을 하지 마세요.\n'+JSON.stringify(data));}
 function financeSave(goals){collect();var b=budgetResult(),s=T.read();s.budgets.household={...b,values:state,updatedAt:Date.now()};s.budgets.monthly=b.fixed+b.variable;if(goals)D.budgetGroups[3][1].forEach(function(title,i){var target=T.amount(state['b3_'+i]);if(target)T.upsert(s.goals,{id:'household-goal-'+i,title:title+' · 월 저축 목표',category:'재무',note:'가계 계획에서 설정한 월 목표 금액 '+target.toLocaleString()+'원',target:target,progress:(s.goals.find(function(g){return g.id==='household-goal-'+i;})||{}).progress||0,status:(s.goals.find(function(g){return g.id==='household-goal-'+i;})||{}).status||'진행 중',start:T.day(new Date()),due:'',updatedAt:Date.now()});});if(T.write(s))T.save(current,state);}
 function routineWeek(week){var saved=T.read().checklists.find(function(x){return x.id==='family-routine-'+week;});for(var i=0;i<7;i++){state['exercise'+i]=false;state['habit'+i]=false;for(var j=0;j<5;j++)state['meal'+i+'_'+j]='';}if(saved){saved.items.forEach(function(x){state[x.id]=x.done;});Object.keys(saved.daily||{}).forEach(function(k){state[k]=saved.daily[k];});}state.week=week;T.draft(current,state);}
 function routineSave(){collect();if(!T.date(state.week)||new Date(state.week+'T12:00:00').getDay()!==1)throw Error('기록 주의 월요일을 선택해 주세요.');if(Number(state.count||0)>7)throw Error('주간 목표 횟수는 0~7회로 입력해 주세요.');var s=T.read(),id='family-routine-'+state.week,items=[],daily={};Object.keys(state).filter(function(k){return /^meal[0-6]_[0-4]$/.test(k);}).forEach(function(k){daily[k]=state[k];});for(var i=0;i<7;i++){var d=new Date(state.week+'T12:00:00');d.setDate(d.getDate()+i);var day=T.day(d);items.push({id:'exercise'+i,text:day+' · '+(state.exercise||'운동')+' / '+(state.time||'시간 미지정'),done:!!state['exercise'+i]});items.push({id:'habit'+i,text:day+' · '+(state.goal||'생활 습관'),done:!!state['habit'+i]});}T.upsert(s.checklists,{id:id,title:'운동·생활 루틴 · '+state.week,desc:'식사 기록은 저장함의 운동·영양에서 확인',daily:daily,items:items,updatedAt:Date.now(),createdAt:Date.now()});T.upsert(s.habits,{id:'family-wellness',title:state.goal||'생활 습관',freq:'weekly',note:state.exercise||'',updatedAt:Date.now()});if(T.write(s))T.save(current,state);}
 function calendarSave(){collect();var id=state.seriesId||'family-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),rows=T.calendar(state,id),s=T.read();s.events=s.events.filter(function(x){return x.seriesId!==id&&x.id!==state.editId;});rows.forEach(function(x){T.upsert(s.events,x);});if(T.write(s)){state.seriesId=id;state.viewDate=state.date;T.save(current,state);calendarList();}}
 function datedChecklist(){collect();var s=T.read(),count=0;checkRows().forEach(function(x){var date=state['due_'+x.key];if(T.date(date)){T.upsert(s.events,{id:'family-wedding-'+x.key,title:'결혼 준비 · '+x.text,date:date,start:'',end:'',allDay:true,category:'가족',note:state['note_'+x.key]||'',source:'life-stage-30',updatedAt:Date.now()});count++;}});if(T.date(state.date)){T.upsert(s.events,{id:'family-wedding-day',title:'결혼 예정일',date:state.date,start:'',end:'',allDay:true,category:'기념일',source:'life-stage-30',updatedAt:Date.now()});count++;}if(!count)throw Error('일정에 추가할 예정일을 먼저 입력해 주세요.');if(T.write(s))U.notice(count+'개 일정을 내 생활에 반영했습니다.');}
 function run(name){if(name==='health-calendar'){var target=window.LivonServices.all().find(function(x){return x.id==='service-30-09';});T.draft(target,{title:'건강검진 일정',category:'병원',repeat:'없음',count:'1'});location.hash=href(9);return;}if(name==='source-save'&&selected){window.LivonPlatform.saveItem({id:'source:'+selected.id,title:selected.title,label:selected.title,type:current.type,href:location.hash,source:selected.source||'공식 정보',lifeStage:'30'});return U.notice('내 생활 저장함에 저장했습니다.');}if(name==='source-calendar'&&selected&&T.date(selected.date)){var data=T.read();T.upsert(data.events,{id:'source:'+selected.id,title:selected.title,date:selected.date,start:'',end:'',allDay:true,category:'가족',note:selected.sourceUrl,source:'life-stage-30',updatedAt:Date.now()});if(T.write(data))U.notice('내 일정에 저장했습니다.');return;}if(name==='save')return saved();if(name==='ai')return ask();if(name==='finance-save'||name==='goals')return financeSave(name==='goals');if(name==='routine-save')return routineSave();if(name==='wedding-calendar')return datedChecklist();if(name==='checklist')return checklistSave();if(name==='education')return explore(state.education||'교육','program');if(name==='housing')return explore('주거','');if(name==='commerce')return explore(kind==='products'?state.category||'육아용품':'가구 가전','product');if(name==='activities')return explore(state.exercise||'운동','program');if(name.indexOf('view-')===0){state.view=name.slice(5);T.draft(current,state);return calendarList();}if(name==='new-event'){['title','date','time','members','place','note','seriesId','editId','count'].forEach(function(k){delete state[k];});state.repeat='없음';T.draft(current,state);window.LivonServices.open(location.hash.slice(1));}}
 function active(){return current&&location.hash.indexOf('#life-service-'+current.id)===0;}
 document.addEventListener('submit',function(ev){if(!active()||!ev.target.matches('[data-family-form]'))return;ev.preventDefault();collect();try{if(kind==='finance'){state.calculated=true;T.draft(current,state);return budgetResult();}if(kind==='products')return productResult();if(kind==='calendar')return calendarSave();if(kind==='wellness')return routineSave();if(D.checks[kind]&&!D.feeds[kind]){checklistSave();if(kind==='wedding')weddingResult();return;}if(kind==='mentor')return explore(state.field+' '+state.topic,'expert');if(kind==='home')return explore(state.category,'service');if(kind==='experience')return experienceResult();result(section('선택한 조건',summary()+action('내 생활에 저장','save',true)));if(D.feeds[kind])sourceResults();}catch(err){U.notice(err.message);}});
 document.addEventListener('change',function(ev){if(!active()||!host.contains(ev.target))return;if(ev.target.matches('[data-family-calendar-date]')){if(!T.date(ev.target.value))return U.notice('확인할 날짜를 선택해 주세요.');state.viewDate=ev.target.value;T.draft(current,state);return calendarList();}if(kind==='wellness'&&ev.target.name==='week'){routineWeek(ev.target.value);return window.LivonServices.open(location.hash.slice(1));}collect();});
 document.addEventListener('click',function(ev){if(!active())return;var b=ev.target.closest('[data-family-action], [data-family-edit], [data-family-content]');if(!b)return;try{if(b.dataset.familyEdit){var x=T.read().events.find(function(v){return v.id===b.dataset.familyEdit;});if(x){state={...state,...x,time:x.start,members:(x.familyMembers||[]).join(', '),editId:x.id,seriesId:'',repeat:'없음',count:1};T.draft(current,state);window.LivonServices.open(location.hash.slice(1));}return;}if(b.dataset.familyContent){var x=(window.LivonTodayData.contents||[]).find(function(v){return v.id===b.dataset.familyContent;});if(x){window.LivonPlatform.saveItem({id:'td:'+x.id,title:x.title,label:x.title,type:'Discovery',href:'#td-item-'+x.id,source:'오늘의 발견',lifeStage:'30'});U.notice('내 생활 저장함에 저장했습니다.');}return;}collect();run(b.dataset.familyAction);}catch(err){U.notice(err.message);}});
 window.LivonFamily={render:render,mount:mount,ask:ask,save:saved};
})();
