window.LivonTodayData = {
  checkedAt: "2026-09-25",
  interests: ["여행", "맛집", "카페", "문화", "공연", "전시", "스포츠", "취미", "교육", "자기계발", "건강", "자연", "지역 활동", "생활 정보"],
  regions: ["서울", "경기", "인천", "부산", "대구", "광주", "대전", "전국", "온라인"],
  budgets: ["무료", "1만 원 이하", "1만~3만 원", "3만~5만 원", "5만~10만 원", "10만 원 이상"],
  companions: ["혼자", "연인", "친구", "가족", "자녀", "부모님", "새로운 사람들"],
  activityTypes: ["산책", "관람", "체험", "배움", "운동", "미식", "여행"],
  placePrefs: ["실내", "야외", "상관없음"],
  modePrefs: ["오프라인", "온라인", "상관없음"],
  statusLabel: { guide: "가이드", info: "정보 안내", link: "공식 연결", evergreen: "상시 추천" },
  contents: [
    {
      id: "place-hangang",
      type: "place",
      category: "공원",
      title: "한강공원에서 하루를 열어보기",
      blurb: "산책·피크닉·자전거까지. 가까운 강변에서 하루의 리듬을 바꿔 보세요.",
      body: "한강공원은 구간마다 분위기와 편의시설이 다릅니다. 공식 안내에서 구간별 시설·주차·안전을 확인한 뒤 방문하세요. 운영·시설 정보는 변경될 수 있습니다.",
      img: "/livon/assets/topics/hangang.jpg",
      alt: "강변을 걷는 사람들",
      tags: ["자연", "여행", "건강", "가족"],
      region: "서울",
      address: "서울 한강공원 일대 (구간별 상이)",
      hours: "상시 · 구간·시설별 상이",
      price: "무료 (일부 시설 유료)",
      indoorOutdoor: "야외",
      companion: ["혼자", "연인", "친구", "가족"],
      budget: "무료",
      source: "서울특별시 한강사업본부",
      officialUrl: "https://hangang.seoul.go.kr/",
      status: "info",
      featured: true,
      evergreen: true,
      reason: "가까운 야외 공간에서 가벼운 휴식을 원할 때",
      layout: "feature",
      sections: ["hero", "place", "season", "together"],
      seasons: ["spring", "summer", "autumn"],
      links: { explore: "#explore", lifeNow: "#life-now", community: "#community", ai: "한강공원에서 하루 일정을 추천해 줘." }
    },
    {
      id: "place-namsan",
      type: "place",
      category: "산책로",
      title: "남산 산책로, 도심 속 전망 코스",
      blurb: "짧은 산책으로도 도심을 내려다볼 수 있는 대표 코스입니다.",
      body: "남산 일대는 산책로·공원·전망 포인트가 연결되어 있습니다. 공식 안내의 개방 시간과 교통편을 확인하고, 혼잡 시간대를 피하면 더 여유롭게 즐길 수 있습니다.",
      img: "/livon/assets/topics/namsan.jpg",
      alt: "도심 야경 전망",
      tags: ["여행", "건강", "연인", "자연"],
      region: "서울",
      address: "서울 중구·용산구 남산 일대",
      hours: "공원·시설별 상이",
      price: "공원 산책 무료 (일부 시설 유료)",
      indoorOutdoor: "야외",
      companion: ["혼자", "연인", "친구"],
      budget: "무료",
      source: "서울의 공원 / 남산공원 안내",
      officialUrl: "https://parks.seoul.go.kr/",
      status: "info",
      featured: true,
      evergreen: true,
      reason: "도심에서 짧은 야외 산책을 원할 때",
      layout: "place",
      sections: ["hero", "place"],
      links: { explore: "#explore", lifeNow: "#ml-saved", ai: "남산 산책 코스를 짧게 짜 줘." }
    },
    {
      id: "place-mmca",
      type: "place",
      category: "미술관",
      title: "국립현대미술관으로 가는 문화 하루",
      blurb: "전시·교육·공간 안내를 공식 사이트에서 확인하고 관람을 계획하세요.",
      body: "국립현대미술관은 과천·서울·청주·덕수궁 등 관별로 전시와 운영이 다릅니다. 현재 전시·관람 시간·예약 여부는 반드시 공식 사이트에서 확인하세요. 임의로 전시 일정이나 입장료를 기재하지 않습니다.",
      img: "/livon/assets/topics/museum.jpg",
      alt: "미술관 전시 공간",
      tags: ["문화", "전시", "교육", "혼자"],
      region: "서울",
      address: "관별 상이 (공식 안내 참고)",
      hours: "관별·전시별 상이",
      price: "전시·프로그램별 상이",
      indoorOutdoor: "실내",
      companion: ["혼자", "연인", "친구", "가족"],
      budget: "1만~3만 원",
      source: "국립현대미술관",
      officialUrl: "https://www.mmca.go.kr/",
      status: "link",
      featured: true,
      evergreen: true,
      reason: "검증된 문화 공간에서 전시를 만나고 싶을 때",
      layout: "feature",
      sections: ["hero", "place", "week"],
      links: { explore: "#ex-categories", community: "#community", lifeNow: "#life-now", ai: "이번 주 미술관 관람 계획을 세워 줘." }
    },
    {
      id: "place-library",
      type: "place",
      category: "도서관",
      title: "국립중앙도서관에서 하루 공부·독서",
      blurb: "열람·디지털 자료·문화 프로그램을 공식 안내로 확인하세요.",
      body: "국립중앙도서관은 열람실·자료·행사 이용 조건이 있습니다. 회원가입·좌석·프로그램은 공식 안내를 따르고, 변경될 수 있는 운영 정보는 확인 날짜와 함께 공식 페이지를 기준하세요.",
      img: "/livon/assets/topics/library.jpg",
      alt: "도서관 열람 공간",
      tags: ["교육", "자기계발", "문화", "혼자"],
      region: "서울",
      address: "서울 서초구 반포대로 201",
      hours: "공식 안내 참고",
      price: "기본 이용 무료 (일부 유료)",
      indoorOutdoor: "실내",
      companion: ["혼자", "친구"],
      budget: "무료",
      source: "국립중앙도서관",
      officialUrl: "https://www.nl.go.kr/",
      status: "info",
      evergreen: true,
      reason: "조용한 실내 배움·독서 공간을 찾을 때",
      layout: "place",
      sections: ["place", "learn"],
      links: { explore: "#explore", lifeNow: "#ml-goals", life: "#life" }
    },
    {
      id: "exp-pottery",
      type: "experience",
      category: "도자기",
      title: "도자기 원데이, 손으로 만드는 첫 취미",
      blurb: "초보자도 따라갈 수 있는 공예 입문. 클래스 예약은 탐색·공식 신청으로 연결합니다.",
      body: "도자기는 흙을 만지며 집중과 성취감을 얻기 좋은 취미입니다. 난이도는 보통 초급부터 시작합니다. 준비물·소요 시간·비용은 운영 기관마다 다르므로, 신청 전 공식 안내를 확인하세요. LIVON은 예약·결제를 대신 수행하지 않습니다.",
      img: "/livon/assets/topics/pottery.jpg",
      alt: "도자기 만드는 손",
      tags: ["취미", "체험", "자기계발"],
      region: "전국",
      difficulty: "초급",
      duration: "2–3시간",
      price: "클래스별 상이",
      indoorOutdoor: "실내",
      onlineOffline: "오프라인",
      companion: ["혼자", "연인", "친구"],
      budget: "3만~5만 원",
      source: "LIVON 체험 가이드",
      status: "guide",
      featured: true,
      evergreen: true,
      reason: "손으로 만드는 새로운 취미를 시작할 때",
      layout: "experience",
      sections: ["hobby", "week", "hero"],
      links: { explore: "#explore", community: "#community", lifeNow: "#life-now", ai: "초보 도자기 클래스 고르는 기준을 알려 줘." }
    },
    {
      id: "exp-baking",
      type: "experience",
      category: "베이킹",
      title: "집에서도, 클래스에서도 — 베이킹 입문",
      blurb: "소요 시간과 난이도를 기준으로 첫 레시피를 고르는 가이드입니다.",
      body: "베이킹은 재료 계량과 순서만 지키면 초보자도 도전하기 쉽습니다. 온라인 레시피와 오프라인 원데이 클래스 중 선호에 맞게 선택하세요. 실제 클래스 일정·가격은 운영처 공식 정보를 확인하세요.",
      img: "/livon/assets/topics/baking.jpg",
      alt: "갓 구운 빵",
      tags: ["취미", "맛집", "자기계발"],
      difficulty: "초급",
      duration: "1–3시간",
      indoorOutdoor: "실내",
      onlineOffline: "상관없음",
      companion: ["혼자", "가족", "친구"],
      budget: "1만~3만 원",
      source: "LIVON 체험 가이드",
      status: "guide",
      evergreen: true,
      reason: "주말에 집에서 할 수 있는 취미를 원할 때",
      layout: "experience",
      sections: ["hobby", "together"],
      links: { today: "#td-hobby", community: "#community", ai: "초보 베이킹 주말 계획을 세워 줘." }
    },
    {
      id: "exp-yoga",
      type: "experience",
      category: "요가",
      title: "가벼운 요가·스트레칭으로 몸 풀기",
      blurb: "실내 운동 입문. 온라인 루틴과 스튜디오 수업을 구분해 안내합니다.",
      body: "요가는 유연성과 호흡에 초점을 둔 운동입니다. 건강 상태가 걱정되면 전문가와 상담하세요. LIVON은 의료 조언을 대체하지 않습니다. 수업 예약은 탐색 또는 스튜디오 공식 채널을 이용하세요.",
      img: "/livon/assets/topics/yoga.jpg",
      alt: "요가 동작",
      tags: ["건강", "스포츠", "취미"],
      difficulty: "초급",
      duration: "20–60분",
      indoorOutdoor: "실내",
      onlineOffline: "상관없음",
      companion: ["혼자", "친구"],
      budget: "무료",
      source: "LIVON 웰니스 가이드",
      status: "guide",
      evergreen: true,
      reason: "부담 없는 실내 운동을 시작할 때",
      layout: "experience",
      sections: ["hobby", "everyday"],
      links: { explore: "#explore", lifeNow: "#ml-goals", life: "#stage-30" }
    },
    {
      id: "exp-photo",
      type: "experience",
      category: "사진",
      title: "스마트폰으로 시작하는 거리 사진",
      blurb: "장비 없이도 가능한 관찰 습관과 촬영 루틴 가이드.",
      body: "거리 사진은 빛·구도·이야기를 관찰하는 연습입니다. 타인의 초상권과 장소 규칙을 존중하세요. 원데이 클래스나 커뮤니티 모임은 탐색·커뮤니티로 연결합니다.",
      img: "/livon/assets/topics/photo.jpg",
      alt: "카메라로 도시 풍경 촬영",
      tags: ["취미", "여행", "문화"],
      difficulty: "초급",
      duration: "1–2시간",
      indoorOutdoor: "야외",
      companion: ["혼자", "친구"],
      budget: "무료",
      source: "LIVON 체험 가이드",
      status: "guide",
      evergreen: true,
      reason: "산책과 창작을 함께 하고 싶을 때",
      layout: "experience",
      sections: ["hobby", "place"],
      links: { community: "#community", today: "#td-places" }
    },
    {
      id: "learn-kmooc",
      type: "learn",
      category: "무료 온라인 강의",
      title: "K-MOOC에서 관심 강의 찾아보기",
      blurb: "대학·기관이 제공하는 온라인 공개강좌 포털입니다.",
      body: "K-MOOC는 다양한 주제의 온라인 강의를 제공합니다. 수강 신청·이수 조건·수료증은 강의마다 다릅니다. 일정 관리는 내 생활에서, 관련 오프라인 교육은 탐색에서 이어가세요.",
      img: "/livon/assets/topics/study.jpg",
      alt: "노트북으로 학습하는 모습",
      tags: ["교육", "자기계발", "디지털"],
      region: "온라인",
      difficulty: "초급–중급",
      duration: "강의별 상이",
      price: "대부분 무료 (일부 유료)",
      onlineOffline: "온라인",
      companion: ["혼자"],
      budget: "무료",
      source: "K-MOOC",
      officialUrl: "https://www.kmooc.kr/",
      status: "link",
      featured: true,
      evergreen: true,
      reason: "집에서도 새로운 지식을 시작하고 싶을 때",
      layout: "learn",
      sections: ["learn", "hero", "week"],
      links: { lifeNow: "#ml-goals", explore: "#explore", life: "#life", ai: "이번 달 온라인 학습 계획을 세워 줘." }
    },
    {
      id: "learn-finance",
      type: "learn",
      category: "금융 기초",
      title: "생활 금융 기초, 먼저 알아둘 개념",
      blurb: "예산·저축·소비의 기본 개념 정리. 개별 투자 조언이 아닙니다.",
      body: "생활 금융은 수입·지출을 기록하고 목표를 나누는 것부터 시작합니다. 이 콘텐츠는 일반 정보이며 금융·투자 상품 추천이나 전문 상담을 대체하지 않습니다. 필요 시 공인된 기관·전문가를 탐색에서 확인하세요.",
      img: "/livon/assets/topics/finance.jpg",
      alt: "노트와 계산기",
      tags: ["교육", "생활 정보", "자기계발"],
      difficulty: "초급",
      duration: "20분 읽기",
      onlineOffline: "온라인",
      budget: "무료",
      source: "LIVON 생활 가이드",
      status: "guide",
      evergreen: true,
      reason: "돈 관리의 기본 개념을 정리하고 싶을 때",
      layout: "editorial",
      sections: ["learn", "everyday"],
      links: { lifeNow: "#life-now", explore: "#explore", ai: "주간 생활비 기록 체크리스트를 만들어 줘." }
    },
    {
      id: "learn-digital-senior",
      type: "learn",
      category: "시니어 디지털 교육",
      title: "스마트폰·키오스크, 천천히 익히기",
      blurb: "시니어 디지털 교육의 출발점. 지역 프로그램은 공식 기관 안내를 확인하세요.",
      body: "디지털 교육은 속도보다 반복과 안전이 중요합니다. 주민센터·복지관·평생학습관의 프로그램을 공식 채널에서 확인하세요. Ongil·라이프 스테이지의 시니어 영역과도 연결할 수 있습니다.",
      img: "/livon/assets/topics/senior-digital.jpg",
      alt: "태블릿을 함께 보는 사람들",
      tags: ["교육", "지역 활동", "자기계발"],
      difficulty: "초급",
      region: "전국",
      onlineOffline: "상관없음",
      companion: ["혼자", "가족", "부모님"],
      budget: "무료",
      source: "LIVON 배움 가이드",
      status: "guide",
      evergreen: true,
      reason: "디지털 생활을 천천히 익히고 싶을 때",
      layout: "learn",
      sections: ["learn", "together"],
      links: { life: "#stage-60", explore: "#explore", ongil: "/ongil-start/#learn" }
    },
    {
      id: "together-solo",
      type: "together",
      category: "혼자 즐기는 활동",
      title: "혼자만의 반나절 루틴 만들기",
      blurb: "카페·산책·전시·독서를 조합한 혼자 일정 가이드.",
      body: "혼자 하는 활동은 ‘무엇을 할지’보다 ‘얼마나 여유를 둘지’가 중요합니다. 이동 동선을 짧게 잡고, 관심 장소를 1–2곳만 고르세요. 저장한 콘텐츠는 내 생활에서 일정으로 옮길 수 있습니다.",
      img: "/livon/assets/topics/solo.jpg",
      alt: "창가 카페에서 혼자 있는 모습",
      tags: ["카페", "문화", "여행"],
      companion: ["혼자"],
      budget: "1만~3만 원",
      indoorOutdoor: "상관없음",
      source: "LIVON 함께 가이드",
      status: "guide",
      evergreen: true,
      reason: "혼자만의 시간을 알차게 보내고 싶을 때",
      layout: "together",
      sections: ["together", "everyday"],
      links: { lifeNow: "#life-now", today: "#td-places", ai: "혼자 반나절 서울 일정을 짜 줘." }
    },
    {
      id: "together-family",
      type: "together",
      category: "가족 나들이",
      title: "가족과 함께하는 가벼운 나들이 설계",
      blurb: "이동 거리·휴식·식사 포인트를 먼저 정하는 가족 일정 가이드.",
      body: "가족 나들이는 구성원의 체력과 관심사가 다릅니다. 야외·실내를 섞고, 식사와 휴식 시간을 미리 비워 두세요. 미성년자 프로그램은 연령 제한·안전 수칙을 공식 안내에서 확인하세요.",
      img: "/livon/assets/topics/family.jpg",
      alt: "가족과 함께 걷는 모습",
      tags: ["가족", "자연", "여행"],
      companion: ["가족", "자녀", "부모님"],
      budget: "1만~3만 원",
      indoorOutdoor: "야외",
      source: "LIVON 함께 가이드",
      status: "guide",
      evergreen: true,
      reason: "가족과 부담 없는 하루를 만들고 싶을 때",
      layout: "together",
      sections: ["together", "season"],
      links: { life: "#stage-30", lifeNow: "#life-now", community: "#community" }
    },
    {
      id: "together-date",
      type: "together",
      category: "커플 데이트",
      title: "전시 + 산책, 여유 있는 데이트 코스",
      blurb: "실내 관람과 야외 산책을 잇는 데이트 구성 팁.",
      body: "데이트는 예약·대기 시간에 영향을 받기 쉽습니다. 전시·식당은 공식 예약 채널을 이용하고, 날씨에 따라 실내 대안을 하나 준비하세요.",
      img: "/livon/assets/topics/date.jpg",
      alt: "나란히 걷는 두 사람",
      tags: ["문화", "전시", "카페"],
      companion: ["연인"],
      budget: "3만~5만 원",
      indoorOutdoor: "상관없음",
      source: "LIVON 함께 가이드",
      status: "guide",
      evergreen: true,
      reason: "전시와 산책을 함께 즐기는 데이트를 원할 때",
      layout: "together",
      sections: ["together", "place"],
      links: { today: "#td-places", explore: "#explore" }
    },
    {
      id: "season-spring",
      type: "season",
      category: "봄",
      title: "봄 산책과 피크닉, 가볍게 시작하기",
      blurb: "벚꽃·봄꽃 명소는 개화 시기가 해마다 다릅니다. 공식 개화 정보를 확인하세요.",
      body: "봄은 야외 활동이 늘어나는 계절입니다. 혼잡한 명소는 이른 시간대를 추천하고, 쓰레기는 되가져가세요. 특정 축제의 일정은 주최 측 공지를 따르며, 확인되지 않은 일정을 진행 중처럼 표시하지 않습니다.",
      img: "/livon/assets/topics/spring.jpg",
      alt: "봄꽃 산책길",
      tags: ["자연", "여행", "가족"],
      seasons: ["spring"],
      indoorOutdoor: "야외",
      budget: "무료",
      source: "LIVON 계절 가이드",
      status: "guide",
      evergreen: true,
      reason: "봄철 야외 활동을 준비하고 싶을 때",
      layout: "season",
      sections: ["season"],
      links: { today: "#td-places", lifeNow: "#life-now" }
    },
    {
      id: "season-summer",
      type: "season",
      category: "여름",
      title: "더운 날의 실내 문화생활 체크리스트",
      blurb: "미술관·도서관·실내 체험으로 더위를 피하는 하루 구성.",
      body: "한여름에는 야외 일정을 짧게 하고 실내 문화·배움을 중심에 두면 편안합니다. 냉방·혼잡·휴관일은 장소 공식 안내를 확인하세요.",
      img: "/livon/assets/topics/summer-indoor.jpg",
      alt: "여름 바다와 하늘",
      tags: ["문화", "여행", "건강"],
      seasons: ["summer"],
      indoorOutdoor: "실내",
      budget: "1만~3만 원",
      source: "LIVON 계절 가이드",
      status: "guide",
      evergreen: true,
      reason: "더운 날 실내 중심으로 하루를 짜고 싶을 때",
      layout: "season",
      sections: ["season"],
      links: { today: "#td-places", today2: "#td-learn" }
    },
    {
      id: "season-autumn",
      type: "season",
      category: "가을",
      title: "가을 단풍·캠핑, 준비부터 점검",
      blurb: "단풍 시기와 캠핑장 예약은 해마다 다릅니다. 공식 정보를 기준으로 하세요.",
      body: "가을 야외 활동은 일교차와 안전 장비가 중요합니다. 국립공원·지자체 공지에서 통제·예약 여부를 확인하세요. 확인되지 않은 축제 일정을 현재 행사처럼 추천하지 않습니다.",
      img: "/livon/assets/topics/autumn.jpg",
      alt: "가을 단풍 숲길",
      tags: ["자연", "여행", "아웃도어"],
      seasons: ["autumn"],
      indoorOutdoor: "야외",
      budget: "1만~3만 원",
      source: "LIVON 계절 가이드",
      status: "guide",
      evergreen: true,
      reason: "가을 야외 활동을 계획할 때",
      layout: "season",
      sections: ["season", "hobby"],
      links: { explore: "#explore", lifeNow: "#life-now" }
    },
    {
      id: "season-winter",
      type: "season",
      category: "겨울",
      title: "겨울 실내 취미와 연말 문화 즐기기",
      blurb: "스키·눈축제는 운영 여부를 공식 확인. 실내 취미로도 계절을 채워 보세요.",
      body: "겨울에는 실내 취미·공연·전시와 짧은 야외 산책을 조합하기 좋습니다. 스키장·축제 등은 기상과 운영 상황에 따라 달라지므로 공식 공지만을 기준으로 하세요.",
      img: "/livon/assets/topics/winter.jpg",
      alt: "눈 덮인 도시 풍경",
      tags: ["취미", "문화", "공연"],
      seasons: ["winter"],
      indoorOutdoor: "실내",
      budget: "1만~3만 원",
      source: "LIVON 계절 가이드",
      status: "guide",
      evergreen: true,
      reason: "추운 계절에 실내 중심으로 새로운 경험을 원할 때",
      layout: "season",
      sections: ["season", "hobby"],
      links: { today: "#td-hobby", community: "#community" }
    },
    {
      id: "life-declutter",
      type: "life",
      category: "정리·수납",
      title: "주말 30분 정리 루틴",
      blurb: "한 구역만 끝내는 작은 정리 습관으로 공간을 바꿉니다.",
      body: "정리의 핵심은 ‘전부’가 아니라 ‘오늘 한 구역’입니다. 버리기 전에 서류·개인정보는 안전하게 처리하세요. 관련 생활 서비스는 탐색에서 연결할 수 있습니다.",
      img: "/livon/assets/topics/declutter.jpg",
      alt: "정돈된 선반",
      tags: ["생활 정보", "주거"],
      duration: "30분",
      budget: "무료",
      source: "LIVON 생활 가이드",
      checkedAt: "2026-09-25",
      status: "guide",
      evergreen: true,
      reason: "작은 습관으로 주거 환경을 개선하고 싶을 때",
      layout: "editorial",
      sections: ["everyday"],
      links: { lifeNow: "#ml-goals", explore: "#explore", ai: "주말 정리 체크리스트를 만들어 줘." }
    },
    {
      id: "life-public",
      type: "life",
      category: "공공서비스",
      title: "정부24로 생활 민원 한눈에 보기",
      blurb: "주민등록·증명서 등 온라인 민원 창구. 서비스 범위는 공식 안내를 따릅니다.",
      body: "정부24는 다양한 행정 서비스를 온라인으로 제공합니다. 본인인증과 서류 요건은 서비스마다 다릅니다. 정책·수수료는 변경될 수 있으니 이용 직전 공식 페이지를 확인하세요.",
      img: "/livon/assets/topics/public-service.jpg",
      alt: "서류와 노트북",
      tags: ["생활 정보", "디지털"],
      onlineOffline: "온라인",
      budget: "무료",
      source: "정부24",
      officialUrl: "https://www.gov.kr/",
      checkedAt: "2026-09-25",
      status: "link",
      evergreen: true,
      reason: "생활 민원을 온라인으로 처리하고 싶을 때",
      layout: "editorial",
      sections: ["everyday", "week"],
      links: { explore: "#explore", lifeNow: "#life-now" }
    },
    {
      id: "life-green",
      type: "life",
      category: "친환경 생활",
      title: "하루 한 가지 친환경 습관",
      blurb: "텀블러·장바구니·전기 절약처럼 바로 실천 가능한 작은 선택.",
      body: "친환경 생활은 완벽한 전환보다 지속 가능한 한 가지부터입니다. 지역 분리배출 규칙은 지자체 안내를 확인하세요.",
      img: "/livon/assets/topics/eco.jpg",
      alt: "식물과 재활용 소재",
      tags: ["생활 정보", "건강"],
      budget: "무료",
      source: "LIVON 생활 가이드",
      checkedAt: "2026-09-25",
      status: "guide",
      evergreen: true,
      reason: "일상에서 실천 가능한 작은 변화를 원할 때",
      layout: "editorial",
      sections: ["everyday"],
      links: { community: "#community", lifeNow: "#ml-goals" }
    },
    {
      id: "edit-daytrip",
      type: "editorial",
      category: "지역별 하루 여행",
      title: "하루 여행의 공식: 이동 2 · 경험 2 · 여유 1",
      blurb: "과한 일정을 줄이고, 남는 시간으로 퀄리티를 높이는 에디토리얼.",
      body: "하루 여행은 이동 시간을 과소평가하기 쉽습니다. 주요 경험 두 가지와 여유 슬롯 하나를 남기면 만족도가 높아집니다. 관련 장소 콘텐츠와 라이프 스테이지의 여가 분야로 이어가 보세요.",
      img: "/livon/assets/topics/daytrip.jpg",
      alt: "여행 가방과 지도",
      tags: ["여행", "문화", "자기계발"],
      source: "LIVON Editorial",
      status: "guide",
      featured: true,
      evergreen: true,
      reason: "여행 일정을 덜 바쁘게 짜고 싶을 때",
      layout: "editorial",
      sections: ["editorial", "hero"],
      links: { today: "#td-places", life: "#life", ai: "하루 여행 일정을 여유롭게 짜 줘." }
    },
    {
      id: "edit-hobby-start",
      type: "editorial",
      category: "새로운 취미 입문 가이드",
      title: "새 취미, 장비가 아니라 루틴으로 시작하기",
      blurb: "장비 구매 전에 3회 체험 규칙을 제안하는 입문 가이드.",
      body: "취미를 시작할 때 가장 흔한 실수는 장비를 먼저 사는 것입니다. 세 번 체험해 보고 나서야 필요한 도구가 보입니다. 체험·클래스는 탐색으로, 기록은 내 생활로 연결하세요.",
      img: "/livon/assets/topics/hobby.jpg",
      alt: "미술 도구와 스케치",
      tags: ["취미", "자기계발"],
      source: "LIVON Editorial",
      status: "guide",
      evergreen: true,
      reason: "새로운 취미를 부담 없이 시작하고 싶을 때",
      layout: "editorial",
      sections: ["editorial", "hobby"],
      links: { today: "#td-hobby", community: "#community", lifeNow: "#life-now" }
    },
    {
      id: "edit-generations",
      type: "editorial",
      category: "세대별 생활 이야기",
      title: "세대가 달라도, ‘새로운 하루’의 조건은 같다",
      blurb: "관심·체력·예산에 맞춰 발견을 고르는 관점 에세이.",
      body: "연령은 추천의 힌트일 뿐 제한이 아닙니다. 같은 전시도 혼자·가족과 함께일 때 경험이 달라집니다. 라이프 스테이지에서 생활 분야를 살펴본 뒤, 오늘의 발견에서 콘텐츠를 고르세요.",
      img: "/livon/assets/topics/generations.jpg",
      alt: "여러 세대가 함께 웃는 모습",
      tags: ["문화", "가족", "지역 활동"],
      source: "LIVON Editorial",
      status: "guide",
      evergreen: true,
      reason: "나와 가족을 위한 발견을 함께 보고 싶을 때",
      layout: "editorial",
      sections: ["editorial", "together"],
      links: { life: "#life", today: "#td-together" }
    },
    {
      id: "event-howto",
      type: "event",
      category: "문화 행사",
      title: "이번 주 행사 찾는 법 (공식 캘린더 활용)",
      blurb: "검증되지 않은 행사를 나열하지 않습니다. 공식 문화 캘린더로 연결합니다.",
      body: "전시·공연·축제는 주최 측 일정이 수시로 바뀝니다. 서울문화포털 등 공식 캘린더에서 날짜·지역·유료 여부를 확인한 뒤, 관심 행사를 내 생활에 저장하세요. LIVON은 임의의 행사 일정을 생성하지 않습니다.",
      img: "/livon/assets/topics/culture-event.jpg",
      alt: "공연장의 관객들",
      tags: ["문화", "공연", "전시"],
      region: "서울",
      price: "행사별 상이",
      source: "서울문화포털",
      officialUrl: "https://culture.seoul.go.kr/",
      checkedAt: "2026-09-25",
      status: "link",
      evergreen: true,
      reason: "이번 주 실제 행사를 공식 정보로 찾고 싶을 때",
      layout: "event",
      sections: ["week", "hero"],
      free: false,
      links: { explore: "#explore", lifeNow: "#life-now", community: "#community", ai: "이번 주말 서울 문화 행사 찾는 방법을 알려 줘." }
    },
    {
      id: "event-popup-guide",
      type: "event",
      category: "팝업스토어",
      title: "팝업·플리마켓, 방문 전 확인할 체크리스트",
      blurb: "운영 기간이 짧은 팝업은 공식 SNS·사이트 공지가 기준입니다.",
      body: "팝업스토어와 플리마켓은 기간·장소 변경이 잦습니다. 방문 전 운영 시간·입장 방식·현금/카드 여부를 공식 공지로 확인하세요. 종료된 팝업을 현재처럼 추천하지 않습니다.",
      img: "/livon/assets/topics/market.jpg",
      alt: "마켓 부스와 사람들",
      tags: ["문화", "지역 활동", "취미"],
      status: "guide",
      evergreen: true,
      source: "LIVON 행사 가이드",
      reason: "짧은 기간 팝업을 현명하게 고르고 싶을 때",
      layout: "event",
      sections: ["week"],
      links: { explore: "#explore", community: "#community" }
    }
  ]
};
