/**
 * APP PROTOTYPE service detail — KO/EN copy.
 * Path: /{lang}/business/app/
 */
import { resolveKoEnPack } from "./i18n/copy-lang.mjs";

export const APP_COPY = {
  ko: {
    seoTitle: "APP PROTOTYPE | Newon Business",
    metaDescription:
      "앱 아이디어를 iOS·Android 화면과 흐름으로 구현하는 인터랙티브 프로토타입. 투자·내부 검증·개발 착수 전에 경험을 먼저 확인합니다. Newon APP PROTOTYPE.",
    crumbBusiness: "BUSINESS",
    crumbServices: "SERVICES",
    crumbBuild: "BUILD",
    crumbHere: "APP PROTOTYPE",
    eyebrow: "APP PROTOTYPE",
    subEyebrow: "BUILD",
    headline: "앱 아이디어를\n실제 경험으로 만듭니다.",
    lead: "핵심 화면과 iOS·Android 플로우가 동작하는 앱 프로토타입을 설계하고 구현합니다. 투자 미팅, 내부 공유, 개발 착수 전 — 아이디어가 실제로 어떻게 느껴지는지 빠르게 검증할 수 있습니다.",
    ctaPrimary: "APP PROTOTYPE 문의 →",
    ctaSecondary: "프로토타입 흐름 보기 ↓",
    meta: [
      { k: "SERVICE", v: "App Prototype" },
      { k: "BEST FOR", v: "투자·내부 검증용 프로토타입" },
      { k: "TIMELINE", v: "약 2–3주" },
      { k: "PRICE", v: "₩1,000,000부터" },
    ],
    overviewLabel: "OVERVIEW",
    overviewTitle: "설명은 있는데,\n경험이 없습니다.",
    overviewBody: [
      "앱 아이디어는 슬라이드와 와이어프레임으로는 충분히 전달되지 않습니다. 투자자·파트너·내부 이해관계자는 ‘직접 써보면 어떤가’를 먼저 묻고, 개발팀은 화면·플로우·상태 정의 없이는 착수하기 어렵습니다.",
      "완성형 앱을 처음부터 만들면 시간과 비용이 과하고, Figma만으로는 인터랙션·전환·모바일 맥락이 부족합니다. 필요한 것은 핵심 플로우가 실제로 동작하는 프로토타입입니다.",
      "APP PROTOTYPE은 앱 목적과 핵심 시나리오를 먼저 정의합니다. iOS·Android 화면, 사용자 흐름, 인터랙션을 설계하고, 클릭·스와이프·상태 전환이 느껴지는 프로토타입으로 공유·검증·개발 인수인계까지 연결합니다.",
    ],
    problemsLabel: "PROBLEMS",
    problemsTitle: "이런 상황에서 도움이 됩니다.",
    problems: [
      {
        n: "01",
        t: "IDEA ONLY",
        d: "앱 컨셉은 있지만 실제 화면·흐름으로 보여줄 수 없는 경우.\n설명만으로는 설득이 어려운 경우.",
      },
      {
        n: "02",
        t: "INVESTOR DEMO",
        d: "투자·파트너 미팅 전에 동작하는 데모가 필요한 경우.\n핵심 가치가 느껴지는 경험이 필요한 경우.",
      },
      {
        n: "03",
        t: "INTERNAL ALIGN",
        d: "내부 팀·경영진·기획·디자인·개발 간 이해가 맞지 않는 경우.\n하나의 프로토타입으로 합의가 필요한 경우.",
      },
      {
        n: "04",
        t: "FLOW GAP",
        d: "와이어·목업만 있고 실제 플로우·상태 전환이 검증되지 않은 경우.\n온보딩·핵심 액션·예외 흐름이 불명확한 경우.",
      },
      {
        n: "05",
        t: "PRE-DEV RISK",
        d: "개발 착수 전 범위·화면·우선순위가 정리되지 않은 경우.\nMVP 범위를 줄이기 전 검증이 필요한 경우.",
      },
      {
        n: "06",
        t: "PLATFORM CHOICE",
        d: "iOS·Android·웹 중 어디에 먼저 맞출지 결정이 필요한 경우.\n플랫폼별 UX 차이를 확인해야 하는 경우.",
      },
    ],
    baLabel: "BEFORE / AFTER",
    baTitle: "정적인 목업 vs\n동작하는 프로토타입",
    beforeLabel: "BEFORE",
    afterLabel: "AFTER",
    before: [
      "슬라이드·와이어·정적 목업만 존재",
      "핵심 플로우가 말로만 설명됨",
      "투자·내부 공유 시 ‘상상’에 의존",
      "개발 범위·화면 우선순위가 불명확",
    ],
    after: [
      "핵심 화면과 iOS·Android 플로우 정의",
      "클릭·전환이 동작하는 프로토타입",
      "투자·내부 검증용 공유 링크/빌드",
      "개발 착수용 화면·플로우·스펙 정리",
    ],
    capsLabel: "CAPABILITIES",
    capsTitle: "프로토타입에 필요한 작업을\n한 구조로 진행합니다.",
    caps: [
      {
        t: "GOAL FRAMING",
        d: "앱 목적, 핵심 사용자, 성공 시나리오를 정의합니다.\n프로토타입으로 검증할 가설을 명확히 합니다.",
      },
      {
        t: "FLOW DESIGN",
        d: "온보딩·핵심 액션·주요 상태 전환을 설계합니다.\niOS·Android 맥락에 맞는 흐름을 정리합니다.",
      },
      {
        t: "UX / UI DESIGN",
        d: "핵심 화면 UI와 정보 구조를 설계합니다.\n모바일 터치·내비게이션 패턴을 반영합니다.",
      },
      {
        t: "INTERACTIVE BUILD",
        d: "인터랙션이 동작하는 프로토타입을 구현합니다.\n핵심 플로우 중심으로 빠르게 완성합니다.",
      },
      {
        t: "PLATFORM SCOPE",
        d: "iOS·Android·웹 중 프로젝트 목적에 맞는 범위를 정합니다.\n플랫폼별 차이를 필요한 만큼 반영합니다.",
      },
      {
        t: "VALIDATION SUPPORT",
        d: "투자·내부 데모·사용성 확인을 위한 공유 형태를 준비합니다.\n피드백 반영 라운드를 포함합니다.",
      },
      {
        t: "SPEC & HANDOFF",
        d: "화면·플로우·인터랙션 스펙을 정리합니다.\nMVP/본개발 인수인계를 위한 문서를 제공합니다.",
      },
      {
        t: "NEXT STEP PATH",
        d: "프로토타입 이후 MVP·스토어 출시형 개발 경로를 연결합니다.\n범위·일정·견적을 이어서 제안합니다.",
      },
    ],
    sourcesLabel: "PROJECT INPUTS",
    sourcesTitle: "프로토타입에 활용하는 정보와 자료를 조합합니다.",
    sourcesNote: "아이디어 단계, 기존 기획, 참고 앱에 따라 실제 입력은 프로젝트마다 달라집니다.",
    sources: [
      "앱 컨셉·목적 설명",
      "타깃 사용자·시나리오",
      "참고 앱·레퍼런스",
      "기존 와이어·기획서",
      "브랜드·UI 가이드",
      "경쟁·시장 맥락",
      "핵심 기능 목록",
      "온보딩·핵심 액션 정의",
      "iOS·Android 우선순위",
      "투자·데모 일정",
      "내부 이해관계자 피드백",
      "향후 MVP·출시 계획",
    ],
    useLabel: "USE CASES",
    useTitle: "이런 프로토타입을 만들 수 있습니다.",
    useBadge: "구축 가능 예시",
    useCases: [
      {
        t: "INVESTOR DEMO",
        d: "투자·파트너 미팅용 핵심 플로우 데모.\n가치가 느껴지는 인터랙션 중심.",
      },
      {
        t: "INTERNAL VALIDATION",
        d: "경영·기획·디자인·개발 간 합의용 프로토타입.\n내부 리뷰·피드백 루프.",
      },
      {
        t: "CONSUMER APP IDEA",
        d: "B2C 앱 아이디어의 온보딩·핵심 사용 흐름.\niOS·Android UX 검증.",
      },
      {
        t: "SERVICE APP",
        d: "예약·주문·구독·매칭 등 서비스형 앱 플로우.\n상태 전환·CTA 중심 설계.",
      },
      {
        t: "INTERNAL MOBILE TOOL",
        d: "현장·운영·관리용 모바일 도구 프로토타입.\n역할·권한·작업 흐름 확인.",
      },
      {
        t: "FEATURE PoC",
        d: "신규 기능·리디자인·온보딩 변경 검증.\n기존 앱 확장 전 PoC.",
      },
      {
        t: "MULTI-PLATFORM",
        d: "iOS·Android 공통 핵심 + 플랫폼별 차이 반영.\n우선순위 플랫폼 결정 지원.",
      },
      {
        t: "PRE-MVP SCOPE",
        d: "본개발 전 MVP 범위·화면·우선순위 정리.\n개발 견적·일정 협의용 자료.",
      },
    ],
    flowLabel: "EXAMPLE WORKFLOW",
    flowTitle: "아이디어에서 공유 가능한 프로토타입까지",
    flow: [
      {
        n: "01",
        t: "DEFINE",
        d: "앱 목적, 사용자, 핵심 시나리오를 정의합니다.\n프로토타입으로 검증할 범위를 합의합니다.",
        examples: ["목적", "사용자", "시나리오", "일정"],
      },
      {
        n: "02",
        t: "STRUCTURE",
        d: "화면 목록, 정보 구조, 플로우를 설계합니다.\niOS·Android 범위를 정합니다.",
        examples: ["화면", "플로우", "IA", "Platform"],
      },
      {
        n: "03",
        t: "DESIGN",
        d: "핵심 화면 UI와 인터랙션 방향을 설계합니다.\n데모·검증에 필요한 화면을 확정합니다.",
        examples: ["UI", "Motion", "States", "Review"],
      },
      {
        n: "04",
        t: "PROTOTYPE",
        d: "동작하는 프로토타입을 구현합니다.\n핵심 플로우 중심으로 빠르게 완성합니다.",
        examples: ["Tap", "Swipe", "Navigate", "States"],
      },
      {
        n: "05",
        t: "SHARE",
        d: "공유 링크·빌드·스펙을 전달합니다.\n피드백 반영과 다음 단계를 연결합니다.",
        examples: ["Link", "Demo", "Spec", "MVP"],
      },
    ],
    reportLabel: "OUTPUT",
    reportTitle: "결과물은 공유·검증 가능한 프로토타입과 스펙으로 전달합니다.",
    reportLead: "프로젝트 범위에 따라 구성은 달라집니다. 아래는 자주 포함되는 항목 예시입니다.",
    reportMockStatus: "프로토타입 · 스펙",
    reportMockK: "App Prototype Spec",
    reportMockT: "화면·플로우·플랫폼·인터랙션 요약",
    reportItems: [
      "Goals & Scenarios",
      "Screen List",
      "User Flow Map",
      "Core UI Screens",
      "Interaction Notes",
      "Platform Scope",
      "Prototype Link/Build",
      "Validation Notes",
      "Handoff Summary",
      "MVP Path (optional)",
    ],
    dashTitle: "한 화면에서 화면·플로우·플랫폼 범위를 공유할 수 있습니다.",
    dashLead: "Screens, Flows, Platforms, Integrations를 함께 정리해 범위 합의와 데모 준비가 빨라집니다.",
    dashNote: "화면 수, 플랫폼, 인터랙션 깊이는 프로젝트 목적과 일정에 따라 달라집니다.",
    dashMetrics: ["Screens", "Flows", "Platforms", "Integrations"],
    dashFilters: ["전체", "Core", "iOS", "Android"],
    aiLabel: "ACCELERATION",
    aiTitle: "반복 작업은 자동화하고,\n설계·프로토타입에 집중합니다.",
    aiLead:
      "화면 목록 초안, 플로우 정리, 인터랙션 노트, QA 체크리스트 등 반복 작업은 AI 보조로 속도를 높이고, UX·핵심 플로우·프로토타입 품질에는 사람이 집중합니다.",
    aiExamples: [
      "화면·플로우 목록 초안",
      "시나리오·상태 전환 정리",
      "UI 카피·라벨 초안",
      "사용성·데모 체크리스트",
      "핸드오프·스펙 문서 초안",
      "MVP 범위·우선순위 비교",
    ],
    aiNote: "최종 화면·플로우·인터랙션 판단은 프로젝트 팀과 함께 확정합니다.",
    delLabel: "DELIVERABLES",
    delTitle: "프로젝트 완료 후 제공되는 것",
    delLead: "범위에 따라 아래 항목 중 필요한 결과물을 제공합니다.",
    deliverables: [
      "Interactive App Prototype",
      "Core Screen UI",
      "User Flow Map",
      "Screen & Interaction Spec",
      "Platform Scope Notes",
      "Prototype Link / Build",
      "Validation Demo Support",
      "Handoff Pack",
      "MVP Scope Proposal (optional)",
    ],
    processLabel: "PROCESS",
    processTitle: "목적 정의에서 공유까지.",
    process: [
      {
        n: "01",
        t: "DISCOVERY",
        d: "앱 목적, 사용자, 핵심 시나리오, 일정을 확인합니다.\n데모·검증 목표를 파악합니다.",
        examples: ["목적", "사용자", "데모", "일정"],
      },
      {
        n: "02",
        t: "STRUCTURE",
        d: "화면 목록, IA, 플로우, 플랫폼 범위를 정의합니다.\n핵심 vs 확장 화면을 구분합니다.",
        examples: ["화면", "플로우", "iOS", "Android"],
      },
      {
        n: "03",
        t: "DESIGN",
        d: "핵심 화면 UI와 인터랙션 방향을 설계합니다.\n리뷰·피드백 라운드를 진행합니다.",
        examples: ["UI", "States", "Review", "Revise"],
      },
      {
        n: "04",
        t: "PROTOTYPE",
        d: "동작하는 프로토타입을 구현합니다.\n핵심 플로우와 전환을 검수합니다.",
        examples: ["Build", "Tap", "Navigate", "Polish"],
      },
      {
        n: "05",
        t: "VALIDATE",
        d: "데모·내부 리뷰·사용성 확인을 지원합니다.\n피드백을 반영합니다.",
        examples: ["Demo", "Feedback", "Fixes", "Sign-off"],
      },
      {
        n: "06",
        t: "SPEC",
        d: "화면·플로우·인터랙션 스펙을 정리합니다.\n개발 인수인계용 문서를 준비합니다.",
        examples: ["Spec", "Notes", "Assets", "Handoff"],
      },
      {
        n: "07",
        t: "NEXT",
        d: "MVP·본개발·스토어 출시 경로를 연결합니다.\n범위·일정·견적을 이어서 제안합니다.",
        examples: ["MVP", "Scope", "Quote", "Phase 2"],
      },
    ],
    scopeLabel: "SCOPE LEVELS",
    scopeTitle: "프로젝트 복잡도를 이해하기 위한 구분입니다.",
    scopeLead: "고정 패키지가 아닙니다. 화면 수, 플랫폼, 인터랙션 깊이, 연동 범위에 맞춰 범위를 정합니다.",
    scopes: [
      {
        t: "PROTOTYPE",
        items: [
          "핵심 화면 5–8개",
          "1–2개 핵심 플로우",
          "인터랙션 프로토타입",
          "iOS 또는 Android 중심",
          "투자·내부 검증용",
        ],
      },
      {
        t: "MVP APP",
        items: [
          "확장 화면·복수 플로우",
          "iOS + Android 범위",
          "상태·예외 흐름 포함",
          "기본 연동·API Mock",
          "개발 착수용 스펙",
        ],
      },
      {
        t: "STORE-READY",
        items: [
          "스토어 출시형 앱 개발",
          "백엔드·인증·결제·푸시",
          "QA·배포·스토어 제출",
          "운영·유지보수 연계",
          "별도 견적·일정 협의",
        ],
      },
    ],
    timeLabel: "TIMELINE",
    timeTitle: "범위에 따라 일정이 달라집니다.",
    timeLead: "화면 수, 인터랙션 깊이, 플랫폼, 피드백 라운드에 따라 기간이 달라질 수 있습니다.",
    timelines: [
      { t: "Prototype", d: "약 2–3주 · 범위별 상이" },
      { t: "MVP App", d: "약 4–6주 · 범위별 상이" },
      { t: "Store-ready", d: "별도 협의" },
    ],
    priceLabel: "PROJECT COST",
    priceTitle: "프로젝트별 맞춤 견적입니다.",
    priceName: "APP PROTOTYPE",
    priceValue: "₩500,000부터",
    priceFactorsLabel: "가격 결정 요소",
    priceFactors: [
      "Screens — 핵심·확장 화면 수",
      "Flows — 플로우·상태 복잡도",
      "Platform — iOS / Android / Web",
      "Interaction — 인터랙션·모션 깊이",
      "Timeline — 일정·피드백 라운드",
      "Integration — API Mock·연동 범위",
      "Design depth — UI·디자인 시스템",
      "Next step — MVP·출시형 개발 연계",
    ],
    priceNote: "₩500,000은 APP PROTOTYPE 시작가입니다. MVP App·Store-ready 앱은 화면·기능·연동 범위에 따라 별도 견적합니다.",
    faqLabel: "FAQ",
    faqTitle: "자주 묻는 질문",
    faqs: [
      {
        q: "₩500,000은 어떤 범위인가요?",
        a: "APP PROTOTYPE 시작가입니다. 핵심 화면과 1–2개 플로우 중심의 인터랙션 프로토타입 범위를 기준으로 합니다. MVP App·Store-ready는 별도 견적입니다.",
      },
      {
        q: "실제 스토어 출시용 앱인가요?",
        a: "기본은 투자·내부 검증·개발 착수 전 프로토타입입니다. 스토어 출시형 앱 개발은 Store-ready 범위로 별도 제안합니다.",
      },
      {
        q: "iOS와 Android 모두 가능한가요?",
        a: "가능합니다. 프로젝트 목적에 맞게 한 플랫폼 중심 또는 양쪽 범위를 설계합니다. 화면·플랫폼 수에 따라 견적이 달라집니다.",
      },
      {
        q: "작업 기간은 얼마나 걸리나요?",
        a: "Prototype은 보통 2–3주, MVP App은 4–6주입니다. 화면 수·인터랙션·피드백 라운드에 따라 달라집니다.",
      },
      {
        q: "이후 개발로 이어질 수 있나요?",
        a: "가능합니다. 프로토타입과 스펙을 기준으로 MVP·본개발·스토어 출시 범위를 이어서 제안합니다.",
      },
      {
        q: "수정은 몇 번 가능한가요?",
        a: "기본 수정 2회가 포함됩니다. 범위 밖 변경·화면 추가는 일정·견적에 반영합니다.",
      },
      {
        q: "Figma만 제공하나요, 동작하는 프로토타입인가요?",
        a: "핵심은 인터랙션이 동작하는 프로토타입입니다. 필요 시 UI 파일·스펙 문서도 함께 제공합니다.",
      },
    ],
    finalLabel: "START A PROJECT",
    finalTitle: "설명 전에\n경험부터 보여주세요.",
    finalLead:
      "앱 아이디어, 데모 목적, 참고 앱, 일정이 있다면 알려주세요. iOS·Android 프로토타입 범위와 검증 방식을 함께 확인합니다.",
    ctaFinalSecondary: "BUILD 전체 보기 →",
    ctaFinalSecondaryHref: "../build/",
  },
  en: {
    seoTitle: "APP PROTOTYPE | Newon Business",
    metaDescription:
      "Turn app ideas into interactive iOS and Android screens and flows — validate with investors and internal teams before full development. Newon APP PROTOTYPE.",
    crumbBusiness: "BUSINESS",
    crumbServices: "SERVICES",
    crumbBuild: "BUILD",
    crumbHere: "APP PROTOTYPE",
    eyebrow: "APP PROTOTYPE",
    subEyebrow: "BUILD",
    headline: "Turn an app idea\ninto a real experience.",
    lead: "We design and build interactive app prototypes with core iOS and Android flows. Before investor meetings, internal reviews, or development kickoff — validate how the idea actually feels when people use it.",
    ctaPrimary: "App prototype inquiry →",
    ctaSecondary: "See the prototype flow ↓",
    meta: [
      { k: "SERVICE", v: "App Prototype" },
      { k: "BEST FOR", v: "Investor & internal validation" },
      { k: "TIMELINE", v: "About 2–3 weeks" },
      { k: "PRICE", v: "From ₩1,000,000" },
    ],
    overviewLabel: "OVERVIEW",
    overviewTitle: "You have the story.\nNot the experience.",
    overviewBody: [
      "App ideas rarely land through slides and wireframes alone. Investors, partners, and internal stakeholders ask to try it — and engineering teams struggle to start without defined screens, flows, and states.",
      "Building a production app from day one costs too much time and money. Figma alone often lacks interaction, transitions, and mobile context. What you need is a prototype where core flows actually work.",
      "APP PROTOTYPE starts by defining app goals and key scenarios. We design iOS and Android screens, user flows, and interactions — then deliver a clickable prototype for sharing, validation, and dev handoff.",
    ],
    problemsLabel: "PROBLEMS",
    problemsTitle: "Helpful when you face these situations.",
    problems: [
      {
        n: "01",
        t: "IDEA ONLY",
        d: "You have a concept but nothing to show as real screens and flows.\nExplanation alone does not convince.",
      },
      {
        n: "02",
        t: "INVESTOR DEMO",
        d: "You need a working demo before investor or partner meetings.\nThe core value must be felt, not imagined.",
      },
      {
        n: "03",
        t: "INTERNAL ALIGN",
        d: "Product, design, engineering, and leadership are not aligned.\nYou need one prototype everyone can react to.",
      },
      {
        n: "04",
        t: "FLOW GAP",
        d: "You have wires or mocks but no validated flow or state transitions.\nOnboarding, core actions, and edge paths are unclear.",
      },
      {
        n: "05",
        t: "PRE-DEV RISK",
        d: "Scope, screens, and priorities are undefined before development.\nYou need validation before committing to MVP build.",
      },
      {
        n: "06",
        t: "PLATFORM CHOICE",
        d: "You must decide iOS, Android, or web first.\nPlatform UX differences need to be tested.",
      },
    ],
    baLabel: "BEFORE / AFTER",
    baTitle: "Static mocks vs\nworking prototype",
    beforeLabel: "BEFORE",
    afterLabel: "AFTER",
    before: [
      "Slides, wires, and static mocks only",
      "Core flows explained in words",
      "Investor and internal reviews rely on imagination",
      "Dev scope and screen priority unclear",
    ],
    after: [
      "Core screens and iOS/Android flows defined",
      "Clickable prototype with real transitions",
      "Share link or build for investor and internal validation",
      "Screen, flow, and spec pack for development kickoff",
    ],
    capsLabel: "CAPABILITIES",
    capsTitle: "We run app prototype work\nas one structured engagement.",
    caps: [
      {
        t: "GOAL FRAMING",
        d: "Define app purpose, core users, and success scenarios.\nClarify what the prototype must validate.",
      },
      {
        t: "FLOW DESIGN",
        d: "Design onboarding, core actions, and key state transitions.\nShape flows for iOS and Android context.",
      },
      {
        t: "UX / UI DESIGN",
        d: "Design core screen UI and information structure.\nReflect mobile touch and navigation patterns.",
      },
      {
        t: "INTERACTIVE BUILD",
        d: "Build a prototype where interactions work.\nFocus on core flows for speed.",
      },
      {
        t: "PLATFORM SCOPE",
        d: "Set iOS, Android, or web scope for the project goal.\nReflect platform differences where needed.",
      },
      {
        t: "VALIDATION SUPPORT",
        d: "Prepare share formats for investor, internal, and usability review.\nInclude feedback revision rounds.",
      },
      {
        t: "SPEC & HANDOFF",
        d: "Document screens, flows, and interactions.\nProvide handoff for MVP or production build.",
      },
      {
        t: "NEXT STEP PATH",
        d: "Connect prototype to MVP or store-ready development.\nPropose scope, timeline, and quote next.",
      },
    ],
    sourcesLabel: "PROJECT INPUTS",
    sourcesTitle: "We combine the inputs your prototype needs.",
    sourcesNote: "Actual inputs vary by idea stage, existing specs, and reference apps.",
    sources: [
      "App concept and purpose",
      "Target users and scenarios",
      "Reference apps",
      "Existing wires or specs",
      "Brand and UI guidelines",
      "Market and competitor context",
      "Core feature list",
      "Onboarding and core action definition",
      "iOS vs Android priority",
      "Investor or demo deadline",
      "Internal stakeholder feedback",
      "Future MVP or launch plan",
    ],
    useLabel: "USE CASES",
    useTitle: "Prototypes we can build.",
    useBadge: "Example build types",
    useCases: [
      {
        t: "INVESTOR DEMO",
        d: "Core-flow demo for investor and partner meetings.\nInteraction that makes value tangible.",
      },
      {
        t: "INTERNAL VALIDATION",
        d: "Alignment prototype for leadership, product, design, and engineering.\nInternal review and feedback loop.",
      },
      {
        t: "CONSUMER APP IDEA",
        d: "Onboarding and core usage for B2C app ideas.\niOS and Android UX validation.",
      },
      {
        t: "SERVICE APP",
        d: "Booking, order, subscription, or matching app flows.\nState transitions and CTA-focused design.",
      },
      {
        t: "INTERNAL MOBILE TOOL",
        d: "Field, ops, or admin mobile tool prototype.\nRoles, permissions, and task flow check.",
      },
      {
        t: "FEATURE PoC",
        d: "Validate new feature, redesign, or onboarding change.\nPoC before extending an existing app.",
      },
      {
        t: "MULTI-PLATFORM",
        d: "Shared core plus platform-specific differences.\nSupport platform priority decisions.",
      },
      {
        t: "PRE-MVP SCOPE",
        d: "Define MVP scope, screens, and priority before full build.\nMaterial for dev quote and timeline.",
      },
    ],
    flowLabel: "EXAMPLE WORKFLOW",
    flowTitle: "From idea to shareable prototype",
    flow: [
      {
        n: "01",
        t: "DEFINE",
        d: "Define app purpose, users, and key scenarios.\nAgree what the prototype must validate.",
        examples: ["Purpose", "Users", "Scenarios", "Timeline"],
      },
      {
        n: "02",
        t: "STRUCTURE",
        d: "Design screen list, IA, and flows.\nSet iOS and Android scope.",
        examples: ["Screens", "Flows", "IA", "Platform"],
      },
      {
        n: "03",
        t: "DESIGN",
        d: "Design core screen UI and interaction direction.\nConfirm screens needed for demo and validation.",
        examples: ["UI", "Motion", "States", "Review"],
      },
      {
        n: "04",
        t: "PROTOTYPE",
        d: "Build a working prototype.\nComplete core flows quickly.",
        examples: ["Tap", "Swipe", "Navigate", "States"],
      },
      {
        n: "05",
        t: "SHARE",
        d: "Deliver share link, build, and spec.\nConnect feedback and next steps.",
        examples: ["Link", "Demo", "Spec", "MVP"],
      },
    ],
    reportLabel: "OUTPUT",
    reportTitle: "Deliverables are a shareable prototype and supporting spec.",
    reportLead: "Composition varies by project scope. Below are common items.",
    reportMockStatus: "PROTOTYPE · SPEC",
    reportMockK: "APP PROTOTYPE SPEC",
    reportMockT: "Screens, flows, platforms, interactions",
    reportItems: [
      "Goals & Scenarios",
      "Screen List",
      "User Flow Map",
      "Core UI Screens",
      "Interaction Notes",
      "Platform Scope",
      "Prototype Link/Build",
      "Validation Notes",
      "Handoff Summary",
      "MVP Path (optional)",
    ],
    dashTitle: "Share screen, flow, and platform scope on one view.",
    dashLead: "Screens, Flows, Platforms, and Integrations together speed scope agreement and demo prep.",
    dashNote: "Screen count, platform, and interaction depth vary by project goal and timeline.",
    dashMetrics: ["Screens", "Flows", "Platforms", "Integrations"],
    dashFilters: ["All", "Core", "iOS", "Android"],
    aiLabel: "ACCELERATION",
    aiTitle: "Automate repetition.\nFocus on design and prototype.",
    aiLead:
      "Screen lists, flow drafts, interaction notes, and QA checklists can be AI-assisted for speed — while people focus on UX, core flows, and prototype quality.",
    aiExamples: [
      "Draft screen and flow lists",
      "Structure scenarios and state transitions",
      "Draft UI copy and labels",
      "Usability and demo checklists",
      "Handoff and spec doc drafts",
      "Compare MVP scope and priority",
    ],
    aiNote: "Final screens, flows, and interaction decisions are confirmed with your project team.",
    delLabel: "DELIVERABLES",
    delTitle: "What you receive when the project completes",
    delLead: "We deliver the items below as needed for your scope.",
    deliverables: [
      "Interactive App Prototype",
      "Core Screen UI",
      "User Flow Map",
      "Screen & Interaction Spec",
      "Platform Scope Notes",
      "Prototype Link / Build",
      "Validation Demo Support",
      "Handoff Pack",
      "MVP Scope Proposal (optional)",
    ],
    processLabel: "PROCESS",
    processTitle: "From purpose to share.",
    process: [
      {
        n: "01",
        t: "DISCOVERY",
        d: "Confirm app purpose, users, key scenarios, and timeline.\nUnderstand demo and validation goals.",
        examples: ["Purpose", "Users", "Demo", "Timeline"],
      },
      {
        n: "02",
        t: "STRUCTURE",
        d: "Define screen list, IA, flows, and platform scope.\nSeparate core from expansion screens.",
        examples: ["Screens", "Flows", "iOS", "Android"],
      },
      {
        n: "03",
        t: "DESIGN",
        d: "Design core screen UI and interaction direction.\nRun review and feedback rounds.",
        examples: ["UI", "States", "Review", "Revise"],
      },
      {
        n: "04",
        t: "PROTOTYPE",
        d: "Build a working prototype.\nVerify core flows and transitions.",
        examples: ["Build", "Tap", "Navigate", "Polish"],
      },
      {
        n: "05",
        t: "VALIDATE",
        d: "Support demo, internal review, and usability check.\nApply feedback.",
        examples: ["Demo", "Feedback", "Fixes", "Sign-off"],
      },
      {
        n: "06",
        t: "SPEC",
        d: "Document screens, flows, and interactions.\nPrepare handoff for development.",
        examples: ["Spec", "Notes", "Assets", "Handoff"],
      },
      {
        n: "07",
        t: "NEXT",
        d: "Connect MVP, full build, or store-ready path.\nPropose scope, timeline, and quote next.",
        examples: ["MVP", "Scope", "Quote", "Phase 2"],
      },
    ],
    scopeLabel: "SCOPE LEVELS",
    scopeTitle: "How to think about project complexity.",
    scopeLead: "Not a fixed package. Scope is set by screen count, platform, interaction depth, and integrations.",
    scopes: [
      {
        t: "PROTOTYPE",
        items: [
          "5–8 core screens",
          "1–2 core flows",
          "Interactive prototype",
          "iOS or Android focus",
          "Investor and internal validation",
        ],
      },
      {
        t: "MVP APP",
        items: [
          "Expanded screens and multiple flows",
          "iOS + Android scope",
          "States and edge paths included",
          "Basic integration or API mock",
          "Dev kickoff spec pack",
        ],
      },
      {
        t: "STORE-READY",
        items: [
          "Store-ready app development",
          "Backend, auth, payments, push",
          "QA, deploy, store submission",
          "Ops and maintenance link",
          "Custom quote and timeline",
        ],
      },
    ],
    timeLabel: "TIMELINE",
    timeTitle: "Timeline depends on scope.",
    timeLead: "Duration varies by screen count, interaction depth, platform, and feedback rounds.",
    timelines: [
      { t: "Prototype", d: "About 2–3 weeks · varies" },
      { t: "MVP App", d: "About 4–6 weeks · varies" },
      { t: "Store-ready", d: "Custom · separate scope" },
    ],
    priceLabel: "PROJECT COST",
    priceTitle: "Quoted per project.",
    priceName: "APP PROTOTYPE",
    priceValue: "From ₩500,000",
    priceFactorsLabel: "Pricing factors",
    priceFactors: [
      "Screens — core and expansion count",
      "Flows — flow and state complexity",
      "Platform — iOS / Android / web",
      "Interaction — interaction and motion depth",
      "Timeline — schedule and feedback rounds",
      "Integration — API mock and link scope",
      "Design depth — UI and design system",
      "Next step — MVP or store-ready link",
    ],
    priceNote: "From ₩500,000 is the starting price for APP PROTOTYPE. MVP App and store-ready builds are quoted separately by scope.",
    faqLabel: "FAQ",
    faqTitle: "Frequently asked questions",
    faqs: [
      {
        q: "What does From ₩500,000 cover?",
        a: "It is the starting price for APP PROTOTYPE — typically core screens and 1–2 interactive flows. MVP App and store-ready builds are quoted separately.",
      },
      {
        q: "Is this a store-ready app?",
        a: "The default is a prototype for investor, internal, and pre-dev validation. Store-ready app development is a separate Store-ready scope.",
      },
      {
        q: "Can you cover both iOS and Android?",
        a: "Yes. We design for one platform focus or both, depending on project goal. Quote varies by screens and platform count.",
      },
      {
        q: "How long does it take?",
        a: "Prototype is typically 2–3 weeks; MVP App about 4–6 weeks. Depends on screens, interaction depth, and feedback rounds.",
      },
      {
        q: "Can this continue into development?",
        a: "Yes. We can propose MVP, full build, or store-ready scope from the prototype and spec.",
      },
      {
        q: "How many revisions?",
        a: "Two revision rounds are included. Out-of-scope changes and extra screens affect timeline and quote.",
      },
      {
        q: "Figma only, or a working prototype?",
        a: "The focus is an interactive working prototype. UI files and spec docs can be included when needed.",
      },
    ],
    finalLabel: "START A PROJECT",
    finalTitle: "Show the experience\nbefore the pitch deck.",
    finalLead:
      "If you have an app idea, demo goal, reference apps, or a deadline, tell us what you need to validate. We will confirm iOS/Android prototype scope and validation approach together.",
    ctaFinalSecondary: "View all BUILD →",
    ctaFinalSecondaryHref: "../build/",
  },
};

export function getAppCopy(lang) {
  return resolveKoEnPack(APP_COPY, lang, "app-copy");
}
