/** BabyLog page copy — merged by apply-babylog-locales.mjs */

export const blKo = {
  brandAria: "BabyLog 상단으로",
  globalReachBadge: "From pregnancy to growth · Worldwide service",
  badge: "👶 육아 기록 · 성장 관리 · 가족 공유 · AI 분석",
  h1: "BabyLog",
  subtitleHtml: `<span class="ox-accent">아이의 모든 순간을 하나의 이야기로 기록하세요</span>`,
  heroReachSummary:
    "임신부터 청소년기까지 아이의 성장 데이터를 쌓고, 가족과 함께 성장 스토리를 만들어가는 디지털 성장 아카이브입니다.",
  heroLogoAlt: "BabyLog 앱 로고: 파스텔 핑크 3D B 문자",
  showcaseCollageAria:
    "BabyLog 앱 스크린샷 7장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt:
    "BabyLog — AI와 함께 더 스마트한 육아, 우리 아이의 모든 순간을 BabyLog에",
  imgShot2Alt:
    "BabyLog — 하루의 모든 육아 기록을 한곳에, 기록 탭과 빠른 기록 안내",
  imgShot3Alt:
    "BabyLog 캘린더 — 우리 아이와 가족의 일정을 한곳에 관리",
  imgShot4Alt:
    "BabyLog 커뮤니티 — 부모들과 실시간 육아 이야기와 고민을 함께 나누기",
  imgShot5Alt:
    "BabyLog 육아 아카이브 — 아이의 모든 순간을 하나의 성장 스토리로, AI 추억",
  imgShot6Alt:
    "BabyLog 기록 추가 — 필요한 기록을 더 빠르고 간편하게 추가",
  imgShot7Alt:
    "BabyLog 프리미엄 — 기록을 넘어 자세한 성장 분석까지",
  introLabel: "브랜드",
  introTitle: "왜 BabyLog인가",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>아이의 모든 순간을 하나의 이야기로 기록하세요</strong></p><p><strong>BabyLog</strong>는 임신부터 유아기, 학령기와 청소년기까지 아이의 성장과 일상을 한곳에 기록하고 관리할 수 있는 올인원 성장 기록 플랫폼입니다.</p><p>수유와 수면부터 건강, 학습, 일정, 추억까지 아이의 모든 순간을 체계적으로 보관할 수 있습니다.</p><p>BabyLog는 단순히 기록을 남기는 앱이 아니라, 아이의 성장 데이터를 쌓고 변화를 이해하며 더 나은 육아를 도와주는 AI 기반 성장 파트너입니다.</p><p>오늘의 작은 기록은 내일 아이의 소중한 추억이 됩니다.</p>',
  introClosing: "아이의 하루를 기록하고 평생의 성장 스토리를 만들어보세요.",  reviewsTitle: "사용자 이야기",  review1Quote: "사진만 남는 줄 알았는데 그날의 감정까지 기억하게 되네요.",  review2Emoji: "👨🏻",  review2Meta: "아빠 · 36세",  review3Quote: "몇 년 뒤 아이와 함께 볼 생각을 하면 벌써 설렙니다.",  review4Emoji: "👨🏽",  review4Meta: "아빠 · 38세",
  reviewsLabel: "후기",
  reviewsTitle: "사용자 이야기",
  review1Emoji: "👩🏻",
  review1Quote: "사진만 남는 줄 알았는데 그날의 감정까지 기억하게 되네요.",
  review1Meta: "엄마 · 31세",
  review2Emoji: "👨🏻",
  review2Quote: "아이의 첫 순간들을 놓치지 않게 됐어요.",
  review2Meta: "아빠 · 36세",
  review3Emoji: "👩🏼",
  review3Quote: "몇 년 뒤 아이와 함께 볼 생각을 하면 벌써 설렙니다.",
  review3Meta: "엄마 · 29세",
  review4Emoji: "👨🏽",
  review4Quote: "육아 기록이 쌓일수록 가족 앨범이 만들어지는 기분이에요.",
  review4Meta: "아빠 · 38세",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "육아 기록",
  feat1Lead: "수유, 수면, 배변, 식사, 놀이,",
  feat1Note: "감정 상태 등을 간편하게 기록할 수 있습니다.",
  feat2Title: "아이 프로필 관리",
  feat2Lead: "성장 단계, 건강 정보, 학교 정보,",
  feat2Note: "기본 일정 등을 체계적으로 관리합니다.",
  feat3Title: "성장 · 건강 기록",
  feat3Lead: "키, 몸무게, BMI, 발달 상태,",
  feat3Note: "예방접종과 건강 이력을 기록합니다.",
  feat4Title: "일정 관리",
  feat4Lead: "병원 방문, 예방접종, 학원·학교 행사,",
  feat4Note: "가족 일정 등을 한곳에서 관리합니다.",
  feat5Title: "성장 통계",
  feat5Lead: "성장 추이, 생활 패턴, 수면 시간,",
  feat5Note: "학습 변화 등을 시각적으로 확인할 수 있습니다.",
  feat6Title: "가족 공유",
  feat6Lead: "부모, 조부모, 보호자와 함께",
  feat6Note: "아이의 기록을 공유할 수 있습니다.",
  feat7Title: "커뮤니티",
  feat7Lead: "육아 경험 공유, 정보 교환,",
  feat7Note: "질문과 답변, 성장 이야기 나눔.",
  feat8Title: "AI 육아 분석",
  feat8Lead: "성장·수면·생활 습관 패턴 분석,",
  feat8Note: "AI 육아 인사이트를 제공합니다.",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 아이 등록",
  how1P: "아이의 프로필과 기본 정보를 생성하세요.",
  how2Title: "2️⃣ 일상 기록",
  how2P: "수유, 수면, 배변, 식사, 놀이를 기록하세요.",
  how3Title: "3️⃣ 성장 기록",
  how3P: "키, 몸무게, 건강 데이터를 꾸준히 입력하세요.",
  how4Title: "4️⃣ 일정 관리",
  how4P: "병원 일정, 예방접종, 학교 일정을 등록하세요.",
  how5Title: "5️⃣ 성장 통계 확인",
  how5P: "아이의 성장 변화와 생활 패턴을 분석하세요.",
  how6Title: "6️⃣ 가족 공유",
  how6P: "가족을 초대하여 함께 기록을 관리하세요.",
  how7Title: "7️⃣ AI 분석",
  how7P: "아이의 데이터를 기반으로 성장 인사이트를 받아보세요.",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "AI와 데이터로<br />더 똑똑한 육아",
  premFeatHeading: "프리미엄 기능",
  prem1Title: "AI 육아 코치",
  prem1Lead: "아이 성장 분석, 발달 인사이트,",
  prem1Note: "생활 패턴 제안과 맞춤형 육아 가이드를 제공합니다.",
  prem2Title: "성장 예측",
  prem2Lead: "성장 추이 분석, 발달 변화 예측,",
  prem2Note: "연령별 비교 데이터를 제공합니다.",
  prem3Title: "성장 리포트",
  prem3Lead: "월간 성장 리포트, PDF 아카이브,",
  prem3Note: "추억 보관과 성장 앨범 테마를 지원합니다.",
  prem4Title: "학습 분석",
  prem4Lead: "학습 기록, 성취도 분석,",
  prem4Note: "공부 습관 인사이트를 확인합니다.",
  prem5Title: "고급 성장 통계",
  prem5Lead: "기간별 성장 비교, 패턴 분석,",
  prem5Note: "데이터 기반 육아 인사이트를 제공합니다.",
  prem6Title: "백업 · 동기화",
  prem6Lead: "기록 안전 보관, 클라우드 백업,",
  prem6Note: "다중 기기 연동을 지원합니다.",
  prem7Title: "가족 프리미엄 공유",
  prem7Lead: "가족 구성원 초대, 동시 관리,",
  prem7Note: "공동 육아 환경을 제공합니다.",
  prem8Title: "광고 제거",
  prem8Lead: "광고 없이",
  prem8Note: "아이의 기록에 집중할 수 있습니다.",
  recoTitle: "이런 분들에게 추천",
  reco1: "👶 아이의 모든 기록을 한곳에 관리하고 싶은 부모",
  reco2: "👨‍👩‍👧 가족과 함께 육아 정보를 공유하고 싶은 분",
  reco3: "📈 성장 데이터를 체계적으로 관리하고 싶은 분",
  reco4: "🤖 AI 분석을 통해 아이의 패턴을 이해하고 싶은 분",
  reco5: "📄 성장 리포트와 PDF 앨범을 만들고 싶은 분",
  reco6: "🩺 병원·예방접종 일정을 놓치고 싶지 않은 분",
  reco7: "💖 아이의 소중한 순간을 오래 간직하고 싶은 분",
  premHiKicker: "하루의 육아 기록으로",
  premHiLine: "아이의 성장 이야기를 만들어가세요.",
  premHiSub: "BabyLog가 당신의<br />육아 여정을 더 특별하게 만듭니다.",
  closingHtml:
    `<p>아이의 오늘이<br /><span class="ox-accent">평생의 추억이 됩니다</span></p><p>BabyLog는 기록을 남기는 앱이 아니라<br />가족의 소중한 순간을 이어가는 공간입니다.</p><p>빠르게 지나가는 성장의 시간을<br /><span class="ox-accent">오래 기억할 수 있도록 함께합니다.</span></p>`,
  closingAria: "마무리 문구",
  footerRights: "© BabyLog ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY 소개",
  drawerBl: "BabyLog · 이 화면",
  appStoreUrl: "https://apps.apple.com/kr/app/babylog-%EC%8A%A4%EB%A7%88%ED%8A%B8%ED%95%9C-ai-%EC%9C%A1%EC%95%84-%EA%B8%B0%EB%A1%9D/id6768019196",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.babylog&pcampaignid=web_share",
  appStoreBadgeAria: "App Store에서 BabyLog(새 탭)",
  googlePlayBadgeAria: "Google Play에서 BabyLog(새 탭)",
};

export const blEn = {
  brandAria: "Back to top of BabyLog",
  globalReachBadge: "From pregnancy to growth · worldwide service",
  badge: "👶 Childcare logs · Growth · Family sharing · AI analysis",
  h1: "BabyLog",
  subtitleHtml: `<span class="ox-accent">Turn every moment into one growth story</span>`,
  heroReachSummary:
    "A digital growth archive—from pregnancy through teens—that helps families build a lasting story from every record.",
  heroLogoAlt: "BabyLog app logo: glossy pastel pink 3D letter B on white",
  showcaseCollageAria:
    "Seven BabyLog app screenshots. Scroll horizontally to view all.",
  imgShot1Alt:
    "BabyLog intro — AI-powered smarter parenting; capture every moment of your child with BabyLog",
  imgShot2Alt:
    "BabyLog Records — manage your child and family schedules in one place; Premium AI",
  imgShot3Alt:
    "BabyLog Calendar — all your daily parenting records in one place, May plans and summaries",
  imgShot4Alt:
    "BabyLog Community — connect with parents in real time; share stories and concerns",
  imgShot5Alt:
    "BabyLog Parenting archive — turn every moment into a beautiful growth story; AI memory",
  imgShot6Alt:
    "BabyLog Add record — add important records faster and easier",
  imgShot7Alt:
    "BabyLog Premium — beyond records, detailed growth insights and AI tools",
  introLabel: "Brand",
  introTitle: "Why BabyLog",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>Turn every moment into one growth story</strong></p><p><strong>BabyLog</strong> is an all-in-one growth platform—from pregnancy through school years and teens—to record and manage your child\'s daily life in one place.</p><p>From feeds and sleep to health, learning, schedules, and memories—keep every moment organized.</p><p>BabyLog is not just a log. It is an AI growth partner that builds data over time, helps you understand change, and supports better parenting.</p><p>Today\'s small entry becomes tomorrow\'s precious memory.</p>',
  introClosing: "Log each day and build a lifetime growth story.",  reviewsTitle: "User stories",  review1Quote: "I thought I'd only keep photos—but I remember how each day felt.",  review2Emoji: "👨🏻",  review2Meta: "Dad · 36",  review3Quote: "Thinking about watching these with my kid years from now already excites me.",  review4Emoji: "👨🏽",  review4Meta: "Dad · 38",
  reviewsLabel: "Reviews",
  reviewsTitle: "User stories",
  review1Emoji: "👩🏻",
  review1Quote: "I thought I'd only keep photos—but I remember how each day felt.",
  review1Meta: "Mom · 31",
  review2Emoji: "👨🏻",
  review2Quote: "I don't miss my child's first moments anymore.",
  review2Meta: "Dad · 36",
  review3Emoji: "👩🏼",
  review3Quote: "Thinking about watching these with my kid years from now already excites me.",
  review3Meta: "Mom · 29",
  review4Emoji: "👨🏽",
  review4Quote: "As logs pile up, it feels like our family album is building itself.",
  review4Meta: "Dad · 38",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Parenting logs",
  feat1Lead: "Feeds, sleep, diapers, meals, play,",
  feat1Note: "and mood—logged with ease.",
  feat2Title: "Child profiles",
  feat2Lead: "Growth stage, health info, school details,",
  feat2Note: "and core schedules—organized per child.",
  feat3Title: "Growth & health",
  feat3Lead: "Height, weight, BMI, milestones,",
  feat3Note: "vaccinations, and health history.",
  feat4Title: "Scheduling",
  feat4Lead: "Clinic visits, vaccinations, classes,",
  feat4Note: "school events, and family plans in one place.",
  feat5Title: "Growth statistics",
  feat5Lead: "Growth trends, daily patterns, sleep,",
  feat5Note: "and learning changes—visualized clearly.",
  feat6Title: "Family sharing",
  feat6Lead: "Share records with parents, grandparents,",
  feat6Note: "and caregivers together.",
  feat7Title: "Community",
  feat7Lead: "Share experiences, swap tips,",
  feat7Note: "ask questions, and tell growth stories.",
  feat8Title: "AI parenting insights",
  feat8Lead: "Growth, sleep, and routine pattern analysis—",
  feat8Note: "with AI-powered parenting insights.",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Add a child",
  how1P: "Create a profile and enter the basics.",
  how2Title: "2️⃣ Log daily life",
  how2P: "Record feeds, sleep, diapers, meals, and play.",
  how3Title: "3️⃣ Track growth",
  how3P: "Keep height, weight, and health data up to date.",
  how4Title: "4️⃣ Manage schedules",
  how4P: "Add clinic visits, vaccinations, and school plans.",
  how5Title: "5️⃣ Review growth stats",
  how5P: "Analyze growth changes and daily patterns.",
  how6Title: "6️⃣ Share with family",
  how6P: "Invite loved ones to manage records together.",
  how7Title: "7️⃣ AI analysis",
  how7P: "Get growth insights from your child's data.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "Smarter parenting<br />with AI and data",
  premFeatHeading: "Premium features",
  prem1Title: "AI parenting coach",
  prem1Lead: "Growth analysis, development insights,",
  prem1Note: "routine suggestions, and tailored guides.",
  prem2Title: "Growth forecasting",
  prem2Lead: "Trend analysis, development predictions,",
  prem2Note: "and age-based comparison data.",
  prem3Title: "Growth reports",
  prem3Lead: "Monthly reports, PDF archives,",
  prem3Note: "memory keepsakes, and album themes.",
  prem4Title: "Learning analysis",
  prem4Lead: "Learning logs, achievement tracking,",
  prem4Note: "and study-habit insights.",
  prem5Title: "Advanced growth stats",
  prem5Lead: "Period comparisons and pattern analysis—",
  prem5Note: "data-driven parenting insights.",
  prem6Title: "Backup & sync",
  prem6Lead: "Safe record storage, cloud backup,",
  prem6Note: "and multi-device sync.",
  prem7Title: "Family premium sharing",
  prem7Lead: "Invite family, manage together,",
  prem7Note: "and share one premium plan.",
  prem8Title: "Remove ads",
  prem8Lead: "No ads—",
  prem8Note: "focus on your child's records.",
  recoTitle: "Great if you…",
  reco1: "👶 Want every record in one organized place",
  reco2: "👨‍👩‍👧 Want to share parenting with family",
  reco3: "📈 Want structured growth data over time",
  reco4: "🤖 Want AI help to understand patterns",
  reco5: "📄 Want growth reports and PDF albums",
  reco6: "🩺 Never want to miss clinic or vaccine dates",
  reco7: "💖 Want to keep precious moments for years",
  premHiKicker: "From daily parenting logs",
  premHiLine: "Shape your child's growth story.",
  premHiSub: "BabyLog makes your<br />parenting journey more meaningful.",
  closingHtml:
    `<p>Today's moments<br /><span class="ox-accent">Become lifelong memories</span></p><p>BabyLog isn't just for logging—<br />it's a space to keep your family's precious moments.</p><p>We'll help you remember<br /><span class="ox-accent">how quickly they grow.</span></p>`,
  closingAria: "Closing message",
  footerRights: "© BabyLog ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "SAVY intro",
  drawerBl: "BabyLog · this screen",
  appStoreUrl: "https://apps.apple.com/kr/app/babylog-%EC%8A%A4%EB%A7%88%ED%8A%B8%ED%95%9C-ai-%EC%9C%A1%EC%95%84-%EA%B8%B0%EB%A1%9D/id6768019196",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.babylog&pcampaignid=web_share",
  appStoreBadgeAria: "BabyLog on the App Store (opens in a new tab)",
  googlePlayBadgeAria: "BabyLog on Google Play (opens in a new tab)",
};

/** Japanese — same structure as blEn; showcase alts match JA promo screens */
export const blJa = {
  ...blEn,
  showcaseCollageAria:
    "BabyLogアプリのスクリーンショット7枚です。横にスクロールしてご覧ください。",
  imgShot1Alt:
    "BabyLog — AIでもっとスマートな育児、子どものすべての瞬間をBabyLogに",
  imgShot2Alt:
    "BabyLog記録 — 子どもと家族の予定をひとつに管理できる記録ホーム・クイック記録の案内",
  imgShot3Alt:
    "BabyLogカレンダー — 毎日の育児記録をひとつに、月表示と家族・マイルストーン概要",
  imgShot4Alt:
    "BabyLogコミュニティ — リアルタイムでつながる育児、悩みや経験をみんなで共有",
  imgShot5Alt:
    "BabyLog子育てアーカイブ — 子どものすべての瞬間を成長ストーリーに、AIメモリー",
  imgShot6Alt:
    "BabyLog記録を追加 — 必要な記録をもっと素早く簡単に",
  imgShot7Alt:
    "BabyLogプレミアム — 記録を超えた成長分析まで、プレミアムAI機能の一覧",
  drawerBl: "BabyLog · この画面",
};

/** Spanish — showcase alts match ES promo screens */
export const blEs = {
  ...blEn,
  showcaseCollageAria:
    "Siete capturas de la app BabyLog. Desplázate horizontalmente para verlas todas.",
  imgShot1Alt:
    "BabyLog — Una crianza más inteligente con IA; todos los momentos de tu bebé en BabyLog",
  imgShot2Alt:
    "BabyLog registros — Organiza horarios de tu bebé y familia en un solo lugar, IA Premium",
  imgShot3Alt:
    "BabyLog calendario — Todos los registros diarios del bebé en un solo lugar, mayo de 2026",
  imgShot4Alt:
    "BabyLog comunidad — Conecta con padres en tiempo real, comparte experiencias",
  imgShot5Alt:
    "BabyLog archivo de crianza — Convierte cada momento en una historia de crecimiento, archivo de memoria IA",
  imgShot6Alt:
    "BabyLog añadir registro — Registros importantes de forma rápida y sencilla",
  imgShot7Alt:
    "BabyLog Premium — Más que registros, análisis detallados del crecimiento con IA",
  drawerBl: "BabyLog · esta pantalla",
};

/** Portuguese (pt-BR) — showcase alts match PT promo screens */
export const blPtBr = {
  ...blEn,
  showcaseCollageAria:
    "Sete capturas de tela do app BabyLog. Role na horizontal para ver todas.",
  imgShot1Alt:
    "BabyLog — Parentalidade mais inteligente com IA; todos os momentos do bebê no BabyLog",
  imgShot2Alt:
    "BabyLog registros — Organize horários da família e do bebê num só lugar, registro rápido e IA Premium",
  imgShot3Alt:
    "BabyLog calendário — Todos os registros diários do bebê num só lugar, maio 2026 e resumos",
  imgShot4Alt:
    "BabyLog comunidade — Converse com outros pais em tempo real, partilhe dúvidas e experiências",
  imgShot5Alt:
    "BabyLog arquivo dos pais — Transforme cada momento numa história de crescimento, arquivo de memória IA",
  imgShot6Alt:
    "BabyLog adicionar registro — Registros importantes de forma rápida e fácil",
  imgShot7Alt:
    "BabyLog Premium — Muito além dos registros, análises completas de crescimento e IA",
  drawerBl: "BabyLog · esta tela",
};
