/**
 * Company hub copy (KO / EN). Other locales fall back to EN.
 */

const SHARED_KO = {
  crumbCompany: "COMPANY",
  exploreTitle: "MORE FROM COMPANY",
  exploreProducts: "Products",
  exploreBusiness: "Business",
  exploreResources: "Resources",
  viewProject: "VIEW PROJECT →",
  readUpdate: "READ →",
  prev: "PREVIOUS",
  next: "NEXT",
  moreNews: "MORE NEWS",
  morePortfolio: "MORE FROM NEWON",
  copyEmail: "COPY EMAIL",
  copied: "COPIED",
  emailLabel: "GENERAL / BUSINESS",
  responseNote: "문의 내용을 확인한 후 순차적으로 답변드립니다.",
  directContact: "DIRECT CONTACT",
};

const SHARED_EN = {
  crumbCompany: "COMPANY",
  exploreTitle: "MORE FROM COMPANY",
  exploreProducts: "Products",
  exploreBusiness: "Business",
  exploreResources: "Resources",
  viewProject: "VIEW PROJECT →",
  readUpdate: "READ →",
  prev: "PREVIOUS",
  next: "NEXT",
  moreNews: "MORE NEWS",
  morePortfolio: "MORE FROM NEWON",
  copyEmail: "COPY EMAIL",
  copied: "COPIED",
  emailLabel: "GENERAL / BUSINESS",
  responseNote: "We review inquiries in order and reply when we can.",
  directContact: "DIRECT CONTACT",
};

const KO = {
  ...SHARED_KO,
  about: {
    seoTitle: "About Newon | Company",
    metaDescription:
      "Newon은 아이디어를 제품으로 설계하고, 만들고, 출시하고, 운영하는 Independent Product Studio입니다.",
    eyebrow: "NEWON",
    subEyebrow: "INDEPENDENT PRODUCT STUDIO",
    headline: "아이디어를\n실제 제품으로 만듭니다.",
    lead: "Newon은 아이디어를 제품으로 설계하고, 직접 만들고, 출시하고, 운영하며 새로운 디지털 경험을 실험하는 Product Studio입니다.",
    ctaProducts: "제품 보기 →",
    ctaPortfolio: "Portfolio →",
    indexTitle: "NEWON / PRODUCT SYSTEM",
    indexItems: [
      { k: "PRODUCTS", href: "../products/" },
      { k: "GAMES", href: "../games/" },
      { k: "TOOLS", href: "../tools/" },
      { k: "EXPERIMENTS", href: "../resources/labs/" },
    ],
    buildTitle: "하나의 아이디어에서\n실제 사용자에게 닿는 제품까지.",
    buildEyebrow: "WHAT WE BUILD",
    buildItems: [
      { n: "01", title: "PRODUCTS", body: "앱과 디지털 제품" },
      { n: "02", title: "GAMES", body: "인터랙티브 경험과 게임" },
      { n: "03", title: "TOOLS", body: "실용적인 디지털 도구" },
      { n: "04", title: "EXPERIMENTS", body: "AI와 새로운 인터페이스 실험" },
      { n: "05", title: "BUSINESS", body: "브랜드를 위한 제품·웹·자동화" },
    ],
    workEyebrow: "HOW WE WORK",
    workTitle: "제품을 만드는 방식",
    workSteps: [
      { n: "01", title: "DISCOVER", body: "문제와 기회를 찾습니다." },
      { n: "02", title: "DESIGN", body: "제품 구조와 경험을 설계합니다." },
      { n: "03", title: "BUILD", body: "실제로 작동하는 제품을 만듭니다." },
      { n: "04", title: "LAUNCH", body: "사용자에게 출시합니다." },
      { n: "05", title: "LEARN", body: "반응을 바탕으로 개선합니다." },
      { n: "06", title: "ITERATE", body: "다음 버전을 만듭니다." },
    ],
    principlesEyebrow: "PRINCIPLES",
    principlesTitle: "제품 철학",
    principles: [
      { n: "01", title: "BUILD, NOT JUST PLAN.", body: "아이디어를 문서에 남겨두지 않고 실제 제품으로 만듭니다." },
      { n: "02", title: "SMALL → REAL.", body: "작게 시작하되 실제 사용 가능한 제품을 만듭니다." },
      { n: "03", title: "LEARN FROM USERS.", body: "출시 이후의 반응을 다음 제품에 반영합니다." },
      { n: "04", title: "KEEP BUILDING.", body: "하나의 출시를 끝이 아니라 다음 실험의 시작으로 봅니다." },
    ],
    systemEyebrow: "NEWON SYSTEM",
    systemTitle: "아이디어가 제품이 되는 구조",
    systemFlow: ["IDEA", "PRODUCT", "LAUNCH", "USER", "FEEDBACK", "ITERATION"],
    systemHubs: [
      { title: "PRODUCTS", href: "../products/" },
      { title: "BUSINESS", href: "../business/" },
      { title: "RESOURCES", href: "../resources/" },
      { title: "COMPANY", href: "./" },
    ],
    timelineEyebrow: "TIMELINE",
    timelineTitle: "Newon 이력",
    timelineNote: "확인된 프로젝트·업데이트만 표시합니다.",
    visionEyebrow: "VISION",
    visionTitle: "우리는\n다음 제품을 만듭니다.",
    visionEn: "WE BUILD WHAT'S NEXT.",
    visionCtaPortfolio: "Portfolio 보기 →",
    visionCtaContact: "Newon과 프로젝트 시작하기 →",
  },
  portfolio: {
    seoTitle: "Portfolio | Newon Company",
    metaDescription: "Newon이 기획·설계·개발한 제품과 프로젝트를 살펴보세요.",
    eyebrow: "PORTFOLIO",
    subEyebrow: "SELECTED WORK",
    headline: "아이디어에서\n출시까지.",
    lead: "Newon이 기획하고 설계하고 개발한 제품과 프로젝트를 살펴보세요.",
    filterAll: "ALL",
    emptyFilter: "이 카테고리에 해당하는 프로젝트가 없습니다.",
    metaCategory: "CATEGORY",
    metaYear: "YEAR",
    metaPlatform: "PLATFORM",
    metaStatus: "STATUS",
    caseEyebrow: "PROJECT",
    caseSections: {
      overview: "01 OVERVIEW",
      idea: "02 THE IDEA",
      problem: "03 THE PROBLEM",
      product: "04 PRODUCT",
      design: "05 DESIGN",
      build: "06 BUILD",
      launch: "07 LAUNCH",
      learnings: "08 LEARNINGS",
      next: "09 NEXT",
    },
    appStore: "APP STORE →",
    googlePlay: "GOOGLE PLAY →",
    playGame: "PLAY / VISIT →",
    backPortfolio: "← Portfolio",
  },
  news: {
    seoTitle: "News | Newon Company",
    metaDescription: "제품 출시, 업데이트, Newon의 공식 소식을 확인하세요.",
    eyebrow: "NEWON NEWSROOM",
    headline: "Newon의\n새로운 소식.",
    lead: "제품 출시, 업데이트, 새로운 프로젝트와 Newon의 주요 소식을 확인하세요.",
    latestLabel: "LATEST UPDATE",
    filterAll: "ALL",
    empty: "아직 게시된 뉴스가 없습니다.",
    listView: "LIST",
    timelineView: "TIMELINE",
    backNews: "← News",
  },
  idea: {
    seoTitle: "Newon Idea | Company",
    metaDescription: "필요했던 기능과 제품 아이디어를 Newon에 제안하세요.",
    eyebrow: "NEWON IDEA",
    headline: "작은 아이디어도\n제품의 시작이 될 수 있습니다.",
    lead: "필요했던 기능, 불편했던 경험, 있었으면 좋겠다고 생각한 제품을 Newon에 제안해주세요. 모든 아이디어가 제품이 되는 것은 아니지만, 새로운 제품을 만드는 과정에서 검토할 수 있습니다.",
    ctaForm: "아이디어 제안하기 ↓",
    howEyebrow: "HOW IT WORKS",
    howTitle: "제안이 이어지는 방식",
    howSteps: [
      { n: "01", title: "SUBMIT", body: "아이디어를 보내주세요." },
      { n: "02", title: "REVIEW", body: "Newon에서 내용을 검토합니다." },
      { n: "03", title: "EXPLORE", body: "가능성이 있는 아이디어를 더 살펴봅니다." },
      { n: "04", title: "BUILD", body: "적합한 아이디어는 제품 실험으로 이어질 수 있습니다." },
    ],
    formEyebrow: "IDEA FORM",
    formTitle: "아이디어 보내기",
    step1: "어떤 아이디어인가요?",
    titleLabel: "아이디어 제목 *",
    titlePh: "예: 이런 앱이 있었으면 좋겠어요",
    step2: "어떤 문제를 해결하나요? *",
    problemPh: "불편했던 점이나 해결하고 싶은 문제를 적어주세요.",
    step3: "누가 사용할까요?",
    audience: ["나 자신", "일반 사용자", "학생", "직장인", "가족", "사업자", "기타"],
    step4: "어떤 형태의 제품인가요?",
    forms: ["APP", "WEB", "AI", "GAME", "TOOL", "NOT SURE"],
    step5: "조금 더 설명해주세요.",
    morePh: "선택 사항 — 추가로 전하고 싶은 내용",
    step6: "참고할 링크",
    linkPh: "https://",
    step7: "연락받을 이메일",
    emailPh: "you@email.com",
    emailHint: "답변이 필요할 때만 사용합니다. (선택)",
    legalTitle: "아이디어 제출 전 안내",
    legalItems: [
      "제출된 아이디어는 Newon의 기존 또는 향후 프로젝트와 유사할 수 있습니다.",
      "제출만으로 비밀유지계약(NDA), 보상 또는 사업 관계가 성립하지 않습니다.",
      "민감하거나 기밀인 정보는 제출하지 마세요.",
    ],
    legalCheck: "아이디어 제출 안내를 확인했습니다.",
    submit: "아이디어 보내기 →",
    submitting: "SUBMITTING...",
    successTitle: "IDEA RECEIVED",
    successBody: "아이디어가 전달되었습니다. Newon에 의견을 보내주셔서 감사합니다.",
    errRequired: "필수 항목을 입력해주세요.",
    errEmail: "이메일 형식을 확인해주세요.",
    errUrl: "URL 형식을 확인해주세요.",
    errLegal: "안내 확인에 동의해주세요.",
    errSend: "전송에 실패했습니다. 잠시 후 다시 시도하거나 newon@newon.app으로 보내주세요.",
  },
  contact: {
    seoTitle: "Contact | Newon Company",
    metaDescription: "프로젝트, 파트너십, 비즈니스, 미디어 문의를 Newon에 보내주세요.",
    eyebrow: "CONTACT NEWON",
    headline: "무엇을 함께\n만들 수 있을까요?",
    lead: "프로젝트, 파트너십, 비즈니스, 미디어 및 기타 문의를 보내주세요.",
    typeEyebrow: "CONTACT TYPE",
    typeTitle: "문의 유형을 선택하세요",
    types: [
      { id: "project", title: "PROJECT", body: "제품 제작 / 개발 프로젝트" },
      { id: "partnership", title: "PARTNERSHIP", body: "브랜드 / 서비스 협업" },
      { id: "business", title: "BUSINESS", body: "B2B / 사업 문의" },
      { id: "media", title: "MEDIA", body: "인터뷰 / 미디어" },
      { id: "support", title: "SUPPORT", body: "Newon 제품 관련 문의" },
      { id: "other", title: "OTHER", body: "기타 문의" },
    ],
    formEyebrow: "CONTACT FORM",
    formTitle: "문의 보내기",
    nameLabel: "이름 *",
    emailLabel: "이메일 *",
    companyLabel: "회사 / 조직",
    subjectLabel: "문의 제목 *",
    messageLabel: "문의 내용 *",
    urlLabel: "관련 URL",
    projectKindLabel: "프로젝트 종류",
    projectKinds: ["APP", "WEB", "AI", "SaaS", "DESIGN", "OTHER"],
    timelineLabel: "예상 일정",
    timelines: ["ASAP", "1–2 MONTHS", "3–6 MONTHS", "NOT DECIDED"],
    brandLabel: "회사 / 브랜드명",
    collabLabel: "협업 유형",
    mediaNameLabel: "매체명",
    mediaRequestLabel: "요청 내용",
    mediaDateLabel: "희망 일정",
    productLabel: "사용 중인 제품",
    issueLabel: "문제 유형",
    submit: "문의 보내기 →",
    submitting: "SENDING...",
    successTitle: "MESSAGE RECEIVED",
    successBody: "문의가 정상적으로 전달되었습니다. 확인 후 답변드리겠습니다.",
    errRequired: "필수 항목을 입력해주세요.",
    errEmail: "이메일 형식을 확인해주세요.",
    errUrl: "URL 형식을 확인해주세요.",
    errSend: "전송에 실패했습니다. 잠시 후 다시 시도하거나 newon@newon.app으로 보내주세요.",
  },
};

const EN = {
  ...SHARED_EN,
  about: {
    seoTitle: "About Newon | Company",
    metaDescription:
      "Newon is an independent product studio that designs, builds, launches, and operates digital products.",
    eyebrow: "NEWON",
    subEyebrow: "INDEPENDENT PRODUCT STUDIO",
    headline: "We turn ideas\ninto real products.",
    lead: "Newon is a product studio that designs ideas into products, builds them, ships them, operates them, and experiments with new digital experiences.",
    ctaProducts: "View products →",
    ctaPortfolio: "Portfolio →",
    indexTitle: "NEWON / PRODUCT SYSTEM",
    indexItems: [
      { k: "PRODUCTS", href: "../products/" },
      { k: "GAMES", href: "../games/" },
      { k: "TOOLS", href: "../tools/" },
      { k: "EXPERIMENTS", href: "../resources/labs/" },
    ],
    buildTitle: "From one idea\nto a product people can use.",
    buildEyebrow: "WHAT WE BUILD",
    buildItems: [
      { n: "01", title: "PRODUCTS", body: "Apps and digital products" },
      { n: "02", title: "GAMES", body: "Interactive experiences and games" },
      { n: "03", title: "TOOLS", body: "Practical digital tools" },
      { n: "04", title: "EXPERIMENTS", body: "AI and new interface experiments" },
      { n: "05", title: "BUSINESS", body: "Product, web, and automation for brands" },
    ],
    workEyebrow: "HOW WE WORK",
    workTitle: "How products get made",
    workSteps: [
      { n: "01", title: "DISCOVER", body: "Find the problem and the opportunity." },
      { n: "02", title: "DESIGN", body: "Shape structure and experience." },
      { n: "03", title: "BUILD", body: "Ship something that actually works." },
      { n: "04", title: "LAUNCH", body: "Put it in front of users." },
      { n: "05", title: "LEARN", body: "Improve from real response." },
      { n: "06", title: "ITERATE", body: "Make the next version." },
    ],
    principlesEyebrow: "PRINCIPLES",
    principlesTitle: "Product principles",
    principles: [
      { n: "01", title: "BUILD, NOT JUST PLAN.", body: "Ideas leave the doc and become products." },
      { n: "02", title: "SMALL → REAL.", body: "Start small — but ship something usable." },
      { n: "03", title: "LEARN FROM USERS.", body: "Post-launch signal feeds the next build." },
      { n: "04", title: "KEEP BUILDING.", body: "A launch is the start of the next experiment." },
    ],
    systemEyebrow: "NEWON SYSTEM",
    systemTitle: "How ideas become products",
    systemFlow: ["IDEA", "PRODUCT", "LAUNCH", "USER", "FEEDBACK", "ITERATION"],
    systemHubs: [
      { title: "PRODUCTS", href: "../products/" },
      { title: "BUSINESS", href: "../business/" },
      { title: "RESOURCES", href: "../resources/" },
      { title: "COMPANY", href: "./" },
    ],
    timelineEyebrow: "TIMELINE",
    timelineTitle: "Newon timeline",
    timelineNote: "Only verified projects and updates.",
    visionEyebrow: "VISION",
    visionTitle: "We build\nwhat's next.",
    visionEn: "WE BUILD WHAT'S NEXT.",
    visionCtaPortfolio: "View Portfolio →",
    visionCtaContact: "Start a project with Newon →",
  },
  portfolio: {
    seoTitle: "Portfolio | Newon Company",
    metaDescription: "Selected work Newon planned, designed, and built.",
    eyebrow: "PORTFOLIO",
    subEyebrow: "SELECTED WORK",
    headline: "From idea\nto launch.",
    lead: "Explore products and projects Newon planned, designed, and developed.",
    filterAll: "ALL",
    emptyFilter: "No projects in this category yet.",
    metaCategory: "CATEGORY",
    metaYear: "YEAR",
    metaPlatform: "PLATFORM",
    metaStatus: "STATUS",
    caseEyebrow: "PROJECT",
    caseSections: {
      overview: "01 OVERVIEW",
      idea: "02 THE IDEA",
      problem: "03 THE PROBLEM",
      product: "04 PRODUCT",
      design: "05 DESIGN",
      build: "06 BUILD",
      launch: "07 LAUNCH",
      learnings: "08 LEARNINGS",
      next: "09 NEXT",
    },
    appStore: "APP STORE →",
    googlePlay: "GOOGLE PLAY →",
    playGame: "PLAY / VISIT →",
    backPortfolio: "← Portfolio",
  },
  news: {
    seoTitle: "News | Newon Company",
    metaDescription: "Official Newon launches, updates, and company news.",
    eyebrow: "NEWON NEWSROOM",
    headline: "What's new\nat Newon.",
    lead: "Product launches, updates, new projects, and official Newon news.",
    latestLabel: "LATEST UPDATE",
    filterAll: "ALL",
    empty: "No published news yet.",
    listView: "LIST",
    timelineView: "TIMELINE",
    backNews: "← News",
  },
  idea: {
    seoTitle: "Newon Idea | Company",
    metaDescription: "Submit product ideas and feature requests to Newon.",
    eyebrow: "NEWON IDEA",
    headline: "Even a small idea\ncan start a product.",
    lead: "Share a feature you needed, a friction you felt, or a product you wish existed. Not every idea becomes a product — but we review them as we build what’s next.",
    ctaForm: "Submit an idea ↓",
    howEyebrow: "HOW IT WORKS",
    howTitle: "How submissions move",
    howSteps: [
      { n: "01", title: "SUBMIT", body: "Send your idea." },
      { n: "02", title: "REVIEW", body: "Newon reviews the note." },
      { n: "03", title: "EXPLORE", body: "Promising ideas get a closer look." },
      { n: "04", title: "BUILD", body: "Some become product experiments." },
    ],
    formEyebrow: "IDEA FORM",
    formTitle: "Send an idea",
    step1: "What’s the idea?",
    titleLabel: "Idea title *",
    titlePh: "e.g. I wish there was an app for…",
    step2: "What problem does it solve? *",
    problemPh: "Describe the friction or need.",
    step3: "Who would use it?",
    audience: ["Myself", "General users", "Students", "Professionals", "Families", "Businesses", "Other"],
    step4: "What kind of product?",
    forms: ["APP", "WEB", "AI", "GAME", "TOOL", "NOT SURE"],
    step5: "Anything else?",
    morePh: "Optional — extra context",
    step6: "Reference link",
    linkPh: "https://",
    step7: "Email for follow-up",
    emailPh: "you@email.com",
    emailHint: "Optional — only if you want a reply.",
    legalTitle: "Before you submit",
    legalItems: [
      "Your idea may overlap with existing or future Newon work.",
      "Submitting does not create an NDA, payment, or business relationship.",
      "Do not submit sensitive or confidential information.",
    ],
    legalCheck: "I have read the idea submission notice.",
    submit: "Send idea →",
    submitting: "SUBMITTING...",
    successTitle: "IDEA RECEIVED",
    successBody: "Thanks — your idea was sent to Newon.",
    errRequired: "Please fill required fields.",
    errEmail: "Check the email format.",
    errUrl: "Check the URL format.",
    errLegal: "Please confirm the notice.",
    errSend: "Send failed. Try again or email newon@newon.app.",
  },
  contact: {
    seoTitle: "Contact | Newon Company",
    metaDescription: "Contact Newon for projects, partnerships, business, or media.",
    eyebrow: "CONTACT NEWON",
    headline: "What can we\nbuild together?",
    lead: "Send project, partnership, business, media, or other inquiries.",
    typeEyebrow: "CONTACT TYPE",
    typeTitle: "Choose an inquiry type",
    types: [
      { id: "project", title: "PROJECT", body: "Product / development work" },
      { id: "partnership", title: "PARTNERSHIP", body: "Brand or service collaboration" },
      { id: "business", title: "BUSINESS", body: "B2B / business inquiry" },
      { id: "media", title: "MEDIA", body: "Interview / press" },
      { id: "support", title: "SUPPORT", body: "Help with a Newon product" },
      { id: "other", title: "OTHER", body: "Something else" },
    ],
    formEyebrow: "CONTACT FORM",
    formTitle: "Send a message",
    nameLabel: "Name *",
    emailLabel: "Email *",
    companyLabel: "Company / organization",
    subjectLabel: "Subject *",
    messageLabel: "Message *",
    urlLabel: "Related URL",
    projectKindLabel: "Project type",
    projectKinds: ["APP", "WEB", "AI", "SaaS", "DESIGN", "OTHER"],
    timelineLabel: "Timeline",
    timelines: ["ASAP", "1–2 MONTHS", "3–6 MONTHS", "NOT DECIDED"],
    brandLabel: "Company / brand",
    collabLabel: "Collaboration type",
    mediaNameLabel: "Publication",
    mediaRequestLabel: "Request",
    mediaDateLabel: "Preferred timing",
    productLabel: "Product in use",
    issueLabel: "Issue type",
    submit: "Send message →",
    submitting: "SENDING...",
    successTitle: "MESSAGE RECEIVED",
    successBody: "Your message was sent. We’ll review and reply.",
    errRequired: "Please fill required fields.",
    errEmail: "Check the email format.",
    errUrl: "Check the URL format.",
    errSend: "Send failed. Try again or email newon@newon.app.",
  },
};

export function getCompanyCopy(slug, lang) {
  const pack = lang === "ko" ? KO : EN;
  const shared = lang === "ko" ? SHARED_KO : SHARED_EN;
  const page = pack[slug] || EN[slug] || {};
  return { ...shared, ...page, _lang: lang === "ko" ? "ko" : "en" };
}

export function getCompanyShared(lang) {
  return lang === "ko" ? { ...SHARED_KO } : { ...SHARED_EN };
}
