/** CountUp page copy — merged into locales/*.json by apply-countup-locales.mjs */

export const cuKo = {
  brandAria: "CountUp 상단으로",
  globalReachBadge: "173개국 출시 · 13개 언어 지원",
  badge: "🔢 카운트 기록 · 목표 추적 · AI 인사이트",
  h1: "CountUp",
  subtitleHtml: "작은 기록이 모여 더 큰 성장을 만듭니다",
  heroReachSummary:
    "매일의 행동을 카운트하고 목표 달성률, 연속 기록, 성장 흐름까지 한 번에 관리하는 스마트 카운트 앱입니다.",
  heroLogoAlt: "CountUp 앱 로고: 노란 상승 화살표",
  introLabel: "앱 소개",
  introTitle: "앱 소개",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>CountUp</strong>은 반복되는 행동을 쉽고 빠르게 기록하며</p><p>꾸준한 성장 습관을 만들어가는 앱입니다.</p><p>운동, 물 마시기, 공부, 독서, 저축, 루틴 등 원하는 모든 목표를 카운트로 관리할 수 있습니다.</p><p>매일의 작은 기록부터 장기적인 성장 변화까지 한눈에 확인해보세요.</p><p>작은 카운트가 모이면 더 큰 변화가 시작됩니다.</p>',
  introClosing: "오늘의 작은 기록이 미래의 큰 성장을 만듭니다.",
  showcaseCollageAria: "CountUp 앱 미리보기 6장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt: "CountUp — 작은 기록이 큰 변화를 만듭니다",
  imgShot2Alt: "CountUp — 매일의 작은 행동을 기록하고 목표를 쉽게 카운트",
  imgShot3Alt: "CountUp — 연속 기록과 통계로 꾸준함 확인",
  imgShot4Alt: "CountUp — AI 코치, 성장 리포트, 고급 통계 프리미엄",
  imgShot5Alt: "CountUp — AI 코치 데이터 기반 인사이트",
  imgShot6Alt: "CountUp — 10초 만에 새 카운트 만들기",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "카운트 기록",
  feat1Lead: "원하는 행동을 쉽고 빠르게 카운트할 수 있습니다.",
  feat1Note: "하루 여러 번 기록하며 작은 실천을 쌓아갈 수 있습니다.",
  feat2Title: "목표 설정",
  feat2Lead: "목표 횟수와 기간을 설정하고 진행률을 확인할 수 있습니다.",
  feat2Note: "목표까지 얼마나 남았는지 직관적으로 보여줍니다.",
  feat3Title: "연속 기록",
  feat3Lead: "꾸준히 기록한 날과 연속 달성 흐름을 확인할 수 있습니다.",
  feat3Note: "습관이 끊기지 않도록 동기부여를 제공합니다.",
  feat4Title: "기록 알림",
  feat4Lead: "원하는 시간에 기록 리마인드를 받을 수 있습니다.",
  feat4Note: "잊지 않고 매일 실천할 수 있도록 도와줍니다.",
  feat5Title: "성장 통계",
  feat5Lead: "일별, 주별, 월별 카운트 흐름을 분석합니다.",
  feat5Note: "내가 얼마나 성장했는지 데이터로 확인할 수 있습니다.",
  feat6Title: "통계 시각화",
  feat6Lead: "기록 추이와 목표 달성률을 그래프로 보여줍니다.",
  feat6Note: "성장 과정을 직관적으로 확인할 수 있습니다.",
  feat7Title: "AI 인사이트",
  feat7Lead: "AI가 기록 패턴을 분석하여 맞춤 성장 인사이트를 제공합니다.",
  feat7Note: "더 꾸준한 습관 형성을 도와줍니다.",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 카운트 만들기",
  how1P: "기록하고 싶은 행동이나 목표를 추가하세요.",
  how2Title: "2️⃣ 목표 설정",
  how2P: "목표 횟수, 기간, 알림을 설정하세요.",
  how3Title: "3️⃣ 매일 카운트하기",
  how3P: "실천할 때마다 간단하게 숫자를 올려보세요.",
  how4Title: "4️⃣ 기록 흐름 확인",
  how4P: "캘린더와 통계로 성장 흐름을 확인하세요.",
  how5Title: "5️⃣ AI 인사이트 확인",
  how5P: "나의 기록 패턴과 성장 포인트를 확인하세요.",
  how6Title: "6️⃣ 꾸준히 성장하기",
  how6P: "작은 기록을 이어가며 더 큰 변화를 만들어보세요.",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "더 깊은 분석과<br />더 스마트한 카운트 경험을 제공합니다.",
  premFeatHeading: "프리미엄 기능",
  prem1Title: "고급 통계",
  prem1Lead: "일별, 주별, 월별 기록 패턴을",
  prem1Note: "더 자세히 분석합니다.",
  prem2Title: "AI 성장 리포트",
  prem2Lead: "사용자의 카운트 기록을 기반으로",
  prem2Note: "성장 인사이트를 제공합니다.",
  prem3Title: "AI 목표 코치",
  prem3Lead: "기록 패턴을 분석해",
  prem3Note: "목표 달성 전략을 제안합니다.",
  prem4Title: "상세 분석",
  prem4Lead: "시간대, 요일별 기록 패턴과",
  prem4Note: "성공 흐름을 제공합니다.",
  prem5Title: "위젯 확장",
  prem5Lead: "홈 화면에서 더 편하게",
  prem5Note: "카운트를 기록하고 확인할 수 있습니다.",
  prem6Title: "광고 제거",
  prem6Lead: "광고 없이",
  prem6Note: "CountUp을 이용할 수 있습니다.",
  recoTitle: "이런 분들에게 추천",
  reco1: "매일 작은 행동을 기록하고 싶은 분",
  reco2: "운동, 공부, 독서, 물 마시기 등을 카운트하고 싶은 분",
  reco3: "목표 횟수와 진행률을 관리하고 싶은 분",
  reco4: "꾸준한 습관을 만들고 싶은 분",
  reco5: "성장 과정을 숫자로 확인하고 싶은 분",
  reco6: "AI 기반 기록 분석을 받고 싶은 분",
  reco7: "간단하고 예쁜 카운트 앱을 찾는 분",
  premHiKicker: "한 줄 강조 문구",
  premHiLine: "행동을 카운트하고 성장 습관을 만드는 경험",
  premHiSub: "작은 기록이 큰 변화를 만듭니다.",
  closingHtml:
    "<p><strong>CountUp</strong>과 함께<br />더 꾸준하고<br />더 의미 있는 기록을 시작하세요.</p>",
  closingAria: "마무리 문구",
  footerRights: "© CountUp ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY 소개",
  drawerBl: "BabyLog 소개",
  drawerPl: "PetLog 소개",
  drawerPu: "PiggyUp 소개",
  drawerGu: "GoalUp 소개",
  drawerCu: "CountUp · 이 화면",
  appStoreUrl: "https://newon.app",
  googlePlayUrl: "https://newon.app",
  appStoreBadgeAria: "App Store에서 CountUp(새 탭)",
  googlePlayBadgeAria: "Google Play에서 CountUp(새 탭)",
};

export const cuEn = {
  brandAria: "Back to top of CountUp",
  globalReachBadge: "173 countries · 13 languages supported",
  badge: "🔢 Count tracking · goals · AI insights",
  h1: "CountUp",
  subtitleHtml: "Small counts add up to bigger growth",
  heroReachSummary:
    "A smart count app—track daily actions, goal progress, streaks, and growth flow in one place.",
  heroLogoAlt: "CountUp app logo: yellow upward arrow",
  introLabel: "About the app",
  introTitle: "About the app",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>CountUp</strong> makes it easy to log</p><p>repeated actions and build steady growth habits.</p><p>Count workouts, water, study, reading, savings, routines—whatever matters to you.</p><p>See daily logs and long-term growth at a glance.</p><p>Small counts add up to meaningful change.</p>',
  introClosing: "Today's small log builds tomorrow's big growth.",
  showcaseCollageAria: "Six CountUp app previews. Scroll horizontally to view all.",
  imgShot1Alt: "CountUp — Small actions create big changes",
  imgShot2Alt: "CountUp — Track daily actions and count goals easily",
  imgShot3Alt: "CountUp — See growth in numbers with streaks and statistics",
  imgShot4Alt: "CountUp — Premium with AI coaching, growth reports, and advanced insights",
  imgShot5Alt: "CountUp — AI Coach delivers insights powered by your data",
  imgShot6Alt: "CountUp — Start a new habit and create a counter in 10 seconds",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Count logging",
  feat1Lead: "Count any action quickly and easily.",
  feat1Note: "Log multiple times a day and stack small wins.",
  feat2Title: "Goal settings",
  feat2Lead: "Set target counts and periods, then track progress.",
  feat2Note: "See intuitively how close you are to your goal.",
  feat3Title: "Streak tracking",
  feat3Lead: "View streaks and momentum over time.",
  feat3Note: "Stay motivated so habits don't break.",
  feat4Title: "Log reminders",
  feat4Lead: "Get reminders at the times you choose.",
  feat4Note: "Helps you practice daily without forgetting.",
  feat5Title: "Growth stats",
  feat5Lead: "Analyze daily, weekly, and monthly count flow.",
  feat5Note: "See your growth as data.",
  feat6Title: "Chart visualization",
  feat6Lead: "Graph trends and goal completion rates.",
  feat6Note: "Track growth intuitively over time.",
  feat7Title: "AI insights",
  feat7Lead: "AI analyzes your patterns",
  feat7Note: "and offers tailored growth insights.",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Create a count",
  how1P: "Add the action or goal you want to track.",
  how2Title: "2️⃣ Set your goal",
  how2P: "Choose target count, period, and alerts.",
  how3Title: "3️⃣ Count daily",
  how3P: "Tap to increment whenever you act.",
  how4Title: "4️⃣ Review your flow",
  how4P: "Use calendar and stats to see growth.",
  how5Title: "5️⃣ Check AI insights",
  how5P: "Review patterns and growth points.",
  how6Title: "6️⃣ Keep growing",
  how6P: "Small logs lead to bigger change.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "Deeper analysis and<br />a smarter count experience",
  premFeatHeading: "Premium features",
  prem1Title: "Advanced stats",
  prem1Lead: "Daily, weekly, monthly",
  prem1Note: "record patterns in detail.",
  prem2Title: "AI growth reports",
  prem2Lead: "From your count history,",
  prem2Note: "get personalized growth insights.",
  prem3Title: "AI goal coach",
  prem3Lead: "Analyzes patterns and",
  prem3Note: "suggests strategies to hit goals.",
  prem4Title: "Detailed analysis",
  prem4Lead: "Time-of-day and day-of-week",
  prem4Note: "success flow patterns.",
  prem5Title: "Widget expansion",
  prem5Lead: "Log and check counts",
  prem5Note: "more easily from your home screen.",
  prem6Title: "Remove ads",
  prem6Lead: "Use CountUp",
  prem6Note: "without interruptions.",
  recoTitle: "Great if you…",
  reco1: "Want to log small daily actions",
  reco2: "Want to count workouts, study, reading, water, etc.",
  reco3: "Want to manage target counts and progress",
  reco4: "Want to build steady habits",
  reco5: "Want to see growth as numbers",
  reco6: "Want AI-based log analysis",
  reco7: "Want a simple, beautiful count app",
  premHiKicker: "In one line",
  premHiLine: "Count actions—and build growth habits.",
  premHiSub: "Small logs make big change.",
  closingHtml:
    "<p>Start steadier, more meaningful logging<br />with <strong>CountUp</strong>.</p>",
  closingAria: "Closing message",
  footerRights: "© CountUp ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "Open SAVY intro",
  drawerBl: "Open BabyLog intro",
  drawerPl: "Open PetLog intro",
  drawerPu: "Open PiggyUp intro",
  drawerGu: "Open GoalUp intro",
  drawerCu: "CountUp · this screen",
  appStoreUrl: "https://newon.app",
  googlePlayUrl: "https://newon.app",
  appStoreBadgeAria: "CountUp on the App Store (opens in a new tab)",
  googlePlayBadgeAria: "CountUp on Google Play (opens in a new tab)",
};
