/** CountUp page copy — merged into locales/*.json by apply-countup-locales.mjs */

export const cuKo = {
  brandAria: "CountUp 상단으로",
  globalReachBadge: "From small counts · Worldwide service",
  badge: "🔢 카운트 기록 · 목표 추적 · AI 인사이트",
  h1: "CountUp",
  subtitleHtml: `<span class="ox-accent">작은 기록이 모여<br />더 큰 변화를 만듭니다</span>`,
  heroReachSummary:
    "운동, 공부, 독서, 금연처럼 반복되는 행동을 숫자로 기록하고 성장 흐름을 확인할 수 있는 카운팅 기록 앱입니다.",
  heroLogoAlt: "CountUp 앱 로고: 노란 상승 화살표",
  introLabel: "브랜드",
  introTitle: "왜 CountUp인가",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>CountUp</strong>은</p><p>반복되는 행동과 목표를 숫자로 기록하고 꾸준함을 시각적으로 확인할 수 있는 스마트 카운팅 플랫폼입니다.</p><p>운동 횟수, 독서량, 금연, 공부 시간, 습관 유지 기록까지 모든 성장 과정을 한 곳에서 관리할 수 있습니다.</p><p>AI 분석을 통해 패턴을 확인하고 더 나은 루틴을 만들어보세요.</p><p>작은 숫자가 쌓이면 더 큰 성장이 시작됩니다.</p>',
  introClosing: "오늘의 기록이 내일의 변화를 만듭니다.",
  showcaseCollageAria: "CountUp 앱 미리보기 6장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt: "CountUp — 작은 기록이 큰 변화를 만듭니다",
  imgShot2Alt: "CountUp — 매일의 작은 행동을 기록하고 목표를 쉽게 카운트",
  imgShot3Alt: "CountUp — 연속 기록과 통계로 꾸준함 확인",
  imgShot4Alt: "CountUp — AI 코치, 성장 리포트, 고급 통계 프리미엄",
  imgShot5Alt: "CountUp — AI 코치 데이터 기반 인사이트",
  imgShot6Alt: "CountUp — 10초 만에 새 카운트 만들기",  reviewsTitle: "사용자 이야기",  review1Quote: "공부 시간, 독서량, 운동 횟수까지 모두 기록하고 있어요.",  review2Emoji: "👨🏻",  review2Meta: "사진작가 · 32세",  review3Quote: "몇 달 전의 나와 지금의 나를 비교하는 재미가 생겼어요.",  review4Emoji: "👨🏽",  review4Meta: "건축사 · 41세",
  reviewsLabel: "후기",
  reviewsTitle: "사용자 이야기",
  review1Emoji: "👩🏼",
  review1Quote: "공부 시간, 독서량, 운동 횟수까지 모두 기록하고 있어요.",
  review1Meta: "의대생 · 24세",
  review2Emoji: "👨🏻",
  review2Quote: "기억은 사라지지만 기록은 남더라고요.",
  review2Meta: "사진작가 · 32세",
  review3Emoji: "👩🏻",
  review3Quote: "몇 달 전의 나와 지금의 나를 비교하는 재미가 생겼어요.",
  review3Meta: "콘텐츠 크리에이터 · 26세",
  review4Emoji: "👨🏽",
  review4Quote: "작은 숫자가 쌓여서 큰 변화를 만든다는 걸 느끼게 됩니다.",
  review4Meta: "건축사 · 41세",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "카운트 기록",
  feat1Lead: "오늘의 행동을 기록하고 횟수와 누적 데이터를 간편하게 관리할 수 있습니다.",
  feat1Note: "운동, 독서, 공부, 물 마시기 등 다양한 활동을 카운트할 수 있습니다.",
  feat2Title: "목표 설정",
  feat2Lead: "목표 횟수와 기간을 설정하고 진행 상황을 실시간으로 확인하세요.",
  feat2Note: "작은 목표가 큰 성과로 이어집니다.",
  feat3Title: "연속 기록",
  feat3Lead: "연속 달성 기록을 확인하고 꾸준한 실천을 습관으로 만들어보세요.",
  feat3Note: "성취감을 높여주는 성장 시스템을 제공합니다.",
  feat4Title: "마일스톤",
  feat4Lead: "100회, 500회, 1000회 달성 기록을 저장하고",
  feat4Note: "성장의 순간을 기념해보세요.",
  feat5Title: "통계 분석",
  feat5Lead: "일간, 주간, 월간, 연간 기록을 분석합니다.",
  feat5Note: "데이터를 통해 성장 과정을 시각적으로 확인하세요.",
  feat6Title: "그래프 시각화",
  feat6Lead: "누적 기록과 성장 추이를 그래프로 확인할 수 있습니다.",
  feat6Note: "변화를 직관적으로 파악할 수 있습니다.",
  feat7Title: "AI 인사이트",
  feat7Lead: "AI가 기록 패턴을 분석하고 개선 방향과 추천 목표를 제공합니다.",
  feat7Note: "더 효율적인 습관 형성을 도와줍니다.",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 카운터 생성",
  how1P: "기록하고 싶은 활동을 추가하세요.",
  how2Title: "2️⃣ 목표 설정",
  how2P: "횟수와 기간을 설정하세요.",
  how3Title: "3️⃣ 꾸준히 기록하기",
  how3P: "매일 행동을 카운트하세요.",
  how4Title: "4️⃣ 통계 확인",
  how4P: "성장 그래프를 확인하세요.",
  how5Title: "5️⃣ AI 분석 보기",
  how5P: "패턴과 인사이트를 확인하세요.",
  how6Title: "6️⃣ 목표 달성하기",
  how6P: "작은 기록을 쌓아 성장해보세요.",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "카운터·AI·위젯으로<br />더 깊은 성장 기록",
  premFeatHeading: "프리미엄 기능",
  prem1Title: "무제한 카운터",
  prem1Lead: "5개 제한 없이 모든 행동을",
  prem1Note: "카운트할 수 있습니다.",
  prem2Title: "고급 통계",
  prem2Lead: "연간·전체 기간과 시간대·요일",
  prem2Note: "분석으로 흐름을 파악합니다.",
  prem3Title: "AI 코치",
  prem3Lead: "성장 분석·패턴·동기 코칭으로",
  prem3Note: "꾸준함을 이어갑니다.",
  prem4Title: "AI 성장 리포트",
  prem4Lead: "주간·월간 자동 리포트로",
  prem4Note: "변화를 돌아봅니다.",
  prem5Title: "AI 인사이트",
  prem5Lead: "1개 미리보기가 아닌",
  prem5Note: "전체 인사이트를 확인합니다.",
  prem6Title: "홈 위젯",
  prem6Lead: "잠금 오버레이 없이 카운터·",
  prem6Note: "요약 위젯을 사용합니다.",
  prem7Title: "Streak·캘린더",
  prem7Lead: "무제한 로그와 연속 기록을",
  prem7Note: "캘린더에서 확인합니다.",
  prem8Title: "광고 제거",
  prem8Lead: "배너·전면 광고 없이",
  prem8Note: "기록에 집중할 수 있습니다.",
  recoTitle: "이런 분들에게 추천",
  reco1: "운동 기록을 꾸준히 남기고 싶은 분",
  reco2: "금연·금주 기록을 관리하고 싶은 분",
  reco3: "독서와 공부량을 기록하고 싶은 분",
  reco4: "습관 형성을 데이터로 확인하고 싶은 분",
  reco5: "작은 성취를 시각적으로 보고 싶은 분",
  reco6: "AI 분석으로 성장 패턴을 알고 싶은 분",
  reco7: "연속 기록을 유지하며 동기부여 받고 싶은 분",
  premHiKicker: "작은 기록부터",
  premHiLine: "꾸준함이 성장을 완성합니다.",
  premHiSub: "CountUp이 당신의<br />실천을 더 눈에 보이게 만듭니다.",
  closingHtml:
    `<p>기록된 순간이<br /><span class="ox-accent">성장의 흔적이 됩니다</span></p><p>CountUp은 숫자를 세는 앱이 아니라<br />나의 변화와 성취를 기록하는 공간입니다.</p><p>하루의 작은 기록들이 모여<br /><span class="ox-accent">나만의 성장 이야기가 완성됩니다.</span></p>`,
  closingAria: "마무리 문구",
  footerRights: "© CountUp ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY 소개",
  drawerBl: "BabyLog 소개",
  drawerPl: "PetLog 소개",
  drawerPu: "PiggyUp 소개",
  drawerGu: "GoalUp 소개",
  drawerCu: "CountUp · 이 화면",
  appStoreUrl: "https://apps.apple.com/kr/app/countup-%EC%B9%B4%EC%9A%B4%ED%8A%B8-%EB%AA%A9%ED%91%9C-%EA%B4%80%EB%A6%AC/id6786910628",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.countup&pcampaignid=web_share",
  appStoreBadgeAria: "App Store에서 CountUp(새 탭)",
  googlePlayBadgeAria: "Google Play에서 CountUp(새 탭)",
};

export const cuEn = {
  brandAria: "Back to top of CountUp",
  globalReachBadge: "173 countries · 13 languages supported",
  badge: "🔢 Count tracking · Goal progress · AI insights",
  h1: "CountUp",
  subtitleHtml: `<span class="ox-accent">Small logs add up to<br />bigger change</span>`,
  heroReachSummary:
    "From daily actions to life goals—count, log, and see your growth.",
  heroLogoAlt: "CountUp app logo: yellow upward arrow",
  introLabel: "Brand",
  introTitle: "Why CountUp",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>CountUp</strong> is</p><p>a smart counting platform to log repeated actions and goals as numbers—and see consistency visually.</p><p>Track workouts, reading, quitting smoking, study time, habit streaks, and every step of growth in one place.</p><p>Use AI analysis to spot patterns and build better routines.</p><p>Small numbers stack into bigger growth.</p>',
  introClosing: "Today's log builds tomorrow's change.",
  showcaseCollageAria: "Six CountUp app previews. Scroll horizontally to view all.",
  imgShot1Alt: "CountUp — Small actions create big changes",
  imgShot2Alt: "CountUp — Track daily actions and count goals easily",
  imgShot3Alt: "CountUp — See growth in numbers with streaks and statistics",
  imgShot4Alt: "CountUp — Premium with AI coaching, growth reports, and advanced insights",
  imgShot5Alt: "CountUp — AI Coach delivers insights powered by your data",
  imgShot6Alt: "CountUp — Start a new habit and create a counter in 10 seconds",  reviewsTitle: "User stories",  review1Quote: "Study hours, books read, workouts—I track it all.",  review2Emoji: "👨🏻",  review2Meta: "Photographer · 32",  review3Quote: "It's fun comparing me from months ago to me today.",  review4Emoji: "👨🏽",  review4Meta: "Architect · 41",
  reviewsLabel: "Reviews",
  reviewsTitle: "User stories",
  review1Emoji: "👩🏼",
  review1Quote: "Study hours, books read, workouts—I track it all.",
  review1Meta: "Med student · 24",
  review2Emoji: "👨🏻",
  review2Quote: "Memory fades, but the log stays.",
  review2Meta: "Photographer · 32",
  review3Emoji: "👩🏻",
  review3Quote: "It's fun comparing me from months ago to me today.",
  review3Meta: "Content creator · 26",
  review4Emoji: "👨🏽",
  review4Quote: "Small numbers add up—and you feel the bigger shift.",
  review4Meta: "Architect · 41",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Count logging",
  feat1Lead: "Log today's actions and manage counts and cumulative data easily.",
  feat1Note: "Track workouts, reading, study, water intake, and more.",
  feat2Title: "Goal settings",
  feat2Lead: "Set target counts and periods, then check progress in real time.",
  feat2Note: "Small goals lead to big results.",
  feat3Title: "Streak tracking",
  feat3Lead: "See streak records and turn steady practice into habits.",
  feat3Note: "A growth system that boosts your sense of achievement.",
  feat4Title: "Milestones",
  feat4Lead: "Save achievements at 100, 500, and 1,000 counts—",
  feat4Note: "and celebrate moments of growth.",
  feat5Title: "Statistics",
  feat5Lead: "Analyze daily, weekly, monthly, and yearly logs.",
  feat5Note: "See your growth journey visually through data.",
  feat6Title: "Chart visualization",
  feat6Lead: "View cumulative logs and growth trends as graphs.",
  feat6Note: "Understand change at a glance.",
  feat7Title: "AI insights",
  feat7Lead: "AI analyzes your patterns and suggests improvements and goals.",
  feat7Note: "Helps you build more effective habits.",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Create a counter",
  how1P: "Add the activity you want to track.",
  how2Title: "2️⃣ Set your goal",
  how2P: "Choose target count and period.",
  how3Title: "3️⃣ Log consistently",
  how3P: "Count your actions every day.",
  how4Title: "4️⃣ Check statistics",
  how4P: "Review your growth charts.",
  how5Title: "5️⃣ View AI analysis",
  how5P: "See patterns and insights.",
  how6Title: "6️⃣ Reach your goals",
  how6P: "Stack small logs and grow.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "Count · analysis · AI<br />for smarter growth",
  premFeatHeading: "Premium features",
  prem1Title: "Unlimited counters",
  prem1Lead: "Create as many",
  prem1Note: "counters as you need.",
  prem2Title: "Advanced statistics",
  prem2Lead: "Detailed analysis by weekday,",
  prem2Note: "time, and period.",
  prem3Title: "AI growth analysis",
  prem3Lead: "Record patterns and",
  prem3Note: "growth insights.",
  prem4Title: "Milestone records",
  prem4Lead: "Achievement history",
  prem4Note: "saved automatically.",
  prem5Title: "PDF reports",
  prem5Lead: "Save count data",
  prem5Note: "as reports.",
  prem6Title: "Home widgets",
  prem6Lead: "Today's logs and",
  prem6Note: "streaks on your home screen.",
  prem7Title: "Cloud backup",
  prem7Lead: "Keep your records",
  prem7Note: "stored safely.",
  prem8Title: "Remove ads",
  prem8Lead: "No ads—",
  prem8Note: "focus on logging.",
  recoTitle: "Great if you…",
  reco1: "Want to log workouts consistently",
  reco2: "Want to track quitting smoking or drinking",
  reco3: "Want to record reading and study volume",
  reco4: "Want to see habit building as data",
  reco5: "Want to visualize small wins",
  reco6: "Want AI analysis of your growth patterns",
  reco7: "Want streak motivation to stay on track",
  premHiKicker: "From small logs",
  premHiLine: "Consistency completes growth.",
  premHiSub: "CountUp makes your<br />daily practice visible.",
  closingHtml:
    `<p>Recorded moments<br /><span class="ox-accent">Traces of growth</span></p><p>CountUp isn't just counting—<br />it's a space to record change and achievement.</p><p>Small daily logs come together<br /><span class="ox-accent">into your growth story.</span></p>`,
  closingAria: "Closing message",
  footerRights: "© CountUp ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "Open SAVY intro",
  drawerBl: "Open BabyLog intro",
  drawerPl: "Open PetLog intro",
  drawerPu: "Open PiggyUp intro",
  drawerGu: "Open GoalUp intro",
  drawerCu: "CountUp · this screen",
  appStoreUrl: "https://apps.apple.com/kr/app/countup-%EC%B9%B4%EC%9A%B4%ED%8A%B8-%EB%AA%A9%ED%91%9C-%EA%B4%80%EB%A6%AC/id6786910628",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.countup&pcampaignid=web_share",
  appStoreBadgeAria: "CountUp on the App Store (opens in a new tab)",
  googlePlayBadgeAria: "CountUp on Google Play (opens in a new tab)",
};
