/** EatOn page copy — merged into locales/*.json by apply-eaton-locales.mjs */

export const eoKo = {
  brandAria: "EatOn 상단으로",
  globalReachBadge: "요리 · 외식 · 배달 · AI 레시피 · 재료 쇼핑",
  badge: "🍴 요리 · 외식 · 배달 · AI 레시피",
  h1: "EatOn",
  subtitleHtml: `<span class="ox-accent">오늘 뭐 먹지?<br />요리부터 외식, 배달까지 한곳에서.</span>`,
  heroValueLine: "오늘 뭐 먹지? 이제 EatOn에서 한 번에.",
  heroReachSummary:
    "맛있는 인기 요리 레시피부터 유명 맛집, 인기 배달 음식, 재료 쇼핑까지. YouTube, Instagram, Blog와 다양한 맛집 정보를 한곳에서 탐색하고, AI로 더 빠르고 간편하게 음식 정보를 확인할 수 있는 통합 푸드 플랫폼입니다.",
  heroLogoAlt: "EatOn 앱 로고",
  introLabel: "브랜드",
  introTitle: "왜 EatOn인가",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>EatOn</strong>은</p><p>단순한 레시피 앱이나 맛집 앱이 아닙니다.</p><p>먹고 싶은 음식이 생겼을 때<br />직접 만들어 먹을지,<br />맛집에 가서 먹을지,<br />배달시켜 먹을지<br />각각 다른 서비스를 찾아다닐 필요가 없습니다.</p><p>EatOn 하나에서 인기 레시피, 유명 맛집, 배달 음식, 필요한 재료까지<br />한 번에 탐색할 수 있습니다.</p><p>YouTube, Instagram, Blog에 흩어진 레시피를 한곳에서 비교하고,<br />원하는 레시피 링크를 입력하면 AI가 핵심 내용을 간단하게 정리합니다.</p><p>외식과 배달에서는<br />TV 방송, YouTube, SNS, 블루리본 등 다양한 출처에서 주목받은 곳을<br />한눈에 확인할 수 있습니다.</p>',
  introClosing: "오늘 무엇을 먹을지 고민하는 순간부터 실제 식사까지, EatOn이 하나로 연결합니다.",
  showcaseCollageAria: "EatOn 앱 스크린샷 자리 4장입니다. 가로로 스크롤하여 모두 볼 수 있습니다. 현재 준비중입니다.",
  showcaseSoonLabel: "준비중",
  imgShot1Alt: "EatOn — 요리 홈 (준비중)",
  imgShot2Alt: "EatOn — 레시피 통합 탐색 (준비중)",
  imgShot3Alt: "EatOn — AI 레시피 (준비중)",
  imgShot4Alt: "EatOn — 외식·배달 (준비중)",
  shot1Cap: "요리 홈",
  shot2Cap: "레시피 탐색",
  shot3Cap: "AI 레시피",
  shot4Cap: "외식 · 배달",
  reviewsLabel: "이야기",
  reviewsTitle: "이런 경험을 위해",
  review1Emoji: "👩🏼",
  review1Quote: "레시피 찾을 때 유튜브랑 블로그를 계속 왔다 갔다 했는데 한곳에서 보니까 편할 것 같아요.",
  review1Meta: "직장인 · 27세",
  review2Emoji: "👨🏻",
  review2Quote: "영상 링크만 넣어도 요리 과정을 짧게 정리해 주면 빠르게 볼 수 있을 것 같아요.",
  review2Meta: "대학생 · 23세",
  review3Emoji: "👩🏻",
  review3Quote: "방송 맛집이랑 SNS에서 주목받은 곳을 같이 보면 어디 갈지 고르기 쉬울 것 같아요.",
  review3Meta: "회사원 · 31세",
  review4Emoji: "👨🏽",
  review4Quote: "먹고 싶은 음식 하나 검색하고 요리할지 배달할지 바로 비교할 수 있으면 좋겠어요.",
  review4Meta: "자취생 · 25세",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "인기 요리 레시피",
  feat1Lead: "맛있는 인기 요리를 탐색하고 원하는 메뉴의 다양한 레시피를 확인합니다.",
  feat1Note: "오늘 먹고 싶은 요리를 빠르게 찾아보세요.",
  feat2Title: "레시피 통합 탐색",
  feat2Lead: "YouTube, Instagram, Blog의 다양한 요리 콘텐츠를 한곳에서 비교합니다.",
  feat2Note: "한 가지 요리도 여러 방식으로 만나보세요.",
  feat3Title: "AI 레시피 요약",
  feat3Lead: "레시피 링크를 입력하면 AI가 핵심 정보를 빠르게 정리합니다.",
  feat3Note: "요리 이름 · 재료 · 조리 시간 · 순서 · 난이도 · 조리 팁",
  feat4Title: "재료 쇼핑",
  feat4Lead: "레시피에 필요한 재료를 확인하고 여러 쇼핑 채널의 상품을 탐색할 수 있습니다.",
  feat4Note: "필요한 재료를 더 합리적인 가격으로 탐색해 보세요.",
  feat5Title: "외식 맛집",
  feat5Lead: "TV 방송, YouTube, SNS, 블루리본 등 다양한 출처에서 주목받은 맛집 정보를 한눈에 확인합니다.",
  feat5Note: "출처 예: TV 방송 · YouTube · SNS 인기 · Blue Ribbon",
  feat6Title: "배달 탐색",
  feat6Lead: "지역과 음식 카테고리를 기반으로 인기 있는 배달 음식과 매장을 탐색합니다.",
  feat6Note: "오늘 사람들이 많이 찾는 메뉴를 빠르게 확인하세요.",
  feat7Title: "음식 통합 검색",
  feat7Lead: "먹고 싶은 음식 하나를 검색하면 관련된 요리, 레시피, 외식, 배달, 재료 쇼핑 정보를 연결해 보여줍니다.",
  feat7Note: "예: 김치찌개 → 레시피 · YouTube · Instagram · Blog · 재료 · 쇼핑 · 맛집 · 배달",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 음식 검색",
  how1P: "먹고 싶은 음식이나 메뉴를 검색하세요.",
  how2Title: "2️⃣ 방식 선택",
  how2P: "요리 / 외식 / 배달 중 원하는 방식을 선택하세요.",
  how3Title: "3️⃣ 레시피 탐색",
  how3P: "YouTube, Instagram, Blog에서 다양한 레시피를 비교하세요.",
  how4Title: "4️⃣ AI 요약",
  how4P: "원하는 레시피 링크를 입력하고 핵심 내용을 빠르게 확인하세요.",
  how5Title: "5️⃣ 재료 또는 맛집 확인",
  how5P: "요리에 필요한 재료를 찾아보거나 외식·배달 정보를 탐색하세요.",
  how6Title: "6️⃣ 원하는 방식으로 연결",
  how6P: "레시피 원문, 쇼핑, 맛집, 배달 관련 정보로 이동해 자세히 확인하세요.",
  premiumLabel: "요금",
  premiumTitle: "✨ 프리미엄",
  premiumTagline: "요금제와 상세 혜택은<br />출시 전 확정 예정입니다",
  premFeatHeading: "준비 중인 방향",
  prem1Title: "AI 레시피 분석 확대",
  prem1Lead: "더 많은 레시피 링크 요약과",
  prem1Note: "분석 범위를 준비 중입니다.",
  prem2Title: "AI 맞춤 음식 추천",
  prem2Lead: "취향·상황에 맞춘 추천을",
  prem2Note: "강화하는 방향을 준비 중입니다.",
  prem3Title: "레시피 저장 확대",
  prem3Lead: "저장·즐겨찾기 용량을",
  prem3Note: "넓히는 방향을 준비 중입니다.",
  prem4Title: "광고 제거",
  prem4Lead: "광고 없이 더 집중해서",
  prem4Note: "탐색할 수 있는 방향을 준비 중입니다.",
  prem5Title: "개인 맞춤 추천 강화",
  prem5Lead: "관심 음식·패턴 기반 추천을",
  prem5Note: "더 정교하게 만드는 방향을 준비 중입니다.",
  prem6Title: "음식 취향 분석",
  prem6Lead: "나의 식사 취향 패턴을",
  prem6Note: "이해하는 방향을 준비 중입니다.",
  prem7Title: "컬렉션 고급 기능",
  prem7Lead: "즐겨찾기·컬렉션을",
  prem7Note: "더 편리하게 모으는 방향을 준비 중입니다.",
  prem8Title: "출시 후 안내",
  prem8Lead: "확정된 요금·혜택은",
  prem8Note: "출시 시점에 공개합니다.",
  recoTitle: "이런 분들에게 추천",
  reco1: "매일 오늘 뭐 먹을지 고민하는 분",
  reco2: "맛있는 인기 요리를 직접 만들어보고 싶은 분",
  reco3: "YouTube, Instagram, Blog 레시피를 한곳에서 보고 싶은 분",
  reco4: "긴 레시피 영상을 AI로 빠르게 정리해서 보고 싶은 분",
  reco5: "유명 방송 맛집과 SNS에서 주목받은 맛집을 찾는 분",
  reco6: "외식과 배달 중 무엇을 먹을지 비교하고 싶은 분",
  reco7: "요리 후 필요한 재료까지 편하게 찾고 싶은 분",
  reco8: "음식과 관련된 여러 앱을 따로 사용하기 번거로운 분",
  premHiKicker: "작은 고민부터",
  premHiLine: "오늘 뭐 먹지? 이제 EatOn에서 한 번에.",
  premHiSub: "요리부터 외식, 배달까지.<br />먹고 싶은 모든 순간을 EatOn이 연결합니다.",
  closingHtml:
    `<p>오늘 뭐 먹지?<br /><span class="ox-accent">이제 EatOn에서 한 번에.</span></p><p>요리부터 외식, 배달까지.<br />먹고 싶은 모든 순간을 EatOn이 연결합니다.</p><p>YouTube · Instagram · Blog 레시피부터<br /><span class="ox-accent">맛집·배달·재료 쇼핑까지 한곳에서.</span></p>`,
  closingAria: "마무리 문구",
  footerRights: "© EatOn ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY 소개",
  drawerBl: "BabyLog 소개",
  drawerPl: "PetLog 소개",
  drawerPu: "PiggyUp 소개",
  drawerGu: "GoalUp 소개",
  drawerCu: "CountUp 소개",
  drawerNp: "Newon 소개",
  drawerMw: "My World 소개",
  drawerEo: "EatOn · 이 화면",
  comingSoonLabel: "출시 예정",
  appStoreUrl: "#eo-top",
  googlePlayUrl: "#eo-top",
  appStoreBadgeAria: "App Store — 출시 예정",
  googlePlayBadgeAria: "Google Play — 출시 예정",
  deleteAccountLink: "계정 삭제",
};

export const eoEn = {
  brandAria: "Back to top of EatOn",
  globalReachBadge: "Cooking · Dining · Delivery · AI recipes · Ingredient shopping",
  badge: "🍴 Cooking · Dining out · Delivery · AI recipes",
  h1: "EatOn",
  subtitleHtml: `<span class="ox-accent">What to eat today?<br />Cooking, dining out, and delivery in one place.</span>`,
  heroValueLine: "What to eat today? Find it all in EatOn.",
  heroReachSummary:
    "From popular recipes to notable restaurants, delivery picks, and ingredient shopping. Explore YouTube, Instagram, blogs, and restaurant mentions in one place—and use AI to review food info faster.",
  heroLogoAlt: "EatOn app logo",
  introLabel: "Brand",
  introTitle: "Why EatOn",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>EatOn</strong> is</p><p>not just another recipe or restaurant app.</p><p>When you know what you want to eat,<br />you shouldn’t have to hop between apps<br />to cook it, dine out, or order delivery.</p><p>In EatOn you can explore popular recipes, notable places, delivery options, and ingredients together.</p><p>Compare recipes scattered across YouTube, Instagram, and blogs—then paste a link so AI can summarize the essentials.</p><p>For dining and delivery, browse places mentioned across broadcasts, YouTube, SNS, and Blue Ribbon–style sources in one view.</p>',
  introClosing: "From “what should I eat?” to the meal itself, EatOn connects it in one place.",
  showcaseCollageAria: "Four EatOn screenshot placeholders. Scroll horizontally to view all. Screenshots coming soon.",
  showcaseSoonLabel: "Coming soon",
  imgShot1Alt: "EatOn — Cooking home (coming soon)",
  imgShot2Alt: "EatOn — Unified recipe browse (coming soon)",
  imgShot3Alt: "EatOn — AI recipes (coming soon)",
  imgShot4Alt: "EatOn — Dining & delivery (coming soon)",
  shot1Cap: "Cooking home",
  shot2Cap: "Recipe browse",
  shot3Cap: "AI recipes",
  shot4Cap: "Dining · Delivery",
  reviewsLabel: "Stories",
  reviewsTitle: "Built for moments like these",
  review1Emoji: "👩🏼",
  review1Quote: "I bounce between YouTube and blogs for recipes—having them in one place would help.",
  review1Meta: "Office worker · 27",
  review2Emoji: "👨🏻",
  review2Quote: "If pasting a video link summarized the cooking steps, I could skim it faster.",
  review2Meta: "Student · 23",
  review3Emoji: "👩🏻",
  review3Quote: "Seeing broadcast mentions alongside SNS buzz would make choosing a place easier.",
  review3Meta: "Office worker · 31",
  review4Emoji: "👨🏽",
  review4Quote: "I’d love to search one dish and compare cooking vs delivery right away.",
  review4Meta: "Living alone · 25",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Popular recipes",
  feat1Lead: "Browse popular dishes and explore multiple recipes for the menu you want.",
  feat1Note: "Find what you want to cook today, faster.",
  feat2Title: "Unified recipe browse",
  feat2Lead: "Compare cooking content from YouTube, Instagram, and blogs in one place.",
  feat2Note: "See one dish prepared many ways.",
  feat3Title: "AI recipe summary",
  feat3Lead: "Paste a recipe link and AI summarizes the essentials.",
  feat3Note: "Name · ingredients · time · steps · difficulty · tips",
  feat4Title: "Ingredient shopping",
  feat4Lead: "Review ingredients for a recipe and browse products across linked shopping channels.",
  feat4Note: "Explore reasonably priced options—no lowest-price guarantee.",
  feat5Title: "Dining out",
  feat5Lead: "Explore restaurants mentioned across TV, YouTube, SNS, and Blue Ribbon–style sources.",
  feat5Note: "Source examples: TV · YouTube · SNS · Blue Ribbon",
  feat6Title: "Delivery discovery",
  feat6Lead: "Explore popular delivery menus and places by area and category.",
  feat6Note: "Quickly check menus people are looking for today.",
  feat7Title: "Unified food search",
  feat7Lead: "Search one dish and connect related cooking, recipes, dining, delivery, and shopping.",
  feat7Note: "e.g. kimchi jjigae → recipes · YouTube · Instagram · blogs · ingredients · shopping · places · delivery",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Search food",
  how1P: "Search the dish or menu you want.",
  how2Title: "2️⃣ Pick a path",
  how2P: "Choose cooking, dining out, or delivery.",
  how3Title: "3️⃣ Explore recipes",
  how3P: "Compare recipes across YouTube, Instagram, and blogs.",
  how4Title: "4️⃣ AI summary",
  how4P: "Paste a recipe link and review the essentials quickly.",
  how5Title: "5️⃣ Ingredients or places",
  how5P: "Find ingredients to cook—or explore dining and delivery options.",
  how6Title: "6️⃣ Connect outward",
  how6P: "Open the original recipe, shopping, place, or delivery details.",
  premiumLabel: "Pricing",
  premiumTitle: "✨ Premium",
  premiumTagline: "Plans and benefits will be<br />confirmed before launch",
  premFeatHeading: "Directions in progress",
  prem1Title: "Expanded AI recipe analysis",
  prem1Lead: "Broader link summaries and",
  prem1Note: "analysis — in preparation.",
  prem2Title: "Personalized AI food recommendations",
  prem2Lead: "Stronger suggestions by taste and context",
  prem2Note: "— in preparation.",
  prem3Title: "Expanded recipe saves",
  prem3Lead: "More room for saves and favorites",
  prem3Note: "— in preparation.",
  prem4Title: "Ad-free",
  prem4Lead: "A cleaner browsing experience",
  prem4Note: "— in preparation.",
  prem5Title: "Stronger personalization",
  prem5Lead: "Recommendations based on interests and patterns",
  prem5Note: "— in preparation.",
  prem6Title: "Taste insights",
  prem6Lead: "Understanding your meal preference patterns",
  prem6Note: "— in preparation.",
  prem7Title: "Advanced collections",
  prem7Lead: "Richer favorites and collections",
  prem7Note: "— in preparation.",
  prem8Title: "Details at launch",
  prem8Lead: "Confirmed pricing and benefits",
  prem8Note: "will be shared at launch.",
  recoTitle: "Recommended if you…",
  reco1: "Wonder what to eat every day",
  reco2: "Want to cook popular dishes yourself",
  reco3: "Want YouTube, Instagram, and blog recipes in one place",
  reco4: "Want long recipe videos summarized with AI",
  reco5: "Look for broadcast mentions and SNS buzz around restaurants",
  reco6: "Want to compare dining out vs delivery",
  reco7: "Want ingredients after choosing a recipe",
  reco8: "Are tired of juggling multiple food apps",
  premHiKicker: "From a small question",
  premHiLine: "What to eat today? Find it all in EatOn.",
  premHiSub: "From cooking to dining out and delivery.<br />EatOn connects every craving.",
  closingHtml:
    `<p>What to eat today?<br /><span class="ox-accent">Find it all in EatOn.</span></p><p>From cooking to dining out and delivery.<br />EatOn connects every craving.</p><p>From YouTube · Instagram · blog recipes<br /><span class="ox-accent">to places, delivery, and shopping—in one place.</span></p>`,
  closingAria: "Closing message",
  footerRights: "© EatOn ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "Open SAVY intro",
  drawerBl: "Open BabyLog intro",
  drawerPl: "Open PetLog intro",
  drawerPu: "Open PiggyUp intro",
  drawerGu: "Open GoalUp intro",
  drawerCu: "Open CountUp intro",
  drawerNp: "Open Newon intro",
  drawerMw: "Open My World intro",
  drawerEo: "EatOn · this screen",
  comingSoonLabel: "Coming soon",
  appStoreUrl: "#eo-top",
  googlePlayUrl: "#eo-top",
  appStoreBadgeAria: "App Store — Coming soon",
  googlePlayBadgeAria: "Google Play — Coming soon",
  deleteAccountLink: "Delete account",
};
