/** FitOn page copy — merged into locales/*.json by apply-fiton-locales.mjs */

export const foKo = {
  brandAria: "FitOn 상단으로",
  globalReachBadge: "운동 · 스포츠 · AI 분석 · 커뮤니티 · 챌린지 · 쇼핑",
  badge: "🏃 운동 · 스포츠 · AI 분석 · 커뮤니티",
  h1: "FitOn",
  subtitleHtml: `<span class="ox-accent">하고 싶은 모든 운동을<br />한곳에서.</span>`,
  heroValueLine: "하고 싶은 모든 운동을 FitOn 하나에서.",
  heroReachSummary:
    "러닝, 헬스, 홈트, 축구, 농구, 테니스, 수영, 골프, 사이클링, 요가 등 다양한 운동과 스포츠를 탐색하고 기록하며, AI 운동 분석, 커뮤니티, 챌린지, 스포츠 쇼핑까지 하나의 앱에서 연결하는 통합 스포츠·피트니스 플랫폼입니다.",
  heroLogoAlt: "FitOn 앱 로고",
  introLabel: "브랜드",
  introTitle: "왜 FitOn인가",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>FitOn</strong>은</p><p>특정 운동 하나만을 위한 앱이 아닙니다.</p><p>러닝은 러닝 앱,<br />헬스는 헬스 앱,<br />홈트는 홈트 앱,<br />축구·농구·테니스 같은 스포츠는 또 다른 앱,<br />운동 커뮤니티와 운동복 쇼핑은 다시 다른 서비스를 사용해야 합니다.</p><p>FitOn은 이렇게 흩어진 운동 경험을 하나로 연결합니다.</p><p>러닝, 헬스, 홈트, 축구, 농구, 테니스, 수영, 골프, 사이클링, 등산, 요가 등 다양한 운동을 한곳에서 탐색하고 기록할 수 있습니다.</p><p>운동 기록이 쌓이면 AI가 운동 빈도, 운동 시간, 목표 달성률, 운동 패턴 등을 분석해 사용자가 자신의 운동 흐름을 쉽게 이해할 수 있도록 도와줍니다.</p><p>운동 후에는 커뮤니티에서 기록과 경험을 공유하고,<br />다른 사용자의 운동 루틴, 기록, 스포츠 이야기와 팁을 확인할 수 있습니다.</p><p>또한 운동복, 운동화, 스포츠 장비 등 인기 운동 상품을 탐색하고 여러 쇼핑 채널의 가격 정보를 비교할 수 있는 구조로 확장합니다.</p>',
  introClosing: "운동을 찾는 순간부터 기록, 분석, 소통, 쇼핑까지 FitOn 하나로.",
  showcaseCollageAria: "FitOn 앱 스크린샷 자리 5장입니다. 가로로 스크롤하여 모두 볼 수 있습니다. 현재 준비중입니다.",
  showcaseSoonLabel: "준비중",
  imgShot1Alt: "FitOn — 운동 홈 (준비중)",
  imgShot2Alt: "FitOn — 내 운동 (준비중)",
  imgShot3Alt: "FitOn — AI 운동 분석 (준비중)",
  imgShot4Alt: "FitOn — 커뮤니티 (준비중)",
  imgShot5Alt: "FitOn — 쇼핑 (준비중)",
  shot1Cap: "운동 홈",
  shot2Cap: "내 운동",
  shot3Cap: "AI 분석",
  shot4Cap: "커뮤니티",
  shot5Cap: "쇼핑",
  reviewsLabel: "이야기",
  reviewsTitle: "이런 경험을 위해",
  review1Emoji: "👩🏼",
  review1Quote: "러닝이랑 헬스를 따로 기록하지 않아도 되면 편할 것 같아요.",
  review1Meta: "직장인 · 27세",
  review2Emoji: "👨🏻",
  review2Quote: "운동한 기록을 AI가 한 번에 정리해 주면 흐름을 보기 좋을 것 같아요.",
  review2Meta: "대학생 · 24세",
  review3Emoji: "👩🏻",
  review3Quote: "운동 인증이나 루틴을 다른 사람들과 공유할 수 있으면 더 꾸준히 하게 될 것 같아요.",
  review3Meta: "회사원 · 31세",
  review4Emoji: "👨🏽",
  review4Quote: "한 가지 운동만 하는 게 아니라 여러 스포츠를 관리할 수 있으면 좋겠어요.",
  review4Meta: "운동 취미 · 29세",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "모든 운동 탐색",
  feat1Lead: "러닝, 헬스, 홈트, 축구, 농구, 테니스, 배드민턴, 수영, 골프, 사이클링, 등산, 요가 등 다양한 운동과 스포츠를 탐색합니다.",
  feat1Note: "오늘 하고 싶은 운동을 빠르게 찾아보세요.",
  feat2Title: "운동 기록",
  feat2Lead: "운동 종류, 시간, 거리, 횟수, 운동량과 개인 기록을 관리합니다.",
  feat2Note: "여러 운동 기록을 하나의 흐름으로 확인하세요.",
  feat3Title: "AI 운동 분석",
  feat3Lead: "사용자의 운동 기록과 목표를 기반으로 운동 패턴과 성과를 분석합니다.",
  feat3Note: "빈도 · 운동량 · 목표 달성률 · 종목 비율 · 지속성 · 기록 변화 · 일반적인 가이드 (의료 진단 아님)",
  feat4Title: "운동 커뮤니티",
  feat4Lead: "운동 인증, 루틴, 기록, 스포츠 이야기, 운동 팁을 다른 사용자들과 공유합니다.",
  feat4Note: "러닝 · 헬스 · 홈트 · 축구 · 농구 · 테니스 · 수영 · 골프 · 등산 · 자유 이야기",
  feat5Title: "챌린지",
  feat5Lead: "러닝 거리, 운동 횟수, 연속 운동, 특정 스포츠 등 다양한 운동 챌린지에 참여합니다.",
  feat5Note: "예: 주 3회 운동 · 한 달 50km 러닝 · 30일 홈트 · 주말 등산",
  feat6Title: "목표 관리",
  feat6Lead: "개인 운동 목표를 설정하고 진행 상황과 달성률을 확인합니다.",
  feat6Note: "작은 목표부터 꾸준한 운동 습관을 만들어보세요.",
  feat7Title: "운동 습관 / 연속 기록",
  feat7Lead: "운동한 날을 기록하고 연속 운동 일수와 운동 습관을 확인합니다.",
  feat7Note: "꾸준한 흐름을 한눈에 살펴보세요.",
  feat8Title: "스포츠 쇼핑",
  feat8Lead: "인기 운동복, 운동화, 스포츠 장비와 운동 용품을 탐색합니다.",
  feat8Note: "여러 쇼핑 채널의 상품과 가격 정보를 비교해 합리적인 상품을 찾아보세요.",
  feat9Title: "운동 통계",
  feat9Lead:
    "이번 주 운동 시간, 이번 달 운동 횟수, 총 거리, 가장 많이 한 운동, 종목별 비율, 목표 달성률, 연속 운동 일수 등 나의 운동 통계를 한눈에 확인합니다.",
  feat9Note: "의료·부상 진단 수치가 아니며, 활동 기록 기반 참고용입니다. 실제 지원 항목은 출시 범위에 따라 달라질 수 있습니다.",
  feat10Title: "개인 운동 캘린더",
  feat10Lead:
    "운동한 날과 예정된 운동을 캘린더에서 한눈에 확인합니다. 일정, 완료한 운동, 종류, 시간, 목표 달성 여부를 날짜별로 살펴봅니다.",
  feat10Note: "헬스장·클래스 예약 기능이 아닙니다.",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 운동 선택",
  how1P: "하고 싶은 운동이나 스포츠를 선택하세요.",
  how2Title: "2️⃣ 목표 설정",
  how2P: "운동 횟수, 거리, 시간 등 개인 목표를 설정하세요.",
  how3Title: "3️⃣ 운동 기록",
  how3P: "운동을 완료하고 기록을 남기세요.",
  how4Title: "4️⃣ AI 분석",
  how4P: "AI가 운동 패턴과 목표 달성 흐름을 분석합니다.",
  how5Title: "5️⃣ 커뮤니티 참여",
  how5P: "운동 기록과 경험을 다른 사용자와 공유하세요.",
  how6Title: "6️⃣ 챌린지 / 쇼핑",
  how6P: "새로운 운동 챌린지에 참여하거나 필요한 스포츠 상품을 탐색하세요.",
  premiumLabel: "요금",
  premiumTitle: "✨ 프리미엄",
  premiumTagline: "요금제와 상세 혜택은<br />출시 전 확정 예정입니다",
  premFeatHeading: "준비 중인 방향",
  prem1Title: "AI 운동 분석 확대",
  prem1Lead: "더 세밀한 운동 패턴 분석과",
  prem1Note: "요약을 준비 중입니다.",
  prem2Title: "고급 운동 통계",
  prem2Lead: "주간·월간 통계와 종목 비율을",
  prem2Note: "더 자세히 보는 방향을 준비 중입니다.",
  prem3Title: "맞춤 운동 추천 강화",
  prem3Lead: "관심·기록 기반 추천을",
  prem3Note: "강화하는 방향을 준비 중입니다.",
  prem4Title: "무제한 기록",
  prem4Lead: "기록·저장 용량을",
  prem4Note: "넓히는 방향을 준비 중입니다.",
  prem5Title: "광고 제거",
  prem5Lead: "광고 없이 더 집중해서",
  prem5Note: "운동 흐름을 이어가는 방향을 준비 중입니다.",
  prem6Title: "챌린지 고급 기능",
  prem6Lead: "챌린지 참여·관리를",
  prem6Note: "더 편리하게 만드는 방향을 준비 중입니다.",
  prem7Title: "운동 리포트",
  prem7Lead: "기간별 운동 요약을",
  prem7Note: "리포트로 보는 방향을 준비 중입니다.",
  prem8Title: "데이터 백업",
  prem8Lead: "개인 운동 데이터 백업·동기화를",
  prem8Note: "준비 중입니다. 확정 요금은 출시 시 공개합니다.",
  recoTitle: "이런 분들에게 추천",
  reco1: "여러 종류의 운동을 즐기는 분",
  reco2: "러닝, 헬스, 스포츠 기록을 한곳에서 관리하고 싶은 분",
  reco3: "AI로 내 운동 패턴과 성과를 분석해보고 싶은 분",
  reco4: "다른 운동 사용자와 소통하고 싶은 분",
  reco5: "새로운 운동과 스포츠를 찾아보고 싶은 분",
  reco6: "운동 챌린지로 꾸준한 습관을 만들고 싶은 분",
  reco7: "인기 운동복과 운동 용품을 찾아보고 싶은 분",
  reco8: "여러 운동 앱을 따로 사용하는 것이 번거로운 분",
  premHiKicker: "작은 시작부터",
  premHiLine: "하고 싶은 모든 운동을 FitOn 하나에서.",
  premHiSub: "운동 탐색부터 기록, AI 분석, 커뮤니티, 챌린지까지.<br />당신의 모든 운동을 하나로 연결합니다.",
  closingHtml:
    `<p>하고 싶은 모든 운동을<br /><span class="ox-accent">FitOn 하나에서.</span></p><p>운동 탐색부터 기록, AI 분석, 커뮤니티, 챌린지까지.<br />당신의 모든 운동을 하나로 연결합니다.</p><p>기록과 습관부터<br /><span class="ox-accent">스포츠 쇼핑 탐색까지 한곳에서.</span></p>`,
  closingAria: "마무리 문구",
  footerRights: "© FitOn ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY 소개",
  drawerBl: "BabyLog 소개",
  drawerPl: "PetLog 소개",
  drawerPu: "PiggyUp 소개",
  drawerGu: "GoalUp 소개",
  drawerCu: "CountUp 소개",
  drawerNp: "Newon 소개",
  drawerMw: "My World 소개",
  drawerEo: "EatOn 소개",
  drawerFo: "FitOn · 이 화면",
  comingSoonLabel: "출시 예정",
  appStoreUrl: "#fo-top",
  googlePlayUrl: "#fo-top",
  appStoreBadgeAria: "App Store — 출시 예정",
  googlePlayBadgeAria: "Google Play — 출시 예정",
  deleteAccountLink: "계정 삭제",
};

export const foEn = {
  brandAria: "Back to top of FitOn",
  globalReachBadge: "Workout · Sports · AI analysis · Community · Challenges · Shopping",
  badge: "🏃 Workout · Sports · AI analysis · Community",
  h1: "FitOn",
  subtitleHtml: `<span class="ox-accent">Every workout you want,<br />in one place.</span>`,
  heroValueLine: "Every workout you want — in FitOn.",
  heroReachSummary:
    "Explore and log running, gym, home workouts, soccer, basketball, tennis, swimming, golf, cycling, yoga, and more—then connect AI activity insights, community, challenges, and sports shopping in one sports & fitness platform.",
  heroLogoAlt: "FitOn app logo",
  introLabel: "Brand",
  introTitle: "Why FitOn",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>FitOn</strong> is</p><p>not an app for only one sport.</p><p>Running apps for running,<br />gym apps for the gym,<br />home-workout apps for home training,<br />other apps for soccer, basketball, or tennis,<br />and still other services for community and gear shopping.</p><p>FitOn connects those scattered workout experiences.</p><p>Explore and log many activities—from running and gym to home workouts, team sports, swimming, golf, cycling, hiking, and yoga—in one place.</p><p>As logs build up, AI helps you understand frequency, time, goal progress, and patterns so your workout flow is easier to see.</p><p>Afterwards, share records and experiences in the community,<br />and browse routines, stories, and tips from others.</p><p>You can also explore popular gear—apparel, shoes, equipment—and compare listed prices across linked shopping channels.</p>',
  introClosing: "From finding a workout to logging, analyzing, connecting, and shopping — FitOn in one place.",
  showcaseCollageAria: "Five FitOn screenshot placeholders. Scroll horizontally to view all. Screenshots coming soon.",
  showcaseSoonLabel: "Coming soon",
  imgShot1Alt: "FitOn — Workout home (coming soon)",
  imgShot2Alt: "FitOn — My workouts (coming soon)",
  imgShot3Alt: "FitOn — AI workout analysis (coming soon)",
  imgShot4Alt: "FitOn — Community (coming soon)",
  imgShot5Alt: "FitOn — Shopping (coming soon)",
  shot1Cap: "Workout home",
  shot2Cap: "My workouts",
  shot3Cap: "AI analysis",
  shot4Cap: "Community",
  shot5Cap: "Shopping",
  reviewsLabel: "Stories",
  reviewsTitle: "Built for moments like these",
  review1Emoji: "👩🏼",
  review1Quote: "It would help if I didn’t have to log running and gym in separate apps.",
  review1Meta: "Office worker · 27",
  review2Emoji: "👨🏻",
  review2Quote: "I’d like AI to summarize my workout flow so I can see the pattern faster.",
  review2Meta: "Student · 24",
  review3Emoji: "👩🏻",
  review3Quote: "Sharing check-ins and routines with others would help me stay consistent.",
  review3Meta: "Office worker · 31",
  review4Emoji: "👨🏽",
  review4Quote: "Managing several sports—not just one—in one place would be great.",
  review4Meta: "Fitness hobby · 29",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Explore every workout",
  feat1Lead: "Browse running, gym, home workouts, soccer, basketball, tennis, badminton, swimming, golf, cycling, hiking, yoga, and more.",
  feat1Note: "Find what you want to do today, faster.",
  feat2Title: "Workout logging",
  feat2Lead: "Manage activity type, time, distance, reps, volume, and personal records.",
  feat2Note: "See multiple sports as one flow.",
  feat3Title: "AI workout analysis",
  feat3Lead: "Analyze patterns and progress from your logs and goals.",
  feat3Note: "Frequency · volume · goal progress · sport mix · consistency · trends · general guidance (not medical diagnosis)",
  feat4Title: "Workout community",
  feat4Lead: "Share check-ins, routines, records, sports stories, and tips with others.",
  feat4Note: "Running · gym · home · soccer · basketball · tennis · swimming · golf · hiking · free talk",
  feat5Title: "Challenges",
  feat5Lead: "Join challenges by distance, session count, streaks, or sport.",
  feat5Note: "e.g. 3×/week · 50km/month run · 30-day home workout · weekend hike",
  feat6Title: "Goal tracking",
  feat6Lead: "Set personal workout goals and check progress and completion rate.",
  feat6Note: "Build steady habits from small goals.",
  feat7Title: "Habits / streaks",
  feat7Lead: "Mark workout days and review streak length and habit flow.",
  feat7Note: "See consistency at a glance.",
  feat8Title: "Sports shopping",
  feat8Lead: "Explore popular apparel, shoes, equipment, and gear.",
  feat8Note: "Compare listed prices across linked channels—no lowest-price guarantee.",
  feat9Title: "Workout stats",
  feat9Lead:
    "View weekly time, monthly sessions, total distance, top activities, sport mix, goal progress, streaks, and more at a glance.",
  feat9Note: "Not medical or injury diagnosis—activity-log reference only. Supported metrics may vary by release.",
  feat10Title: "Personal workout calendar",
  feat10Lead:
    "See completed and planned workouts on a calendar—schedule, finished sessions, activity type, duration, and goal status by date.",
  feat10Note: "Not gym or class booking.",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Pick a workout",
  how1P: "Choose the sport or activity you want.",
  how2Title: "2️⃣ Set a goal",
  how2P: "Set personal goals for sessions, distance, or time.",
  how3Title: "3️⃣ Log activity",
  how3P: "Finish a session and save the record.",
  how4Title: "4️⃣ AI analysis",
  how4P: "Review patterns and goal progress with AI.",
  how5Title: "5️⃣ Join the community",
  how5P: "Share records and experiences with others.",
  how6Title: "6️⃣ Challenges / shopping",
  how6P: "Join a challenge or explore sports products you need.",
  premiumLabel: "Pricing",
  premiumTitle: "✨ Premium",
  premiumTagline: "Plans and benefits will be<br />confirmed before launch",
  premFeatHeading: "Directions in progress",
  prem1Title: "Expanded AI analysis",
  prem1Lead: "Deeper pattern analysis and",
  prem1Note: "summaries — in preparation.",
  prem2Title: "Advanced workout stats",
  prem2Lead: "Richer weekly/monthly stats and sport mix",
  prem2Note: "— in preparation.",
  prem3Title: "Stronger recommendations",
  prem3Lead: "Suggestions from interests and logs",
  prem3Note: "— in preparation.",
  prem4Title: "Unlimited logging",
  prem4Lead: "More room for saves and records",
  prem4Note: "— in preparation.",
  prem5Title: "Ad-free",
  prem5Lead: "A cleaner, more focused experience",
  prem5Note: "— in preparation.",
  prem6Title: "Advanced challenges",
  prem6Lead: "Richer challenge participation and management",
  prem6Note: "— in preparation.",
  prem7Title: "Workout reports",
  prem7Lead: "Period summaries as reports",
  prem7Note: "— in preparation.",
  prem8Title: "Data backup",
  prem8Lead: "Backup and sync for personal workout data",
  prem8Note: "— in preparation. Pricing confirmed at launch.",
  recoTitle: "Recommended if you…",
  reco1: "Enjoy more than one kind of workout",
  reco2: "Want running, gym, and sports logs in one place",
  reco3: "Want AI insights on patterns and progress",
  reco4: "Want to connect with other active people",
  reco5: "Want to discover new sports and workouts",
  reco6: "Want challenges that build steady habits",
  reco7: "Want to browse popular gear and apparel",
  reco8: "Are tired of juggling multiple fitness apps",
  premHiKicker: "From a small start",
  premHiLine: "Every workout you want — in FitOn.",
  premHiSub: "From discovery to logging, AI analysis, community, and challenges.<br />Connect every workout in one place.",
  closingHtml:
    `<p>Every workout you want<br /><span class="ox-accent">in FitOn.</span></p><p>From discovery to logging, AI analysis, community, and challenges.<br />Connect every workout in one place.</p><p>From habits and records<br /><span class="ox-accent">to sports shopping exploration.</span></p>`,
  closingAria: "Closing message",
  footerRights: "© FitOn ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "Open SAVY intro",
  drawerBl: "Open BabyLog intro",
  drawerPl: "Open PetLog intro",
  drawerPu: "Open PiggyUp intro",
  drawerGu: "Open GoalUp intro",
  drawerCu: "Open CountUp intro",
  drawerNp: "Open Newon intro",
  drawerMw: "Open My World intro",
  drawerEo: "Open EatOn intro",
  drawerFo: "FitOn · this screen",
  comingSoonLabel: "Coming soon",
  appStoreUrl: "#fo-top",
  googlePlayUrl: "#fo-top",
  appStoreBadgeAria: "App Store — Coming soon",
  googlePlayBadgeAria: "Google Play — Coming soon",
  deleteAccountLink: "Delete account",
};
