/** GoalUp page copy — merged into locales/*.json by apply-goalup-locales.mjs */

export const guKo = {
  brandAria: "GoalUp 상단으로",
  globalReachBadge: "From small goals · Worldwide service",
  badge: "🎯 목표 관리 · 챌린지 · AI 성장 코치",
  h1: "GoalUp",
  subtitleHtml: `<span class="ox-accent">작은 목표가 모여 더 큰 성장을 만듭니다</span>`,
  heroReachSummary:
    "목표 설정부터 실행 관리, 챌린지와 AI 성장 분석까지. 꾸준한 실천을 성장 경험으로 바꾸어주는 스마트 목표 플랫폼입니다.",
  heroLogoAlt: "GoalUp 앱 로고: 보라색 깃발",
  introLabel: "브랜드",
  introTitle: "왜 GoalUp인가",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>GoalUp</strong>은</p><p>목표를 세우고 꾸준히 실천하며 성장 과정을 기록할 수 있는 스마트 성장 플랫폼입니다.</p><p>매일의 작은 행동부터 장기 목표까지 체계적으로 관리할 수 있으며, AI 분석을 통해 더 효율적인 목표 달성을 경험할 수 있습니다.</p><p>챌린지, 성장 통계, 실행 기록 기능을 통해 꾸준함이 눈에 보이는 성장 경험을 만들어보세요.</p><p>작은 목표가 모이면 더 큰 변화가 시작됩니다.</p>',
  introClosing: "오늘의 작은 실천이 미래의 큰 성장을 만듭니다.",
  showcaseCollageAria: "GoalUp 앱 미리보기 7장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt: "GoalUp — 목표 관리부터 습관 형성, 챌린지, AI 분석까지",
  imgShot2Alt: "GoalUp — 오늘 해야 할 목표를 한눈에 관리",
  imgShot3Alt: "GoalUp — 추천 챌린지에 함께 참여하고 성장",
  imgShot4Alt: "GoalUp — 목표를 체계적으로 관리하고 진행 상황 확인",
  imgShot5Alt: "GoalUp — AI 기반 고급 통계 분석",
  imgShot6Alt: "GoalUp — 나만의 챌린지를 빠르게 시작",
  imgShot7Alt: "GoalUp — 프리미엄 AI 코치와 고급 분석",  reviewsTitle: "사용자 이야기",  review1Quote: "목표를 세우는 사람이 아니라 목표를 달성하는 사람이 된 것 같아요.",  review2Emoji: "👩🏻",  review2Meta: "대학생 · 22세",  review3Quote: "포기하던 목표들을 끝까지 해내게 되었습니다.",  review4Emoji: "👨🏽",  review4Meta: "연구원 · 38세",
  reviewsLabel: "후기",
  reviewsTitle: "사용자 이야기",
  review1Emoji: "👨🏻",
  review1Quote: "목표를 세우는 사람이 아니라 목표를 달성하는 사람이 된 것 같아요.",
  review1Meta: "스타트업 대표 · 34세",
  review2Emoji: "👩🏻",
  review2Quote: "작은 성공이 쌓이니까 자신감도 같이 커졌어요.",
  review2Meta: "대학생 · 22세",
  review3Emoji: "👩🏼",
  review3Quote: "포기하던 목표들을 끝까지 해내게 되었습니다.",
  review3Meta: "마케터 · 28세",
  review4Emoji: "👨🏽",
  review4Quote: "성장 과정을 눈으로 볼 수 있다는 게 가장 좋습니다.",
  review4Meta: "연구원 · 38세",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "목표 관리",
  feat1Lead: "목표를 생성하고 카테고리별로 관리할 수 있습니다.",
  feat1Note: "반복 주기, 알림, 우선순위, 기간 설정을 지원합니다.",
  feat2Title: "챌린지",
  feat2Lead: "혼자 또는 친구와 함께 챌린지를 진행할 수 있습니다.",
  feat2Note: "꾸준한 실천을 재미있게 이어갈 수 있습니다.",
  feat3Title: "목표 알림",
  feat3Lead: "반복 알림과 리마인더를 통해",
  feat3Note: "목표를 잊지 않도록 도와줍니다.",
  feat4Title: "성장 분석",
  feat4Lead: "성공률, 연속 기록, 완료 추이를 분석합니다.",
  feat4Note: "꾸준함을 데이터로 확인할 수 있습니다.",
  feat5Title: "통계 시각화",
  feat5Lead: "주간, 월간, 연간 목표 달성률을 그래프로 확인할 수 있습니다.",
  feat5Note: "성장 과정을 직관적으로 보여줍니다.",
  feat6Title: "AI 성장 분석",
  feat6Lead: "AI가 목표 패턴을 분석하고 실패 원인과 개선 방향을 제안합니다.",
  feat6Note: "더 효과적인 성장 루틴을 만들 수 있습니다.",
  feat7Title: "연속 기록",
  feat7Lead: "연속 달성 기록과 성장 히스토리를 관리합니다.",
  feat7Note: "작은 실천이 습관으로 이어집니다.",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 목표 만들기",
  how1P: "달성하고 싶은 목표를 추가하세요.",
  how2Title: "2️⃣ 일정 설정",
  how2P: "주기와 알림을 설정하세요.",
  how3Title: "3️⃣ 꾸준히 기록하기",
  how3P: "매일 목표를 완료하며 성장해보세요.",
  how4Title: "4️⃣ AI 분석 확인",
  how4P: "성장 리포트와 인사이트를 확인하세요.",
  how5Title: "5️⃣ 챌린지 참여",
  how5P: "친구들과 함께 목표를 달성해보세요.",
  how6Title: "6️⃣ 성장 경험하기",
  how6P: "작은 성공을 쌓으며 더 큰 목표에 도전해보세요.",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "목표·챌린지·AI로<br />더 스마트한 성장",
  premFeatHeading: "프리미엄 기능",
  prem1Title: "무제한 목표",
  prem1Lead: "개수 제한 없이",
  prem1Note: "원하는 만큼 목표를 설정합니다.",
  prem2Title: "무제한 챌린지",
  prem2Lead: "개인·그룹 챌린지를",
  prem2Note: "제한 없이 진행할 수 있습니다.",
  prem3Title: "AI 목표 코치",
  prem3Lead: "성공률 분석, 주간 리포트,",
  prem3Note: "맞춤 전략을 제공합니다.",
  prem4Title: "AI 성공 예측",
  prem4Lead: "목표 패턴을 분석하고",
  prem4Note: "달성 가능성을 예측합니다.",
  prem5Title: "고급 통계",
  prem5Lead: "요일, 시간, 카테고리별",
  prem5Note: "성장 패턴 분석과 PDF 리포트를 제공합니다.",
  prem6Title: "포커스 목표",
  prem6Lead: "홈 화면 고정, 우선순위 강조,",
  prem6Note: "집중 모드를 제공합니다.",
  prem7Title: "홈 위젯",
  prem7Lead: "오늘 목표, D-Day, 연속 기록을",
  prem7Note: "홈 화면에서 확인합니다.",
  prem8Title: "광고 제거",
  prem8Lead: "광고 없이",
  prem8Note: "목표 달성에 집중하세요.",
  recoTitle: "이런 분들에게 추천",
  reco1: "🎯 꾸준한 습관을 만들고 싶은 분",
  reco2: "📋 목표를 체계적으로 관리하고 싶은 분",
  reco3: "🤖 AI 성장 분석을 경험하고 싶은 분",
  reco4: "💪 동기부여가 필요한 분",
  reco5: "🏆 챌린지를 좋아하는 분",
  reco6: "📚 자기계발을 꾸준히 이어가고 싶은 분",
  reco7: "📈 성장 과정을 기록하고 싶은 분",
  premHiKicker: "작은 목표부터",
  premHiLine: "성장 습관을 만드는 경험",
  premHiSub: "GoalUp이 당신의<br />목표 달성을 더 꾸준하게 만듭니다.",
  closingHtml:
    `<p>작은 목표가<br /><span class="ox-accent">더 큰 성장을 만듭니다</span></p><p>GoalUp은 목표를 적는 앱이 아니라<br />꾸준함을 성장으로 바꾸는 플랫폼입니다.</p><p>오늘의 작은 실천이<br /><span class="ox-accent">미래의 큰 변화를 만들어갑니다.</span></p>`,
  closingAria: "마무리 문구",
  footerRights: "© GoalUp ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY 소개",
  drawerBl: "BabyLog 소개",
  drawerPl: "PetLog 소개",
  drawerPu: "PiggyUp 소개",
  drawerGu: "GoalUp · 이 화면",
  drawerCu: "CountUp 소개",
  appStoreUrl: "https://apps.apple.com/kr/app/goalup-ai-%EB%AA%A9%ED%91%9C-%EA%B4%80%EB%A6%AC-%EC%B1%8C%EB%A6%B0%EC%A7%80/id6780510853",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=goalup.newon.app&pcampaignid=web_share",
  appStoreBadgeAria: "App Store에서 GoalUp(새 탭)",
  googlePlayBadgeAria: "Google Play에서 GoalUp(새 탭)",
};

export const guEn = {
  brandAria: "Back to top of GoalUp",
  globalReachBadge: "173 countries · 13 languages supported",
  badge: "🎯 Goal tracking · Challenges · AI growth coach",
  h1: "GoalUp",
  subtitleHtml: `<span class="ox-accent">Small goals add up to bigger growth</span>`,
  heroReachSummary:
    "From goal setting to execution, challenges, and AI growth analysis—turn steady practice into a growth experience.",
  heroLogoAlt: "GoalUp app logo: purple flag",
  introLabel: "Brand",
  introTitle: "Why GoalUp",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>GoalUp</strong> is</p><p>a smart growth platform to set goals, stay consistent, and record your progress over time.</p><p>Manage daily actions and long-term goals in one system—and use AI analysis for more efficient achievement.</p><p>Challenges, growth stats, and execution logs help you see consistency become visible progress.</p><p>Small goals add up to meaningful change.</p>',
  introClosing: "Today's small step builds tomorrow's big growth.",
  showcaseCollageAria: "Seven GoalUp app previews. Scroll horizontally to view all.",
  imgShot1Alt: "GoalUp — Goal management, habits, challenges, and AI insights",
  imgShot2Alt: "GoalUp — See today's goals at a glance",
  imgShot3Alt: "GoalUp — Challenge yourself and grow with friends",
  imgShot4Alt: "GoalUp — Manage goals and track progress in one place",
  imgShot5Alt: "GoalUp — Advanced analytics powered by AI",
  imgShot6Alt: "GoalUp — Create your own challenge quickly",
  imgShot7Alt: "GoalUp — Premium AI coach and advanced insights",  reviewsTitle: "User stories",  review1Quote: "I feel like someone who finishes goals—not just sets them.",  review2Emoji: "👩🏻",  review2Meta: "College student · 22",  review3Quote: "Goals I used to drop—I actually see through now.",  review4Emoji: "👨🏽",  review4Meta: "Researcher · 38",
  reviewsLabel: "Reviews",
  reviewsTitle: "User stories",
  review1Emoji: "👨🏻",
  review1Quote: "I feel like someone who finishes goals—not just sets them.",
  review1Meta: "Startup founder · 34",
  review2Emoji: "👩🏻",
  review2Quote: "Small wins stacked up—and so did my confidence.",
  review2Meta: "College student · 22",
  review3Emoji: "👩🏼",
  review3Quote: "Goals I used to drop—I actually see through now.",
  review3Meta: "Marketer · 28",
  review4Emoji: "👨🏽",
  review4Quote: "The best part is seeing my growth in plain sight.",
  review4Meta: "Researcher · 38",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Goal management",
  feat1Lead: "Create goals and organize them by category.",
  feat1Note: "Set repeat cycles, alerts, priority, and time ranges.",
  feat2Title: "Challenges",
  feat2Lead: "Run challenges solo or with friends.",
  feat2Note: "Keep steady practice fun and engaging.",
  feat3Title: "Goal alerts",
  feat3Lead: "Recurring alerts and reminders",
  feat3Note: "help you never forget your goals.",
  feat4Title: "Growth analysis",
  feat4Lead: "Analyze success rate, streaks, and completion trends.",
  feat4Note: "See consistency as data.",
  feat5Title: "Stats visualization",
  feat5Lead: "View weekly, monthly, and yearly completion in charts.",
  feat5Note: "See your growth journey intuitively.",
  feat6Title: "AI growth analysis",
  feat6Lead: "AI analyzes goal patterns and suggests failure causes and improvements.",
  feat6Note: "Build more effective growth routines.",
  feat7Title: "Streak tracking",
  feat7Lead: "Manage streaks and growth history.",
  feat7Note: "Small steps become lasting habits.",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Create a goal",
  how1P: "Add what you want to achieve.",
  how2Title: "2️⃣ Set a schedule",
  how2P: "Choose cadence and reminders.",
  how3Title: "3️⃣ Log consistently",
  how3P: "Complete goals daily and grow.",
  how4Title: "4️⃣ Check AI insights",
  how4P: "Review growth reports and tips.",
  how5Title: "5️⃣ Join challenges",
  how5P: "Reach goals together with friends.",
  how6Title: "6️⃣ Experience growth",
  how6P: "Stack small wins and take on bigger goals.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "Goals, challenges & AI<br />for smarter growth",
  premFeatHeading: "Premium features",
  prem1Title: "Unlimited goals",
  prem1Lead: "No cap—set as many",
  prem1Note: "goals as you need.",
  prem2Title: "Unlimited challenges",
  prem2Lead: "Personal and group challenges",
  prem2Note: "with no limits.",
  prem3Title: "AI goal coach",
  prem3Lead: "Success-rate analysis, weekly reports,",
  prem3Note: "and tailored strategies.",
  prem4Title: "AI success forecast",
  prem4Lead: "Analyze goal patterns and",
  prem4Note: "predict achievement likelihood.",
  prem5Title: "Advanced statistics",
  prem5Lead: "Weekday, time, and category",
  prem5Note: "pattern analysis plus PDF reports.",
  prem6Title: "Focus goals",
  prem6Lead: "Home pinning, priority emphasis,",
  prem6Note: "and focus mode.",
  prem7Title: "Home widgets",
  prem7Lead: "Today's goals, D-day, and streaks",
  prem7Note: "on your home screen.",
  prem8Title: "Remove ads",
  prem8Lead: "No ads—",
  prem8Note: "focus on achieving your goals.",
  recoTitle: "Great if you…",
  reco1: "🎯 Want to build steady habits",
  reco2: "📋 Want structured goal management",
  reco3: "🤖 Want AI-powered growth analysis",
  reco4: "💪 Need motivation to keep going",
  reco5: "🏆 Enjoy challenges",
  reco6: "📚 Want to keep improving yourself",
  reco7: "📈 Want to record your growth journey",
  premHiKicker: "With small goals",
  premHiLine: "Build growth habits that last.",
  premHiSub: "GoalUp helps you<br />stay consistent with your goals.",
  closingHtml:
    `<p>Small goals<br /><span class="ox-accent">Bigger growth</span></p><p>GoalUp isn't for writing goals—<br />it's a platform that turns consistency into growth.</p><p>Today's small steps<br /><span class="ox-accent">build tomorrow's big change.</span></p>`,
  closingAria: "Closing message",
  footerRights: "© GoalUp ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "Open SAVY intro",
  drawerBl: "Open BabyLog intro",
  drawerPl: "Open PetLog intro",
  drawerPu: "Open PiggyUp intro",
  drawerGu: "GoalUp · this screen",
  drawerCu: "Open CountUp intro",
  appStoreUrl: "https://apps.apple.com/kr/app/goalup-ai-%EB%AA%A9%ED%91%9C-%EA%B4%80%EB%A6%AC-%EC%B1%8C%EB%A6%B0%EC%A7%80/id6780510853",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=goalup.newon.app&pcampaignid=web_share",
  appStoreBadgeAria: "GoalUp on the App Store (opens in a new tab)",
  googlePlayBadgeAria: "GoalUp on Google Play (opens in a new tab)",
};
