/** GoalUp page copy — merged into locales/*.json by apply-goalup-locales.mjs */

export const guKo = {
  brandAria: "GoalUp 상단으로",
  globalReachBadge: "173개국 출시 · 13개 언어 지원",
  badge: "🎯 목표 관리 · 챌린지 · AI 성장 코치",
  h1: "GoalUp",
  subtitleHtml: "작은 목표가 모여 더 큰 성장을 만듭니다",
  heroReachSummary:
    "목표 설정부터 진행률 분석, AI 성장 인사이트까지 한 번에 관리하는 스마트 목표 관리 앱입니다.",
  heroLogoAlt: "GoalUp 앱 로고: 보라색 깃발",
  introLabel: "앱 소개",
  introTitle: "앱 소개",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>GoalUp</strong>은 목표를 세우고 꾸준히 실천하며</p><p>성장 습관을 만들어가는 앱입니다.</p><p>매일의 작은 행동부터 장기 목표까지 체계적으로 관리할 수 있으며 AI 성장 분석을 통해 더 효율적인 목표 달성을 경험할 수 있습니다.</p><p>챌린지, 목표 추적, 통계 분석 기능을 통해 꾸준한 성장을 시각적으로 확인해보세요.</p><p>작은 목표가 모이면 더 큰 변화가 시작됩니다.</p>',
  introClosing: "오늘의 작은 실천이 미래의 큰 성장을 만듭니다.",
  showcaseCollageAria: "GoalUp 앱 미리보기 7장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt: "GoalUp — 목표 관리부터 습관 형성, 챌린지, AI 분석까지",
  imgShot2Alt: "GoalUp — 오늘 해야 할 목표를 한눈에 관리",
  imgShot3Alt: "GoalUp — 추천 챌린지에 함께 참여하고 성장",
  imgShot4Alt: "GoalUp — 목표를 체계적으로 관리하고 진행 상황 확인",
  imgShot5Alt: "GoalUp — AI 기반 고급 통계 분석",
  imgShot6Alt: "GoalUp — 나만의 챌린지를 빠르게 시작",
  imgShot7Alt: "GoalUp — 프리미엄 AI 코치와 고급 분석",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "목표 관리",
  feat1Lead: "목표를 생성하고 카테고리별로 관리할 수 있습니다.",
  feat1Note: "반복 주기, 중요도, 알림 등을 설정하여 체계적인 목표 관리를 제공합니다.",
  feat2Title: "챌린지",
  feat2Lead: "개인 또는 친구와 함께 챌린지를 진행할 수 있습니다.",
  feat2Note: "꾸준한 실천을 게임처럼 즐길 수 있습니다.",
  feat3Title: "목표 알림",
  feat3Lead: "목표 달성을 잊지 않도록 알림을 제공합니다.",
  feat3Note: "반복 알림과 리마인더를 지원합니다.",
  feat4Title: "성장 분석",
  feat4Lead: "성공률, 연속 기록, 완료 추이를 분석합니다.",
  feat4Note: "꾸준함을 데이터로 확인할 수 있습니다.",
  feat5Title: "통계 시각화",
  feat5Lead: "주간, 월간, 연간 목표 달성률을 시각적으로 제공합니다.",
  feat5Note: "성장 과정을 직관적으로 확인할 수 있습니다.",
  feat6Title: "AI 성장 분석",
  feat6Lead: "AI가 목표 패턴을 분석하여 맞춤 인사이트를 제공합니다.",
  feat6Note: "더 효율적인 습관 형성을 도와줍니다.",
  feat7Title: "연속 기록",
  feat7Lead: "연속 달성 기록과 성장 흐름을 확인할 수 있습니다.",
  feat7Note: "꾸준한 실천 습관 형성을 지원합니다.",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 목표 만들기",
  how1P: "달성하고 싶은 목표를 추가하세요.",
  how2Title: "2️⃣ 일정 설정",
  how2P: "주기와 알림을 설정하세요.",
  how3Title: "3️⃣ 꾸준히 기록하기",
  how3P: "매일 목표를 완료하며 성장해보세요.",
  how4Title: "4️⃣ AI 분석 확인",
  how4P: "성장 리포트와 인사이트를 확인하세요.",
  how5Title: "5️⃣ 챌린지 참여",
  how5P: "친구들과 함께 목표를 달성해보세요.",
  how6Title: "6️⃣ 성장 경험하기",
  how6P: "작은 성공이 더 큰 목표로 이어집니다.",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "더 깊은 분석과<br />더 스마트한 목표 경험을 제공합니다.",
  premFeatHeading: "프리미엄 기능",
  prem1Title: "고급 통계",
  prem1Lead: "주간, 월간, 연간 목표 패턴을",
  prem1Note: "분석합니다.",
  prem2Title: "AI 성장 리포트",
  prem2Lead: "사용자의 기록을 기반으로",
  prem2Note: "성장 인사이트를 제공합니다.",
  prem3Title: "AI 목표 코치",
  prem3Lead: "성공 가능성을 예측하고",
  prem3Note: "목표 전략을 제안합니다.",
  prem4Title: "상세 분석",
  prem4Lead: "시간대, 요일별 성공 패턴을",
  prem4Note: "제공합니다.",
  prem5Title: "광고 제거",
  prem5Lead: "광고 없이",
  prem5Note: "GoalUp을 이용할 수 있습니다.",
  recoTitle: "이런 분들에게 추천",
  reco1: "꾸준한 습관을 만들고 싶은 분",
  reco2: "목표 달성을 체계적으로 관리하고 싶은 분",
  reco3: "AI 성장 분석을 경험하고 싶은 분",
  reco4: "동기부여가 필요한 분",
  reco5: "챌린지를 좋아하는 분",
  reco6: "자기계발을 꾸준히 이어가고 싶은 분",
  reco7: "성장 과정을 기록하고 싶은 분",
  premHiKicker: "한 줄 강조 문구",
  premHiLine: "목표를 기록하고 성장 습관을 만드는 경험",
  premHiSub: "작은 목표가 큰 변화를 만듭니다.",
  closingHtml:
    "<p><strong>GoalUp</strong>과 함께<br />더 꾸준하고<br />더 의미 있는 성장을 시작하세요.</p>",
  closingAria: "마무리 문구",
  footerRights: "© GoalUp ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY 소개",
  drawerBl: "BabyLog 소개",
  drawerPl: "PetLog 소개",
  drawerPu: "PiggyUp 소개",
  drawerGu: "GoalUp · 이 화면",
  drawerCu: "CountUp 소개",
  appStoreUrl: "https://apps.apple.com/kr/app/goalup-ai-%EB%AA%A9%ED%91%9C-%EA%B4%80%EB%A6%AC-%EC%B1%8C%EB%A6%B0%EC%A7%80/id6780510853",
  googlePlayUrl: "https://newon.app",
  appStoreBadgeAria: "App Store에서 GoalUp(새 탭)",
  googlePlayBadgeAria: "Google Play에서 GoalUp(새 탭)",
};

export const guEn = {
  brandAria: "Back to top of GoalUp",
  globalReachBadge: "173 countries · 13 languages supported",
  badge: "🎯 Goal management · challenges · AI growth coach",
  h1: "GoalUp",
  subtitleHtml: "Small goals add up to bigger growth",
  heroReachSummary:
    "A smart goal app—from setting targets to progress analysis and AI growth insights, all in one place.",
  heroLogoAlt: "GoalUp app logo: purple flag",
  introLabel: "About the app",
  introTitle: "About the app",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>GoalUp</strong> helps you set goals, stay consistent,</p><p>and build growth habits over time.</p><p>Manage daily actions and long-term goals in one system—and use AI growth analysis for more efficient progress.</p><p>Challenges, goal tracking, and stats help you see steady growth visually.</p><p>Small goals add up to meaningful change.</p>',
  introClosing: "Today's small step builds tomorrow's big growth.",
  showcaseCollageAria: "Seven GoalUp app previews. Scroll horizontally to view all.",
  imgShot1Alt: "GoalUp — Goal management, habits, challenges, and AI insights",
  imgShot2Alt: "GoalUp — See today's goals at a glance",
  imgShot3Alt: "GoalUp — Challenge yourself and grow with friends",
  imgShot4Alt: "GoalUp — Manage goals and track progress in one place",
  imgShot5Alt: "GoalUp — Advanced analytics powered by AI",
  imgShot6Alt: "GoalUp — Create your own challenge quickly",
  imgShot7Alt: "GoalUp — Premium AI coach and advanced insights",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Goal management",
  feat1Lead: "Create goals and organize them by category.",
  feat1Note: "Set repeat cycles, priority, and alerts for structured goal management.",
  feat2Title: "Challenges",
  feat2Lead: "Run challenges solo or with friends.",
  feat2Note: "Make steady progress feel like a game.",
  feat3Title: "Goal alerts",
  feat3Lead: "Reminders so you don't miss your goals.",
  feat3Note: "Supports recurring alerts and nudges.",
  feat4Title: "Growth analysis",
  feat4Lead: "Analyze success rate, streaks, and completion trends.",
  feat4Note: "See consistency as data.",
  feat5Title: "Stats visualization",
  feat5Lead: "Weekly, monthly, and yearly goal completion at a glance.",
  feat5Note: "Track growth intuitively over time.",
  feat6Title: "AI growth analysis",
  feat6Lead: "AI reads your goal patterns",
  feat6Note: "and offers tailored insights for better habits.",
  feat7Title: "Streak tracking",
  feat7Lead: "View streaks and growth momentum.",
  feat7Note: "Supports building steady practice habits.",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Create a goal",
  how1P: "Add what you want to achieve.",
  how2Title: "2️⃣ Set a schedule",
  how2P: "Choose cadence and reminders.",
  how3Title: "3️⃣ Log consistently",
  how3P: "Complete goals daily and grow.",
  how4Title: "4️⃣ Check AI insights",
  how4P: "Review growth reports and tips.",
  how5Title: "5️⃣ Join challenges",
  how5P: "Reach goals together with friends.",
  how6Title: "6️⃣ Experience growth",
  how6P: "Small wins lead to bigger goals.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "Deeper analysis and<br />a smarter goal experience",
  premFeatHeading: "Premium features",
  prem1Title: "Advanced stats",
  prem1Lead: "Weekly, monthly, and yearly",
  prem1Note: "goal pattern analysis.",
  prem2Title: "AI growth reports",
  prem2Lead: "From your activity history,",
  prem2Note: "get personalized growth insights.",
  prem3Title: "AI goal coach",
  prem3Lead: "Predict success likelihood",
  prem3Note: "and suggest goal strategies.",
  prem4Title: "Detailed analysis",
  prem4Lead: "Time-of-day and day-of-week",
  prem4Note: "success patterns.",
  prem5Title: "Remove ads",
  prem5Lead: "Use GoalUp",
  prem5Note: "without interruptions.",
  recoTitle: "Great if you…",
  reco1: "Want to build steady habits",
  reco2: "Want structured goal management",
  reco3: "Want AI-powered growth analysis",
  reco4: "Need motivation to keep going",
  reco5: "Enjoy challenges",
  reco6: "Want to keep improving yourself",
  reco7: "Want to record your growth journey",
  premHiKicker: "In one line",
  premHiLine: "Record goals—and build growth habits.",
  premHiSub: "Small goals make big change.",
  closingHtml:
    "<p>Start steadier, more meaningful growth<br />with <strong>GoalUp</strong>.</p>",
  closingAria: "Closing message",
  footerRights: "© GoalUp ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "Open SAVY intro",
  drawerBl: "Open BabyLog intro",
  drawerPl: "Open PetLog intro",
  drawerPu: "Open PiggyUp intro",
  drawerGu: "GoalUp · this screen",
  drawerCu: "Open CountUp intro",
  appStoreUrl: "https://apps.apple.com/kr/app/goalup-ai-%EB%AA%A9%ED%91%9C-%EA%B4%80%EB%A6%AC-%EC%B1%8C%EB%A6%B0%EC%A7%80/id6780510853",
  googlePlayUrl: "https://newon.app",
  appStoreBadgeAria: "GoalUp on the App Store (opens in a new tab)",
  googlePlayBadgeAria: "GoalUp on Google Play (opens in a new tab)",
};
