/**
 * MVP DEVELOPMENT service detail — KO/EN copy.
 * Path: /{lang}/business/mvp/
 */
import { resolveKoEnPack } from "./i18n/copy-lang.mjs";

export const MVP_COPY = {
  ko: {
    seoTitle: "MVP DEVELOPMENT | Newon Business",
    metaDescription:
      "아이디어를 빠르게 검증할 수 있는 실제 제품으로 만듭니다. 문제 정의, UX, 개발, 배포까지 IDEA → BUILD → LAUNCH 흐름으로 진행합니다. Newon MVP DEVELOPMENT.",
    crumbBusiness: "BUSINESS",
    crumbServices: "SERVICES",
    crumbBuild: "BUILD",
    crumbHere: "MVP",
    eyebrow: "MVP DEVELOPMENT",
    subEyebrow: "BUILD",
    headline: "아이디어를\n실제 제품으로.",
    lead: "아이디어 검증부터 핵심 기능 정의, UX/UI, 개발, 테스트, 출시까지. 초기 제품을 빠르게 실제 사용자에게 전달할 수 있도록 설계합니다. 기획·디자인·개발이 끊기지 않는 IDEA → BUILD → LAUNCH 흐름으로 진행합니다.",
    ctaPrimary: "MVP 개발 문의 →",
    ctaSecondary: "구축 흐름 보기 ↓",
    meta: [
      { k: "SERVICE", v: "MVP Development" },
      { k: "BEST FOR", v: "아이디어 검증·첫 제품 출시" },
      { k: "TIMELINE", v: "보통 3–6주" },
      { k: "PRICE", v: "₩1,000,000부터" },
    ],
    overviewLabel: "OVERVIEW",
    overviewTitle: "아이디어는 있는데,\n형태가 없습니다.",
    overviewBody: [
      "아이디어는 분명하지만 무엇을 먼저 만들지, 어디까지 만들지 정하지 못한 상태가 흔합니다. 기능을 많이 넣으면 출시가 늦어지고, 데모만 있으면 실제 검증이 어렵습니다.",
      "MVP는 '최소'이지만 '동작하는 제품'이어야 합니다. 슬라이드 데모가 아니라 사용자가 클릭하고 입력하고 목표를 달성할 수 있는 Web 또는 App이 필요합니다.",
      "MVP DEVELOPMENT는 먼저 해결할 문제와 검증 질문을 정의합니다. 그다음 핵심 흐름만 남긴 UX/UI를 설계하고, 필요한 백엔드·데이터·배포까지 포함해 실제 출시 가능한 첫 버전을 만듭니다.",
    ],
    problemsLabel: "PROBLEMS",
    problemsTitle: "이런 상황에서 도움이 됩니다.",
    problems: [
      {
        n: "01",
        t: "IDEA ONLY",
        d: "아이디어는 있지만 무엇을 먼저 만들지 정하지 못한 경우.\n검증에 필요한 최소 제품 구조가 필요한 경우.",
      },
      {
        n: "02",
        t: "SCOPE CREEP",
        d: "처음부터 크게 만들면 위험한 경우.\n기능이 많아져 출시가 계속 미뤄지는 경우.",
      },
      {
        n: "03",
        t: "DISCONNECTED BUILD",
        d: "기획·디자인·개발이 끊겨 산출물이 데모 수준에 머무는 경우.\n한 흐름으로 이어지는 파트너가 필요한 경우.",
      },
      {
        n: "04",
        t: "NO VALIDATION PATH",
        d: "만들기는 했지만 실제 사용자에게 보여줄 환경이 없는 경우.\n배포·공유·피드백 루프가 없는 경우.",
      },
      {
        n: "05",
        t: "PLATFORM UNCERTAINTY",
        d: "웹과 앱 중 무엇이 맞는지 판단이 어려운 경우.\n검증 목표에 맞는 플랫폼 선택이 필요한 경우.",
      },
      {
        n: "06",
        t: "POST-MVP GAP",
        d: "출시 후 무엇을 확장할지 우선순위가 없는 경우.\n검증 결과를 다음 단계로 연결할 구조가 필요한 경우.",
      },
    ],
    baLabel: "BEFORE / AFTER",
    baTitle: "데모 수준 산출물 vs\n검증 가능한 첫 제품",
    beforeLabel: "BEFORE",
    afterLabel: "AFTER",
    before: [
      "아이디어와 기능 목록만 있고 범위가 없음",
      "기획·디자인·개발이 단계별로 끊김",
      "클릭해볼 수 없는 슬라이드·목업 수준",
      "출시 환경·다음 단계 계획이 없음",
    ],
    after: [
      "문제·사용자·검증 질문을 먼저 정의",
      "핵심 흐름 중심 UX/UI와 범위 합의",
      "실제로 쓸 수 있는 Web 또는 App MVP",
      "배포 환경과 다음 단계 로드맵까지 전달",
    ],
    capsLabel: "CAPABILITIES",
    capsTitle: "MVP 구축에 필요한 작업을\n한 구조로 진행합니다.",
    caps: [
      {
        t: "PROBLEM FRAMING",
        d: "해결할 문제, 주요 사용자, 검증 질문을 정의합니다.\nMVP에 넣을 것과 빼야 할 것을 명확히 합니다.",
      },
      {
        t: "SCOPE DEFINITION",
        d: "첫 버전에 필요한 핵심 기능만 남깁니다.\nCore / Next / Later로 우선순위를 구분합니다.",
      },
      {
        t: "UX / UI DESIGN",
        d: "화면 단위가 아니라 사용자 목표 달성 경로를 설계합니다.\n실제 제품 인터페이스를 만듭니다.",
      },
      {
        t: "PRODUCT BUILD",
        d: "Web 또는 App MVP를 구현합니다.\n데모가 아닌 동작하는 제품을 만듭니다.",
      },
      {
        t: "BACKEND & DATA",
        d: "로그인, 저장, 조회 등 검증에 필요한 최소 서버·데이터 구조를 포함합니다.\n실제 사용 시나리오를 지원합니다.",
      },
      {
        t: "INTEGRATIONS",
        d: "결제, 알림, API, 외부 서비스 등 MVP에 필요한 연동을 구현합니다.\n범위 내에서만 포함합니다.",
      },
      {
        t: "QA & LAUNCH",
        d: "핵심 시나리오를 검수하고 실제 환경에 배포합니다.\n팀·초기 사용자에게 공유할 수 있게 합니다.",
      },
      {
        t: "NEXT-STEP ROADMAP",
        d: "MVP 이후 확장·보류·폐기 항목을 정리합니다.\n검증 결과를 다음 BUILD 단계로 연결합니다.",
      },
    ],
    sourcesLabel: "PROJECT INPUTS",
    sourcesTitle: "프로젝트에 활용하는 정보와 자료를 조합합니다.",
    sourcesNote: "아이디어 단계, 준비된 자료, 팀 상황에 따라 실제 입력은 프로젝트마다 달라집니다.",
    sources: [
      "아이디어·문제 설명",
      "타깃 사용자 정의",
      "경쟁·참고 서비스",
      "기존 와이어·기획",
      "브랜드·UI 가이드",
      "기술·플랫폼 제약",
      "비즈니스 모델 가설",
      "검증 질문·KPI",
      "초기 콘텐츠·데이터",
      "API·연동 요구",
      "출시·배포 환경",
      "향후 확장 계획",
    ],
    useLabel: "USE CASES",
    useTitle: "이런 MVP를 만들 수 있습니다.",
    useBadge: "구축 가능 예시",
    useCases: [
      {
        t: "WEB MVP",
        d: "웹에서 바로 쓰는 핵심 플로우.\n가입·사용·전환까지 검증 가능한 첫 버전.",
      },
      {
        t: "MOBILE APP MVP",
        d: "모바일에서만 성립하는 습관·알림·현장 경험.\niOS·Android 첫 출시.",
      },
      {
        t: "INTERNAL TOOL MVP",
        d: "팀이 매일 쓰는 운영 도구의 첫 버전.\n속도와 정확도 우선.",
      },
      {
        t: "AI PRODUCT MVP",
        d: "반복 업무를 줄이는 AI 기능.\n모델보다 워크플로와 검증에 집중.",
      },
      {
        t: "CLICKABLE PROTOTYPE",
        d: "투자·팀 설득용 클릭 가능한 시연.\n빠르게, 선명하게.",
      },
      {
        t: "LANDING + PRODUCT",
        d: "설득용 랜딩과 실제 제품 진입을 한 흐름으로.\n전환과 사용을 함께 검증.",
      },
      {
        t: "SAAS MVP",
        d: "구독·권한·관리 기능을 포함한 SaaS 첫 버전.\n핵심 가치 흐름 중심.",
      },
      {
        t: "MARKETPLACE MVP",
        d: "다중 사용자·역할이 있는 플랫폼형 첫 버전.\n목록·매칭·기본 관리 포함.",
      },
    ],
    flowLabel: "EXAMPLE WORKFLOW",
    flowTitle: "IDEA → BUILD → LAUNCH",
    flow: [
      {
        n: "01",
        t: "IDEA",
        d: "아이디어와 해결하려는 문제를 정리합니다.\n검증 질문과 성공 기준을 함께 정의합니다.",
        examples: ["문제", "사용자", "가설", "KPI"],
      },
      {
        n: "02",
        t: "SCOPE",
        d: "첫 버전에 필요한 핵심 기능을 결정합니다.\n넣을 것과 빼야 할 것을 명확히 구분합니다.",
        examples: ["Core", "Next", "Later", "플랫폼"],
      },
      {
        n: "03",
        t: "DESIGN",
        d: "사용자의 핵심 흐름과 인터페이스를 설계합니다.\n화면 구조와 UX를 확정합니다.",
        examples: ["플로우", "UI", "화면", "Review"],
      },
      {
        n: "04",
        t: "BUILD",
        d: "작동하는 제품을 개발합니다.\n핵심 기능·백엔드·연동을 구현합니다.",
        examples: ["Frontend", "Backend", "API", "QA"],
      },
      {
        n: "05",
        t: "LAUNCH",
        d: "테스트 후 실제 환경에 배포합니다.\n다음 단계 로드맵을 함께 전달합니다.",
        examples: ["Deploy", "Share", "Feedback", "Roadmap"],
      },
    ],
    reportLabel: "OUTPUT",
    reportTitle: "결과물은 실제 검증 가능한 제품과 문서로 전달합니다.",
    reportLead: "프로젝트 범위에 따라 구성은 달라집니다. 아래는 자주 포함되는 항목 예시입니다.",
    reportMockStatus: "제품 · 범위",
    reportMockK: "MVP Scope Spec",
    reportMockT: "기능·플로우·마일스톤 요약",
    reportItems: [
      "Problem & Goals",
      "Scope Summary",
      "User Flow Map",
      "Feature List (Core / Next / Later)",
      "UX / UI Overview",
      "Technical Stack",
      "Backend & Data Model",
      "Integration Notes",
      "QA Checklist",
      "Post-MVP Roadmap",
    ],
    dashTitle: "한 화면에서 MVP 범위와 진행 상태를 공유할 수 있습니다.",
    dashLead: "기능·화면·플로우·연동을 함께 정리해 범위 합의와 개발 논의가 빨라집니다.",
    dashNote: "기능 구성과 우선순위는 검증 목표와 예산에 따라 달라집니다.",
    dashMetrics: ["Features", "Screens", "Flows", "Integrations"],
    dashFilters: ["전체", "Core", "Next", "Later"],
    aiLabel: "ACCELERATION",
    aiTitle: "반복 업무는 자동화하고,\n설계·구현에 집중합니다.",
    aiLead:
      "요구 정리, 플로우 초안, 화면 목록, QA 체크리스트 등 반복 작업은 AI 보조로 속도를 높이고, 범위 결정·UX·핵심 구현에는 사람이 집중합니다.",
    aiExamples: [
      "아이디어·요구사항 구조화",
      "플로우·화면 목록 초안",
      "기능 우선순위 정리",
      "API·데이터 모델 초안",
      "QA·테스트 체크리스트",
      "Post-MVP 로드맵 초안",
    ],
    aiNote: "최종 범위·설계·품질 판단은 프로젝트 팀과 함께 확정합니다.",
    delLabel: "DELIVERABLES",
    delTitle: "프로젝트 완료 후 제공되는 것",
    delLead: "범위에 따라 아래 항목 중 필요한 결과물을 제공합니다.",
    deliverables: [
      { title: "Scope Definition Document", body: "MVP에 넣을 것과 빼는 것을 문서화합니다." },
      { title: "UX Flow / Screen Structure", body: "핵심 사용자 흐름과 화면 구조를 정리합니다." },
      { title: "Working MVP (Web or App)", body: "실제로 동작하는 첫 버전을 구현합니다." },
      { title: "Essential Backend & Data", body: "필수 데이터와 백엔드 기반을 구성합니다." },
      { title: "Deployed Environment", body: "스테이징·프로덕션에 배포된 환경을 제공합니다." },
      { title: "UX / UI Design Files", body: "디자인 파일과 주요 화면 스펙을 전달합니다." },
      { title: "Technical Documentation", body: "구조·연동·운영에 필요한 기술 문서를 남깁니다." },
      { title: "QA Report", body: "핵심 시나리오 점검 결과를 정리합니다." },
      { title: "Post-MVP Roadmap", body: "출시 이후 개선·확장 우선순위를 제안합니다." },
    ],
    processLabel: "PROCESS",
    processTitle: "아이디어에서 출시까지.",
    process: [
      {
        n: "01",
        t: "DISCOVERY",
        d: "아이디어, 문제, 사용자, 제약을 확인합니다.\n검증 질문과 성공 기준을 함께 정의합니다.",
        examples: ["아이디어", "문제", "사용자", "KPI"],
      },
      {
        n: "02",
        t: "SCOPE",
        d: "MVP에 넣을 핵심 기능과 빼야 할 기능을 결정합니다.\n플랫폼·일정·예산을 합의합니다.",
        examples: ["Core", "Next", "Later", "플랫폼"],
      },
      {
        n: "03",
        t: "UX / DESIGN",
        d: "핵심 흐름과 화면 구조를 설계합니다.\n실제 제품 인터페이스를 확정합니다.",
        examples: ["플로우", "UI", "화면", "Review"],
      },
      {
        n: "04",
        t: "DEVELOPMENT",
        d: "프론트·백엔드·연동을 구현합니다.\n단계별 데모와 검수를 진행합니다.",
        examples: ["Frontend", "Backend", "API", "Integrations"],
      },
      {
        n: "05",
        t: "TEST",
        d: "핵심 시나리오를 검수합니다.\n실제 사용 흐름 기준으로 확인합니다.",
        examples: ["QA", "UAT", "Fixes", "Sign-off"],
      },
      {
        n: "06",
        t: "LAUNCH",
        d: "배포 환경을 준비하고 릴리스합니다.\n팀·초기 사용자에게 공유합니다.",
        examples: ["Staging", "Prod", "Access", "Share"],
      },
      {
        n: "07",
        t: "NEXT STEPS",
        d: "검증 결과와 확장 우선순위를 정리합니다.\n다음 BUILD 단계를 연결합니다.",
        examples: ["Feedback", "Roadmap", "Expand", "Pivot"],
      },
    ],
    scopeLabel: "SCOPE LEVELS",
    scopeTitle: "MVP 복잡도를 이해하기 위한 구분입니다.",
    scopeLead: "고정 패키지가 아닙니다. 검증 목표, 플랫폼, 기능·연동 범위에 맞춰 범위를 정합니다.",
    scopes: [
      {
        t: "FOCUSED MVP",
        items: [
          "단일 핵심 흐름",
          "Web 또는 App 중 하나",
          "핵심 화면 5–8개",
          "기본 백엔드·데이터",
          "배포·공유 환경",
        ],
      },
      {
        t: "STANDARD MVP",
        items: [
          "복수 핵심 기능·플로우",
          "Web 또는 App + Admin",
          "로그인·권한·저장",
          "1–2개 연동",
          "Post-MVP 로드맵",
        ],
      },
      {
        t: "EXTENDED MVP",
        items: [
          "복수 모듈·역할",
          "다중 연동·API",
          "AI·결제·알림 포함",
          "확장 설계 포함",
          "별도 협의 범위",
        ],
      },
    ],
    timeLabel: "TIMELINE",
    timeTitle: "범위에 따라 일정이 달라집니다.",
    timeLead: "기능 수, 플랫폼, 연동, 디자인 깊이, 피드백 속도에 따라 기간이 달라질 수 있습니다.",
    timelines: [
      { t: "Focused MVP", d: "약 3–4주" },
      { t: "Standard MVP", d: "약 4–6주" },
      { t: "Extended", d: "별도 협의" },
    ],
    priceLabel: "PROJECT COST",
    priceTitle: "필요한 범위만 견적합니다.",
    priceName: "MVP DEVELOPMENT",
    priceValue: "₩1,000,000부터",
    priceFactorsLabel: "가격 결정 요소",
    priceFactors: [
      "Scope — 기능·화면·플로우 범위",
      "Platform — Web / App / Both",
      "Complexity — 데이터·권한·로직",
      "Timeline — 일정·리소스",
      "Integration — API·결제·알림",
      "Design depth — UX/UI 범위",
      "Backend — 서버·DB·인증",
      "Post-launch — 확장·유지",
    ],
    priceNote: "플랫폼, Scope, Complexity, Timeline을 검토한 뒤 견적을 제공합니다. 최종 금액은 범위 확정 후 안내합니다.",
    faqLabel: "FAQ",
    faqTitle: "자주 묻는 질문",
    faqs: [
      {
        q: "기획서가 없어도 시작할 수 있나요?",
        a: "가능합니다. 아이디어와 해결하고 싶은 문제만 있어도 범위를 함께 정리할 수 있습니다.",
      },
      {
        q: "웹과 앱 중 무엇을 만들까요?",
        a: "검증 목표와 사용자 환경에 맞춰 제안합니다. 처음부터 둘 다 만들지는 않습니다.",
      },
      {
        q: "기간은 얼마나 걸리나요?",
        a: "범위에 따라 다릅니다. Focused MVP는 약 3–4주, Standard MVP는 약 4–6주가 일반적입니다.",
      },
      {
        q: "견적은 바로 알 수 있나요?",
        a: "기능 범위와 플랫폼에 따라 달라집니다. ₩1,000,000부터 시작하며, 검토 후 정확한 견적을 안내합니다.",
      },
      {
        q: "MVP 이후 확장도 가능한가요?",
        a: "가능합니다. MVP에서 검증된 흐름을 기준으로 기능을 확장하거나 개선할 수 있습니다.",
      },
      {
        q: "RESEARCH와 함께 진행할 수 있나요?",
        a: "가능합니다. 시장·경쟁·사용자 리서치 결과를 MVP 범위와 기능 우선순위에 연결할 수 있습니다.",
      },
      {
        q: "기밀 유지는 어떻게 하나요?",
        a: "협의된 범위 내에서만 자료를 사용합니다. NDA가 필요하면 체결 후 진행합니다.",
      },
    ],
    finalLabel: "START A PROJECT",
    finalTitle: "아이디어를\n첫 번째 제품으로.",
    finalLead:
      "만들고 싶은 서비스와 현재 단계만 알려주셔도 됩니다. MVP 범위와 IDEA → BUILD → LAUNCH 흐름을 함께 확인합니다.",
    ctaFinalSecondary: "BUILD 전체 보기 →",
    ctaFinalSecondaryHref: "../build/",
  },
  en: {
    seoTitle: "MVP DEVELOPMENT | Newon Business",
    metaDescription:
      "Turn an idea into a real product you can validate quickly — from problem framing through UX, build, and launch. Newon MVP DEVELOPMENT.",
    crumbBusiness: "BUSINESS",
    crumbServices: "SERVICES",
    crumbBuild: "BUILD",
    crumbHere: "MVP",
    eyebrow: "MVP DEVELOPMENT",
    subEyebrow: "BUILD",
    headline: "From idea to\na working product.",
    lead: "From idea validation and core feature definition through UX/UI, development, testing, and release — we design the first version so you can put it in front of real users quickly. One continuous path from planning to deploy: IDEA → BUILD → LAUNCH.",
    ctaPrimary: "MVP development inquiry →",
    ctaSecondary: "See the build flow ↓",
    meta: [
      { k: "SERVICE", v: "MVP Development" },
      { k: "BEST FOR", v: "Idea validation & first release" },
      { k: "TIMELINE", v: "Usually 3–6 weeks" },
      { k: "PRICE", v: "₩1,000,000부터" },
    ],
    overviewLabel: "OVERVIEW",
    overviewTitle: "You have the idea.\nNot the product shape.",
    overviewBody: [
      "The idea is clear, but what to build first — and how much — often is not. More features delay launch; a demo alone cannot validate the real question.",
      "An MVP must be minimal, but it must be a working product. Not slides — something users can click, type into, and complete the core job on web or app.",
      "MVP DEVELOPMENT starts by defining the problem and validation question. Then we design UX/UI around the core flow only, and deliver a shippable first version including backend, data, and deploy.",
    ],
    problemsLabel: "PROBLEMS",
    problemsTitle: "Helpful when you face these situations.",
    problems: [
      {
        n: "01",
        t: "IDEA ONLY",
        d: "You have an idea but cannot decide what to build first.\nYou need the smallest product structure that can test the real question.",
      },
      {
        n: "02",
        t: "SCOPE CREEP",
        d: "Building everything first is risky.\nFeature lists keep growing and launch keeps slipping.",
      },
      {
        n: "03",
        t: "DISCONNECTED BUILD",
        d: "Planning, design, and development feel like separate vendors.\nOutput stays at demo level with no one owning the full path.",
      },
      {
        n: "04",
        t: "NO VALIDATION PATH",
        d: "You built something but have no environment to show users.\nNo deploy, share, or feedback loop.",
      },
      {
        n: "05",
        t: "PLATFORM UNCERTAINTY",
        d: "Hard to choose between web and app.\nYou need a recommendation matched to validation goals.",
      },
      {
        n: "06",
        t: "POST-MVP GAP",
        d: "After launch, no priority for what to expand.\nYou need structure to connect validation to next steps.",
      },
    ],
    baLabel: "BEFORE / AFTER",
    baTitle: "Demo-level output vs\na product you can validate",
    beforeLabel: "BEFORE",
    afterLabel: "AFTER",
    before: [
      "Idea and feature list with no clear scope",
      "Planning, design, and build disconnected",
      "Slides and mockups — nothing to click",
      "No deploy environment or next-step plan",
    ],
    after: [
      "Problem, users, and validation question defined first",
      "Core-flow UX/UI and agreed scope",
      "Working web or app MVP people can use",
      "Deploy environment and post-MVP roadmap delivered",
    ],
    capsLabel: "CAPABILITIES",
    capsTitle: "We run MVP build\nas one structured engagement.",
    caps: [
      {
        t: "PROBLEM FRAMING",
        d: "Define problem, primary users, and validation question.\nClarify what belongs in the MVP — and what does not.",
      },
      {
        t: "SCOPE DEFINITION",
        d: "Keep only what the first version needs.\nSeparate Core, Next, and Later priorities.",
      },
      {
        t: "UX / UI DESIGN",
        d: "Design around the user goal path — not random screens.\nBuild the actual product interface.",
      },
      {
        t: "PRODUCT BUILD",
        d: "Implement a web or app MVP.\nA working product, not a presentation.",
      },
      {
        t: "BACKEND & DATA",
        d: "Include minimal server and data structure for validation.\nLogin, save, read — whatever the scenario requires.",
      },
      {
        t: "INTEGRATIONS",
        d: "Implement payments, notifications, APIs, external services as scoped.\nOnly what the MVP needs.",
      },
      {
        t: "QA & LAUNCH",
        d: "Verify core scenarios and deploy to a real environment.\nReady to share with team or early users.",
      },
      {
        t: "NEXT-STEP ROADMAP",
        d: "Document expand, hold, or cut items after MVP.\nConnect validation results to the next BUILD phase.",
      },
    ],
    sourcesLabel: "PROJECT INPUTS",
    sourcesTitle: "We combine the inputs your project needs.",
    sourcesNote: "Actual inputs vary by idea stage, available material, and team context.",
    sources: [
      "Idea and problem description",
      "Target user definition",
      "Competitor and reference services",
      "Existing wireframes or specs",
      "Brand and UI guidelines",
      "Technical and platform constraints",
      "Business model hypothesis",
      "Validation questions and KPIs",
      "Initial content and data",
      "API and integration requirements",
      "Launch and deploy environment",
      "Future expansion plans",
    ],
    useLabel: "USE CASES",
    useTitle: "MVPs we can build.",
    useBadge: "Example build types",
    useCases: [
      {
        t: "WEB MVP",
        d: "Core flow usable in the browser.\nSignup to value — a first version you can validate.",
      },
      {
        t: "MOBILE APP MVP",
        d: "Habits, alerts, and on-the-go use that only make sense on mobile.\nFirst iOS or Android release.",
      },
      {
        t: "INTERNAL TOOL MVP",
        d: "First version of daily ops software for your team.\nSpeed and accuracy first.",
      },
      {
        t: "AI PRODUCT MVP",
        d: "AI that cuts repeat work.\nWorkflow and validation over model theater.",
      },
      {
        t: "CLICKABLE PROTOTYPE",
        d: "A clickable demo for investors and teams — fast and sharp.",
      },
      {
        t: "LANDING + PRODUCT",
        d: "Persuasion and product entry in one continuous path.\nValidate conversion and usage together.",
      },
      {
        t: "SAAS MVP",
        d: "First SaaS version with subscription, permissions, admin.\nCore value flow centered.",
      },
      {
        t: "MARKETPLACE MVP",
        d: "First platform version with multiple users and roles.\nListing, matching, basic admin included.",
      },
    ],
    flowLabel: "EXAMPLE WORKFLOW",
    flowTitle: "IDEA → BUILD → LAUNCH",
    flow: [
      {
        n: "01",
        t: "IDEA",
        d: "Organize the idea and problem to solve.\nDefine validation questions and success criteria together.",
        examples: ["Problem", "Users", "Hypothesis", "KPIs"],
      },
      {
        n: "02",
        t: "SCOPE",
        d: "Decide core features for the first version.\nClearly separate in-scope from out-of-scope.",
        examples: ["Core", "Next", "Later", "Platform"],
      },
      {
        n: "03",
        t: "DESIGN",
        d: "Design core user flows and interface.\nConfirm screen structure and UX.",
        examples: ["Flows", "UI", "Screens", "Review"],
      },
      {
        n: "04",
        t: "BUILD",
        d: "Develop a working product.\nImplement core features, backend, and integrations.",
        examples: ["Frontend", "Backend", "API", "QA"],
      },
      {
        n: "05",
        t: "LAUNCH",
        d: "Test and deploy to a real environment.\nDeliver next-step roadmap together.",
        examples: ["Deploy", "Share", "Feedback", "Roadmap"],
      },
    ],
    reportLabel: "OUTPUT",
    reportTitle: "Deliverables are a product you can validate and supporting docs.",
    reportLead: "Composition varies by project scope. Below are common items.",
    reportMockStatus: "PRODUCT · SCOPE",
    reportMockK: "MVP SCOPE SPEC",
    reportMockT: "Features, flows, milestones",
    reportItems: [
      "Problem & Goals",
      "Scope Summary",
      "User Flow Map",
      "Feature List (Core / Next / Later)",
      "UX / UI Overview",
      "Technical Stack",
      "Backend & Data Model",
      "Integration Notes",
      "QA Checklist",
      "Post-MVP Roadmap",
    ],
    dashTitle: "Share MVP scope and progress in one view.",
    dashLead: "Features, screens, flows, and integrations together speed scope agreement and build discussions.",
    dashNote: "Feature composition and priority vary by validation goal and budget.",
    dashMetrics: ["Features", "Screens", "Flows", "Integrations"],
    dashFilters: ["All", "Core", "Next", "Later"],
    aiLabel: "ACCELERATION",
    aiTitle: "Automate repetition.\nFocus on design and build.",
    aiLead:
      "Requirement structuring, flow drafts, screen lists, and QA checklists can be AI-assisted for speed — while people focus on scope decisions, UX, and core implementation.",
    aiExamples: [
      "Structure ideas and requirements",
      "Draft flows and screen lists",
      "Organize feature priority",
      "Draft API and data models",
      "QA and test checklists",
      "Post-MVP roadmap drafts",
    ],
    aiNote: "Final scope, design, and quality decisions are confirmed with your project team.",
    delLabel: "DELIVERABLES",
    delTitle: "What you receive when the project completes",
    delLead: "We deliver the items below as needed for your scope.",
    deliverables: [
      { title: "Scope Definition Document", body: "What ships in the MVP — and what stays out." },
      { title: "UX Flow / Screen Structure", body: "Core user flows and screen structure." },
      { title: "Working MVP (Web or App)", body: "A first version that actually runs." },
      { title: "Essential Backend & Data", body: "Essential data and backend foundations." },
      { title: "Deployed Environment", body: "Staging and production environments ready to use." },
      { title: "UX / UI Design Files", body: "Design files and key screen specs." },
      { title: "Technical Documentation", body: "Structure, integrations, and ops notes." },
      { title: "QA Report", body: "Results from core scenario checks." },
      { title: "Post-MVP Roadmap", body: "Priorities for improvement after launch." },
    ],
    processLabel: "PROCESS",
    processTitle: "From idea to launch.",
    process: [
      {
        n: "01",
        t: "DISCOVERY",
        d: "Confirm idea, problem, users, and constraints.\nDefine validation questions and success criteria.",
        examples: ["Idea", "Problem", "Users", "KPIs"],
      },
      {
        n: "02",
        t: "SCOPE",
        d: "Decide core features in and out of the MVP.\nAgree platform, timeline, and budget.",
        examples: ["Core", "Next", "Later", "Platform"],
      },
      {
        n: "03",
        t: "UX / DESIGN",
        d: "Design core flows and screen structure.\nConfirm the actual product interface.",
        examples: ["Flows", "UI", "Screens", "Review"],
      },
      {
        n: "04",
        t: "DEVELOPMENT",
        d: "Implement frontend, backend, and integrations.\nDemo and review in phases.",
        examples: ["Frontend", "Backend", "API", "Integrations"],
      },
      {
        n: "05",
        t: "TEST",
        d: "Verify core scenarios.\nCheck against real usage flows.",
        examples: ["QA", "UAT", "Fixes", "Sign-off"],
      },
      {
        n: "06",
        t: "LAUNCH",
        d: "Prepare deploy environment and release.\nShare with team or early users.",
        examples: ["Staging", "Prod", "Access", "Share"],
      },
      {
        n: "07",
        t: "NEXT STEPS",
        d: "Organize validation results and expansion priority.\nConnect to the next BUILD phase.",
        examples: ["Feedback", "Roadmap", "Expand", "Pivot"],
      },
    ],
    scopeLabel: "SCOPE LEVELS",
    scopeTitle: "How to think about MVP complexity.",
    scopeLead: "Not a fixed package. Scope is set by validation goal, platform, and feature/integration range.",
    scopes: [
      {
        t: "FOCUSED MVP",
        items: [
          "Single core flow",
          "Web or app — one platform",
          "5–8 core screens",
          "Basic backend and data",
          "Deploy and share environment",
        ],
      },
      {
        t: "STANDARD MVP",
        items: [
          "Multiple core features and flows",
          "Web or app + admin",
          "Login, permissions, save",
          "1–2 integrations",
          "Post-MVP roadmap",
        ],
      },
      {
        t: "EXTENDED MVP",
        items: [
          "Multiple modules and roles",
          "Multi-integration and API",
          "AI, payments, notifications",
          "Expansion design included",
          "Scoped separately",
        ],
      },
    ],
    timeLabel: "TIMELINE",
    timeTitle: "Timeline depends on scope.",
    timeLead: "Duration varies by feature count, platform, integrations, design depth, and feedback speed.",
    timelines: [
      { t: "Focused MVP", d: "About 3–4 weeks" },
      { t: "Standard MVP", d: "About 4–6 weeks" },
      { t: "Extended", d: "Scoped separately" },
    ],
    priceLabel: "PROJECT COST",
    priceTitle: "We quote only the scope you need.",
    priceName: "MVP DEVELOPMENT",
    priceValue: "₩1,000,000부터",
    priceFactorsLabel: "Pricing factors",
    priceFactors: [
      "Scope — features, screens, flows",
      "Platform — web, app, or both",
      "Complexity — data, permissions, logic",
      "Timeline — schedule and resourcing",
      "Integration — API, payments, alerts",
      "Design depth — UX/UI range",
      "Backend — server, DB, auth",
      "Post-launch — expansion, maintenance",
    ],
    priceNote: "We review platform, scope, complexity, and timeline, then provide a quote. Final amount is confirmed after scope lock.",
    faqLabel: "FAQ",
    faqTitle: "Frequently asked questions",
    faqs: [
      {
        q: "Can we start without a full plan?",
        a: "Yes. An idea and the problem you want to solve are enough to shape scope together.",
      },
      {
        q: "Web or app — which one?",
        a: "We recommend based on your validation goal and users. We do not build both by default.",
      },
      {
        q: "How long does it take?",
        a: "It depends on scope. Focused MVP is typically about 3–4 weeks; Standard MVP about 4–6 weeks.",
      },
      {
        q: "Can I get a fixed price on the website?",
        a: "Pricing depends on platform and scope. Starting from ₩1,000,000 — we guide you after reviewing the inquiry.",
      },
      {
        q: "Can we expand after the MVP?",
        a: "Yes. We extend from the flows that already proved useful.",
      },
      {
        q: "Can this connect to RESEARCH?",
        a: "Yes. Market, competitor, and user research can feed MVP scope and feature priority.",
      },
      {
        q: "How is confidentiality handled?",
        a: "Materials are used only within agreed scope. NDA available when required.",
      },
    ],
    finalLabel: "START A PROJECT",
    finalTitle: "Turn your idea\ninto a first product.",
    finalLead:
      "Tell us the service you want to build and your current stage. We will confirm MVP scope and the IDEA → BUILD → LAUNCH path together.",
    ctaFinalSecondary: "View all BUILD →",
    ctaFinalSecondaryHref: "../build/",
  },
};

export function getMvpCopy(lang) {
  return resolveKoEnPack(MVP_COPY, lang, "mvp-copy");
}
