/** My World page copy — merged into locales/*.json by apply-myworld-locales.mjs */

export const mwKo = {
  brandAria: "My World 상단으로",
  globalReachBadge: "Travel journal · Worldwide service",
  badge: "🗺️ 여행 기록 · 여행 지도 · AI 리포트",
  h1: "My World",
  subtitleHtml: `<span class="ox-accent">세상 모든 여행을<br />기록하세요</span>`,
  heroReachSummary:
    "방문한 나라와 도시를 기록하고, 여행 일정과 사진을 관리하며, AI 여행 리포트와 다양한 여행 통계를 확인할 수 있는 올인원 여행 기록 플랫폼입니다.",
  heroLogoAlt: "My World 앱 로고: 지구본",
  introLabel: "브랜드",
  introTitle: "왜 My World인가",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>My World</strong>는</p><p>여행을 기록하고 추억을 관리하는 올인원 여행 플랫폼입니다.</p><p>방문 국가와 도시를 세계 지도에서 시각적으로 확인할 수 있으며,</p><p>여행 일정, 사진, 메모, AI 여행 리포트, 여행 통계를 한 곳에서 관리할 수 있습니다.</p><p>여행을 많이 할수록 나만의 세계지도가 완성됩니다.</p>',
  introClosing: "오늘의 여행이 평생의 추억이 됩니다.",
  showcaseCollageAria: "My World 앱 미리보기 7장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt: "My World — 세상 모든 여행을 기록하다",
  imgShot2Alt: "My World — 방문 국가와 도시 지도",
  imgShot3Alt: "My World — 이동 경로 지도",
  imgShot4Alt: "My World — AI 여행 리포트",
  imgShot5Alt: "My World — 도시·지역 방문 기록",
  imgShot6Alt: "My World — 커뮤니티",
  imgShot7Alt: "My World — 여행 계획·컬렉션",
  reviewsLabel: "후기",
  reviewsTitle: "사용자 이야기",
  review1Emoji: "👩🏼",
  review1Quote: "여행했던 나라를 지도로 보는 재미가 있어요.",
  review1Meta: "대학생 · 24세",
  review2Emoji: "👨🏻",
  review2Quote: "AI 리포트가 여행을 다시 돌아보게 해줘요.",
  review2Meta: "직장인 · 31세",
  review3Emoji: "👩🏻",
  review3Quote: "여행 일정과 기록을 한 앱에서 관리해서 편해요.",
  review3Meta: "여행 크리에이터 · 27세",
  review4Emoji: "👨🏽",
  review4Quote: "방문 국가를 하나씩 채우는 재미가 있습니다.",
  review4Meta: "회사원 · 35세",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "여행 지도",
  feat1Lead: "방문한 국가와 도시를 세계 지도에서 확인하세요.",
  feat1Note: "국가·도시별 방문 현황을 자동으로 기록합니다.",
  feat2Title: "방문 국가",
  feat2Lead: "방문 국가, 도시, 지역을 체계적으로 관리합니다.",
  feat2Note: "여행 목표도 함께 설정하세요.",
  feat3Title: "여행 일정",
  feat3Lead: "여행 계획부터 완료된 일정까지 한 번에 관리합니다.",
  feat3Note: "캘린더로 확인하세요.",
  feat4Title: "여행 기록",
  feat4Lead: "사진, 메모, 여행 노트를 함께 저장합니다.",
  feat4Note: "추억을 오래 보관하세요.",
  feat5Title: "여행 통계",
  feat5Lead: "방문 국가 수, 여행일, 비행 횟수, 거리, 대륙 달성률 등을 제공합니다.",
  feat5Note: "여행 데이터를 한눈에 확인하세요.",
  feat6Title: "AI 여행 리포트",
  feat6Lead: "AI가 여행 패턴을 분석하고 여행 스타일, 추천 여행지, 여행 요약을 제공합니다.",
  feat6Note: "여행을 더 깊게 돌아보세요.",
  feat7Title: "여행 목표",
  feat7Lead: "올해 방문하고 싶은 국가와 여행 목표를 설정하세요.",
  feat7Note: "목표를 채울수록 세계지도가 완성됩니다.",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 여행 추가",
  how1P: "여행을 생성하세요.",
  how2Title: "2️⃣ 일정 작성",
  how2P: "국가와 도시를 선택하고 일정을 입력하세요.",
  how3Title: "3️⃣ 여행 기록",
  how3P: "사진, 메모, 방문 장소를 기록하세요.",
  how4Title: "4️⃣ 지도 확인",
  how4P: "방문한 국가를 세계 지도에서 확인하세요.",
  how5Title: "5️⃣ AI 리포트",
  how5P: "AI가 여행을 분석합니다.",
  how6Title: "6️⃣ 통계 보기",
  how6P: "여행 데이터를 그래프로 확인하세요.",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "AI·통계·지도로<br />더 깊은 여행 기록",
  premFeatHeading: "프리미엄 기능",
  prem1Title: "무제한 여행",
  prem1Lead: "제한 없이 모든 여행을",
  prem1Note: "기록하세요.",
  prem2Title: "고급 통계",
  prem2Lead: "방문 국가, 도시, 대륙, 여행 거리,",
  prem2Note: "여행일, 비행 횟수 등을 제공합니다.",
  prem3Title: "AI 여행 코치",
  prem3Lead: "여행 스타일 분석, 추천 여행,",
  prem3Note: "여행 인사이트를 제공합니다.",
  prem4Title: "AI 여행 리포트",
  prem4Lead: "여행이 끝나면",
  prem4Note: "자동 리포트를 생성합니다.",
  prem5Title: "여행 히트맵",
  prem5Lead: "가장 많이 방문한 지역을",
  prem5Note: "시각화합니다.",
  prem6Title: "클라우드 백업",
  prem6Lead: "모든 여행을",
  prem6Note: "안전하게 동기화합니다.",
  prem7Title: "PDF 내보내기",
  prem7Lead: "여행 기록을",
  prem7Note: "PDF로 저장합니다.",
  prem8Title: "광고 제거",
  prem8Lead: "광고 없이",
  prem8Note: "쾌적하게 이용하세요.",
  recoTitle: "이런 분들에게 추천",
  reco1: "여행을 자주 다니는 분",
  reco2: "방문 국가를 기록하고 싶은 분",
  reco3: "세계지도를 채우고 싶은 분",
  reco4: "여행 일정을 체계적으로 관리하고 싶은 분",
  reco5: "AI 여행 리포트를 받아보고 싶은 분",
  reco6: "여행 통계를 보고 싶은 분",
  reco7: "여행 사진과 메모를 함께 보관하고 싶은 분",
  premHiKicker: "작은 여행부터",
  premHiLine: "여행이 인생의 추억이 됩니다.",
  premHiSub: "My World가 당신의<br />모든 여행을 기록합니다.",
  closingHtml:
    `<p>기록된 순간이<br /><span class="ox-accent">평생의 여행이 됩니다.</span></p><p>My World는 단순한 여행 기록 앱이 아니라<br />여행의 모든 순간을 관리하는 공간입니다.</p><p>오늘의 여행이 모여<br /><span class="ox-accent">나만의 세계지도가 완성됩니다.</span></p>`,
  closingAria: "마무리 문구",
  footerRights: "© My World ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY 소개",
  drawerBl: "BabyLog 소개",
  drawerPl: "PetLog 소개",
  drawerPu: "PiggyUp 소개",
  drawerGu: "GoalUp 소개",
  drawerCu: "CountUp 소개",
  drawerNp: "Newon 소개",
  drawerMw: "My World · 이 화면",
  appStoreUrl: "https://newon.app",
  googlePlayUrl: "https://newon.app",
  appStoreBadgeAria: "App Store에서 My World(새 탭)",
  googlePlayBadgeAria: "Google Play에서 My World(새 탭)",
  deleteAccountLink: "계정 삭제",
};

export const mwEn = {
  brandAria: "Back to top of My World",
  globalReachBadge: "177 countries · 13 languages supported",
  badge: "🗺️ Travel journal · Travel map · AI report",
  h1: "My World",
  subtitleHtml: `<span class="ox-accent">Record every journey<br />around the world</span>`,
  heroReachSummary:
    "An all-in-one travel journal to log countries and cities, manage itineraries and photos, and explore AI travel reports and stats.",
  heroLogoAlt: "My World app logo: globe",
  introLabel: "Brand",
  introTitle: "Why My World",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>My World</strong> is</p><p>an all-in-one travel platform to record trips and keep memories.</p><p>See visited countries and cities on a world map,</p><p>and manage itineraries, photos, notes, AI travel reports, and travel stats in one place.</p><p>The more you travel, the more your personal world map comes to life.</p>',
  introClosing: "Today's trip becomes a lifelong memory.",
  showcaseCollageAria: "Seven My World app previews. Scroll horizontally to view all.",
  imgShot1Alt: "My World — Capture every journey",
  imgShot2Alt: "My World — Visited countries and cities map",
  imgShot3Alt: "My World — Travel route map",
  imgShot4Alt: "My World — AI travel report",
  imgShot5Alt: "My World — City and region visit records",
  imgShot6Alt: "My World — Community",
  imgShot7Alt: "My World — Travel plans and collections",
  reviewsLabel: "Reviews",
  reviewsTitle: "User stories",
  review1Emoji: "👩🏼",
  review1Quote: "It's fun seeing the countries I've visited on a map.",
  review1Meta: "Student · 24",
  review2Emoji: "👨🏻",
  review2Quote: "The AI report helps me look back on each trip.",
  review2Meta: "Office worker · 31",
  review3Emoji: "👩🏻",
  review3Quote: "Managing itineraries and journals in one app is so convenient.",
  review3Meta: "Travel creator · 27",
  review4Emoji: "👨🏽",
  review4Quote: "Filling in visited countries one by one is addictive.",
  review4Meta: "Office worker · 35",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Travel map",
  feat1Lead: "See visited countries and cities on a world map.",
  feat1Note: "Visit status by country and city is logged automatically.",
  feat2Title: "Visited countries",
  feat2Lead: "Organize countries, cities, and regions systematically.",
  feat2Note: "Set travel goals along the way.",
  feat3Title: "Trip itinerary",
  feat3Lead: "Manage plans and completed trips in one place.",
  feat3Note: "Check everything on a calendar.",
  feat4Title: "Travel journal",
  feat4Lead: "Save photos, notes, and travel memos together.",
  feat4Note: "Keep memories for the long run.",
  feat5Title: "Travel stats",
  feat5Lead: "Countries visited, travel days, flights, distance, continent progress, and more.",
  feat5Note: "See your travel data at a glance.",
  feat6Title: "AI travel report",
  feat6Lead: "AI analyzes patterns and shares travel style, recommendations, and summaries.",
  feat6Note: "Reflect on trips more deeply.",
  feat7Title: "Travel goals",
  feat7Lead: "Set countries and travel goals you want to hit this year.",
  feat7Note: "Fill goals and complete your world map.",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Add a trip",
  how1P: "Create a new trip.",
  how2Title: "2️⃣ Build the itinerary",
  how2P: "Pick countries and cities, then enter your schedule.",
  how3Title: "3️⃣ Journal the trip",
  how3P: "Log photos, notes, and places you visited.",
  how4Title: "4️⃣ Check the map",
  how4P: "See visited countries on the world map.",
  how5Title: "5️⃣ AI report",
  how5P: "Let AI analyze your travels.",
  how6Title: "6️⃣ View stats",
  how6P: "Explore travel data in charts.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "Deeper travel journals<br />with AI, stats, and maps",
  premFeatHeading: "Premium features",
  prem1Title: "Unlimited trips",
  prem1Lead: "Record every trip",
  prem1Note: "with no limits.",
  prem2Title: "Advanced stats",
  prem2Lead: "Countries, cities, continents, distance,",
  prem2Note: "travel days, flights, and more.",
  prem3Title: "AI travel coach",
  prem3Lead: "Travel style analysis, recommendations,",
  prem3Note: "and travel insights.",
  prem4Title: "AI travel report",
  prem4Lead: "When a trip ends,",
  prem4Note: "auto-generate a report.",
  prem5Title: "Travel heatmap",
  prem5Lead: "Visualize the regions",
  prem5Note: "you visit most.",
  prem6Title: "Cloud backup",
  prem6Lead: "Sync every trip",
  prem6Note: "safely across devices.",
  prem7Title: "Export PDF",
  prem7Lead: "Save travel journals",
  prem7Note: "as PDF files.",
  prem8Title: "Remove ads",
  prem8Lead: "Enjoy a clean experience",
  prem8Note: "with no ads.",
  recoTitle: "Great if you…",
  reco1: "Travel often",
  reco2: "Want to log visited countries",
  reco3: "Want to fill in a world map",
  reco4: "Want organized trip itineraries",
  reco5: "Want AI travel reports",
  reco6: "Want travel statistics",
  reco7: "Want photos and notes kept together",
  premHiKicker: "From small trips",
  premHiLine: "Travel becomes life’s memories.",
  premHiSub: "My World records<br />every journey you take.",
  closingHtml:
    `<p>Recorded moments become<br /><span class="ox-accent">lifelong travels.</span></p><p>My World isn’t just a travel log—<br />it’s a space to manage every moment of the journey.</p><p>Today’s trips gather until<br /><span class="ox-accent">your own world map is complete.</span></p>`,
  closingAria: "Closing message",
  footerRights: "© My World ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "Open SAVY intro",
  drawerBl: "Open BabyLog intro",
  drawerPl: "Open PetLog intro",
  drawerPu: "Open PiggyUp intro",
  drawerGu: "Open GoalUp intro",
  drawerCu: "Open CountUp intro",
  drawerNp: "Open Newon intro",
  drawerMw: "My World · this screen",
  appStoreUrl: "https://newon.app",
  googlePlayUrl: "https://newon.app",
  appStoreBadgeAria: "My World on the App Store (opens in a new tab)",
  googlePlayBadgeAria: "My World on Google Play (opens in a new tab)",
  deleteAccountLink: "Delete account",
};

/** Portuguese (Brazil) showcase alt text — merged into locales/pt-br.json mw */
export const mwPtBrShowcase = {
  showcaseCollageAria: "7 prévias do app My World. Role horizontalmente para ver todas.",
  imgShot1Alt: "My World — Registre cada viagem",
  imgShot2Alt: "My World — Mapa de países e cidades visitados",
  imgShot3Alt: "My World — Mapa de rotas de viagem",
  imgShot4Alt: "My World — Relatório de viagem com IA",
  imgShot5Alt: "My World — Registros de visitas por cidade e região",
  imgShot6Alt: "My World — Comunidade",
  imgShot7Alt: "My World — Planos de viagem e coleções",
};

/** Spanish showcase alt text — merged into locales/es.json mw */
export const mwEsShowcase = {
  showcaseCollageAria: "7 vistas previas de la app My World. Desliza horizontalmente para verlas todas.",
  imgShot1Alt: "My World — Registra cada viaje",
  imgShot2Alt: "My World — Mapa de países y ciudades visitados",
  imgShot3Alt: "My World — Mapa de rutas de viaje",
  imgShot4Alt: "My World — Informe de viaje con IA",
  imgShot5Alt: "My World — Registros de visitas por ciudad y región",
  imgShot6Alt: "My World — Comunidad",
  imgShot7Alt: "My World — Planes de viaje y colecciones",
};

/** Japanese showcase alt text — merged into locales/ja.json mw */
export const mwJaShowcase = {
  showcaseCollageAria: "My Worldアプリのプレビュー7枚。横にスクロールしてすべて表示できます。",
  imgShot1Alt: "My World — すべての旅を記録しよう",
  imgShot2Alt: "My World — 訪れた国と都市の地図",
  imgShot3Alt: "My World — 移動ルートマップ",
  imgShot4Alt: "My World — AI旅行レポート",
  imgShot5Alt: "My World — 都市・地域の訪問記録",
  imgShot6Alt: "My World — コミュニティ",
  imgShot7Alt: "My World — 旅行計画・コレクション",
};
