/** Noting page copy — merged into locales by apply-noting-locales.mjs */

export const ntKo = {
  brandAria: "Noting 상단으로",
  globalReachBadge: "173개국 출시 · 13개 언어 지원",
  badge: "📚 필사 기록 · 독서 노트 · 명언 저장",
  h1: "NOTING",
  subtitleHtml: "좋은 문장을 오래 기억하세요",
  heroReachSummary:
    "책을 읽으며 마음에 남은 문장과 생각을 기록하고 정리할 수 있는 필사 플랫폼입니다. 좋은 문장을 단순히 저장하는 것을 넘어 다시 읽고, 다시 생각하고, 삶에 적용할 수 있도록 도와줍니다. 필사 기록, 독서 노트, 책별 정리, 태그 관리까지 하나의 공간에서 경험해보세요.",
  heroLogoAlt: "Noting 앱 로고: 연필 아이콘",
  webReleaseLabel: "Web 서비스 제공",
  webCtaBtn: "웹으로 시작하기",
  webCtaAria: "Noting 웹 서비스 시작 (새 탭)",
  webUrl: "https://noting.app",
  introLabel: "앱 소개",
  introTitle: "앱 소개",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>Noting</strong>은 단순한 메모 앱이 아닙니다.</p><p>책 속 문장과 나의 생각을 함께 기록하고 관리할 수 있는 필사 중심 독서 플랫폼입니다.</p><p>읽고 끝나는 독서가 아닌, 기억하고 성장하는 독서를 만들 수 있도록 설계되었습니다.</p><p>좋은 문장을 저장하고, 생각을 기록하고, 시간이 지나 다시 꺼내보며 나만의 지식 아카이브를 만들어보세요.</p><p>작은 문장 하나가 인생을 바꿀 수 있습니다.</p>',
  introClosing: "좋은 문장은 기록될 때 더 오래 남습니다.",
  showcaseCollageAria: "Noting 앱 미리보기 6장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt: "Noting — 필사 기록 화면",
  imgShot2Alt: "Noting — 책별 정리",
  imgShot3Alt: "Noting — 태그 관리",
  imgShot4Alt: "Noting — 독서 노트",
  imgShot5Alt: "Noting — 검색",
  imgShot6Alt: "Noting — 오늘의 문장",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "필사 기록",
  feat1Lead: "책을 읽으며 마음에 드는 문장을 저장할 수 있습니다.",
  feat1Note: "책 제목과 페이지를 함께 기록할 수 있습니다.",
  feat2Title: "책별 정리",
  feat2Lead: "저장한 필사를 책별로 정리하고 관리할 수 있습니다.",
  feat2Note: "읽은 책의 핵심 내용을 한눈에 확인할 수 있습니다.",
  feat3Title: "태그 관리",
  feat3Lead: "습관, 성장, 경제, 사업 등 원하는 태그로 정리할 수 있습니다.",
  feat3Note: "필요한 문장을 빠르게 찾을 수 있습니다.",
  feat4Title: "강력한 검색",
  feat4Lead: "기록한 모든 문장과 메모를 검색할 수 있습니다.",
  feat4Note: "수백 개의 필사도 쉽게 찾을 수 있습니다.",
  feat5Title: "독서 노트",
  feat5Lead: "필사와 함께 나만의 생각을 기록할 수 있습니다.",
  feat5Note: "문장을 단순 저장하지 않고 내 것으로 만들 수 있습니다.",
  feat6Title: "다양한 글씨체",
  feat6Lead: "취향에 맞는 글씨체를 선택해 감성적인 필사 경험을 제공합니다.",
  feat6Note: "더 편안하게 읽고 기록할 수 있습니다.",
  feat7Title: "오늘의 문장",
  feat7Lead: "저장한 필사 중 하나를 랜덤으로 다시 보여줍니다.",
  feat7Note: "좋은 문장을 반복해서 기억할 수 있습니다.",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 책 등록",
  how1P: "읽고 있는 책을 추가하세요.",
  how2Title: "2️⃣ 문장 저장",
  how2P: "마음에 드는 문장을 기록하세요.",
  how3Title: "3️⃣ 태그 선택",
  how3P: "주제에 맞는 태그를 지정하세요.",
  how4Title: "4️⃣ 생각 작성",
  how4P: "문장에 대한 나의 생각을 기록하세요.",
  how5Title: "5️⃣ 다시 읽기",
  how5P: "저장한 문장을 언제든 꺼내보세요.",
  how6Title: "6️⃣ 성장 기록",
  how6P: "독서와 함께 쌓인 생각을 확인하세요.",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "더 깊이 있는 독서 경험을 제공합니다.",
  premFeatHeading: "🔒 프리미엄 기능",
  prem1Title: "🤖 AI 독서 요약",
  prem1Lead: "필사와 메모를 기반으로 핵심 내용을 요약합니다.",
  prem1Note: "",
  prem2Title: "📊 독서 통계",
  prem2Lead: "월별 독서량과 필사 기록을 분석합니다.",
  prem2Note: "",
  prem3Title: "☁️ 클라우드 백업",
  prem3Lead: "모든 기록을 안전하게 저장하고 동기화합니다.",
  prem3Note: "",
  prem4Title: "🎨 프리미엄 글씨체",
  prem4Lead: "다양한 감성 글꼴을 사용할 수 있습니다.",
  prem4Note: "",
  prem5Title: "📄 PDF 내보내기",
  prem5Lead: "필사 노트를 PDF로 저장할 수 있습니다.",
  prem5Note: "",
  recoTitle: "이런 분들에게 추천",
  reco1: "독서를 꾸준히 기록하고 싶은 분",
  reco2: "좋은 문장을 오래 기억하고 싶은 분",
  reco3: "필사를 좋아하는 분",
  reco4: "독서 노트를 체계적으로 관리하고 싶은 분",
  reco5: "자기계발 책을 자주 읽는 분",
  reco6: "생각을 글로 정리하는 습관을 만들고 싶은 분",
  reco7: "책을 읽고도 금방 잊어버리는 분",
  premHiKicker: "읽고 끝나는 독서가 아닌",
  premHiLine: "기록하고 성장하는 독서",
  premHiSub: "좋은 문장이 삶의 자산이 됩니다.",
  closingHtml:
    "<p><strong>NOTING</strong>과 함께<br />좋은 문장을 모으고<br />생각을 기록하세요.</p>",
  closingCtaBtn: "지금 시작하기",
  closingAria: "마무리 문구",
  footerRights: "© Noting ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY 소개",
  drawerBl: "BabyLog 소개",
  drawerPl: "PetLog 소개",
  drawerPu: "PiggyUp 소개",
  drawerNt: "Noting · 이 화면",
  mobileBabylogHint: "BabyLog 소개 보기",
  mobilePetlogHint: "PetLog 소개 보기",
};

export const ntEn = {
  brandAria: "Back to top of Noting",
  globalReachBadge: "173 countries · 13 languages supported",
  badge: "📚 Transcription · reading notes · quotes",
  h1: "NOTING",
  subtitleHtml: "Remember good sentences longer",
  heroReachSummary:
    "A transcription platform to capture and organize sentences and thoughts from your reading. Go beyond saving lines—revisit them, reflect, and apply them to life. Transcription logs, reading notes, books, and tags—all in one place.",
  heroLogoAlt: "Noting app logo: pencil icon",
  webReleaseLabel: "Available on the web",
  webCtaBtn: "Start on the web",
  webCtaAria: "Start Noting on the web (opens in a new tab)",
  webUrl: "https://noting.app",
  introLabel: "About the app",
  introTitle: "About the app",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>Noting</strong> is not a simple memo app.</p><p>It is a transcription-first reading platform to record and manage book quotes alongside your own thoughts.</p><p>Designed for reading you remember and grow from—not reading you finish and forget.</p><p>Save good lines, write your thoughts, and revisit them over time to build your personal knowledge archive.</p><p>One small sentence can change your life.</p>',
  introClosing: "Good sentences last longer when they are written down.",
  showcaseCollageAria: "Six Noting preview screens. Scroll horizontally to view all.",
  imgShot1Alt: "Noting — transcription log",
  imgShot2Alt: "Noting — organize by book",
  imgShot3Alt: "Noting — tag management",
  imgShot4Alt: "Noting — reading notes",
  imgShot5Alt: "Noting — search",
  imgShot6Alt: "Noting — quote of the day",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Transcription log",
  feat1Lead: "Save sentences that resonate while you read.",
  feat1Note: "Record the book title and page together.",
  feat2Title: "By book",
  feat2Lead: "Organize and manage transcriptions by book.",
  feat2Note: "See each book’s highlights at a glance.",
  feat3Title: "Tags",
  feat3Lead: "Sort by habits, growth, business, and more.",
  feat3Note: "Find the line you need quickly.",
  feat4Title: "Powerful search",
  feat4Lead: "Search every saved line and note.",
  feat4Note: "Find hundreds of entries with ease.",
  feat5Title: "Reading notes",
  feat5Lead: "Write your thoughts alongside transcriptions.",
  feat5Note: "Make each quote truly yours.",
  feat6Title: "Font choices",
  feat6Lead: "Pick fonts that match your taste for a calmer writing feel.",
  feat6Note: "Read and record more comfortably.",
  feat7Title: "Quote of the day",
  feat7Lead: "Revisit a random saved line.",
  feat7Note: "Remember good sentences through repetition.",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Add a book",
  how1P: "Add the book you are reading.",
  how2Title: "2️⃣ Save a line",
  how2P: "Record a sentence you love.",
  how3Title: "3️⃣ Choose tags",
  how3P: "Tag it by topic.",
  how4Title: "4️⃣ Write thoughts",
  how4P: "Add your reflection on the line.",
  how5Title: "5️⃣ Revisit",
  how5P: "Open saved lines anytime.",
  how6Title: "6️⃣ Track growth",
  how6P: "See how your reading thoughts accumulate.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "A deeper reading experience.",
  premFeatHeading: "🔒 Premium features",
  prem1Title: "🤖 AI reading summary",
  prem1Lead: "Summarize key ideas from your transcriptions and notes.",
  prem1Note: "",
  prem2Title: "📊 Reading stats",
  prem2Lead: "Analyze monthly reading and transcription activity.",
  prem2Note: "",
  prem3Title: "☁️ Cloud backup",
  prem3Lead: "Store and sync all your records safely.",
  prem3Note: "",
  prem4Title: "🎨 Premium fonts",
  prem4Lead: "Use a wider set of expressive typefaces.",
  prem4Note: "",
  prem5Title: "📄 PDF export",
  prem5Lead: "Export transcription notes as PDF.",
  prem5Note: "",
  recoTitle: "Great if you…",
  reco1: "Want to keep a steady reading log",
  reco2: "Want to remember good sentences longer",
  reco3: "Enjoy transcription",
  reco4: "Want structured reading notes",
  reco5: "Read self-development books often",
  reco6: "Want a habit of writing your thoughts",
  reco7: "Forget books soon after finishing them",
  premHiKicker: "Not reading that ends on the last page",
  premHiLine: "Reading you record and grow from",
  premHiSub: "Good sentences become life assets.",
  closingHtml:
    "<p>With <strong>NOTING</strong>,<br />collect good sentences<br />and record your thoughts.</p>",
  closingCtaBtn: "Start now",
  closingAria: "Closing message",
  footerRights: "© Noting ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "Open SAVY intro",
  drawerBl: "Open BabyLog intro",
  drawerPl: "Open PetLog intro",
  drawerPu: "Open PiggyUp intro",
  drawerNt: "Noting · this screen",
  mobileBabylogHint: "Open BabyLog intro",
  mobilePetlogHint: "Open PetLog intro",
};
