/** PetLog page copy — merged by apply-petlog-locales.mjs */

export const plKo = {
  brandAria: "PetLog 상단으로",
  globalReachBadge: "One app for everyday life with pets",
  badge: "🐾 반려동물 기록 · 건강 관리 · 가족 공유 · AI 분석",
  h1: "PetLog",
  subtitleHtml:
    `<span class="ox-accent">반려동물의 모든 순간을<br />하나의 이야기로 기록하세요</span>`,
  heroReachSummary:
    "반려동물의 일상·건강·추억을 쌓고, 가족과 함께 성장 아카이브를 만들어가는 디지털 라이프북입니다.",
  heroLogoAlt: "PetLog 앱 로고 아이콘",
  showcaseCollageAria:
    "PetLog 앱 스크린샷 7장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt:
    "PetLog — AI와 함께 더 스마트한 반려 생활, 우리 아이의 모든 순간을 PetLog에",
  imgShot2Alt:
    "PetLog — 하루의 모든 반려 기록을 한곳에, 기록과 루틴 관리",
  imgShot3Alt:
    "PetLog 일정 및 건강 — 우리 아이의 건강과 일정을 한눈에",
  imgShot4Alt:
    "PetLog 커뮤니티 — 반려인들과 실시간 이야기와 정보 공유",
  imgShot5Alt:
    "PetLog 미디어·기록 보관 — 사진과 활동 로그 한곳에서",
  imgShot6Alt:
    "PetLog 빠른 기록 — 식사·산책·건강 기록 빠르게 입력",
  imgShot7Alt:
    "PetLog 프리미엄 — 건강 분석과 맞춤 인사이트",
  introLabel: "브랜드",
  introTitle: "왜 PetLog인가",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>반려동물의 모든 순간을 하나의 이야기로 기록하세요</strong></p><p><strong>PetLog</strong>는 반려동물의 일상부터 건강, 성장 과정과 추억까지 하나의 공간에서 기록하고 관리할 수 있는 올인원 반려생활 플랫폼입니다.</p><p>식사와 산책, 체중과 건강 기록, 예방접종과 병원 일정, 사진과 추억까지 모든 순간을 체계적으로 보관할 수 있습니다.</p><p>PetLog는 단순한 기록 앱이 아닙니다. 반려동물의 생활 데이터를 축적하고 건강 변화를 이해하며 더 나은 반려생활을 돕는 AI 기반 라이프 파트너입니다.</p><p>오늘의 작은 기록은 우리 아이의 건강한 내일을 만듭니다.</p>',
  introClosing:
    "반려동물의 하루를 기록하고 평생의 추억을 만들어보세요.",  reviewsTitle: "사용자 이야기",  review1Quote: "반려동물의 하루를 기록하는 게 작은 추억 상자 같아요.",  review2Emoji: "👨🏻",  review2Meta: "보호자 · 34세",  review3Quote: "우리 아이와 보낸 시간을 더 오래 기억할 수 있게 됐어요.",  review4Emoji: "👨🏽",  review4Meta: "카페 운영자 · 41세",
  reviewsLabel: "후기",
  reviewsTitle: "사용자 이야기",
  review1Emoji: "👩🏻",
  review1Quote: "반려동물의 하루를 기록하는 게 작은 추억 상자 같아요.",
  review1Meta: "일러스트레이터 · 27세",
  review2Emoji: "👨🏻",
  review2Quote: "병원 기록부터 산책까지 모두 한곳에 모여 있어서 편합니다.",
  review2Meta: "보호자 · 34세",
  review3Emoji: "👩🏼",
  review3Quote: "우리 아이와 보낸 시간을 더 오래 기억할 수 있게 됐어요.",
  review3Meta: "사진작가 · 30세",
  review4Emoji: "👨🏽",
  review4Quote: "반려동물의 성장 과정이 한 권의 일기처럼 남습니다.",
  review4Meta: "카페 운영자 · 41세",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "식사 기록",
  feat1Lead: "사료, 간식, 급수량,",
  feat1Note: "영양 정보를 기록합니다.",
  feat2Title: "산책 기록",
  feat2Lead: "산책 시간, 거리, 활동량,",
  feat2Note: "운동 패턴을 관리합니다.",
  feat3Title: "건강 기록",
  feat3Lead: "예방접종, 병원 방문, 복약 기록,",
  feat3Note: "검사 결과와 건강 이력을 저장합니다.",
  feat4Title: "일정 관리",
  feat4Lead: "병원 예약, 예방접종 일정,",
  feat4Note: "미용·정기 검진 일정을 관리합니다.",
  feat5Title: "통계 분석",
  feat5Lead: "생활 패턴, 체중 변화, 건강 추이,",
  feat5Note: "활동량 데이터를 확인할 수 있습니다.",
  feat6Title: "가족 공유",
  feat6Lead: "가족 구성원과 함께",
  feat6Note: "반려동물의 기록을 공유합니다.",
  feat7Title: "커뮤니티",
  feat7Lead: "반려인 정보 공유, 경험 나눔,",
  feat7Note: "질문과 답변, 반려 이야기 공유.",
  feat8Title: "AI 건강 분석",
  feat8Lead: "생활 패턴·활동성 분석,",
  feat8Note: "건강 변화 감지와 AI 인사이트를 제공합니다.",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 반려동물 등록",
  how1P: "프로필과 기본 정보를 입력하세요.",
  how2Title: "2️⃣ 일상 기록",
  how2P: "식사, 산책, 활동, 건강 정보를 기록하세요.",
  how3Title: "3️⃣ 건강 관리",
  how3P: "예방접종, 병원 방문, 복약 기록을 관리하세요.",
  how4Title: "4️⃣ 일정 등록",
  how4P: "검진 일정, 미용 예약, 예방접종 일정을 추가하세요.",
  how5Title: "5️⃣ 통계 확인",
  how5P: "생활 패턴과 건강 흐름을 분석하세요.",
  how6Title: "6️⃣ 가족 공유",
  how6P: "가족과 함께 기록을 관리하세요.",
  how7Title: "7️⃣ AI 분석",
  how7P: "AI 건강 인사이트를 확인하세요.",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "AI와 데이터로<br />더 똑똑한 반려생활",
  premFeatHeading: "프리미엄 기능",
  prem1Title: "AI 건강 코치",
  prem1Lead: "건강 패턴 분석, 행동 분석,",
  prem1Note: "맞춤 인사이트를 제공합니다.",
  prem2Title: "AI 패턴 분석",
  prem2Lead: "생활·활동·건강 변화를",
  prem2Note: "AI로 깊이 분석합니다.",
  prem3Title: "무제한 사진 보관",
  prem3Lead: "사진 아카이브, 앨범 생성,",
  prem3Note: "추억을 안전하게 저장합니다.",
  prem4Title: "고급 통계",
  prem4Lead: "7일, 30일, 90일,",
  prem4Note: "연간 데이터 분석을 확인합니다.",
  prem5Title: "백업 및 동기화",
  prem5Lead: "클라우드 백업, 다중 기기 동기화,",
  prem5Note: "안전한 데이터 보관을 지원합니다.",
  prem6Title: "PDF 리포트",
  prem6Lead: "건강 리포트 생성, 추억 앨범 제작,",
  prem6Note: "성장 아카이브를 보관합니다.",
  prem7Title: "가족 프리미엄 공유",
  prem7Lead: "보호자 공동 관리, 가족 계정 연동,",
  prem7Note: "프리미엄 공유를 지원합니다.",
  prem8Title: "광고 제거",
  prem8Lead: "광고 없이",
  prem8Note: "반려동물 기록에 집중하세요.",
  recoTitle: "이런 분들에게 추천",
  reco1: "🐶 반려동물의 모든 기록을 한곳에 관리하고 싶은 분",
  reco2: "👨‍👩‍👩‍👧 가족과 함께 반려생활을 공유하고 싶은 분",
  reco3: "🩺 건강 데이터를 꾸준히 관리하고 싶은 보호자",
  reco4: "📅 예방접종과 병원 일정을 놓치고 싶지 않은 분",
  reco5: "📸 사진과 추억을 오래 보관하고 싶은 분",
  reco6: "🤖 AI 분석으로 생활 패턴을 이해하고 싶은 분",
  reco7: "📄 PDF 리포트와 성장 앨범을 만들고 싶은 분",
  premHiKicker: "반려생활의 매 순간을",
  premHiLine: "기록하고, 건강한 반려생활을 만들어가세요.",
  premHiSub: "PetLog가 당신과 반려동물의<br />일상을 더 풍성하게 만듭니다.",
  closingHtml:
    `<p>함께한 하루가<br /><span class="ox-accent">소중한 추억이 됩니다</span></p><p>PetLog는 반려동물을 관리하는 앱이 아니라<br />함께한 순간을 기록하는 공간입니다.</p><p>사랑하는 가족과의 시간을<br /><span class="ox-accent">더 오래 기억해보세요.</span></p>`,
  closingAria: "마무리 문구",
  footerRights: "© PetLog ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY 소개",
  drawerBl: "BabyLog 소개 보기",
  drawerPl: "PetLog · 이 화면",
  appStoreUrl: "https://apps.apple.com/kr/app/petlog-%EC%8A%A4%EB%A7%88%ED%8A%B8%ED%95%9C-ai-%EB%B0%98%EB%A0%A4-%EA%B8%B0%EB%A1%9D/id6770971033",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.petlog&pcampaignid=web_share",
  appStoreBadgeAria: "App Store에서 PetLog(새 탭)",
  googlePlayBadgeAria: "Google Play에서 PetLog(새 탭)",
};

export const plEn = {
  brandAria: "Back to top of PetLog",
  globalReachBadge: "One app for everyday life with pets",
  badge:
    "🐾 Pet logs · health · family sharing · AI analysis",
  h1: "PetLog",
  subtitleHtml:
    `<span class="ox-accent">Turn every pet moment into<br />one life story</span>`,
  heroReachSummary:
    "A digital lifebook for pets—daily life, health, and memories, built together as a family growth archive.",
  heroLogoAlt: "PetLog app logo icon",
  showcaseCollageAria:
    "Seven PetLog app screenshots. Scroll horizontally to view all.",
  imgShot1Alt:
    "PetLog — smarter pet life with AI; every moment with your pet in PetLog",
  imgShot2Alt:
    "PetLog — all feeding, walks, and daily logs together",
  imgShot3Alt:
    "PetLog schedules & health overview at a glance",
  imgShot4Alt:
    "PetLog community — share tips and stories with other pet parents",
  imgShot5Alt:
    "PetLog media vault — photos and activity history in one place",
  imgShot6Alt:
    "PetLog quick log — meals, walks, and health captured fast",
  imgShot7Alt:
    "PetLog Premium — health insights & personalized reports",
  introLabel: "Brand",
  introTitle: "Why PetLog",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>Turn every moment into one life story</strong></p><p><strong>PetLog</strong> is an all-in-one pet life platform—from daily routines and health to growth and memories—in one place.</p><p>Meals and walks, weight and health logs, vaccines and clinic schedules, photos and memories—keep every moment organized.</p><p>PetLog is not just a log. It is an AI life partner that builds data over time, helps you understand health changes, and supports better pet care.</p><p>Today\'s small entry shapes your pet\'s healthier tomorrow.</p>',
  introClosing:
    "Log each day and build a lifetime of memories.",  reviewsTitle: "User stories",  review1Quote: "Logging my pet's day feels like a little memory box.",  review2Emoji: "👨🏻",  review2Meta: "Pet parent · 34",  review3Quote: "I can hold on to time with our fur baby longer.",  review4Emoji: "👨🏽",  review4Meta: "Café owner · 41",
  reviewsLabel: "Reviews",
  reviewsTitle: "User stories",
  review1Emoji: "👩🏻",
  review1Quote: "Logging my pet's day feels like a little memory box.",
  review1Meta: "Illustrator · 27",
  review2Emoji: "👨🏻",
  review2Quote: "Vet visits to walks—everything in one place is so handy.",
  review2Meta: "Pet parent · 34",
  review3Emoji: "👩🏼",
  review3Quote: "I can hold on to time with our fur baby longer.",
  review3Meta: "Photographer · 30",
  review4Emoji: "👨🏽",
  review4Quote: "My pet's growth reads like a diary volume by volume.",
  review4Meta: "Café owner · 41",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Meal logs",
  feat1Lead: "Food, treats, water intake,",
  feat1Note: "and nutrition notes.",
  feat2Title: "Walk logs",
  feat2Lead: "Walk time, distance, activity,",
  feat2Note: "and exercise patterns.",
  feat3Title: "Health records",
  feat3Lead: "Vaccines, clinic visits, medications,",
  feat3Note: "test results, and health history.",
  feat4Title: "Scheduling",
  feat4Lead: "Clinic appointments, vaccination dates,",
  feat4Note: "grooming, and checkup schedules.",
  feat5Title: "Statistics",
  feat5Lead: "Daily patterns, weight trends, health flow,",
  feat5Note: "and activity data—visualized.",
  feat6Title: "Family sharing",
  feat6Lead: "Share records with family members",
  feat6Note: "and manage care together.",
  feat7Title: "Community",
  feat7Lead: "Share tips, swap experiences,",
  feat7Note: "Q&A, and pet life stories.",
  feat8Title: "AI health analysis",
  feat8Lead: "Routine and activity analysis,",
  feat8Note: "health change detection, and AI insights.",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Add your pet",
  how1P: "Create a profile with the essentials.",
  how2Title: "2️⃣ Log daily routines",
  how2P: "Record meals, walks, activity, and health notes.",
  how3Title: "3️⃣ Manage wellness",
  how3P: "Track vaccinations, clinic visits, and medications.",
  how4Title: "4️⃣ Plan schedules",
  how4P: "Add checkups, grooming, and vaccination dates.",
  how5Title: "5️⃣ Review statistics",
  how5P: "Analyze daily patterns and health trends.",
  how6Title: "6️⃣ Share with family",
  how6P: "Manage records together with family.",
  how7Title: "7️⃣ AI analysis",
  how7P: "Open AI-powered health insights.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "Smarter pet life<br />with AI and data",
  premFeatHeading: "Premium perks",
  prem1Title: "AI health coach",
  prem1Lead: "Health pattern and behavior analysis—",
  prem1Note: "with tailored insights.",
  prem2Title: "AI pattern analysis",
  prem2Lead: "Daily, activity, and health changes—",
  prem2Note: "analyzed deeply with AI.",
  prem3Title: "Unlimited photos",
  prem3Lead: "Photo archives, albums,",
  prem3Note: "and safe memory storage.",
  prem4Title: "Advanced statistics",
  prem4Lead: "7-, 30-, 90-day,",
  prem4Note: "and yearly data views.",
  prem5Title: "Backup & sync",
  prem5Lead: "Cloud backup, multi-device sync,",
  prem5Note: "and secure data storage.",
  prem6Title: "PDF reports",
  prem6Lead: "Health reports, memory albums,",
  prem6Note: "and growth archives.",
  prem7Title: "Family premium sharing",
  prem7Lead: "Shared caregiver access, family accounts,",
  prem7Note: "and one premium plan for all.",
  prem8Title: "Remove ads",
  prem8Lead: "No ads—",
  prem8Note: "focus on your pet's records.",
  recoTitle: "Great if you…",
  reco1: "🐶 Want every record in one organized place",
  reco2: "👨‍👩‍👩‍👧 Want to share pet life with family",
  reco3: "🩺 Want steady health data tracking",
  reco4: "📅 Never want to miss vaccines or clinics",
  reco5: "📸 Want to keep photos and memories for years",
  reco6: "🤖 Want AI help to understand patterns",
  reco7: "📄 Want PDF reports and growth albums",
  premHiKicker: "Every moment with your pet",
  premHiLine: "Log life—and build healthier pet care.",
  premHiSub: "PetLog enriches daily life<br />for you and your companion.",
  closingHtml:
    `<p>Days together<br /><span class="ox-accent">Become precious memories</span></p><p>PetLog isn't just pet management—<br />it's a space to record moments together.</p><p>Hold on to time with<br /><span class="ox-accent">the family you love.</span></p>`,
  closingAria: "Closing message",
  footerRights: "© PetLog ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "SAVY intro",
  drawerBl: "Open BabyLog intro",
  drawerPl: "PetLog · this screen",
  appStoreUrl: "https://apps.apple.com/kr/app/petlog-%EC%8A%A4%EB%A7%88%ED%8A%B8%ED%95%9C-ai-%EB%B0%98%EB%A0%A4-%EA%B8%B0%EB%A1%9D/id6770971033",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.petlog&pcampaignid=web_share",
  appStoreBadgeAria: "PetLog on the App Store (new tab)",
  googlePlayBadgeAria: "PetLog on Google Play (new tab)",
};

/** Japanese — localized showcase alts */
export const plJa = {
  ...plEn,
  brandAria: "PetLog の先頭へ",
  heroLogoAlt: "PetLog アプリのアイコン",
  showcaseCollageAria:
    "PetLog アプリのスクリーンショット7枚です。横スクロールでご覧ください。",
  imgShot1Alt:
    "PetLog — 食事・散歩・睡眠までひと目で管理、ペットの日常を簡単に記録",
  imgShot2Alt:
    "PetLog 記録 — よく使う記録をもっと素早く追加",
  imgShot3Alt:
    "PetLog カレンダー — ペットの予定をまとめて確認",
  imgShot4Alt:
    "PetLog コミュニティ — リアルタイムで情報共有",
  imgShot5Alt:
    "PetLog ペットノート — 写真とメモで大切な瞬間を記録",
  imgShot6Alt:
    "PetLog 記録を追加 — 数秒でペット記録を完了",
  imgShot7Alt:
    "PetLog プレミアム機能 — AI分析でペット生活をもっとスマートに",
  drawerBl: "BabyLog の紹介を開く",
  drawerPl: "PetLog · この画面",
};

/** Spanish */
export const plEs = {
  ...plEn,
  brandAria: "Volver arriba en PetLog",
  heroLogoAlt: "Ícono de PetLog",
  showcaseCollageAria:
    "Siete capturas de PetLog. Desplázate horizontalmente.",
  imgShot1Alt:
    "PetLog — Gestiona comidas, paseos y sueño de un vistazo; registra el día de tu mascota con facilidad",
  imgShot2Alt:
    "PetLog Registros — Agrega registros frecuentes más rápido",
  imgShot3Alt:
    "PetLog Calendario — Consulta el calendario de tu mascota fácilmente",
  imgShot4Alt:
    "PetLog Comunidad — Comparte información en tiempo real",
  imgShot5Alt:
    "PetLog — Guarda momentos especiales con fotos y notas",
  imgShot6Alt:
    "PetLog — Completa registros de tu mascota en segundos",
  imgShot7Alt:
    "PetLog Premium — Haz más inteligente el cuidado con IA",
  drawerBl: "Abrir BabyLog",
  drawerPl: "PetLog · esta pantalla",
  appStoreBadgeAria: "PetLog en App Store (nueva pestaña)",
  googlePlayBadgeAria: "PetLog en Google Play (nueva pestaña)",
};

/** pt-BR */
export const plPtBr = {
  ...plEn,
  brandAria: "Voltar ao topo do PetLog",
  heroLogoAlt: "Ícone do aplicativo PetLog",
  showcaseCollageAria:
    "Sete capturas do PetLog. Role horizontalmente.",
  imgShot1Alt:
    "PetLog — Gerencie refeições, passeios e sono rapidamente; registre o dia do seu pet com facilidade",
  imgShot2Alt:
    "PetLog Registros — Adicione registros frequentes ainda mais rápido",
  imgShot3Alt:
    "PetLog Calendário — Veja a agenda do seu pet em um só calendário",
  imgShot4Alt:
    "PetLog Comunidade — Compartilhe dicas em tempo real",
  imgShot5Alt:
    "PetLog — Registre momentos especiais com fotos e notas",
  imgShot6Alt:
    "PetLog Adicionar registro — Conclua registros do pet em segundos",
  imgShot7Alt:
    "PetLog Premium — Cuidados mais inteligentes com IA",
  drawerBl: "Abrir BabyLog",
  drawerPl: "PetLog · esta tela",
  appStoreBadgeAria: "PetLog na App Store (nova guia)",
  googlePlayBadgeAria: "PetLog no Google Play (nova guia)",
};
