/** PiggyUp page copy — merged into locales/*.json by apply-piggyup-locales.mjs */

export const puKo = {
  brandAria: "PiggyUp 상단으로",
  globalReachBadge: "173개국 출시 · 13개 언어 지원",
  badge: "💰 절약 습관 · 소비 분석 · AI 절약 코치",
  h1: "PiggyUp",
  subtitleHtml: "작은 절약이 모여 더 큰 변화를 만듭니다",
  heroReachSummary:
    "소비 기록부터 절약 분석, AI 인사이트까지 한 번에 관리하는 귀엽고 스마트한 절약 습관 앱입니다.",
  heroLogoAlt: "PiggyUp 앱 로고: 귀여운 핑크 돼지 저금통",
  introLabel: "앱 소개",
  introTitle: "앱 소개",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>PiggyUp</strong>는</p><p>복잡한 가계부 없이 소비를 기록하고 절약 습관을 자연스럽게 만들 수 있는 앱입니다.</p><p>매일의 소비 기록부터 AI 절약 분석까지, 돈 관리 스트레스를 줄이며 작은 절약의 성장을 경험할 수 있습니다.</p><p>귀여운 돼지 캐릭터와 함께 금융앱보다 가벼운 라이프스타일 절약 앱을 즐겨보세요.</p><p>작은 기록이 모이면 더 큰 변화가 시작됩니다.</p>',
  introClosing: "작은 절약이 더 나은 습관을 만듭니다.",
  showcaseCollageAria:
    "PiggyUp 앱 스크린샷 7장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt: "PiggyUp — 소비 대신 절약을 기록하는 새로운 방법",
  imgShot2Alt: "PiggyUp — 카테고리별 절약 데이터를 시각적으로 확인",
  imgShot3Alt: "PiggyUp — 절약 습관을 데이터로 확인해보세요",
  imgShot4Alt: "PiggyUp — 다양한 절약 챌린지에 함께 참여",
  imgShot5Alt: "PiggyUp — 쉽고 간단하고 빠르게 기록해보세요",
  imgShot6Alt: "PiggyUp — 작은 습관이 큰 절약으로 이어집니다",
  imgShot7Alt: "PiggyUp — AI 기반 고급 소비·절약 분석",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "소비 기록",
  feat1Lead: "오늘 사용한 금액을 간단하게 기록하고",
  feat1Note: "카테고리별 소비 흐름을 관리할 수 있습니다. 복잡한 입력 없이 빠르게 기록하며 절약 습관을 자연스럽게 만들 수 있습니다.",
  feat2Title: "절약 목표 관리",
  feat2Lead: "목표 금액과 절약 계획을 설정하고",
  feat2Note: "진행 상황을 한눈에 확인할 수 있습니다. 작은 절약도 꾸준히 모이면 큰 목표로 이어질 수 있습니다.",
  feat3Title: "절약 알림",
  feat3Lead: "반복 지출, 소비 위험, 기록 리마인드 등을",
  feat3Note: "알림으로 관리할 수 있습니다. 소비 습관을 놓치지 않도록 도와줍니다.",
  feat4Title: "소비 분석",
  feat4Lead: "카테고리별 소비 패턴과 월별 지출 흐름을",
  feat4Note: "분석할 수 있습니다. 어디에서 돈을 많이 쓰는지 쉽게 확인할 수 있습니다.",
  feat5Title: "통계 시각화",
  feat5Lead: "절약 금액, 소비 흐름, 목표 달성률을",
  feat5Note: "그래프로 보여줍니다. 복잡한 숫자도 직관적으로 확인 가능합니다.",
  feat6Title: "AI 절약 분석",
  feat6Lead: "AI가 소비 습관을 분석하고",
  feat6Note: "절약 포인트와 개선 방향을 알려줍니다. 더 효율적인 소비 습관 형성을 도와줍니다.",
  feat7Title: "목표 달성 추적",
  feat7Lead: "절약 목표 달성률과 성장 기록을",
  feat7Note: "확인할 수 있습니다. 작은 절약이 큰 변화로 이어지는 경험을 만들어보세요.",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 소비 기록",
  how1P: "오늘 사용한 금액과 카테고리를 입력하세요.",
  how2Title: "2️⃣ 절약 목표 설정",
  how2P: "목표 금액과 절약 계획을 설정하세요.",
  how3Title: "3️⃣ 소비 패턴 확인",
  how3P: "카테고리별 소비 흐름을 분석하세요.",
  how4Title: "4️⃣ AI 분석 확인",
  how4P: "AI 절약 리포트와 소비 인사이트를 확인하세요.",
  how5Title: "5️⃣ 절약 습관 만들기",
  how5P: "작은 기록을 꾸준히 이어가보세요.",
  how6Title: "6️⃣ 목표 달성하기",
  how6P: "절약 목표를 달성하며 성장 경험을 만들어보세요.",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "더 깊이 있는 분석과<br />더 스마트한 절약 경험을 제공합니다.",
  premFeatHeading: "프리미엄 기능",
  prem1Title: "고급 소비 분석",
  prem1Lead: "월별, 카테고리별, 반복 소비 패턴을",
  prem1Note: "더 자세히 분석합니다.",
  prem2Title: "AI 절약 리포트",
  prem2Lead: "사용자의 소비 흐름을 기반으로",
  prem2Note: "맞춤 절약 인사이트를 제공합니다.",
  prem3Title: "고급 알림",
  prem3Lead: "예산 초과, 반복 소비, 절약 목표 등을",
  prem3Note: "세밀하게 관리할 수 있습니다.",
  prem4Title: "상세 통계",
  prem4Lead: "소비와 절약 흐름을 더 다양한 방식으로",
  prem4Note: "확인할 수 있습니다.",
  prem5Title: "광고 제거",
  prem5Lead: "방해 없이 깔끔한 환경에서",
  prem5Note: "절약 관리에 집중할 수 있습니다.",
  recoTitle: "이런 분들에게 추천",
  reco1: "불필요한 소비를 줄이고 싶은 분",
  reco2: "돈이 어디로 사라지는지 궁금한 분",
  reco3: "절약 습관을 만들고 싶은 분",
  reco4: "귀엽고 쉬운 가계부 앱을 찾는 분",
  reco5: "AI 기반 소비 분석을 받고 싶은 분",
  reco6: "목표 기반 절약 관리를 하고 싶은 분",
  reco7: "더 체계적인 돈 관리 습관을 만들고 싶은 분",
  premHiKicker: "한 줄 강조 문구",
  premHiLine: "돈을 기록하고, 절약 습관을 만드는 경험",
  premHiSub: "작은 절약이 큰 변화를 만듭니다",
  closingHtml:
    "<p><strong>PiggyUp</strong>과 함께<br />더 귀엽고 똑똑한 절약 습관을 시작하세요.</p>",
  closingAria: "마무리 문구",
  footerRights: "© PiggyUp ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY 소개",
  drawerBl: "BabyLog 소개",
  drawerPl: "PetLog 소개",
  drawerPu: "PiggyUp · 이 화면",
  appStoreUrl: "https://apps.apple.com/kr/app/piggyup-ai-%EC%A0%88%EC%95%BD-%EA%B4%80%EB%A6%AC-%EC%B1%8C%EB%A6%B0%EC%A7%80/id6772744969",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.piggyup&pcampaignid=web_share",
  appStoreBadgeAria: "App Store에서 PiggyUp(새 탭)",
  googlePlayBadgeAria: "Google Play에서 PiggyUp(새 탭)",
};

export const puEn = {
  brandAria: "Back to top of PiggyUp",
  globalReachBadge: "173 countries · 13 languages supported",
  badge: "💰 Saving habits · spending analysis · AI savings coach",
  h1: "PiggyUp",
  subtitleHtml: "Small savings add up to bigger change",
  heroReachSummary:
    "A cute, smart savings app—track spending, analyze habits, and get AI insights in one place.",
  heroLogoAlt: "PiggyUp app logo: cute pink piggy bank",
  introLabel: "About the app",
  introTitle: "About the app",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>PiggyUp</strong> is</p><p>a lightweight savings app that helps you log spending and build saving habits—without a heavy ledger.</p><p>From daily logs to AI savings insights, it lowers money stress and turns small wins into growth.</p><p>With a friendly pig character, it feels more like a lifestyle savings companion than a stiff finance app.</p><p>Small entries add up to meaningful change.</p>',
  introClosing: "Small savings build better habits.",
  showcaseCollageAria:
    "Seven PiggyUp app screenshots. Scroll horizontally to view all.",
  imgShot1Alt: "PiggyUp — A new way to record savings instead of spending",
  imgShot2Alt: "PiggyUp — Visual savings data by category",
  imgShot3Alt: "PiggyUp — See your saving habits as data",
  imgShot4Alt: "PiggyUp — Join savings challenges together",
  imgShot5Alt: "PiggyUp — Record easily, simply, and fast",
  imgShot6Alt: "PiggyUp — Small habits lead to big savings",
  imgShot7Alt: "PiggyUp — AI-powered advanced spending and savings analysis",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Spending log",
  feat1Lead: "Record today’s spending in a few taps",
  feat1Note: "and manage category flow easily—fast input that builds natural saving habits.",
  feat2Title: "Savings goals",
  feat2Lead: "Set target amounts and savings plans",
  feat2Note: "and track progress at a glance. Small wins can grow into big goals.",
  feat3Title: "Savings alerts",
  feat3Lead: "Manage repeat spend, risk signals, and log reminders",
  feat3Note: "with notifications so you don’t lose track of habits.",
  feat4Title: "Spending analysis",
  feat4Lead: "Review category patterns and monthly outflow",
  feat4Note: "and see where money goes most clearly.",
  feat5Title: "Charts & stats",
  feat5Lead: "Visualize savings, spending flow, and goal progress",
  feat5Note: "so numbers feel intuitive, not overwhelming.",
  feat6Title: "AI savings insights",
  feat6Lead: "AI analyzes your habits",
  feat6Note: "and suggests savings points and better routines.",
  feat7Title: "Goal progress",
  feat7Lead: "Track goal completion and growth over time",
  feat7Note: "and turn small savings into a bigger story.",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Log spending",
  how1P: "Enter today’s amount and category.",
  how2Title: "2️⃣ Set savings goals",
  how2P: "Choose a target and savings plan.",
  how3Title: "3️⃣ Review patterns",
  how3P: "Check category spending flow.",
  how4Title: "4️⃣ Read AI insights",
  how4P: "Review AI savings reports and tips.",
  how5Title: "5️⃣ Build the habit",
  how5P: "Keep logging little by little.",
  how6Title: "6️⃣ Reach your goal",
  how6P: "Celebrate milestones as you grow.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "Deeper analysis and<br />a smarter savings experience",
  premFeatHeading: "Premium features",
  prem1Title: "Advanced spending analysis",
  prem1Lead: "Deeper views by month, category,",
  prem1Note: "and repeating spend patterns.",
  prem2Title: "AI savings reports",
  prem2Lead: "From your spending flow,",
  prem2Note: "get tailored savings insights.",
  prem3Title: "Richer notifications",
  prem3Lead: "Finer control for budgets, repeat spend,",
  prem3Note: "and savings goals.",
  prem4Title: "Detailed statistics",
  prem4Lead: "More ways to view spending",
  prem4Note: "and savings over time.",
  prem5Title: "Remove ads",
  prem5Lead: "Focus on savings",
  prem5Note: "without interruptions.",
  recoTitle: "Great if you…",
  reco1: "Want to cut unnecessary spending",
  reco2: "Wonder where your money goes",
  reco3: "Want to build saving habits",
  reco4: "Prefer a cute, easy money app",
  reco5: "Want AI-based spending analysis",
  reco6: "Like goal-based savings management",
  reco7: "Want a more structured money routine",
  premHiKicker: "In one line",
  premHiLine: "Record money—and build saving habits.",
  premHiSub: "Small savings make big change.",
  closingHtml:
    "<p>Start a cuter, smarter savings habit<br />with <strong>PiggyUp</strong>.</p>",
  closingAria: "Closing message",
  footerRights: "© PiggyUp ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "Open SAVY intro",
  drawerBl: "Open BabyLog intro",
  drawerPl: "Open PetLog intro",
  drawerPu: "PiggyUp · this screen",
  appStoreUrl: "https://apps.apple.com/kr/app/piggyup-ai-%EC%A0%88%EC%95%BD-%EA%B4%80%EB%A6%AC-%EC%B1%8C%EB%A6%B0%EC%A7%80/id6772744969",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.piggyup&pcampaignid=web_share",
  appStoreBadgeAria: "PiggyUp on the App Store (opens in a new tab)",
  googlePlayBadgeAria: "PiggyUp on Google Play (opens in a new tab)",
};
