/** PiggyUp page copy — merged into locales/*.json by apply-piggyup-locales.mjs */

export const puKo = {
  brandAria: "PiggyUp 상단으로",
  globalReachBadge: "From small savings · Worldwide service",
  badge: "💰 절약 습관 · 소비 분석 · AI 절약 코치",
  h1: "PiggyUp",
  subtitleHtml: `<span class="ox-accent">작은 절약이 모여 더 큰 변화를 만듭니다</span>`,
  heroReachSummary:
    "소비 기록부터 절약 목표, AI 분석까지. 매일의 지출을 가볍게 기록하고 돈이 새는 패턴을 발견하며 절약 습관을 만들어가는 앱입니다.",
  heroLogoAlt: "PiggyUp 앱 로고: 귀여운 핑크 돼지 저금통",
  introLabel: "브랜드",
  introTitle: "왜 PiggyUp인가",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>PiggyUp</strong>은</p><p>복잡한 가계부 없이 오늘의 소비를 간단히 기록하고 절약 목표를 자연스럽게 이어갈 수 있는 스마트 절약 습관 앱입니다.</p><p>우리는 돈 관리를 어렵게 만드는 대신, 매일의 작은 기록이 절약으로 이어지는 경험을 만듭니다.</p><p>소비를 기록하면 돈이 어디로 사라지는지 보이고, 절약 목표를 세우면 작은 실천이 쌓여 더 큰 변화가 됩니다.</p><p>귀여운 돼지 캐릭터와 함께 부담 없는 돈 관리 습관을 시작해보세요.</p>',
  introClosing: "작은 절약이 더 나은 소비 습관을 만듭니다.",
  showcaseCollageAria:
    "PiggyUp 앱 스크린샷 7장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt: "PiggyUp — 소비 대신 절약을 기록하는 새로운 방법",
  imgShot2Alt: "PiggyUp — 카테고리별 절약 데이터를 시각적으로 확인",
  imgShot3Alt: "PiggyUp — 절약 습관을 데이터로 확인해보세요",
  imgShot4Alt: "PiggyUp — 다양한 절약 챌린지에 함께 참여",
  imgShot5Alt: "PiggyUp — 쉽고 간단하고 빠르게 기록해보세요",
  imgShot6Alt: "PiggyUp — 작은 습관이 큰 절약으로 이어집니다",
  imgShot7Alt: "PiggyUp — AI 기반 고급 소비·절약 분석",  reviewsTitle: "사용자 이야기",  review1Quote: "절약을 게임처럼 만들었다는 게 정말 재밌어요.",  review2Emoji: "👨🏻",  review2Meta: "직장인 · 30세",  review3Quote: "작은 소비 습관들이 하나씩 바뀌기 시작했어요.",  review4Emoji: "👨🏽",  review4Meta: "자영업자 · 39세",
  reviewsLabel: "후기",
  reviewsTitle: "사용자 이야기",
  review1Emoji: "👩🏻",
  review1Quote: "절약을 게임처럼 만들었다는 게 정말 재밌어요.",
  review1Meta: "대학생 · 22세",
  review2Emoji: "👨🏻",
  review2Quote: "돈을 안 쓰는 게 아니라 더 현명하게 쓰게 됐습니다.",
  review2Meta: "직장인 · 30세",
  review3Emoji: "👩🏼",
  review3Quote: "작은 소비 습관들이 하나씩 바뀌기 시작했어요.",
  review3Meta: "승무원 · 29세",
  review4Emoji: "👨🏽",
  review4Quote: "절약이 스트레스가 아니라 성취처럼 느껴집니다.",
  review4Meta: "자영업자 · 39세",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "소비 기록",
  feat1Lead: "오늘 사용한 금액과 카테고리를 간단하게 기록할 수 있습니다.",
  feat1Note: "복잡한 입력 없이 매일의 소비 흐름을 빠르게 확인하세요.",
  feat2Title: "절약 목표 관리",
  feat2Lead: "목표 금액과 절약 계획을 설정하고 진행 상황을 한눈에 확인할 수 있습니다.",
  feat2Note: "작은 절약도 꾸준히 모이면 목표로 이어집니다.",
  feat3Title: "절약 알림",
  feat3Lead: "반복 지출, 소비 위험, 기록 리마인드를 알림으로 관리할 수 있습니다.",
  feat3Note: "소비 습관을 놓치지 않도록 도와줍니다.",
  feat4Title: "소비 분석",
  feat4Lead: "카테고리별 소비 패턴과 월별 지출 흐름을 분석합니다.",
  feat4Note: "어디에서 돈을 많이 쓰는지 쉽게 확인할 수 있습니다.",
  feat5Title: "통계 시각화",
  feat5Lead: "절약 금액, 소비 흐름, 목표 달성률을 그래프와 통계로 보여줍니다.",
  feat5Note: "복잡한 숫자도 직관적으로 이해할 수 있습니다.",
  feat6Title: "AI 절약 분석",
  feat6Lead: "AI가 소비 습관을 분석하고 절약 포인트와 개선 방향을 알려줍니다.",
  feat6Note: "더 효율적인 소비 습관 형성을 도와줍니다.",
  feat7Title: "목표 달성 추적",
  feat7Lead: "절약 목표 달성률과 성장 기록을 확인합니다.",
  feat7Note: "작은 절약이 큰 변화로 이어지는 과정을 눈에 보이게 만들어줍니다.",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 소비 기록",
  how1P: "오늘 사용한 금액과 카테고리를 입력하세요.",
  how2Title: "2️⃣ 절약 목표 설정",
  how2P: "모으고 싶은 금액과 절약 계획을 정하세요.",
  how3Title: "3️⃣ 소비 패턴 확인",
  how3P: "카테고리별 소비 흐름을 분석하세요.",
  how4Title: "4️⃣ AI 분석 확인",
  how4P: "AI 절약 리포트와 소비 인사이트를 확인하세요.",
  how5Title: "5️⃣ 절약 습관 만들기",
  how5P: "작은 기록을 꾸준히 이어가며 절약 루틴을 만들어보세요.",
  how6Title: "6️⃣ 목표 달성하기",
  how6P: "절약 목표를 달성하며 성장 경험을 만들어보세요.",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "절약·챌린지·AI로<br />더 스마트한 저축",
  premFeatHeading: "프리미엄 기능",
  prem1Title: "무제한 챌린지",
  prem1Lead: "개인 절약 챌린지를",
  prem1Note: "제한 없이 진행할 수 있습니다.",
  prem2Title: "공동 저축 모임",
  prem2Lead: "친구, 가족, 커플과 함께",
  prem2Note: "절약 목표를 공유하고 도전할 수 있습니다.",
  prem3Title: "AI 절약 코치",
  prem3Lead: "소비 패턴을 분석하고",
  prem3Note: "맞춤 절약 미션과 개선 방향을 제안합니다.",
  prem4Title: "고급 통계",
  prem4Lead: "카테고리, 요일, 기간별 소비 패턴을",
  prem4Note: "더 깊이 분석할 수 있습니다.",
  prem5Title: "프리미엄 챌린지",
  prem5Lead: "시즌 챌린지, AI 추천 챌린지,",
  prem5Note: "그룹 챌린지를 이용할 수 있습니다.",
  prem6Title: "PDF 리포트 · 백업",
  prem6Lead: "월간 절약 리포트와",
  prem6Note: "클라우드 백업을 지원합니다.",
  prem7Title: "홈 위젯",
  prem7Lead: "오늘의 지출, 절약 현황, 목표 달성률을",
  prem7Note: "앱을 열지 않고 확인할 수 있습니다.",
  prem8Title: "광고 제거",
  prem8Lead: "광고 없이",
  prem8Note: "절약 기록에 집중할 수 있습니다.",
  recoTitle: "이런 분들에게 추천",
  reco1: "💸 불필요한 소비를 줄이고 싶은 분",
  reco2: "🧾 돈이 어디로 사라지는지 궁금한 분",
  reco3: "🐷 절약 습관을 만들고 싶은 분",
  reco4: "🎯 목표 기반 절약을 하고 싶은 분",
  reco5: "🤖 AI 기반 소비 분석을 받고 싶은 분",
  reco6: "👥 친구나 가족과 함께 절약하고 싶은 분",
  reco7: "📊 소비와 절약을 눈으로 확인하고 싶은 분",
  premHiKicker: "작은 절약부터",
  premHiLine: "절약 습관을 만드는 경험",
  premHiSub: "PiggyUp이 당신의<br />금융 습관을 더 즐겁게 만듭니다.",
  closingHtml:
    `<p>작은 절약이<br /><span class="ox-accent">더 큰 자유를 만듭니다</span></p><p>PiggyUp은 돈을 아끼는 앱이 아니라<br />현명한 소비 습관을 만드는 플랫폼입니다.</p><p>절약은 참는 것이 아니라<br /><span class="ox-accent">더 좋은 선택을 하는 경험입니다.</span></p>`,
  closingAria: "마무리 문구",
  footerRights: "© PiggyUp ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY 소개",
  drawerBl: "BabyLog 소개",
  drawerPl: "PetLog 소개",
  drawerPu: "PiggyUp · 이 화면",
  appStoreUrl: "https://apps.apple.com/kr/app/piggyup-ai-%EC%A0%88%EC%95%BD-%EA%B4%80%EB%A6%AC-%EC%B1%8C%EB%A6%B0%EC%A7%80/id6772744969",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.piggyup&pcampaignid=web_share",
  appStoreBadgeAria: "App Store에서 PiggyUp(새 탭)",
  googlePlayBadgeAria: "Google Play에서 PiggyUp(새 탭)",
};

export const puEn = {
  brandAria: "Back to top of PiggyUp",
  globalReachBadge: "173 countries · 13 languages supported",
  badge: "💰 Saving habits · Spending analysis · AI savings coach",
  h1: "PiggyUp",
  subtitleHtml: `<span class="ox-accent">Small savings add up to bigger change</span>`,
  heroReachSummary:
    "From spending logs to savings goals and AI insights—record daily spending lightly, spot money leaks, and build saving habits.",
  heroLogoAlt: "PiggyUp app logo: cute pink piggy bank",
  introLabel: "Brand",
  introTitle: "Why PiggyUp",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>PiggyUp</strong> is</p><p>a smart savings-habit app that lets you log today\'s spending and keep savings goals going—without a heavy ledger.</p><p>Instead of making money care harder, we turn small daily entries into a path toward saving.</p><p>Log spending to see where money goes. Set savings goals so small steps stack into bigger change.</p><p>Start lighter money routines with a friendly pig character by your side.</p>',
  introClosing: "Small savings build better spending habits.",
  showcaseCollageAria:
    "Seven PiggyUp app screenshots. Scroll horizontally to view all.",
  imgShot1Alt: "PiggyUp — A new way to record savings instead of spending",
  imgShot2Alt: "PiggyUp — Visual savings data by category",
  imgShot3Alt: "PiggyUp — See your saving habits as data",
  imgShot4Alt: "PiggyUp — Join savings challenges together",
  imgShot5Alt: "PiggyUp — Record easily, simply, and fast",
  imgShot6Alt: "PiggyUp — Small habits lead to big savings",
  imgShot7Alt: "PiggyUp — AI-powered advanced spending and savings analysis",  reviewsTitle: "User stories",  review1Quote: "Turning saving into a game is genuinely fun.",  review2Emoji: "👨🏻",  review2Meta: "Office worker · 30",  review3Quote: "Little spending habits started changing one by one.",  review4Emoji: "👨🏽",  review4Meta: "Small business owner · 39",
  reviewsLabel: "Reviews",
  reviewsTitle: "User stories",
  review1Emoji: "👩🏻",
  review1Quote: "Turning saving into a game is genuinely fun.",
  review1Meta: "College student · 22",
  review2Emoji: "👨🏻",
  review2Quote: "I'm not spending less—I'm spending smarter.",
  review2Meta: "Office worker · 30",
  review3Emoji: "👩🏼",
  review3Quote: "Little spending habits started changing one by one.",
  review3Meta: "Flight attendant · 29",
  review4Emoji: "👨🏽",
  review4Quote: "Saving feels like a win—not a strain.",
  review4Meta: "Small business owner · 39",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Spending log",
  feat1Lead: "Record today's amount and category with ease.",
  feat1Note: "Check daily spending flow quickly—no heavy input.",
  feat2Title: "Savings goals",
  feat2Lead: "Set target amounts and plans, then track progress at a glance.",
  feat2Note: "Small savings add up toward your goals.",
  feat3Title: "Savings alerts",
  feat3Lead: "Manage repeat spend, risk signals, and log reminders.",
  feat3Note: "Stay on top of your spending habits.",
  feat4Title: "Spending analysis",
  feat4Lead: "Analyze category patterns and monthly outflow.",
  feat4Note: "See where you spend most, easily.",
  feat5Title: "Charts & stats",
  feat5Lead: "Visualize savings, spending flow, and goal progress.",
  feat5Note: "Understand the numbers at a glance.",
  feat6Title: "AI savings insights",
  feat6Lead: "AI analyzes habits and suggests savings points.",
  feat6Note: "Build more efficient spending routines.",
  feat7Title: "Goal progress",
  feat7Lead: "Track goal completion and growth over time.",
  feat7Note: "Make small savings visible as bigger change.",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Log spending",
  how1P: "Enter today’s amount and category.",
  how2Title: "2️⃣ Set savings goals",
  how2P: "Choose how much you want to save and your plan.",
  how3Title: "3️⃣ Review patterns",
  how3P: "Analyze spending flow by category.",
  how4Title: "4️⃣ Read AI insights",
  how4P: "Review AI savings reports and spending insights.",
  how5Title: "5️⃣ Build the habit",
  how5P: "Keep logging little by little and build a savings routine.",
  how6Title: "6️⃣ Reach your goal",
  how6P: "Hit your savings goal and celebrate the growth.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "Savings, challenges & AI<br />for smarter saving",
  premFeatHeading: "Premium features",
  prem1Title: "Unlimited challenges",
  prem1Lead: "Run personal savings challenges",
  prem1Note: "with no limits.",
  prem2Title: "Group saving rooms",
  prem2Lead: "Share savings goals with friends, family, or partners",
  prem2Note: "and take on challenges together.",
  prem3Title: "AI savings coach",
  prem3Lead: "Analyze spending patterns and get",
  prem3Note: "tailored missions and improvement tips.",
  prem4Title: "Advanced statistics",
  prem4Lead: "Go deeper on category, weekday, and period patterns",
  prem4Note: "across your spending data.",
  prem5Title: "Premium challenges",
  prem5Lead: "Seasonal, AI-picked, and group",
  prem5Note: "challenges for extra motivation.",
  prem6Title: "PDF reports & backup",
  prem6Lead: "Monthly savings reports and",
  prem6Note: "cloud backup support.",
  prem7Title: "Home widgets",
  prem7Lead: "Check today's spend, savings status, and goal progress",
  prem7Note: "without opening the app.",
  prem8Title: "Remove ads",
  prem8Lead: "No ads—",
  prem8Note: "focus on your savings records.",
  recoTitle: "Great if you…",
  reco1: "💸 Want to cut unnecessary spending",
  reco2: "🧾 Wonder where your money goes",
  reco3: "🐷 Want to build saving habits",
  reco4: "🎯 Want goal-based savings",
  reco5: "🤖 Want AI-based spending analysis",
  reco6: "👥 Want to save with friends or family",
  reco7: "📊 Want to see spending and savings visually",
  premHiKicker: "From small savings",
  premHiLine: "Build saving habits that stick.",
  premHiSub: "PiggyUp makes money habits<br />more fun and sustainable.",
  closingHtml:
    `<p>Small savings<br /><span class="ox-accent">More freedom</span></p><p>PiggyUp isn't just about saving money—<br />it's a platform for smarter spending habits.</p><p>Saving isn't about deprivation—<br /><span class="ox-accent">it's choosing what matters most.</span></p>`,
  closingAria: "Closing message",
  footerRights: "© PiggyUp ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "Open SAVY intro",
  drawerBl: "Open BabyLog intro",
  drawerPl: "Open PetLog intro",
  drawerPu: "PiggyUp · this screen",
  appStoreUrl: "https://apps.apple.com/kr/app/piggyup-ai-%EC%A0%88%EC%95%BD-%EA%B4%80%EB%A6%AC-%EC%B1%8C%EB%A6%B0%EC%A7%80/id6772744969",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.piggyup&pcampaignid=web_share",
  appStoreBadgeAria: "PiggyUp on the App Store (opens in a new tab)",
  googlePlayBadgeAria: "PiggyUp on Google Play (opens in a new tab)",
};
