/** Pillmate page copy — merged into locales/en.json & ko.json by apply-pm-locales.mjs */
export const pmEn = {
  brandAria: "Back to top of Pillmate",
  badge: "💊 Med reminders · Health logs · Family sharing · Daily routine",
  globalReachBadge: "From today's dose · Worldwide service",
  h1: "Pillmate",
  subtitleHtml:
    `<span class="ox-accent">Make today's doses easier<br />and stay consistent</span>`,
  heroReachSummary:
    "Record and manage medications, supplements, and health routines in one place—and build steady habits with reminders and logs.",
  heroLogoAlt: "Pillmate app logo: red and white diagonal capsule icon",
  introLabel: "Brand",
  introTitle: "Why Pillmate",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>Make today\'s doses easier and more consistent</strong></p><p><strong>Pillmate</strong> is a medication management app where you record and manage pills, supplements, and health routines in one place.</p><p>Set dose times and get reminders so important schedules are not missed.</p><p>From morning to bedtime, build your own pattern and keep healthy habits going.</p><p>When daily medication is logged, it becomes safer and easier to manage over time.</p>',
  introClosing:
    "Pillmate is not just a reminder app—it is a partner for healthier everyday routines.",
  showcaseCollageAria:
    "Pillmate app screenshots — seven screens. Scroll horizontally to view all.",
  imgShot1Alt: "Pillmate — the easiest way to manage your meds, from reminders to tracking",
  imgShot2Alt: "Pillmate — track today’s meds at a glance",
  imgShot3Alt: "Pillmate — stay consistent with smart reminders",
  imgShot4Alt: "Pillmate — add your meds in seconds",
  imgShot5Alt: "Pillmate — never miss meds for your loved ones",
  imgShot6Alt: "Pillmate — monitor multiple people at once",
  imgShot7Alt: "Pillmate — insights, sharing, and reports in premium features",  reviewsTitle: "User stories",  review1Quote: "I almost never forget my meds anymore.",  review2Emoji: "👨🏻",  review2Meta: "Office worker · 35",  review3Quote: "Health really comes down to showing up every day.",  review4Emoji: "👨🏽",  review4Meta: "Fitness coach · 42",
  reviewsLabel: "Reviews",
  reviewsTitle: "User stories",
  review1Emoji: "👩🏼",
  review1Quote: "I almost never forget my meds anymore.",
  review1Meta: "Nurse · 29",
  review2Emoji: "👨🏻",
  review2Quote: "I can help manage my parents' health too—that's a big plus.",
  review2Meta: "Office worker · 35",
  review3Emoji: "👩🏻",
  review3Quote: "Health really comes down to showing up every day.",
  review3Meta: "Pilates instructor · 32",
  review4Emoji: "👨🏽",
  review4Quote: "Taking supplements became a natural habit.",
  review4Meta: "Fitness coach · 42",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Today's dose check",
  feat1Lead: "See today's pills and supplements",
  feat1Note: "at a glance and log them quickly",
  feat2Title: "Time-of-day schedules",
  feat2Lead: "Morning · lunch · evening · bedtime",
  feat2Note: "Split doses into clear daily slots",
  feat3Title: "Smart dose reminders",
  feat3Lead: "Alerts at set times",
  feat3Note: "so important doses are not missed",
  feat4Title: "Dose history",
  feat4Lead: "Review status by date",
  feat4Note: "Track adherence and habit flow",
  feat5Title: "Medication details",
  feat5Lead: "Name, how to take, dose, cautions",
  feat5Note: "Keep notes in one place",
  feat6Title: "Family medication care",
  feat6Lead: "Parents, children, partners",
  feat6Note: "Manage household doses together",
  feat7Title: "Home widget",
  feat7Lead: "Without opening the app",
  feat7Note: "Check today's dose status instantly",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Add a medication",
  how1P: "Register pills or supplements you are taking.",
  how2Title: "2️⃣ Set dose times",
  how2P: "Choose slots like morning, lunch, evening, or bedtime.",
  how3Title: "3️⃣ Get reminders",
  how3P: "Receive alerts at scheduled times so nothing slips by.",
  how4Title: "4️⃣ Check off doses",
  how4P: "After taking a dose, mark it to log today's progress.",
  how5Title: "5️⃣ Review history",
  how5P: "Check adherence and keep your health routine going.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "Safer, more organized<br />medication care",
  premFeatHeading: "Premium features",
  prem1Title: "Unlimited medications",
  prem1Lead: "No count limit—register",
  prem1Note: "all pills and supplements.",
  prem2Title: "AI medication insights",
  prem2Lead: "Pattern and adherence analysis",
  prem2Note: "with health habit insights.",
  prem3Title: "Monthly dose calendar",
  prem3Lead: "Full-month view and",
  prem3Note: "missed-dose analysis.",
  prem4Title: "Smart schedule management",
  prem4Lead: "Run-out forecasts, refill timing,",
  prem4Note: "and clinic visits.",
  prem5Title: "Family sharing",
  prem5Lead: "Invite family, manage together,",
  prem5Note: "with caregiver alerts.",
  prem6Title: "Advanced reminders",
  prem6Lead: "Repeat, escalation, weekday,",
  prem6Note: "and snooze options.",
  prem7Title: "Backup & export",
  prem7Lead: "Cloud backup plus PDF/CSV",
  prem7Note: "to keep records safe.",
  prem8Title: "Remove ads",
  prem8Lead: "No banners or full-screen ads—",
  prem8Note: "a calmer, focused experience.",
  recoTitle: "Great if you…",
  reco1: "💊 Take daily medication",
  reco2: "⏰ Often forget dose times",
  reco3: "👨‍👩‍👧 Manage family medication",
  reco4: "🌿 Take supplements consistently",
  reco5: "📊 Want a clear dose log",
  reco6: "✨ Want a healthier daily routine",
  premHiKicker: "From today's dose",
  premHiLine: "Keep a healthy routine going.",
  premHiSub: "Pillmate helps you<br />stay consistent with your health.",
  closingHtml:
    `<p>Steady doses<br /><span class="ox-accent">Build a healthier life</span></p><p>Pillmate isn't just a reminder app—<br />it's a platform for healthy routines.</p><p>Small daily care<br /><span class="ox-accent">creates a healthier future.</span></p>`,
  closingAria: "Pillmate closing",
  closing: "",
  footerRights: "© Pillmate ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate · this screen",
  appStoreUrl: "https://apps.apple.com/kr/app/pillmate-%EC%8A%A4%EB%A7%88%ED%8A%B8%ED%95%9C-%EB%B3%B5%EC%95%BD-%EC%95%8C%EB%A6%BC/id6768017347",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.pill.mate&pcampaignid=web_share",
  appStoreBadgeAria: "Pillmate on the App Store (opens in a new tab)",
  googlePlayBadgeAria: "Pillmate on Google Play (opens in a new tab)",
};

export const pmKo = {
  brandAria: "Pillmate 상단으로",
  badge: "💊 복약 알림 · 건강 기록 · 가족 공유 · 데일리 루틴",
  h1: "Pillmate",
  subtitleHtml: `<span class="ox-accent">오늘의 복용을 더 쉽고<br />꾸준하게 이어가세요</span>`,
  heroReachSummary:
    "약, 영양제, 건강 루틴을 한곳에서 기록·관리하고 알림과 기록으로 꾸준한 복약 습관을 만드는 앱입니다.",
  heroLogoAlt: "Pillmate 앱 로고: 빨간색과 흰색 대각 분할 캡슐 아이콘",
  introLabel: "브랜드",
  introTitle: "왜 Pillmate인가",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>오늘의 복용을 더 쉽고 꾸준하게</strong></p><p><strong>Pillmate</strong>는 약, 영양제, 건강 루틴을 하나의 공간에서 기록하고 관리할 수 있는 복약 관리 앱입니다.</p><p>복용 시간을 설정하고 알림을 받아 중요한 복용 일정을 놓치지 않도록 도와줍니다.</p><p>아침, 점심, 저녁, 자기 전까지 나만의 복용 패턴을 만들고 꾸준한 건강 습관을 이어가세요.</p><p>매일 반복되는 복약은 기록될 때 더 안전하고 체계적으로 관리될 수 있습니다.</p>',
  introClosing:
    "Pillmate는 단순한 알림 앱이 아니라 건강한 일상을 만드는 복약 파트너입니다.",
  showcaseCollageAria:
    "Pillmate 앱 스크린샷 7장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt: "Pillmate — 약 관리, 알림부터 기록까지",
  imgShot2Alt: "Pillmate — 오늘 복용 한눈에 체크",
  imgShot3Alt: "Pillmate — 아침·점심·저녁 맞춤 알림",
  imgShot4Alt: "Pillmate — 약 추가 화면",
  imgShot5Alt: "Pillmate — 가족 공유",
  imgShot6Alt: "Pillmate — 가족 관리, 여러 명 복용 상태",
  imgShot7Alt: "Pillmate — 프리미엄 기능",  reviewsTitle: "사용자 이야기",  review1Quote: "약 먹는 걸 잊어버리는 일이 거의 없어졌어요.",  review2Emoji: "👨🏻",  review2Meta: "직장인 · 35세",  review3Quote: "건강도 결국은 꾸준함이라는 걸 느끼게 됐어요.",  review4Emoji: "👨🏽",  review4Meta: "운동 코치 · 42세",
  reviewsLabel: "후기",
  reviewsTitle: "사용자 이야기",
  review1Emoji: "👩🏼",
  review1Quote: "약 먹는 걸 잊어버리는 일이 거의 없어졌어요.",
  review1Meta: "간호사 · 29세",
  review2Emoji: "👨🏻",
  review2Quote: "부모님 건강 관리도 함께 할 수 있어서 좋습니다.",
  review2Meta: "직장인 · 35세",
  review3Emoji: "👩🏻",
  review3Quote: "건강도 결국은 꾸준함이라는 걸 느끼게 됐어요.",
  review3Meta: "필라테스 강사 · 32세",
  review4Emoji: "👨🏽",
  review4Quote: "영양제를 챙겨 먹는 습관이 자연스럽게 생겼습니다.",
  review4Meta: "운동 코치 · 42세",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "오늘 복용 체크",
  feat1Lead: "오늘 먹어야 하는 약과 영양제를",
  feat1Note: "한눈에 확인하고 간편하게 기록",
  feat2Title: "시간대별 복용 관리",
  feat2Lead: "아침 · 점심 · 저녁 · 자기 전까지",
  feat2Note: "복용 일정을 세분화하여 관리",
  feat3Title: "스마트 복용 알림",
  feat3Lead: "정해진 시간에 알림을 받아",
  feat3Note: "복용 시간을 놓치지 않도록 안내",
  feat4Title: "복용 기록 관리",
  feat4Lead: "날짜별 복용 현황 확인",
  feat4Note: "복용률과 습관 흐름 파악",
  feat5Title: "약 정보 정리",
  feat5Lead: "약 이름·복용 방법·용량·",
  feat5Note: "주의사항·메모 기록 지원",
  feat6Title: "가족 복약 공유",
  feat6Lead: "부모님·아이·배우자",
  feat6Note: "가족 복약 현황 함께 관리",
  feat7Title: "홈 위젯",
  feat7Lead: "앱을 열지 않아도",
  feat7Note: "오늘 복용 상태를 즉시 확인",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 약 등록",
  how1P: "복용 중인 약이나 영양제를 추가하세요.",
  how2Title: "2️⃣ 복용 시간 설정",
  how2P: "아침, 점심, 저녁, 자기 전 등 원하는 시간대를 선택하세요.",
  how3Title: "3️⃣ 알림 받기",
  how3P: "정해진 시간에 알림을 받아 중요한 복용을 놓치지 마세요.",
  how4Title: "4️⃣ 복용 체크",
  how4P: "복용 후 체크하여 오늘의 복약 상태를 기록하세요.",
  how5Title: "5️⃣ 기록 확인",
  how5P: "복용 이력과 복용률을 확인하고 건강 루틴을 꾸준히 이어가세요.",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "복약 관리를 더 안전하고<br />체계적으로",
  premFeatHeading: "프리미엄 기능",
  prem1Title: "무제한 약 등록",
  prem1Lead: "개수 제한 없이",
  prem1Note: "모든 약과 영양제를 등록합니다.",
  prem2Title: "AI 복약 인사이트",
  prem2Lead: "복용 패턴·복용률 분석과",
  prem2Note: "건강 습관 인사이트를 제공합니다.",
  prem3Title: "월간 복약 캘린더",
  prem3Lead: "월간 복용 현황과",
  prem3Note: "복용 누락일을 분석합니다.",
  prem4Title: "스마트 일정 관리",
  prem4Lead: "약 소진 예정·재구매 시점과",
  prem4Note: "병원 일정을 관리합니다.",
  prem5Title: "가족 공유",
  prem5Lead: "가족 초대·공동 관리와",
  prem5Note: "보호자 알림을 지원합니다.",
  prem6Title: "고급 알림",
  prem6Lead: "반복·에스컬레이션·요일별·",
  prem6Note: "스누즈로 세밀하게 설정합니다.",
  prem7Title: "백업 및 내보내기",
  prem7Lead: "클라우드 백업과 PDF·CSV로",
  prem7Note: "기록을 안전하게 보관합니다.",
  prem8Title: "광고 제거",
  prem8Lead: "배너·전면 광고 없이",
  prem8Note: "집중할 수 있는 환경을 제공합니다.",
  recoTitle: "이런 분들에게 추천",
  reco1: "💊 매일 약을 챙겨 먹어야 하는 분",
  reco2: "⏰ 복용 시간을 자주 잊어버리는 분",
  reco3: "👨‍👩‍👧 부모님이나 가족 복약을 관리하는 분",
  reco4: "🌿 영양제를 꾸준히 챙겨 먹는 분",
  reco5: "📊 복용 기록을 남기고 싶은 분",
  reco6: "✨ 건강한 생활 루틴을 만들고 싶은 분",
  premHiKicker: "오늘의 복용부터",
  premHiLine: "건강한 루틴을 이어가세요.",
  premHiSub: "Pillmate가 당신의<br />건강 관리를 더 꾸준하게 만듭니다.",
  closingHtml:
    `<p>꾸준한 복용이<br /><span class="ox-accent">건강한 삶을 만듭니다</span></p><p>Pillmate는 약을 알리는 앱이 아니라<br />건강한 루틴을 만들어가는 플랫폼입니다.</p><p>하루의 작은 관리가<br /><span class="ox-accent">더 건강한 미래를 만듭니다.</span></p>`,
  closingAria: "Pillmate 마무리",
  closing: "",
  footerRights: "© Pillmate ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate · 이 화면",
  appStoreUrl: "https://apps.apple.com/kr/app/pillmate-%EC%8A%A4%EB%A7%88%ED%8A%B8%ED%95%9C-%EB%B3%B5%EC%95%BD-%EC%95%8C%EB%A6%BC/id6768017347",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.pill.mate&pcampaignid=web_share",
  appStoreBadgeAria: "App Store에서 Pillmate(새 탭)",
  googlePlayBadgeAria: "Google Play에서 Pillmate(새 탭)",
};
