/** Pillmate page copy — merged into locales/en.json & ko.json by apply-pm-locales.mjs */
export const pmEn = {
  brandAria: "Back to top of Pillmate",
  badge: "Medication · reminders · daily routine",
  h1: "Pillmate",
  subtitleHtml:
    "Don't miss a dose—<br /><strong>manage today's medication easily</strong>",
  heroReachSummary:
    "Record and track daily medications, supplements, and health routines in one place.",
  heroLogoAlt: "Pillmate app logo: red and cream capsule with wordmark",
  introLabel: "About the app",
  introTitle: "About Pillmate",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>Pillmate</strong> helps you manage daily pills and supplements by time of day and check them off quickly.</p><p>Split doses into morning, lunch, evening, and bedtime, and use reminders so important times are not missed.</p>',
  introClosing: "Turns easy-to-forget habits into safer, steadier care.",
  showcaseCollageAria:
    "Pillmate app screenshots — seven screens. Scroll horizontally to view all.",
  imgShot1Alt: "Pillmate — the easiest way to manage your meds, from reminders to tracking",
  imgShot2Alt: "Pillmate — track today’s meds at a glance",
  imgShot3Alt: "Pillmate — stay consistent with smart reminders",
  imgShot4Alt: "Pillmate — add your meds in seconds",
  imgShot5Alt: "Pillmate — never miss meds for your loved ones",
  imgShot6Alt: "Pillmate — monitor multiple people at once",
  imgShot7Alt: "Pillmate — insights, sharing, and reports in premium features",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Today's dose check",
  feat1Lead: "See today's pills at a glance",
  feat1Note: "Log doses quickly as you take them",
  feat2Title: "Time-of-day schedules",
  feat2Lead: "Morning · lunch · evening · bedtime",
  feat2Note: "Keep routines easy to scan",
  feat3Title: "Dose reminders",
  feat3Lead: "Reminders at set times",
  feat3Note: "Guidance so important doses are not missed",
  feat4Title: "Dose history",
  feat4Lead: "Review by date",
  feat4Note: "See consistency at a glance",
  feat5Title: "Medication notes",
  feat5Lead: "Name, how to take, amount",
  feat5Note: "Keep what you need in one place",
  feat6Title: "Family care",
  feat6Lead: "Parents, kids, household routines",
  feat6Note: "Support the people you look after",
  feat7Title: "Home widget",
  feat7Lead: "Without opening the app",
  feat7Note: "Check today's dose status on the home screen",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Add a medication",
  how1P: "Register pills or supplements you are taking.",
  how2Title: "2️⃣ Set dose times",
  how2P: "Choose slots like morning, lunch, evening, or bedtime.",
  how3Title: "3️⃣ Get reminders",
  how3P: "Receive alerts at scheduled times so nothing slips by.",
  how4Title: "4️⃣ Check off today",
  how4P: "After taking a dose, mark it to log today's progress.",
  how5Title: "5️⃣ Review history",
  how5P: "Browse past days and keep the habit going.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "More organized care and<br />a smoother logging experience",
  premFeatHeading: "Premium features",
  prem1Title: "Monthly dose log",
  prem1Lead: "See a month of adherence at a glance",
  prem1Note: "Spot missed days and steady streaks quickly",
  prem2Title: "AI dose report",
  prem2Lead: "Based on your logs,",
  prem2Note: "see patterns and ways to improve",
  prem3Title: "Premium themes",
  prem3Lead: "More colors and styles to",
  prem3Note: "personalize your care space",
  prem4Title: "Remove ads",
  prem4Lead: "Focus without interruptions in",
  prem4Note: "a calmer experience",
  recoTitle: "Great if you…",
  reco1: "Take daily meds or supplements",
  reco2: "Often forget dose times",
  reco3: "Help parents or family stay on track",
  reco4: "Want a consistent dose log",
  reco5: "Want a clearer health routine",
  premHiKicker: "In one line",
  premHiLine: "Log today's doses and keep a healthy routine going.",
  closing: "Small dose logs build lasting healthy habits.",
  footerRights: "© Pillmate ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate · this screen",
  appStoreUrl: "https://newon.app",
  googlePlayUrl: "https://newon.app",
  appStoreBadgeAria: "Pillmate on the App Store (opens in a new tab)",
  googlePlayBadgeAria: "Pillmate on Google Play (opens in a new tab)",
};

export const pmKo = {
  brandAria: "Pillmate 상단으로",
  badge: "복약 · 알림 · 데일리 루틴",
  h1: "Pillmate",
  subtitleHtml: "약 복용을 놓치지 않도록<br /><strong>오늘의 복용을 간편하게 관리하세요</strong>",
  heroReachSummary:
    "매일 복용해야 하는 약, 영양제, 건강 루틴을 한곳에서 기록하고 확인할 수 있는 복약 관리 앱입니다.",
  heroLogoAlt: "Pillmate 앱 로고",
  introLabel: "앱 소개",
  introTitle: "앱 소개",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>Pillmate</strong>는 매일 챙겨야 하는 약과 영양제를 시간대별로 관리하고, 복용 여부를 간단하게 체크할 수 있는 복약 기록 앱입니다.</p><p>아침, 점심, 저녁, 자기 전 등 복용 시간을 나누어 관리할 수 있으며 알림을 통해 중요한 복용 시간을 놓치지 않도록 도와줍니다.</p>',
  introClosing: "잊기 쉬운 복용 습관을 더 안전하고 꾸준하게 만들어줍니다.",
  showcaseCollageAria:
    "Pillmate 앱 스크린샷 7장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt: "Pillmate — 약 관리, 알림부터 기록까지",
  imgShot2Alt: "Pillmate — 오늘 복용 한눈에 체크",
  imgShot3Alt: "Pillmate — 아침·점심·저녁 맞춤 알림",
  imgShot4Alt: "Pillmate — 약 추가 화면",
  imgShot5Alt: "Pillmate — 가족 공유",
  imgShot6Alt: "Pillmate — 가족 관리, 여러 명 복용 상태",
  imgShot7Alt: "Pillmate — 프리미엄 기능",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "오늘 복용 체크",
  feat1Lead: "오늘 먹어야 할 약을 한눈에 확인",
  feat1Note: "복용 여부를 빠르게 기록",
  feat2Title: "시간대별 복용 관리",
  feat2Lead: "아침·점심·저녁·자기 전으로 구분",
  feat2Note: "복용 루틴을 쉽게 정리",
  feat3Title: "복용 알림",
  feat3Lead: "정해진 시간에 리마인더 제공",
  feat3Note: "중요한 약 복용을 놓치지 않도록 안내",
  feat4Title: "복용 기록 관리",
  feat4Lead: "날짜별 복용 여부 확인",
  feat4Note: "꾸준한 복용 흐름을 쉽게 파악",
  feat5Title: "약 정보 메모",
  feat5Lead: "약 이름, 복용 방법, 용량 기록",
  feat5Note: "필요한 정보를 한곳에 정리",
  feat6Title: "가족 공유 안내",
  feat6Lead: "부모님, 아이, 가족 복약 관리에 활용",
  feat6Note: "챙겨야 할 사람의 복용도 함께 확인",
  feat7Title: "홈 위젯",
  feat7Lead: "앱을 열지 않아도",
  feat7Note: "오늘 복용 상태를 바로 확인",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 약 추가",
  how1P: "복용 중인 약이나 영양제를 등록하세요",
  how2Title: "2️⃣ 복용 시간 설정",
  how2P: "아침, 점심, 저녁, 자기 전 등 원하는 시간대를 선택하세요",
  how3Title: "3️⃣ 알림 받기",
  how3P: "정해진 시간에 복용 알림을 받아 놓치지 않도록 관리하세요",
  how4Title: "4️⃣ 오늘 복용 체크",
  how4P: "복용 후 체크하여 오늘의 복용 상태를 기록하세요",
  how5Title: "5️⃣ 기록 확인",
  how5P: "날짜별 복용 기록을 확인하고 꾸준한 복용 습관을 이어가세요",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "더 체계적인 복용 관리와<br />편리한 기록 경험을 제공합니다",
  premFeatHeading: "프리미엄 기능",
  prem1Title: "월간 복용 기록",
  prem1Lead: "한 달 동안의 복용 흐름을 확인",
  prem1Note: "놓친 날과 꾸준한 날을 쉽게 파악",
  prem2Title: "AI 복용 리포트",
  prem2Lead: "복용 기록을 기반으로",
  prem2Note: "나의 복용 패턴과 개선 방향 제공",
  prem3Title: "프리미엄 테마",
  prem3Lead: "더 다양한 컬러와 스타일로",
  prem3Note: "나만의 복약 관리 공간을 꾸밀 수 있습니다",
  prem4Title: "광고 제거",
  prem4Lead: "방해 없이 집중할 수 있는",
  prem4Note: "쾌적한 사용 환경을 제공합니다",
  recoTitle: "이런 분들에게 추천",
  reco1: "매일 약이나 영양제를 챙겨야 하는 분",
  reco2: "복용 시간을 자주 잊어버리는 분",
  reco3: "부모님이나 가족의 복약을 함께 챙기고 싶은 분",
  reco4: "복용 기록을 꾸준히 남기고 싶은 분",
  reco5: "더 체계적인 건강 루틴을 만들고 싶은 분",
  premHiKicker: "한 줄 강조 문구",
  premHiLine: "오늘의 복용을 기록하고, 건강한 루틴을 이어가세요",
  closing: "작은 복용 기록이 건강한 습관을 만듭니다",
  footerRights: "© Pillmate ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate · 이 화면",
  appStoreUrl: "https://newon.app",
  googlePlayUrl: "https://newon.app",
  appStoreBadgeAria: "App Store에서 Pillmate(새 탭)",
  googlePlayBadgeAria: "Google Play에서 Pillmate(새 탭)",
};
