/**
 * KO/EN copy for Newon Resources hubs + index.
 * Slugs: index | store | insights | blog | media | labs | newsletter | education
 */

const SHARED = {
  ko: {
    crumbResources: "RESOURCES",
    switcherLabel: "RESOURCES",
    exploreTitle: "리소스 둘러보기",
    exploreIndexLabel: "목록",
    prevLabel: "PREVIOUS",
    nextLabel: "NEXT",
    viewExperiment: "VIEW EXPERIMENT →",
    comingSoon: "COMING SOON",
    inProgress: "IN PROGRESS",
    pricePlaceholder: "₩—",
    searchSoon: "라이브러리가 쌓이면 검색이 열립니다",
    searchSoonEn: "Search coming as library grows",
    filterAll: "ALL",
  },
  en: {
    crumbResources: "RESOURCES",
    switcherLabel: "RESOURCES",
    exploreTitle: "EXPLORE RESOURCES",
    exploreIndexLabel: "INDEX",
    prevLabel: "PREVIOUS",
    nextLabel: "NEXT",
    viewExperiment: "VIEW EXPERIMENT →",
    comingSoon: "COMING SOON",
    inProgress: "IN PROGRESS",
    pricePlaceholder: "—",
    searchSoon: "Search coming as library grows",
    searchSoonEn: "Search coming as library grows",
    filterAll: "ALL",
  },
};

const COPY = {
  ko: {
    index: {
      seoTitle: "Resources | Newon",
      metaDescription:
        "Store · Insights · Blog · Media · Labs · Notes · Education — Newon Resource Hub.",
      eyebrow: "NEWON RESOURCES",
      subEyebrow: "",
      headline: "만들고,\n실험하고,\n기록합니다.",
      lead: "Newon이 제품을 만들고 운영하며 얻은 아이디어, 실험, 인사이트와 디지털 자료를 공유합니다.",
      heroSub: "제품을 만드는 사람을 위한 실험과 기록.",
      ctaBrowse: "리소스 둘러보기 →",
      ctaLabs: "Labs 보기 ↗",
      heroProcessLabel: "PROCESS",
      heroProcess: [
        { n: "01", title: "BUILD", body: "아이디어를 실제 제품으로 만듭니다." },
        { n: "02", title: "TEST", body: "사용자와 데이터를 통해 검증합니다." },
        { n: "03", title: "LEARN", body: "결과와 실패에서 배웁니다." },
        { n: "04", title: "SHARE", body: "얻은 것을 기록하고 공유합니다." },
        { n: "05", title: "BUILD AGAIN", body: "배운 것을 다음 제품에 적용합니다." },
      ],
      ctaPrimary: "",
      emptyTitle: "",
      emptyLead: "",
      indexCountLabel: "INDEX",
      navLabel: "RESOURCES",
      featuredEyebrow: "FEATURED",
      featuredTitle: "지금 Newon에서\n볼 만한 것.",
      featuredLead: "최근 프로젝트와 가장 많이 활용할 수 있는 리소스를 골랐습니다.",
      featuredView: "프로젝트 보기 ↗",
      featuredCta: "프로젝트 보기 ↗",
      catEyebrow: "CATEGORIES",
      catTitle: "리소스 카테고리",
      catLead: "필요한 형식부터 고르세요.",
      catCta: "둘러보기 →",
      latestEyebrow: "LATEST FROM NEWON",
      latestTitle: "최근에 올라온\n리소스.",
      latestViewAll: "전체 리소스 보기 →",
      whyEyebrow: "WHY RESOURCES",
      whyTitle: "만든 것을\n기록하고,\n배운 것을\n공유합니다.",
      whyLead:
        "Newon Resources는 제품을 만드는 과정에서 얻은 경험, 실험과 실패까지 기록해 다음 제품과 다른 제작자에게 연결하기 위한 공간입니다.",
      whySteps: [
        { n: "01", title: "BUILD", body: "아이디어를 실제 제품으로 만듭니다." },
        { n: "02", title: "TEST", body: "사용자와 데이터를 통해 검증합니다." },
        { n: "03", title: "LEARN", body: "결과와 실패에서 배웁니다." },
        { n: "04", title: "SHARE", body: "얻은 것을 기록하고 공유합니다." },
        { n: "05", title: "BUILD AGAIN", body: "배운 것을 다음 제품에 적용합니다." },
      ],
      topicsEyebrow: "EXPLORE BY TOPIC",
      topicsTitle: "관심 있는 주제부터.",
      topics: [
        "AI",
        "App Development",
        "Product",
        "Design",
        "Growth",
        "Startup",
        "Experiment",
        "Game",
        "Marketing",
        "Analytics",
      ],
      searchTitle: "무엇을 찾고 있나요?",
      searchPlaceholder: "리소스, 실험, 글 또는 자료 검색",
      searchEmpty: "일치하는 리소스가 없습니다.",
      searchFilterAll: "All",
      nlEyebrow: "NEWON NOTES",
      nlTitle: "새로운 실험과 제품 이야기를 받아보세요.",
      nlLead: "Newon의 새로운 제품, 실험과 배운 점을 가끔 보내드립니다.",
      nlPlaceholder: "your@email.com",
      nlCta: "구독하기 →",
      nlNote: "스팸 없이, 필요한 이야기만.",
      sectionIndex: "탐색",
      sectionIndexTitle: "Resources",
      sectionIndexRange: "01—08",
      popularEyebrow: "POPULAR",
      popularTitle: "많이 찾는\n리소스.",
      ctaBandEyebrow: "NEWON",
      ctaBandTitle: "제품을 만들\n준비가 되셨나요?",
      ctaBandLead: "Newon Business와 Studio가 아이디어를 제품으로 만드는 과정을 함께합니다.",
      ctaBandPrimary: "프로젝트 문의 →",
      ctaBandSecondary: "Newon 제품 보기 ↗",
      surfaceExtra: {
        publishing: {
          title: "PUBLISHING",
          category: "퍼블리싱",
          lead: "가이드 · 워크북 · 리포트\n컬렉션.",
          desc: "Store 퍼블리싱 컬렉션",
          meta: "Building",
          cta: "퍼블리싱 보기 ↗",
          href: "store/?cat=publishing",
        },
        tools: {
          title: "TOOLS",
          category: "웹 도구",
          lead: "브라우저에서 바로 쓰는\n무료 디지털 도구.",
          desc: "계산 · 생성 · 변환 · 개발",
          meta: "Live + Building",
          cta: "Tools 보기 ↗",
          href: "../tools/",
        },
      },
      indexItems: {
        store: {
          title: "STORE",
          category: "디지털 자료",
          lead: "만들고 바로 사용할 수 있는\n디지털 제품과 자료.",
          desc: "템플릿 · AI/코드 · 비즈니스 · 디자인",
          meta: "디지털 제품",
          cta: "스토어 보기 ↗",
        },
        insights: {
          title: "INSIGHTS",
          category: "리서치 / 관찰",
          lead: "제품·소비자·시장을\n관찰하고 기록합니다.",
          desc: "Tech · AI · Product · Consumer · Startup · Market",
          meta: "Building",
          cta: "Insights 보기 ↗",
        },
        blog: {
          title: "BLOG",
          category: "글 / 노트",
          lead: "제품을 만들며\n배운 것을 기록합니다.",
          desc: "제품 · AI · 개발 · 비즈니스",
          meta: "아티클 & 노트",
          cta: "블로그 읽기 ↗",
        },
        media: {
          title: "MEDIA",
          category: "콘텐츠",
          lead: "Newon의 제품과 이야기를\n다양한 콘텐츠로 만납니다.",
          desc: "영상 · 제품 스토리 · 비주얼 · 업데이트",
          meta: "콘텐츠",
          cta: "미디어 보기 ↗",
        },
        labs: {
          title: "LABS",
          category: "실험",
          lead: "작게 만들고,\n빠르게 검증합니다.",
          desc: "새로운 제품, AI, SaaS와 게임 아이디어를 실험하고 기록합니다.",
          meta: "진행 중 실험",
          metaSub: "테스트 / 리서치",
          cta: "랩스 입장 ↗",
        },
        newsletter: {
          title: "NEWON NOTES",
          category: "뉴스레터",
          lead: "제품과 실험 이야기를\n가끔 받아보세요.",
          desc: "새로운 제품, 실험, 글과 주요 업데이트",
          meta: "Newon Notes",
          cta: "Notes 구독 ↗",
          formPlaceholder: "your@email.com",
          formCta: "구독하기 →",
        },
        education: {
          title: "EDUCATION",
          category: "가이드 / 학습",
          lead: "제품을 만드는 과정을\n배울 수 있는 공간.",
          desc: "제품, 개발, AI와 비즈니스를 다루는 가이드와 교육 콘텐츠를 준비하고 있습니다.",
          meta: "곧 공개",
          cta: "교육 보기 ↗",
        },
      },
    },
    store: {
      seoTitle: "Store | Newon Resources",
      metaDescription: "템플릿, AI/코드, 비즈니스, 디자인, 퍼블리싱 자료 등 Newon이 직접 만드는 디지털 상품.",
      eyebrow: "NEWON STORE",
      subEyebrow: "DIGITAL PRODUCTS",
      headline: "일하는 방식을\n더 빠르게 만드는 자료.",
      lead: "Newon이 제품을 만들고 운영하며 사용하는 템플릿, 프롬프트, 디지털 자료를 제공합니다. 가격이 확정되지 않은 상품은 임의 금액을 넣지 않습니다.",
      ctaPrimary: "전체 상품 보기 ↓",
      emptyTitle: "이 카테고리에는 아직 상품이 없습니다",
      emptyLead: "다른 카테고리를 선택하거나 전체 목록을 확인하세요.",
      navLabel: "STORE",
      shelfTitle: "DIGITAL PRODUCT SHELF",
      shelfLead: "미리보기 · PRODUCT 001–003",
      catalogTitle: "PRODUCT CATALOG",
      filterLabels: {
        all: "ALL",
        templates: "TEMPLATES",
        "ai-code": "AI / CODE",
        business: "BUSINESS",
        design: "DESIGN",
        publishing: "PUBLISHING",
        reports: "REPORTS",
        prompts: "AI / CODE",
        development: "AI / CODE",
        free: "TEMPLATES",
      },
      includesLabel: "WHAT'S INCLUDED",
      audienceLabel: "FOR",
      previewLabel: "PREVIEW",
      versionLabel: "VERSION",
      updatedLabel: "UPDATED",
      waitlistCta: "출시 알림 받기",
      inquiryCta: "문의하기 →",
      waitlistSuccess: "알림 신청이 완료되었습니다.",
      waitlistDuplicate: "이미 등록된 이메일입니다.",
      waitlistError: "잠시 후 다시 시도해 주세요.",
      waitlistNote: "출시되면 이메일로 알려드립니다. 결제는 아직 연결되지 않았습니다.",
      productCta: "상세 보기 →",
      formatLabel: "FORMAT",
      statusLabel: "STATUS",
      howToLabel: "HOW TO USE",
      licenseLabel: "LICENSE",
      licenseNote: "개인·팀 내부 사용 라이선스. 재판매 및 재배포 불가.",
      faqLabel: "FAQ",
      relatedTitle: "관련 리소스",
      productFaq: [
        { q: "지금 구매할 수 있나요?", a: "아직 결제가 연결되지 않았습니다. 출시 알림을 신청하거나 문의해 주세요." },
        { q: "포맷은 무엇인가요?", a: "대부분 Notion, PDF, 또는 편집 가능한 템플릿 파일로 제공됩니다. 상품별 상세는 출시 시 안내됩니다." },
      ],
    },
    blog: {
      seoTitle: "Blog | Newon",
      metaDescription:
        "Newon의 제품, 개발, 디자인, 비즈니스와 제품 제작 과정을 기록하는 블로그.",
      eyebrow: "NEWON BLOG",
      subEyebrow: "NAVER ARCHIVE",
      headline: "Blog",
      lead: "제품을 만들고 운영하며 얻은 생각과 경험을 기록합니다.\nNewon의 개발, 디자인, 비즈니스 이야기를 확인해보세요.",
      ctaPrimary: "글 살펴보기 ↓",
      emptyTitle: "게시글을 불러오지 못했습니다.",
      emptyLead: "잠시 후 다시 시도하거나 네이버 블로그에서 직접 확인해 주세요.",
      filterEmpty: "이 카테고리에 해당하는 글이 없습니다.",
      navLabel: "BLOG",
      latestTitle: "LATEST POSTS",
      indexTitle: "PUBLICATION INDEX",
      featuredTitle: "FEATURED",
      sourceLabel: "NAVER BLOG",
      readFeatured: "Read on Naver →",
      readArticle: "Read article ↗",
      naverLink: "Naver Blog ↗",
      visitNaver: "Visit Naver Blog ↗",
      moreEyebrow: "MORE STORIES",
      moreTitle: "Newon의 모든 기록 보기",
      moreLead: "더 많은 제품, 개발, 비즈니스 이야기는\nNewon 네이버 블로그에서 확인할 수 있습니다.",
      filterAria: "카테고리",
      filterLabels: {
        all: "ALL",
        product: "PRODUCT",
        development: "DEVELOPMENT",
        design: "DESIGN",
        business: "BUSINESS",
        newon: "NEWON",
        note: "NOTE",
      },
    },
    media: {
      seoTitle: "Media | Newon",
      metaDescription:
        "Newon의 제품, 개발, 디자인과 새로운 시도를 영상으로 기록하는 Media Hub.",
      eyebrow: "NEWON MEDIA",
      subEyebrow: "MEDIA HUB",
      headline: "Media",
      lead: "제품을 만들고 출시하는 과정, Newon의 업데이트와 새로운 시도를 영상과 콘텐츠로 기록합니다.",
      subLead: "제품 데모, 개발 과정, 디자인, 런칭 스토리와 Newon의 새로운 실험을 확인해보세요.",
      ctaPrimary: "미디어 살펴보기 ↓",
      emptyTitle: "No media yet.",
      emptyLead: "현재 등록된 콘텐츠가 없습니다.",
      filterEmpty: "No media yet.",
      filterEmptySub: "현재 등록된 콘텐츠가 없습니다.",
      navLabel: "MEDIA",
      featuredTitle: "FEATURED",
      latestTitle: "LATEST MEDIA",
      seriesTitle: "SERIES",
      fromInstagram: "FROM INSTAGRAM",
      fromYoutube: "FROM YOUTUBE",
      igHeroLink: "Instagram ↗",
      ytHeroLink: "YouTube ↗",
      igDirDesc: "Short videos, product moments and updates",
      ytDirDesc: "Product demos, builds and longer stories",
      viewIgDir: "View Instagram ↗",
      viewYtDir: "View YouTube ↗",
      watchYoutube: "Watch on YouTube ↗",
      viewInstagram: "View on Instagram ↗",
      viewAllIg: "View all on Instagram ↗",
      viewAllYt: "View all on YouTube ↗",
      playLabel: "영상 재생",
      viewReelLabel: "Instagram에서 보기",
      socialAria: "Newon 소셜",
      filterAria: "미디어 필터",
      followEyebrow: "FOLLOW NEWON",
      followTitle: "Newon의 다음 이야기를 만나보세요.",
      followLead: "새로운 제품, 개발 과정과 업데이트를 Instagram과 YouTube에서 계속 기록합니다.",
      filterLabels: {
        all: "ALL",
        youtube: "YOUTUBE",
        instagram: "INSTAGRAM",
        product: "PRODUCT",
        build: "BUILD",
        design: "DESIGN",
        newon: "NEWON",
      },
      relatedProductsTitle: "관련 제품",
      relatedTitle: "관련 리소스",
    },
    insights: {
      seoTitle: "Insights | Newon Resources",
      metaDescription: "제품·소비자·시장 관찰. 발행된 리포트가 준비되면 이곳에 공개합니다.",
      eyebrow: "NEWON INSIGHTS",
      subEyebrow: "RESEARCH & OBSERVATION",
      headline: "제품과 시장을\n관찰하고 기록합니다.",
      lead: "Tech, AI, Product, Consumer, Startup, Market. 검증된 인사이트만 공개합니다. 지금은 Building 상태입니다.",
      ctaPrimary: "카탈로그 ↓",
      emptyTitle: "발행된 Insights가 아직 없습니다",
      emptyLead: "리포트와 아티클이 준비되면 이곳에 공개합니다. 가짜 리서치를 올리지 않습니다.",
      navLabel: "INSIGHTS",
      catalogTitle: "INSIGHT CATALOG",
      filterLabels: {
        all: "ALL",
        TECH: "TECH",
        AI: "AI",
        PRODUCT: "PRODUCT",
        CONSUMER: "CONSUMER",
        STARTUP: "STARTUP",
        MARKET: "MARKET",
      },
      typeLabels: {
        ARTICLE: "ARTICLE",
        DATA: "DATA",
        REPORT: "REPORT",
        CUSTOM_RESEARCH: "CUSTOM RESEARCH",
      },
      researchEyebrow: "BUSINESS RESEARCH",
      researchTitle: "맞춤 리서치가 필요하신가요?",
      researchLead: "시장·경쟁·소비자·커스텀 리포트를 Business Research로 문의하세요.",
      researchItems: [
        { title: "Market Research", href: "../../business/research/" },
        { title: "Competitor Analysis", href: "../../business/research/" },
        { title: "Consumer Research", href: "../../business/research/" },
        { title: "Custom Report", href: "../../business/inquiry/" },
      ],
      researchCta: "Business Research 문의 →",
      researchHref: "../../business/research/",
      comingSoon: "COMING SOON",
      detailSummary: "요약",
      detailFindings: "핵심 발견",
      detailEvidence: "근거 · 관찰",
      detailMeaning: "의미",
      detailTake: "Newon 관점",
      relatedTitle: "관련 리소스",
    },
    labs: {
      seoTitle: "Labs | Newon Resources",
      metaDescription: "정식 제품 이전의 실험을 기록하는 Newon Labs.",
      eyebrow: "NEWON LABS",
      subEyebrow: "R&D ARCHIVE",
      headline: "질문에서 시작해\n제품으로 검증합니다.",
      lead: "Newon Labs는 정식 제품 이전의 실험 공간입니다. 작게 만들고, 빠르게 검증하고, 배우면 다음으로 넘깁니다.",
      ctaPrimary: "실험 아카이브 ↓",
      emptyTitle: "해당 상태의 실험이 없습니다",
      emptyLead: "",
      navLabel: "LABS",
      statusTitle: "NEWON LABS",
      indexTitle: "EXPERIMENT INDEX",
      indexYear: "2026",
      indexHeading: "지금 돌리고 있는\n실험.",
      indexLead: "작게 만들고, 빠르게 검증하고, 배우면 다음으로 넘깁니다.",
      cycleLabel: "CURRENT CYCLE",
      cycleValue: "2026.08",
      filterAll: "ALL",
      statsExperiments: "EXPERIMENTS",
      questionLabel: "THE QUESTION",
      hypothesisLabel: "HYPOTHESIS",
      buildLabel: "BUILD",
      resultLabel: "RESULT",
      nextLabelSection: "NEXT",
      activeLabel: "TESTING",
      archivedLabel: "ARCHIVED",
      researchLabel: "RESEARCH",
      prototypeLabel: "PROTOTYPE",
      nextReleaseLabel: "NEXT RELEASE",
      nextReleaseValue: "TBA",
      featuredLabel: "FEATURED EXPERIMENT",
      experimentLabel: "EXPERIMENT",
      viewExperiment: "VIEW EXPERIMENT",
      exploreExperiment: "EXPLORE",
      statusMeta: "STATUS",
      stageMeta: "STAGE",
      categoryMeta: "CATEGORY",
      updatedMeta: "UPDATED",
      lifeEyebrow: "FROM QUESTION TO PRODUCT",
      lifeTitle: "모든 Newon 제품은\n하나의 질문에서 시작합니다.",
      lifeLead: "Every Newon product starts with a question.",
      lifeStages: ["IDEA", "RESEARCH", "BUILDING", "TESTING", "VALIDATED", "PRODUCT"],
      closeEyebrow: "NEWON LABS",
      closeTitle: "만들기 전에 묻고,\n출시하기 전에 검증합니다.",
      closeLead: "Labs에서 검증된 실험은 Newon의 새로운 제품과 서비스로 발전합니다.",
      closeProducts: "EXPLORE NEWON PRODUCTS ↗",
      closeIdea: "SUBMIT AN IDEA ↗",
      productsHref: "../../products/",
      ideasHref: "../../ideas/",
    },
    newsletter: {
      seoTitle: "Newon Notes | Newon Resources",
      metaDescription: "제품, AI, 개발과 Newon 실험을 가끔 받는 Newon Notes.",
      eyebrow: "NEWON NOTES",
      subEyebrow: "NEWSLETTER",
      headline: "새로운 것을 만들면\n가장 먼저 알려드립니다.",
      lead: "새로운 제품, 업데이트, Labs 실험, 제품과 AI에 대한 기록을 이메일로 받아보세요.",
      ctaPrimary: "구독하기 →",
      emptyTitle: "ARCHIVE",
      emptyLead: "발행된 호가 아직 없습니다. 첫 호가 나가면 이곳에 쌓입니다.",
      navLabel: "NOTES",
      getTitle: "WHAT YOU'LL GET",
      getItems: [
        { title: "PRODUCT", body: "새로운 제품과 주요 업데이트" },
        { title: "LABS", body: "새로운 실험과 제작 과정" },
        { title: "INSIGHTS", body: "제품 / AI / 개발 기록" },
        { title: "NEWON", body: "Newon의 주요 소식" },
      ],
      formPlaceholder: "email@example.com",
      formNote: "불필요한 메일 없이, Newon의 중요한 업데이트만 보내드립니다.",
      privacyNote: "개인정보 처리방침",
      success: "등록되었습니다. Newon Notes 소식을 받아보실 수 있습니다.",
      duplicate: "이미 등록된 이메일입니다.",
      error: "잠시 후 다시 시도해 주세요.",
      invalid: "올바른 이메일을 입력해 주세요.",
      archiveTitle: "ARCHIVE",
    },
    education: {
      seoTitle: "Education | Newon Resources",
      metaDescription: "Newon이 탐색 중인 교육 주제. 확정된 코스가 아닙니다.",
      eyebrow: "NEWON EDUCATION",
      subEyebrow: "COMING SOON",
      headline: "만드는 방법을\n배우는 공간.",
      lead: "제품 기획, AI 활용, 개발, 디자인, 출시와 운영까지. Newon이 직접 제품을 만들며 얻은 실전 경험을 교육 콘텐츠로 정리합니다.",
      ctaPrimary: "출시 알림 받기 →",
      emptyTitle: "",
      emptyLead: "",
      navLabel: "EDUCATION",
      badge: "COMING SOON",
      notCourseTitle: "NOT YET ANOTHER COURSE.",
      notCourseLead:
        "이론만 설명하는 교육이 아니라, 실제 제품을 만드는 과정에 초점을 맞춥니다.",
      topicsTitle: "TOPICS WE'RE EXPLORING",
      trackGuides: "FREE GUIDES",
      trackCourses: "COURSES",
      trackWorkshops: "WORKSHOPS",
      notifyTitle: "GET NOTIFIED",
      notifyLead: "Education이 공개되면 알려드립니다.",
      formPlaceholder: "email@example.com",
      success: "알림 신청이 완료되었습니다.",
      duplicate: "이미 등록된 이메일입니다.",
      error: "잠시 후 다시 시도해 주세요.",
      interestHidden: "education",
    },
  },
  en: {
    index: {
      seoTitle: "Resources | Newon",
      metaDescription:
        "Store · Insights · Blog · Media · Labs · Notes · Education — Newon's resource hub.",
      eyebrow: "NEWON RESOURCES",
      subEyebrow: "",
      headline: "We build,\nexperiment,\nand record.",
      lead: "Ideas, experiments, insights, and digital goods from how Newon ships and runs products.",
      heroSub: "Experiments and notes for people who build products.",
      ctaBrowse: "Browse resources →",
      ctaLabs: "Open Labs ↗",
      heroProcessLabel: "PROCESS",
      heroProcess: [
        { n: "01", title: "BUILD", body: "Turn ideas into real products." },
        { n: "02", title: "TEST", body: "Validate with users and data." },
        { n: "03", title: "LEARN", body: "Learn from results and failure." },
        { n: "04", title: "SHARE", body: "Record and share what we gain." },
        { n: "05", title: "BUILD AGAIN", body: "Apply it to the next product." },
      ],
      ctaPrimary: "",
      emptyTitle: "",
      emptyLead: "",
      indexCountLabel: "INDEX",
      navLabel: "RESOURCES",
      featuredEyebrow: "FEATURED",
      featuredTitle: "Worth seeing\nat Newon now.",
      featuredLead: "Recent projects and the resources you'll use most.",
      featuredView: "Explore project ↗",
      featuredCta: "Explore project ↗",
      catEyebrow: "CATEGORIES",
      catTitle: "Resource categories",
      catLead: "Start with the format you need.",
      catCta: "Explore →",
      latestEyebrow: "LATEST FROM NEWON",
      latestTitle: "Recent from\nthe library.",
      latestViewAll: "View all resources →",
      whyEyebrow: "WHY RESOURCES",
      whyTitle: "Record what we make.\nShare what we learn.",
      whyLead:
        "Newon Resources captures experience, experiments, and failure from building — connecting them to the next product and to other makers.",
      whySteps: [
        { n: "01", title: "BUILD", body: "Turn ideas into real products." },
        { n: "02", title: "TEST", body: "Validate with users and data." },
        { n: "03", title: "LEARN", body: "Learn from results and failure." },
        { n: "04", title: "SHARE", body: "Record and share what we gain." },
        { n: "05", title: "BUILD AGAIN", body: "Apply it to the next product." },
      ],
      topicsEyebrow: "EXPLORE BY TOPIC",
      topicsTitle: "Start with a topic.",
      topics: [
        "AI",
        "App Development",
        "Product",
        "Design",
        "Growth",
        "Startup",
        "Experiment",
        "Game",
        "Marketing",
        "Analytics",
      ],
      searchTitle: "What are you looking for?",
      searchPlaceholder: "Search resources, experiments, writing, or kits",
      searchEmpty: "No matching resources.",
      searchFilterAll: "All",
      nlEyebrow: "NEWON NOTES",
      nlTitle: "Get new experiments and product notes.",
      nlLead: "Occasional notes on Newon products, experiments, and lessons.",
      nlPlaceholder: "your@email.com",
      nlCta: "Subscribe →",
      nlNote: "No spam — only when it matters.",
      sectionIndex: "EXPLORE",
      sectionIndexTitle: "Resources",
      sectionIndexRange: "01—08",
      popularEyebrow: "POPULAR",
      popularTitle: "Often picked\nresources.",
      ctaBandEyebrow: "NEWON",
      ctaBandTitle: "Ready to build\na product?",
      ctaBandLead: "Newon Business and Studio help turn ideas into shipped products.",
      ctaBandPrimary: "Start a project →",
      ctaBandSecondary: "Explore products ↗",
      surfaceExtra: {
        publishing: {
          title: "PUBLISHING",
          category: "Publishing",
          lead: "Guides, workbooks,\nand reports.",
          desc: "Store publishing collection",
          meta: "Building",
          cta: "Browse publishing ↗",
          href: "store/?cat=publishing",
        },
        tools: {
          title: "TOOLS",
          category: "Web tools",
          lead: "Free browser tools\nyou can use now.",
          desc: "Calculate · Generate · Convert · Develop",
          meta: "Live + Building",
          cta: "Open Tools ↗",
          href: "../tools/",
        },
      },
      indexItems: {
        store: {
          title: "STORE",
          category: "Digital goods",
          lead: "Digital kits and templates\nyou can use right away.",
          desc: "Templates · AI/Code · Business · Design",
          meta: "Digital products",
          cta: "Browse Store ↗",
        },
        insights: {
          title: "INSIGHTS",
          category: "Research",
          lead: "Observations on products,\nconsumers, and markets.",
          desc: "Tech · AI · Product · Consumer · Startup · Market",
          meta: "Building",
          cta: "Open Insights ↗",
        },
        blog: {
          title: "BLOG",
          category: "Writing",
          lead: "Notes from building products",
          desc: "Product · AI · Development · Business",
          meta: "Essays & notes",
          cta: "Read the blog ↗",
        },
        media: {
          title: "MEDIA",
          category: "Content",
          lead: "Newon products and stories",
          desc: "Video · stories · updates",
          meta: "Content",
          cta: "Browse media ↗",
        },
        labs: {
          title: "LABS",
          category: "Experiments",
          lead: "Build small. Validate fast.",
          desc: "Pre-product experiments and prototypes.",
          meta: "In progress",
          cta: "Enter Labs ↗",
        },
        newsletter: {
          title: "NEWON NOTES",
          category: "Newsletter",
          lead: "Occasional product and\nexperiment notes.",
          desc: "Products, labs, and lessons.",
          meta: "Newon Notes",
          cta: "Subscribe to Notes ↗",
          formPlaceholder: "your@email.com",
          formCta: "Subscribe →",
        },
        education: {
          title: "EDUCATION",
          category: "Learning",
          lead: "Guides for building and running products",
          desc: "Learning content in progress.",
          meta: "Coming soon",
          cta: "View education ↗",
        },
      },
    },
    store: {
      seoTitle: "Store | Newon Resources",
      metaDescription: "Templates, AI/code packs, business kits, and publishing goods Newon builds directly.",
      eyebrow: "NEWON STORE",
      subEyebrow: "DIGITAL PRODUCTS",
      headline: "Practical digital goods\nfor people who build.",
      lead: "Templates, prompts, and planning kits. Pre-launch items stay Coming Soon — no fake prices.",
      ctaPrimary: "Browse products ↓",
      emptyTitle: "Nothing in this category yet",
      emptyLead: "Try another filter or view the full catalog.",
      navLabel: "STORE",
      shelfTitle: "DIGITAL PRODUCT SHELF",
      shelfLead: "Preview · PRODUCT 001–003",
      catalogTitle: "PRODUCT CATALOG",
      filterLabels: {
        all: "ALL",
        templates: "TEMPLATES",
        "ai-code": "AI / CODE",
        business: "BUSINESS",
        design: "DESIGN",
        publishing: "PUBLISHING",
        reports: "REPORTS",
        prompts: "AI / CODE",
        development: "AI / CODE",
        free: "TEMPLATES",
      },
      includesLabel: "WHAT'S INCLUDED",
      audienceLabel: "FOR",
      previewLabel: "PREVIEW",
      versionLabel: "VERSION",
      updatedLabel: "UPDATED",
      waitlistCta: "Notify me at launch",
      inquiryCta: "Inquire →",
      waitlistSuccess: "You're on the list.",
      waitlistDuplicate: "This email is already registered.",
      waitlistError: "Something went wrong. Please try again.",
      waitlistNote: "We'll email you when it launches. Checkout is not connected yet.",
      productCta: "View details →",
      formatLabel: "FORMAT",
      statusLabel: "STATUS",
      howToLabel: "HOW TO USE",
      licenseLabel: "LICENSE",
      licenseNote: "Personal and team internal use. No redistribution.",
      faqLabel: "FAQ",
      relatedTitle: "Related Resources",
      productFaq: [
        { q: "Can I buy this now?", a: "Checkout is not connected yet. Join the waitlist or contact us." },
        { q: "What format is included?", a: "Most items ship as Notion, PDF, or editable templates. Details per product at launch." },
      ],
    },
    blog: {
      seoTitle: "Blog | Newon",
      metaDescription:
        "Notes on Newon products, development, design, business, and the process of building.",
      eyebrow: "NEWON BLOG",
      subEyebrow: "NAVER ARCHIVE",
      headline: "Blog",
      lead: "Notes from building and operating products.\nExplore Newon’s development, design, and business stories.",
      ctaPrimary: "Browse ↓",
      emptyTitle: "Blog posts are temporarily unavailable.",
      emptyLead: "Please try again later, or view the archive on Naver Blog.",
      filterEmpty: "No posts in this category.",
      navLabel: "BLOG",
      latestTitle: "LATEST POSTS",
      indexTitle: "PUBLICATION INDEX",
      featuredTitle: "FEATURED",
      sourceLabel: "NAVER BLOG",
      readFeatured: "Read on Naver →",
      readArticle: "Read article ↗",
      naverLink: "Naver Blog ↗",
      visitNaver: "Visit Naver Blog ↗",
      moreEyebrow: "MORE STORIES",
      moreTitle: "See all of Newon’s notes",
      moreLead: "More product, development, and business stories\nare on the Newon Naver Blog.",
      filterAria: "Categories",
      filterLabels: {
        all: "ALL",
        product: "PRODUCT",
        development: "DEVELOPMENT",
        design: "DESIGN",
        business: "BUSINESS",
        newon: "NEWON",
        note: "NOTE",
      },
    },
    media: {
      seoTitle: "Media | Newon",
      metaDescription:
        "Newon’s Media Hub — product, build, design, and experiments on video.",
      eyebrow: "NEWON MEDIA",
      subEyebrow: "MEDIA HUB",
      headline: "Media",
      lead: "We record how products are built and shipped — updates and new experiments in video.",
      subLead: "Explore demos, builds, design, launch stories, and Newon’s next experiments.",
      ctaPrimary: "Browse media ↓",
      emptyTitle: "No media yet.",
      emptyLead: "No media has been published in this category yet.",
      filterEmpty: "No media yet.",
      filterEmptySub: "No media has been published in this category yet.",
      navLabel: "MEDIA",
      featuredTitle: "FEATURED",
      latestTitle: "LATEST MEDIA",
      seriesTitle: "SERIES",
      fromInstagram: "FROM INSTAGRAM",
      fromYoutube: "FROM YOUTUBE",
      igHeroLink: "Instagram ↗",
      ytHeroLink: "YouTube ↗",
      igDirDesc: "Short videos, product moments and updates",
      ytDirDesc: "Product demos, builds and longer stories",
      viewIgDir: "View Instagram ↗",
      viewYtDir: "View YouTube ↗",
      watchYoutube: "Watch on YouTube ↗",
      viewInstagram: "View on Instagram ↗",
      viewAllIg: "View all on Instagram ↗",
      viewAllYt: "View all on YouTube ↗",
      playLabel: "Play video",
      viewReelLabel: "View on Instagram",
      socialAria: "Newon social",
      filterAria: "Filter media",
      followEyebrow: "FOLLOW NEWON",
      followTitle: "Follow the next Newon story.",
      followLead: "New products, builds, and updates continue on Instagram and YouTube.",
      filterLabels: {
        all: "ALL",
        youtube: "YOUTUBE",
        instagram: "INSTAGRAM",
        product: "PRODUCT",
        build: "BUILD",
        design: "DESIGN",
        newon: "NEWON",
      },
      relatedProductsTitle: "Related Products",
      relatedTitle: "Related Resources",
    },
    insights: {
      seoTitle: "Insights | Newon Resources",
      metaDescription: "Product, consumer, and market observations. Published when real — never fake research.",
      eyebrow: "NEWON INSIGHTS",
      subEyebrow: "RESEARCH & OBSERVATION",
      headline: "Observe products\nand markets carefully.",
      lead: "Tech, AI, Product, Consumer, Startup, Market. Only verified insights publish here. Currently Building.",
      ctaPrimary: "Browse catalog ↓",
      emptyTitle: "No published Insights yet",
      emptyLead: "Reports and articles will appear here when ready. We do not publish fake research.",
      navLabel: "INSIGHTS",
      catalogTitle: "INSIGHT CATALOG",
      filterLabels: {
        all: "ALL",
        TECH: "TECH",
        AI: "AI",
        PRODUCT: "PRODUCT",
        CONSUMER: "CONSUMER",
        STARTUP: "STARTUP",
        MARKET: "MARKET",
      },
      typeLabels: {
        ARTICLE: "ARTICLE",
        DATA: "DATA",
        REPORT: "REPORT",
        CUSTOM_RESEARCH: "CUSTOM RESEARCH",
      },
      researchEyebrow: "BUSINESS RESEARCH",
      researchTitle: "Need custom research?",
      researchLead: "Ask Business Research for market, competitor, consumer, or custom reports.",
      researchItems: [
        { title: "Market Research", href: "../../business/research/" },
        { title: "Competitor Analysis", href: "../../business/research/" },
        { title: "Consumer Research", href: "../../business/research/" },
        { title: "Custom Report", href: "../../business/inquiry/" },
      ],
      researchCta: "Inquire about Business Research →",
      researchHref: "../../business/research/",
      comingSoon: "COMING SOON",
      detailSummary: "SUMMARY",
      detailFindings: "KEY FINDINGS",
      detailEvidence: "EVIDENCE / OBSERVATIONS",
      detailMeaning: "WHAT IT MEANS",
      detailTake: "NEWON TAKE",
      relatedTitle: "Related Resources",
    },
    labs: {
      seoTitle: "Labs | Newon Resources",
      metaDescription: "Pre-product experiments at Newon Labs.",
      eyebrow: "NEWON LABS",
      subEyebrow: "R&D ARCHIVE",
      headline: "Start with a question.\nValidate before product.",
      lead: "Newon Labs is where ideas are built small, tested fast, and graduated — or archived — with evidence.",
      ctaPrimary: "Open the archive ↓",
      emptyTitle: "No experiments in this state",
      emptyLead: "",
      navLabel: "LABS",
      statusTitle: "NEWON LABS",
      indexTitle: "EXPERIMENT INDEX",
      indexYear: "2026",
      indexHeading: "Experiments\nin motion.",
      indexLead: "Build small, test fast, learn — then move on.",
      cycleLabel: "CURRENT CYCLE",
      cycleValue: "2026.08",
      filterAll: "ALL",
      statsExperiments: "EXPERIMENTS",
      questionLabel: "THE QUESTION",
      hypothesisLabel: "HYPOTHESIS",
      buildLabel: "BUILD",
      resultLabel: "RESULT",
      nextLabelSection: "NEXT",
      activeLabel: "TESTING",
      archivedLabel: "ARCHIVED",
      researchLabel: "RESEARCH",
      prototypeLabel: "PROTOTYPE",
      nextReleaseLabel: "NEXT RELEASE",
      nextReleaseValue: "TBA",
      featuredLabel: "FEATURED EXPERIMENT",
      experimentLabel: "EXPERIMENT",
      viewExperiment: "VIEW EXPERIMENT",
      exploreExperiment: "EXPLORE",
      statusMeta: "STATUS",
      stageMeta: "STAGE",
      categoryMeta: "CATEGORY",
      updatedMeta: "UPDATED",
      lifeEyebrow: "FROM QUESTION TO PRODUCT",
      lifeTitle: "Every Newon product\nstarts with a question.",
      lifeLead: "모든 Newon 제품은 하나의 질문에서 시작합니다.",
      lifeStages: ["IDEA", "RESEARCH", "BUILDING", "TESTING", "VALIDATED", "PRODUCT"],
      closeEyebrow: "NEWON LABS",
      closeTitle: "Ask before building.\nValidate before launch.",
      closeLead: "Experiments that clear Labs graduate into Newon products and services.",
      closeProducts: "EXPLORE NEWON PRODUCTS ↗",
      closeIdea: "SUBMIT AN IDEA ↗",
      productsHref: "../../products/",
      ideasHref: "../../ideas/",
    },
    newsletter: {
      seoTitle: "Newon Notes | Newon Resources",
      metaDescription: "Newon Notes — products, AI, development, and experiments in occasional email.",
      eyebrow: "NEWON NOTES",
      subEyebrow: "NEWSLETTER",
      headline: "Products and experiments\nin one email.",
      lead: "Products, AI, development, and Newon experiments. If regular sends haven't started yet, we'll tell you when they do.",
      ctaPrimary: "Subscribe",
      emptyTitle: "ARCHIVE",
      emptyLead: "No issues yet. The archive fills as issues publish.",
      navLabel: "NOTES",
      getTitle: "WHAT YOU'LL GET",
      getItems: [
        { title: "PRODUCT", body: "Launches, updates, and why decisions were made" },
        { title: "AI", body: "Experiments and how we use AI in practice" },
        { title: "BUILD", body: "Short notes from development and design" },
        { title: "LABS", body: "Progress on work that isn't a product yet" },
      ],
      formPlaceholder: "email@example.com",
      formNote: "We'll notify you when Newon Notes starts. No spam — only when it matters.",
      privacyNote: "Privacy policy",
      success: "You're on the list. We'll notify you when Newon Notes launches.",
      duplicate: "This email is already registered.",
      error: "Something went wrong. Please try again.",
      invalid: "Please enter a valid email.",
      archiveTitle: "ARCHIVE",
    },
    education: {
      seoTitle: "Education | Newon Resources",
      metaDescription: "Topics Newon is exploring for education — not confirmed courses.",
      eyebrow: "NEWON EDUCATION",
      subEyebrow: "COMING SOON",
      headline: "Not yet\nanother course.",
      lead: "No fake launch years. No promised curriculum. For now, only topics we're exploring.",
      ctaPrimary: "Get notified",
      emptyTitle: "",
      emptyLead: "",
      navLabel: "EDUCATION",
      badge: "COMING SOON",
      notCourseTitle: "NOT YET ANOTHER COURSE",
      notCourseLead:
        "Not a trendy course pack — we're exploring how to share the thinking and craft Newon actually uses while building products.",
      topicsTitle: "TOPICS WE'RE EXPLORING",
      trackGuides: "FREE GUIDES",
      trackCourses: "COURSES",
      trackWorkshops: "WORKSHOPS",
      notifyTitle: "GET NOTIFIED",
      notifyLead: "We'll email you when education content opens.",
      formPlaceholder: "email@example.com",
      success: "You're on the list.",
      duplicate: "This email is already registered.",
      error: "Something went wrong. Please try again.",
      interestHidden: "education",
    },
  },
};

export function getResourceCopy(slug, lang) {
  const L = lang === "ko" ? "ko" : "en";
  const shared = SHARED[L];
  const page = COPY[L][slug] || COPY.en[slug] || COPY.en.index;
  return { ...shared, ...page };
}

export function getAllResourceCopies(lang) {
  const L = lang === "ko" ? "ko" : "en";
  const out = {};
  for (const slug of Object.keys(COPY[L])) {
    out[slug] = getResourceCopy(slug, L);
  }
  return out;
}
