/** SAVY page copy — merged into locales/en.json & ko.json by apply-savy-locales.mjs */

export const svEn = {
  brandAria: "Back to top of SAVY",
  globalReachBadge: "173 countries · 13 languages supported",
  badge: "💳 Spending · income · subscriptions · AI insights",
  h1: "SAVY",
  subtitleHtml:
    "See your money flow at a glance",
  heroReachSummary:
    "A smart finance app that brings scattered spending, income, and subscriptions together—and helps you trim waste.",
  heroLogoAlt: "SAVY app logo: wallet, cards, and Korean won coin",
  introLabel: "About the app",
  introTitle: "About the app",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>SAVY</strong> is</p><p>a spending tracker that helps you record and review your money flow quickly—without a heavy household ledger.</p><p>Log daily expenses and income in seconds, and keep recurring subscriptions visible in one place.</p><p>SAVY is more than a ledger: it organizes your spending patterns and supports healthier money habits.</p><p>Small consistent entries add up to visible savings and change.</p>',
  introClosing: "Small spending logs build better money habits.",
  showcaseCollageAria:
    "SAVY app screenshots — six screens. Scroll horizontally to view all.",
  imgShot1Alt: "SAVY — See your spending at a glance. Smart expense tracking powered by AI",
  imgShot2Alt: "SAVY — Manage income, expenses, and categories in one place",
  imgShot3Alt: "SAVY — Advanced analytics powered by AI",
  imgShot4Alt: "SAVY — Smarter spending with premium features",
  imgShot5Alt: "SAVY — Quick and simple expense tracking (add entry)",
  imgShot6Alt: "SAVY — Smart notifications so you never miss a record",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Expense logging",
  feat1Lead: "Enter what you spent today in a few taps",
  feat1Note: "Lightweight inputs make it easy to stay consistent",
  feat2Title: "Income logging",
  feat2Lead: "Track salary, side income, allowance, and more",
  feat2Note: "See the full in/out picture more accurately",
  feat3Title: "Subscription management",
  feat3Lead: "Organize recurring charges and subscriptions",
  feat3Note: "Catch easy-to-miss repeating expenses",
  feat4Title: "Spending analysis",
  feat4Lead: "Category totals, monthly trends, and patterns",
  feat4Note: "Spot where money leaks out",
  feat5Title: "Charts & statistics",
  feat5Lead: "Visualize income, spending, and balance flow",
  feat5Note: "Make the numbers intuitive at a glance",
  feat6Title: "Notifications",
  feat6Lead: "Renewal dates, budget alerts, logging nudges",
  feat6Note: "Stay on top of important money moments",
  feat7Title: "AI spending insights",
  feat7Lead: "Analyze patterns from your logs",
  feat7Note: "Get ideas on where you can save",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Log expenses",
  how1P: "Enter today’s amount and category.",
  how2Title: "2️⃣ Add income",
  how2P: "Record salary, side income, allowance, and more.",
  how3Title: "3️⃣ Register subscriptions",
  how3P: "Add recurring payments and subscription services.",
  how4Title: "4️⃣ Review statistics",
  how4P: "Check category breakdowns and monthly cash flow.",
  how5Title: "5️⃣ Analyze spending",
  how5P: "Use AI insights and charts to understand habits.",
  how6Title: "6️⃣ Save smarter",
  how6P: "Cut unnecessary spend and build better routines.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "Deeper analysis and<br />a smoother money-management experience",
  premFeatHeading: "🔒 Premium features",
  prem1Title: "📊 Advanced spending analysis",
  prem1Lead: "Deeper views by month, category,",
  prem1Note: "and repeating spend patterns",
  prem2Title: "🤖 AI spending reports",
  prem2Lead: "From your logs, see habits",
  prem2Note: "and practical savings opportunities",
  prem3Title: "🔔 Richer notifications",
  prem3Lead: "Finer control for renewals, budgets,",
  prem3Note: "and recurring charges",
  prem4Title: "📈 Detailed statistics",
  prem4Lead: "More ways to view income",
  prem4Note: "and spending over time",
  prem5Title: "🚫 Remove ads",
  prem5Lead: "Focus on your finances",
  prem5Note: "without interruptions",
  recoTitle: "Great if you…",
  reco1: "Want to reduce unnecessary spending",
  reco2: "Wonder where your money goes each month",
  reco3: "Juggle many subscriptions and need clarity",
  reco4: "Want a ledger without tedious entry work",
  reco5: "Want income and spending in one view",
  reco6: "Want AI help to improve spending habits",
  reco7: "Want a more structured money routine",
  premHiKicker: "In one line",
  premHiLine: "Record money—and change the flow.",
  premHiSub: "Small logs turn into big savings.",
  closingHtml:
    '<p><strong>SAVY</strong> helps you start smarter money management.</p>',
  closingAria: "Closing message",
  footerRights: "© SAVY ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "SAVY · this screen",
  appStoreUrl: "https://apps.apple.com/kr/app/savy-%EC%8A%A4%EB%A7%88%ED%8A%B8-ai-%EA%B0%80%EA%B3%84%EB%B6%80/id6768017037",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.savy&pcampaignid=web_share",
  appStoreBadgeAria: "SAVY on the App Store (opens in a new tab)",
  googlePlayBadgeAria: "SAVY on Google Play (opens in a new tab)",
};

export const svKo = {
  brandAria: "SAVY 상단으로",
  globalReachBadge: "173개국 출시 · 13개 언어 지원",
  badge: "💳 지출 관리 · 수입 기록 · 구독 관리 · AI 분석",
  h1: "SAVY",
  subtitleHtml: "돈의 흐름을 한눈에 확인하세요",
  heroReachSummary:
    "지출, 수입, 구독까지 흩어진 돈을 하나로 정리하고 불필요한 소비를 줄일 수 있도록 도와주는 스마트 금융 관리 앱입니다.",
  heroLogoAlt: "SAVY 앱 로고",
  introLabel: "앱 소개",
  introTitle: "앱 소개",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>SAVY</strong>는</p><p>복잡한 가계부 없이 내 돈의 흐름을 쉽고 빠르게 기록하고 확인할 수 있는 앱입니다.</p><p>매일 발생하는 지출과 수입을 간단하게 기록하고, 매달 빠져나가는 구독 비용까지 한눈에 관리할 수 있습니다.</p><p>SAVY는 단순히 돈을 기록하는 앱이 아니라, 사용자의 소비 패턴을 정리하고 더 나은 소비 습관을 만들 수 있도록 돕는 금융 관리 앱입니다.</p><p>작은 기록을 꾸준히 쌓아 눈에 보이는 절약과 변화로 만들어보세요.</p>',
  introClosing: "작은 소비 기록이 더 나은 돈 관리 습관을 만듭니다.",
  showcaseCollageAria:
    "SAVY 앱 스크린샷 6장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt: "SAVY — 소비를 한눈에, AI가 분석하는 똑똑한 소비 관리",
  imgShot2Alt: "SAVY — 수입·지출·카테고리를 한 번에",
  imgShot3Alt: "SAVY — AI 기반 고급 통계 분석",
  imgShot4Alt: "SAVY — 프리미엄 기능으로 소비를 더 똑똑하게",
  imgShot5Alt: "SAVY — 빠르고 간편한 소비 기록(내역 추가)",
  imgShot6Alt: "SAVY — 기록을 잊지 않도록 스마트 알림",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "지출 기록",
  feat1Lead: "하루 동안 사용한 돈을 간단하게 입력하고 관리할 수 있습니다.",
  feat1Note: "복잡한 입력 없이 빠르게 기록할 수 있어 꾸준히 사용하기 좋습니다.",
  feat2Title: "수입 기록",
  feat2Lead: "월급, 부수입, 용돈 등 들어온 돈을 함께 기록해",
  feat2Note: "전체적인 돈의 흐름을 더 정확하게 확인할 수 있습니다.",
  feat3Title: "구독 관리",
  feat3Lead: "매달 자동으로 빠져나가는 정기결제와 구독 서비스를 정리할 수 있습니다.",
  feat3Note: "놓치기 쉬운 반복 지출을 한눈에 확인하세요.",
  feat4Title: "소비 분석",
  feat4Lead: "카테고리별 지출, 월별 소비 흐름, 반복되는 소비 패턴을 확인할 수 있습니다.",
  feat4Note: "어디서 돈이 새는지 쉽게 파악할 수 있습니다.",
  feat5Title: "통계 시각화",
  feat5Lead: "수입, 지출, 잔액 흐름을 그래프와 통계로 보여줍니다.",
  feat5Note: "복잡한 숫자도 직관적으로 이해할 수 있습니다.",
  feat6Title: "알림 기능",
  feat6Lead: "구독 결제일, 예산 초과, 기록 리마인드 등",
  feat6Note: "중요한 돈 관리 일정을 놓치지 않도록 도와줍니다.",
  feat7Title: "AI 소비 분석",
  feat7Lead: "기록된 데이터를 바탕으로 소비 패턴을 분석하고",
  feat7Note: "절약할 수 있는 방향을 제안합니다.",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 지출 기록",
  how1P: "오늘 사용한 금액과 카테고리를 간단하게 입력하세요.",
  how2Title: "2️⃣ 수입 입력",
  how2P: "월급, 부수입, 용돈 등 들어온 돈도 함께 기록하세요.",
  how3Title: "3️⃣ 구독 등록",
  how3P: "매달 빠져나가는 정기결제와 구독 서비스를 추가하세요.",
  how4Title: "4️⃣ 통계 확인",
  how4P: "카테고리별 지출과 월별 돈의 흐름을 확인하세요.",
  how5Title: "5️⃣ 소비 분석",
  how5P: "AI 분석과 통계를 통해 내 소비 습관을 파악하세요.",
  how6Title: "6️⃣ 절약 실천",
  how6P: "불필요한 지출을 줄이고 더 나은 돈 관리 습관을 만들어보세요.",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "더 깊이 있는 분석과<br />더 편리한 돈 관리 경험을 제공합니다.",
  premFeatHeading: "🔒 프리미엄 기능",
  prem1Title: "📊 고급 소비 분석",
  prem1Lead: "월별, 카테고리별, 반복 지출 패턴을",
  prem1Note: "더 자세하게 분석합니다.",
  prem2Title: "🤖 AI 소비 리포트",
  prem2Lead: "사용자의 기록을 기반으로 소비 습관과",
  prem2Note: "절약 포인트를 알려줍니다.",
  prem3Title: "🔔 고급 알림",
  prem3Lead: "구독 결제일, 예산 초과, 반복 지출을",
  prem3Note: "더 세밀하게 관리할 수 있습니다.",
  prem4Title: "📈 상세 통계",
  prem4Lead: "수입과 지출 흐름을 더 다양한 방식으로",
  prem4Note: "확인할 수 있습니다.",
  prem5Title: "🚫 광고 제거",
  prem5Lead: "방해 없이 깔끔하게 돈 관리에",
  prem5Note: "집중할 수 있습니다.",
  recoTitle: "이런 분들에게 추천",
  reco1: "불필요한 지출을 줄이고 싶은 분",
  reco2: "매달 돈이 어디로 사라지는지 궁금한 분",
  reco3: "구독 서비스가 많아 관리가 어려운 분",
  reco4: "가계부를 쓰고 싶지만 복잡한 입력이 부담스러운 분",
  reco5: "수입과 지출을 한눈에 보고 싶은 분",
  reco6: "AI 분석으로 소비 습관을 개선하고 싶은 분",
  reco7: "더 체계적인 돈 관리 습관을 만들고 싶은 분",
  premHiKicker: "한 줄 강조 문구",
  premHiLine: "돈을 기록하고, 흐름을 바꾸는 경험",
  premHiSub: "작은 기록이 큰 절약을 만듭니다",
  closingHtml:
    '<p><strong>SAVY</strong>와 함께<br />더 똑똑한 돈 관리를 시작하세요.</p>',
  closingAria: "마무리 문구",
  footerRights: "© SAVY ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY · 이 화면",
  appStoreUrl: "https://apps.apple.com/kr/app/savy-%EC%8A%A4%EB%A7%88%ED%8A%B8-ai-%EA%B0%80%EA%B3%84%EB%B6%80/id6768017037",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.savy&pcampaignid=web_share",
  appStoreBadgeAria: "App Store에서 SAVY(새 탭)",
  googlePlayBadgeAria: "Google Play에서 SAVY(새 탭)",
};
