/** SAVY page copy — merged into locales/en.json & ko.json by apply-savy-locales.mjs */

export const svEn = {
  brandAria: "Back to top of SAVY",
  globalReachBadge: "From money flow · Worldwide service",
  badge: "💳 Spending · Income · Subscriptions · AI analysis",
  h1: "SAVY",
  subtitleHtml: `<span class="ox-accent">See your money flow at a glance</span>`,
  heroReachSummary:
    "A smart finance partner that brings spending, income, and subscriptions together—and helps you understand where money goes and build better spending habits with AI.",
  heroLogoAlt: "SAVY app logo: wallet, cards, and Korean won coin",
  introLabel: "Brand",
  introTitle: "Why SAVY",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>The easiest way to understand your money flow</strong></p><p><strong>SAVY</strong> is a smart finance app that lets you log spending, income, and subscriptions without a heavy ledger—and see your money flow at a glance.</p><p>Record daily spending, analyze patterns, and get help cutting unnecessary expenses.</p><p>The more you log income and spending, the clearer the picture—and clearer records lead to better habits.</p><p>SAVY is not just a logging app. It is a finance partner for smarter spending and healthier money routines.</p>',
  introClosing: "Track your money flow and build better spending habits.",
  showcaseCollageAria:
    "SAVY app screenshots — six screens. Scroll horizontally to view all.",
  imgShot1Alt: "SAVY — See your spending at a glance. Smart expense tracking powered by AI",
  imgShot2Alt: "SAVY — Manage income, expenses, and categories in one place",
  imgShot3Alt: "SAVY — Advanced analytics powered by AI",
  imgShot4Alt: "SAVY — Smarter spending with premium features",
  imgShot5Alt: "SAVY — Quick and simple expense tracking (add entry)",
  imgShot6Alt: "SAVY — Smart notifications so you never miss a record",  reviewsTitle: "User stories",  review1Quote: "I finally understood why money always felt tight.",  review2Emoji: "👨🏻",  review2Meta: "Accountant · 35",  review3Quote: "It feels like learning my spending style—not just logging expenses.",  review4Emoji: "👨🏽",  review4Meta: "IT planner · 40",
  reviewsLabel: "Reviews",
  reviewsTitle: "User stories",
  review1Emoji: "👩🏻",
  review1Quote: "I finally understood why money always felt tight.",
  review1Meta: "Grad student · 25",
  review2Emoji: "👨🏻",
  review2Quote: "The AI read my spending habits more accurately than I expected.",
  review2Meta: "Accountant · 35",
  review3Emoji: "👩🏼",
  review3Quote: "It feels like learning my spending style—not just logging expenses.",
  review3Meta: "UX designer · 28",
  review4Emoji: "👨🏽",
  review4Quote: "First time I've kept a budget past three months.",
  review4Meta: "IT planner · 40",
  featuresLabel: "Features",
  featuresTitle: "Key features",
  feat1Title: "Expense logging",
  feat1Lead: "Enter today’s spending quickly",
  feat1Note: "and manage it by category.",
  feat2Title: "Income logging",
  feat2Lead: "Salary, side income, allowance, business revenue—",
  feat2Note: "manage all income in one place.",
  feat3Title: "Subscription management",
  feat3Lead: "Recurring bills, streaming, phone, insurance—",
  feat3Note: "keep everyday subscriptions together.",
  feat4Title: "Spending analysis",
  feat4Lead: "Category share, monthly patterns, recurring spend—",
  feat4Note: "spot unnecessary expenses easily.",
  feat5Title: "Charts & statistics",
  feat5Lead: "Graphs and charts",
  feat5Note: "make money flow easy to grasp.",
  feat6Title: "Smart alerts",
  feat6Lead: "Subscription due dates, budget overruns,",
  feat6Note: "spending reminders, and goal alerts.",
  feat7Title: "AI spending insights",
  feat7Lead: "Habit analysis, spend forecasting,",
  feat7Note: "savings opportunities, and tailored insights.",
  howTitle: "📖 How to use",
  how1Title: "1️⃣ Log expenses",
  how1P: "Enter today’s amount and category.",
  how2Title: "2️⃣ Add income",
  how2P: "Record salary, side income, allowance, and more.",
  how3Title: "3️⃣ Register subscriptions",
  how3P: "Add recurring payments and subscription services.",
  how4Title: "4️⃣ Review statistics",
  how4P: "Check spending flow and category breakdowns.",
  how5Title: "5️⃣ AI analysis",
  how5P: "Analyze habits and find savings opportunities.",
  how6Title: "6️⃣ Improve spending",
  how6P: "Cut expenses and build healthier money routines.",
  premiumLabel: "Pricing",
  premiumTitle: "Premium",
  premiumTagline: "AI analysis & data-driven<br />spending management",
  premFeatHeading: "Premium features",
  prem1Title: "AI spending analysis",
  prem1Lead: "Pattern analysis and spend insights—",
  prem1Note: "with savings recommendations.",
  prem2Title: "AI savings strategy",
  prem2Lead: "Personalized strategies, budget optimization,",
  prem2Note: "and goal-based savings guides.",
  prem3Title: "Advanced statistics",
  prem3Lead: "Period comparisons, spend forecasts,",
  prem3Note: "and deep category views.",
  prem4Title: "Smart alerts",
  prem4Lead: "Budget overruns, overspending warnings,",
  prem4Note: "and recurring payment reminders.",
  prem5Title: "AI monthly report",
  prem5Lead: "Monthly spend reports, trend analysis,",
  prem5Note: "and savings progress.",
  prem6Title: "Sharing",
  prem6Lead: "Shared budgets for couples and families—",
  prem6Note: "share financial reports together.",
  prem7Title: "Goal-based analysis",
  prem7Lead: "Savings goals, target progress,",
  prem7Note: "and savings tracking.",
  prem8Title: "Remove ads",
  prem8Lead: "No ads—",
  prem8Note: "focus on managing your money.",
  recoTitle: "Great if you…",
  reco1: "💸 Wonder where your money goes each month",
  reco2: "📉 Want to cut unnecessary spending",
  reco3: "📺 Juggle many subscriptions and need clarity",
  reco4: "📝 Want a ledger you can actually stick with",
  reco5: "📊 Want income and spending in one view",
  reco6: "🤖 Want AI help to improve spending habits",
  reco7: "🎯 Want a more structured money routine",
  premHiKicker: "Your money flow",
  premHiLine: "Log spending—and change your habits.",
  premHiSub: "SAVY makes your<br />financial life smarter.",
  closingHtml:
    `<p>Visible spending<br /><span class="ox-accent">Smarter choices</span></p><p>SAVY isn't a ledger app—<br />it's a platform to understand money flow.</p><p>The moment you understand spending,<br /><span class="ox-accent">managing money gets easier.</span></p>`,
  closingAria: "Closing message",
  footerRights: "© SAVY ·",
  drawerOx: "OX MONTH intro",
  drawerSp: "SubPing intro",
  drawerPm: "Pillmate intro",
  drawerSv: "SAVY · this screen",
  appStoreUrl: "https://apps.apple.com/kr/app/savy-%EC%8A%A4%EB%A7%88%ED%8A%B8-ai-%EA%B0%80%EA%B3%84%EB%B6%80/id6768017037",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.savy&pcampaignid=web_share",
  appStoreBadgeAria: "SAVY on the App Store (opens in a new tab)",
  googlePlayBadgeAria: "SAVY on Google Play (opens in a new tab)",
};

export const svKo = {
  brandAria: "SAVY 상단으로",
  globalReachBadge: "173개국 출시 · 13개 언어 지원",
  badge: "💳 지출 관리 · 수입 기록 · 구독 관리 · AI 분석",
  h1: "SAVY",
  subtitleHtml: `<span class="ox-accent">돈의 흐름을 한눈에 확인하세요</span>`,
  heroReachSummary:
    "지출, 수입, 구독까지 흩어진 돈을 하나로 정리하고, AI 분석으로 소비 습관을 바꿀 수 있도록 도와주는 금융 파트너입니다.",
  heroLogoAlt: "SAVY 앱 로고",
  introLabel: "브랜드",
  introTitle: "왜 SAVY인가",
  introHtml:
    '<p class="ox-app-intro__lead"><strong>돈의 흐름을 이해하는 가장 쉬운 방법</strong></p><p><strong>SAVY</strong>는 복잡한 가계부 없이 지출, 수입, 구독 비용을 간편하게 기록하고 돈의 흐름을 한눈에 확인할 수 있는 스마트 금융 관리 앱입니다.</p><p>매일 사용하는 돈을 기록하고, 소비 패턴을 분석하며, 불필요한 지출을 줄일 수 있도록 도와줍니다.</p><p>지출과 수입은 기록할수록 명확해지고, 명확한 기록은 더 나은 소비 습관으로 이어집니다.</p><p>SAVY는 단순히 돈을 기록하는 앱이 아니라, 더 현명한 소비와 건강한 재무 습관을 만드는 금융 파트너입니다.</p>',
  introClosing: "돈의 흐름을 기록하고 더 나은 소비 습관을 만들어보세요.",
  showcaseCollageAria:
    "SAVY 앱 스크린샷 6장입니다. 가로로 스크롤하여 모두 볼 수 있습니다.",
  imgShot1Alt: "SAVY — 소비를 한눈에, AI가 분석하는 똑똑한 소비 관리",
  imgShot2Alt: "SAVY — 수입·지출·카테고리를 한 번에",
  imgShot3Alt: "SAVY — AI 기반 고급 통계 분석",
  imgShot4Alt: "SAVY — 프리미엄 기능으로 소비를 더 똑똑하게",
  imgShot5Alt: "SAVY — 빠르고 간편한 소비 기록(내역 추가)",
  imgShot6Alt: "SAVY — 기록을 잊지 않도록 스마트 알림",  reviewsTitle: "사용자 이야기",  review1Quote: "왜 항상 돈이 부족했는지 처음으로 이해하게 됐어요.",  review2Emoji: "👨🏻",  review2Meta: "회계사 · 35세",  review3Quote: "지출을 기록하는 게 아니라 소비 성향을 배우는 느낌이에요.",  review4Emoji: "👨🏽",  review4Meta: "IT 기획자 · 40세",
  reviewsLabel: "후기",
  reviewsTitle: "사용자 이야기",
  review1Emoji: "👩🏻",
  review1Quote: "왜 항상 돈이 부족했는지 처음으로 이해하게 됐어요.",
  review1Meta: "대학원생 · 25세",
  review2Emoji: "👨🏻",
  review2Quote: "AI가 소비 습관을 분석해주는 게 생각보다 정확합니다.",
  review2Meta: "회계사 · 35세",
  review3Emoji: "👩🏼",
  review3Quote: "지출을 기록하는 게 아니라 소비 성향을 배우는 느낌이에요.",
  review3Meta: "UX 디자이너 · 28세",
  review4Emoji: "👨🏽",
  review4Quote: "가계부를 처음으로 3개월 넘게 쓰고 있습니다.",
  review4Meta: "IT 기획자 · 40세",
  featuresLabel: "기능",
  featuresTitle: "주요 기능",
  feat1Title: "지출 기록",
  feat1Lead: "오늘 사용한 돈을 빠르게 입력하고",
  feat1Note: "카테고리별 소비를 관리합니다.",
  feat2Title: "수입 기록",
  feat2Lead: "월급, 부수입, 용돈, 사업 수익 등",
  feat2Note: "모든 수입을 함께 관리합니다.",
  feat3Title: "구독 관리",
  feat3Lead: "정기결제, 스트리밍, 통신비, 보험료,",
  feat3Note: "생활 구독 등을 한곳에서 관리합니다.",
  feat4Title: "소비 분석",
  feat4Lead: "카테고리별 소비 비중, 월간 소비 패턴,",
  feat4Note: "반복 지출 분석으로 불필요한 소비를 파악합니다.",
  feat5Title: "통계 시각화",
  feat5Lead: "그래프와 차트로",
  feat5Note: "돈의 흐름을 쉽게 이해할 수 있습니다.",
  feat6Title: "스마트 알림",
  feat6Lead: "구독 결제일, 예산 초과,",
  feat6Note: "지출 리마인더와 목표 알림을 제공합니다.",
  feat7Title: "AI 소비 분석",
  feat7Lead: "소비 습관 분석, 지출 패턴 예측,",
  feat7Note: "절약 가능 영역과 맞춤 인사이트를 제공합니다.",
  howTitle: "📖 사용 방법",
  how1Title: "1️⃣ 지출 기록",
  how1P: "오늘 사용한 금액과 카테고리를 입력하세요.",
  how2Title: "2️⃣ 수입 입력",
  how2P: "월급, 부수입, 용돈 등을 기록하세요.",
  how3Title: "3️⃣ 구독 등록",
  how3P: "매달 반복되는 구독과 정기결제를 추가하세요.",
  how4Title: "4️⃣ 통계 확인",
  how4P: "소비 흐름과 카테고리 분석을 확인하세요.",
  how5Title: "5️⃣ AI 분석",
  how5P: "소비 습관을 분석하고 절약 포인트를 확인하세요.",
  how6Title: "6️⃣ 소비 개선",
  how6P: "지출을 줄이고 건강한 돈 관리 습관을 만들어보세요.",
  premiumLabel: "요금",
  premiumTitle: "프리미엄",
  premiumTagline: "AI 분석과 데이터 기반<br />소비 관리",
  premFeatHeading: "프리미엄 기능",
  prem1Title: "AI 소비 분석",
  prem1Lead: "소비 패턴 분석, 지출 인사이트 제공,",
  prem1Note: "절약 포인트를 추천합니다.",
  prem2Title: "AI 절약 전략",
  prem2Lead: "개인 맞춤 소비 전략, 예산 최적화,",
  prem2Note: "목표 기반 절약 가이드를 제공합니다.",
  prem3Title: "고급 통계",
  prem3Lead: "기간별 비교, 지출 예측,",
  prem3Note: "카테고리 심층 분석을 확인합니다.",
  prem4Title: "스마트 알림",
  prem4Lead: "예산 초과 알림, 과소비 경고,",
  prem4Note: "정기 결제 알림을 제공합니다.",
  prem5Title: "AI 월간 리포트",
  prem5Lead: "월간 소비 리포트, 소비 변화 분석,",
  prem5Note: "절약 성과를 확인합니다.",
  prem6Title: "공유 기능",
  prem6Lead: "가족, 커플과 공동 예산 공유,",
  prem6Note: "재무 리포트를 함께 공유합니다.",
  prem7Title: "목표 기반 분석",
  prem7Lead: "저축 목표 설정, 소비 목표 달성률,",
  prem7Note: "절약 현황을 추적합니다.",
  prem8Title: "광고 제거",
  prem8Lead: "광고 없이",
  prem8Note: "집중해서 돈 관리를 할 수 있습니다.",
  recoTitle: "이런 분들에게 추천",
  reco1: "💸 매달 돈이 어디로 사라지는지 궁금한 분",
  reco2: "📉 불필요한 지출을 줄이고 싶은 분",
  reco3: "📺 구독 서비스가 많아 관리가 어려운 분",
  reco4: "📝 가계부를 쓰고 싶지만 오래 못 가는 분",
  reco5: "📊 수입과 지출을 한눈에 보고 싶은 분",
  reco6: "🤖 AI 분석으로 소비 습관을 개선하고 싶은 분",
  reco7: "🎯 더 체계적인 돈 관리 습관을 만들고 싶은 분",
  premHiKicker: "돈의 흐름을",
  premHiLine: "기록하고, 소비 습관을 바꾸세요.",
  premHiSub: "SAVY가 당신의<br />금융 생활을 더 스마트하게 만듭니다.",
  closingHtml:
    `<p>보이는 소비가<br /><span class="ox-accent">더 현명한 선택을 만듭니다</span></p><p>SAVY는 가계부 앱이 아니라<br />돈의 흐름을 이해하도록 돕는 플랫폼입니다.</p><p>소비를 이해하는 순간<br /><span class="ox-accent">돈 관리가 훨씬 쉬워집니다.</span></p>`,
  closingAria: "마무리 문구",
  footerRights: "© SAVY ·",
  drawerOx: "OX MONTH 소개",
  drawerSp: "SubPing 소개",
  drawerPm: "Pillmate 소개",
  drawerSv: "SAVY · 이 화면",
  appStoreUrl: "https://apps.apple.com/kr/app/savy-%EC%8A%A4%EB%A7%88%ED%8A%B8-ai-%EA%B0%80%EA%B3%84%EB%B6%80/id6768017037",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.newon.savy&pcampaignid=web_share",
  appStoreBadgeAria: "App Store에서 SAVY(새 탭)",
  googlePlayBadgeAria: "Google Play에서 SAVY(새 탭)",
};
