/**
 * Newon Store — digital products (Coming Soon until payment connected).
 * Prefer resources-data.mjs for the full public catalog; this list feeds admin snapshots.
 */
export const STORE_CATEGORIES = [
  "templates",
  "ai-code",
  "business",
  "design",
  "publishing",
  "reports",
];

export const STORE_PRODUCTS = [
  {
    slug: "app-launch-kit",
    category: "templates",
    status: "building",
    buyable: false,
    nameKey: "studio.store1Name",
    descKey: "studio.store1Desc",
    priceKo: "Coming Soon",
    priceEn: "Coming Soon",
  },
  {
    slug: "mvp-planning-kit",
    category: "templates",
    status: "building",
    buyable: false,
    nameKey: "studio.store2Name",
    descKey: "studio.store2Desc",
    priceKo: "Coming Soon",
    priceEn: "Coming Soon",
  },
  {
    slug: "cursor-prompt-pack",
    category: "ai-code",
    status: "building",
    buyable: false,
    nameKey: "studio.store3Name",
    descKey: "studio.store3Desc",
    priceKo: "Coming Soon",
    priceEn: "Coming Soon",
  },
  {
    slug: "codex-builder-pack",
    category: "ai-code",
    status: "building",
    buyable: false,
    nameKey: "studio.storeCodexName",
    descKey: "studio.storeCodexDesc",
    priceKo: "Coming Soon",
    priceEn: "Coming Soon",
  },
  {
    slug: "website-launch-checklist",
    category: "templates",
    collection: "publishing",
    status: "building",
    buyable: false,
    nameKey: "studio.storeWebLaunchName",
    descKey: "studio.storeWebLaunchDesc",
    priceKo: "Coming Soon",
    priceEn: "Coming Soon",
  },
  {
    slug: "business-planning-workbook",
    category: "business",
    collection: "publishing",
    status: "building",
    buyable: false,
    nameKey: "studio.storeBizPlanName",
    descKey: "studio.storeBizPlanDesc",
    priceKo: "Coming Soon",
    priceEn: "Coming Soon",
  },
  {
    slug: "product-research-template",
    category: "reports",
    collection: "publishing",
    status: "building",
    buyable: false,
    nameKey: "studio.storeResearchName",
    descKey: "studio.storeResearchDesc",
    priceKo: "Coming Soon",
    priceEn: "Coming Soon",
  },
  {
    slug: "founder-dashboard",
    category: "business",
    status: "concept",
    buyable: false,
    nameKey: "studio.store4Name",
    descKey: "studio.store4Desc",
    priceKo: "Coming Soon",
    priceEn: "Coming Soon",
  },
  {
    slug: "product-roadmap",
    category: "templates",
    status: "concept",
    buyable: false,
    nameKey: "studio.store5Name",
    descKey: "studio.store5Desc",
    priceKo: "Coming Soon",
    priceEn: "Coming Soon",
  },
];
