/**
 * Newon Tools catalog — client-side tools with SEO pages.
 */
export const TOOL_CATEGORIES = [
  "developer",
  "productivity",
  "text",
  "design",
  "finance",
  "random",
  "utility",
];

export const TOOLS = [
  {
    slug: "qr",
    id: "qr-generator",
    category: "utility",
    nameKey: "studio.toolQrName",
    descKey: "studio.toolQrDesc",
    status: "live",
  },
  {
    slug: "random-picker",
    id: "random-picker",
    category: "random",
    nameKey: "studio.toolRandomName",
    descKey: "studio.toolRandomDesc",
    status: "live",
  },
  {
    slug: "wheel",
    id: "wheel-spinner",
    category: "random",
    nameKey: "studio.toolWheelName",
    descKey: "studio.toolWheelDesc",
    status: "live",
  },
  {
    slug: "dday",
    id: "dday-calculator",
    category: "productivity",
    nameKey: "studio.toolDdayName",
    descKey: "studio.toolDdayDesc",
    status: "live",
  },
  {
    slug: "counter",
    id: "text-counter",
    category: "text",
    nameKey: "studio.toolCounterName",
    descKey: "studio.toolCounterDesc",
    status: "live",
  },
  {
    slug: "password",
    id: "password-generator",
    category: "developer",
    nameKey: "studio.toolPasswordName",
    descKey: "studio.toolPasswordDesc",
    status: "live",
  },
  {
    slug: "uuid",
    id: "uuid-generator",
    category: "developer",
    nameKey: "studio.toolUuidName",
    descKey: "studio.toolUuidDesc",
    status: "live",
  },
  {
    slug: "json",
    id: "json-formatter",
    category: "developer",
    nameKey: "studio.toolJsonName",
    descKey: "studio.toolJsonDesc",
    status: "live",
  },
  {
    slug: "color",
    id: "color-converter",
    category: "design",
    nameKey: "studio.toolColorName",
    descKey: "studio.toolColorDesc",
    status: "live",
  },
  {
    slug: "percent",
    id: "percent-calculator",
    category: "finance",
    nameKey: "studio.toolPercentName",
    descKey: "studio.toolPercentDesc",
    status: "live",
  },
  {
    slug: "subscription",
    id: "subscription-calculator",
    category: "finance",
    nameKey: "studio.toolSubName",
    descKey: "studio.toolSubDesc",
    status: "live",
  },
  {
    slug: "date",
    id: "date-calculator",
    category: "productivity",
    nameKey: "studio.toolDateName",
    descKey: "studio.toolDateDesc",
    status: "live",
  },
];
