/**
 * Newon Tools catalog — client-side tools with SEO pages.
 * filters: 전체 / 계산 / 생성 / 변환 / 개발 / 랜덤
 */
export const TOOL_FILTERS = [
  { id: "all", labelKey: "studio.toolsFilterAll", labelEn: "All" },
  { id: "calc", labelKey: "studio.toolsFilterCalc", labelEn: "Calculate" },
  { id: "generate", labelKey: "studio.toolsFilterGenerate", labelEn: "Generate" },
  { id: "convert", labelKey: "studio.toolsFilterConvert", labelEn: "Convert" },
  { id: "developer", labelKey: "studio.toolsFilterDev", labelEn: "Develop" },
  { id: "random", labelKey: "studio.toolsFilterRandom", labelEn: "Random" },
];

/** @deprecated keep for any old imports */
export const TOOL_CATEGORIES = [
  "developer",
  "productivity",
  "text",
  "design",
  "finance",
  "random",
  "utility",
];

/**
 * icon: SVG key in tools-hub-render
 * clientSide: true when processing stays in-browser (QR uses external image API)
 * quickAccess: compact QUICK ACCESS row (not claimed as popularity data)
 * groupKey: footer chip label on cards (studio.toolsGroup*)
 * related: explicit related slugs for detail pages
 */
export const TOOLS = [
  {
    slug: "qr",
    id: "qr-generator",
    category: "utility",
    filters: ["generate"],
    nameKey: "studio.toolQrName",
    descKey: "studio.toolQrDesc",
    status: "live",
    icon: "qr",
    tag: "Generate",
    groupKey: "studio.toolsGroupGenerate",
    featured: true,
    featuredOrder: 1,
    quickAccess: true,
    quickOrder: 1,
    clientSide: false,
    keywords: [
      "qr",
      "qr code",
      "qrcode",
      "generator",
      "url",
      "barcode",
      "큐알",
      "큐알코드",
      "큐알 코드",
      "생성",
    ],
    related: ["counter", "color", "random-picker"],
    howKeys: ["studio.toolQrHow1", "studio.toolQrHow2", "studio.toolQrHow3"],
  },
  {
    slug: "random-picker",
    id: "random-picker",
    category: "random",
    filters: ["random", "generate"],
    nameKey: "studio.toolRandomName",
    descKey: "studio.toolRandomDesc",
    status: "live",
    icon: "shuffle",
    tag: "Random",
    groupKey: "studio.toolsGroupRandom",
    featured: false,
    clientSide: true,
    keywords: ["random", "picker", "choice", "pick", "뽑기", "랜덤", "선택", "제비"],
    related: ["wheel", "password", "uuid"],
    howKeys: ["studio.toolRandomHow1", "studio.toolRandomHow2", "studio.toolRandomHow3"],
  },
  {
    slug: "wheel",
    id: "wheel-spinner",
    category: "random",
    filters: ["random"],
    nameKey: "studio.toolWheelName",
    descKey: "studio.toolWheelDesc",
    status: "live",
    icon: "aperture",
    tag: "Random",
    groupKey: "studio.toolsGroupRandom",
    featured: false,
    clientSide: true,
    keywords: ["wheel", "spin", "roulette", "룰렛", "돌림판", "스피너"],
    related: ["random-picker", "uuid", "password"],
    howKeys: ["studio.toolWheelHow1", "studio.toolWheelHow2", "studio.toolWheelHow3"],
  },
  {
    slug: "dday",
    id: "dday-calculator",
    category: "productivity",
    filters: ["calc"],
    nameKey: "studio.toolDdayName",
    descKey: "studio.toolDdayDesc",
    seoTitleKey: "studio.toolDdaySeoTitle",
    seoDescKey: "studio.toolDdaySeoDesc",
    status: "live",
    icon: "calendar",
    tag: "Calculate",
    groupKey: "studio.toolsGroupCalc",
    featured: true,
    featuredOrder: 2,
    quickAccess: true,
    quickOrder: 2,
    clientSide: true,
    keywords: [
      "dday",
      "d-day",
      "d day",
      "countdown",
      "date",
      "디데이",
      "디 데이",
      "남은날",
      "날짜",
      "계산",
    ],
    related: ["date", "percent", "subscription"],
    howKeys: ["studio.toolDdayHow1", "studio.toolDdayHow2", "studio.toolDdayHow3"],
    productCta: {
      href: "../../portfolio/countup/",
      nameKey: "studio.toolsProductCountUp",
      leadKey: "studio.toolsProductCountUpLead",
    },
  },
  {
    slug: "counter",
    id: "text-counter",
    category: "text",
    filters: ["generate"],
    nameKey: "studio.toolCounterName",
    descKey: "studio.toolCounterDesc",
    seoTitleKey: "studio.toolCounterSeoTitle",
    seoDescKey: "studio.toolCounterSeoDesc",
    status: "live",
    icon: "type",
    tag: "Text",
    groupKey: "studio.toolsGroupText",
    featured: false,
    clientSide: true,
    keywords: [
      "text",
      "counter",
      "character",
      "word",
      "글자",
      "글자수",
      "글자 수",
      "단어",
      "문자",
      "카운터",
    ],
    related: ["qr", "json", "password"],
    howKeys: ["studio.toolCounterHow1", "studio.toolCounterHow2", "studio.toolCounterHow3"],
  },
  {
    slug: "password",
    id: "password-generator",
    category: "developer",
    filters: ["generate", "developer"],
    nameKey: "studio.toolPasswordName",
    descKey: "studio.toolPasswordDesc",
    status: "live",
    icon: "key",
    tag: "Generate",
    groupKey: "studio.toolsGroupGenerate",
    featured: true,
    featuredOrder: 3,
    quickAccess: true,
    quickOrder: 3,
    clientSide: true,
    keywords: [
      "password",
      "passphrase",
      "generator",
      "secure",
      "비밀번호",
      "암호",
      "패스워드",
      "생성",
    ],
    related: ["uuid", "qr", "json"],
    howKeys: ["studio.toolPasswordHow1", "studio.toolPasswordHow2", "studio.toolPasswordHow3"],
  },
  {
    slug: "uuid",
    id: "uuid-generator",
    category: "developer",
    filters: ["generate", "developer"],
    nameKey: "studio.toolUuidName",
    descKey: "studio.toolUuidDesc",
    status: "live",
    icon: "fingerprint",
    tag: "Developer",
    groupKey: "studio.toolsGroupDev",
    featured: false,
    clientSide: true,
    keywords: ["uuid", "guid", "v4", "id", "identifier", "유유아이디", "아이디"],
    related: ["json", "password", "color"],
    howKeys: ["studio.toolUuidHow1", "studio.toolUuidHow2", "studio.toolUuidHow3"],
  },
  {
    slug: "json",
    id: "json-formatter",
    category: "developer",
    filters: ["developer"],
    nameKey: "studio.toolJsonName",
    descKey: "studio.toolJsonDesc",
    seoTitleKey: "studio.toolJsonSeoTitle",
    seoDescKey: "studio.toolJsonSeoDesc",
    status: "live",
    icon: "braces",
    tag: "Developer",
    groupKey: "studio.toolsGroupDev",
    featured: false,
    clientSide: true,
    keywords: ["json", "format", "minify", "validate", "pretty", "포맷", "정리", "포맷터"],
    related: ["uuid", "color", "password"],
    howKeys: ["studio.toolJsonHow1", "studio.toolJsonHow2", "studio.toolJsonHow3"],
  },
  {
    slug: "color",
    id: "color-converter",
    category: "design",
    filters: ["convert", "developer"],
    nameKey: "studio.toolColorName",
    descKey: "studio.toolColorDesc",
    status: "live",
    icon: "pipette",
    tag: "Convert",
    groupKey: "studio.toolsGroupConvert",
    featured: false,
    clientSide: true,
    keywords: ["color", "hex", "rgb", "hsl", "색상", "컬러", "변환", "변환기"],
    related: ["qr", "json", "percent"],
    howKeys: ["studio.toolColorHow1", "studio.toolColorHow2", "studio.toolColorHow3"],
  },
  {
    slug: "percent",
    id: "percent-calculator",
    category: "finance",
    filters: ["calc"],
    nameKey: "studio.toolPercentName",
    descKey: "studio.toolPercentDesc",
    status: "live",
    icon: "percent",
    tag: "Calculate",
    groupKey: "studio.toolsGroupCalc",
    featured: false,
    clientSide: true,
    keywords: ["percent", "percentage", "ratio", "퍼센트", "비율", "증감", "계산"],
    related: ["subscription", "dday", "date"],
    howKeys: ["studio.toolPercentHow1", "studio.toolPercentHow2", "studio.toolPercentHow3"],
  },
  {
    slug: "subscription",
    id: "subscription-calculator",
    category: "finance",
    filters: ["calc"],
    nameKey: "studio.toolSubName",
    descKey: "studio.toolSubDesc",
    status: "live",
    icon: "receipt",
    tag: "Calculate",
    groupKey: "studio.toolsGroupCalc",
    featured: false,
    clientSide: true,
    keywords: [
      "subscription",
      "cost",
      "monthly",
      "구독",
      "구독료",
      "비용",
      "합산",
      "계산",
    ],
    related: ["percent", "date", "dday"],
    howKeys: ["studio.toolSubHow1", "studio.toolSubHow2", "studio.toolSubHow3"],
    productCta: {
      href: "../../portfolio/subping/",
      nameKey: "studio.toolsProductSubPing",
      leadKey: "studio.toolsProductSubPingLead",
    },
  },
  {
    slug: "date",
    id: "date-calculator",
    category: "productivity",
    filters: ["calc"],
    nameKey: "studio.toolDateName",
    descKey: "studio.toolDateDesc",
    status: "live",
    icon: "calendar-range",
    tag: "Calculate",
    groupKey: "studio.toolsGroupCalc",
    featured: false,
    clientSide: true,
    keywords: [
      "date",
      "difference",
      "days",
      "기간",
      "날짜",
      "날짜계산",
      "일수",
      "계산",
    ],
    related: ["dday", "percent", "subscription"],
    howKeys: ["studio.toolDateHow1", "studio.toolDateHow2", "studio.toolDateHow3"],
  },
  {
    slug: "utm",
    id: "utm-builder",
    category: "utility",
    filters: ["generate", "developer"],
    nameKey: "studio.toolUtmName",
    descKey: "studio.toolUtmDesc",
    seoTitleKey: "studio.toolUtmSeoTitle",
    seoDescKey: "studio.toolUtmSeoDesc",
    status: "live",
    icon: "link",
    tag: "Generate",
    groupKey: "studio.toolsGroupGenerate",
    featured: false,
    clientSide: true,
    keywords: ["utm", "campaign", "url", "tracking", "유티엠", "캠페인", "추적"],
    related: ["qr", "password", "uuid"],
    howKeys: ["studio.toolUtmHow1", "studio.toolUtmHow2", "studio.toolUtmHow3"],
  },
  {
    slug: "app-launch-checklist",
    id: "app-launch-checklist",
    category: "productivity",
    filters: ["generate"],
    nameKey: "studio.toolAppLaunchName",
    descKey: "studio.toolAppLaunchDesc",
    status: "building",
    icon: "checklist",
    tag: "Checklist",
    groupKey: "studio.toolsGroupGenerate",
    featured: false,
    clientSide: true,
    keywords: ["app", "launch", "checklist", "출시", "체크리스트", "앱런칭"],
    related: ["mvp-planner", "utm", "dday"],
    howKeys: ["studio.toolAppLaunchHow1", "studio.toolAppLaunchHow2", "studio.toolAppLaunchHow3"],
  },
  {
    slug: "mvp-planner",
    id: "mvp-planner",
    category: "productivity",
    filters: ["generate"],
    nameKey: "studio.toolMvpName",
    descKey: "studio.toolMvpDesc",
    status: "building",
    icon: "map",
    tag: "Plan",
    groupKey: "studio.toolsGroupGenerate",
    featured: false,
    clientSide: true,
    keywords: ["mvp", "planner", "scope", "기획", "범위", "플래너"],
    related: ["app-launch-checklist", "app-pricing-calculator", "dday"],
    howKeys: ["studio.toolMvpHow1", "studio.toolMvpHow2", "studio.toolMvpHow3"],
  },
  {
    slug: "app-pricing-calculator",
    id: "app-pricing-calculator",
    category: "finance",
    filters: ["calc"],
    nameKey: "studio.toolPricingName",
    descKey: "studio.toolPricingDesc",
    status: "building",
    icon: "percent",
    tag: "Calculate",
    groupKey: "studio.toolsGroupCalc",
    featured: false,
    clientSide: true,
    keywords: ["pricing", "price", "subscription", "가격", "요금", "구독"],
    related: ["percent", "subscription", "mvp-planner"],
    howKeys: ["studio.toolPricingHow1", "studio.toolPricingHow2", "studio.toolPricingHow3"],
  },
];

export function featuredTools() {
  return TOOLS.filter((t) => t.featured).sort((a, b) => (a.featuredOrder || 99) - (b.featuredOrder || 99));
}

export function quickAccessTools() {
  return TOOLS.filter((t) => t.quickAccess).sort((a, b) => (a.quickOrder || 99) - (b.quickOrder || 99));
}

export function toolsByFilter(filterId) {
  if (!filterId || filterId === "all") return TOOLS.slice();
  return TOOLS.filter((t) => (t.filters || []).includes(filterId));
}

export function relatedTools(tool, limit = 3) {
  const fromMeta = (tool.related || [])
    .map((slug) => TOOLS.find((t) => t.slug === slug))
    .filter(Boolean)
    .filter((t) => t.slug !== tool.slug);
  if (fromMeta.length) return fromMeta.slice(0, limit);
  return TOOLS.filter((t) => t.slug !== tool.slug)
    .filter((t) => (t.filters || []).some((f) => (tool.filters || []).includes(f)))
    .slice(0, limit);
}
