/**
 * WEB DEVELOPMENT service detail — KO/EN copy.
 * Path: /{lang}/business/web/
 */
export const WEB_COPY = {
  ko: {
    seoTitle: "WEB DEVELOPMENT | Newon Business",
    metaDescription:
      "브랜드와 서비스를 설명하는 완성도 높은 웹을 만듭니다. 회사 사이트, 랜딩, 서비스 웹까지 구조·디자인·구현·배포까지 Newon WEB DEVELOPMENT.",
    crumbBusiness: "BUSINESS",
    crumbServices: "SERVICES",
    crumbBuild: "BUILD",
    crumbHere: "WEB",
    eyebrow: "WEB DEVELOPMENT",
    subEyebrow: "BUILD",
    headline: "브랜드와 제품을 위한\n웹을 만듭니다.",
    lead: "브랜드 사이트부터 랜딩 페이지, 제품 소개 웹과 웹 서비스까지 목적에 맞는 디지털 경험을 설계하고 개발합니다. 정보 구조, UI, 반응형 구현, SEO, 문의·전환 연결, 배포까지 한 흐름으로 진행합니다.",
    ctaPrimary: "웹 프로젝트 문의 →",
    ctaSecondary: "작업 범위 보기 ↓",
    meta: [
      { k: "SERVICE", v: "Web Development" },
      { k: "BEST FOR", v: "브랜드·서비스 웹 구축" },
      { k: "TIMELINE", v: "보통 2–5주" },
      { k: "PRICE", v: "₩700,000부터" },
    ],
    overviewLabel: "OVERVIEW",
    overviewTitle: "사이트는 있는데,\n브랜드가 안 보입니다.",
    overviewBody: [
      "많은 팀은 웹이 있지만 브랜드와 서비스가 한눈에 읽히지 않습니다. 템플릿처럼 보이는 구성, 모바일에서 깨지는 레이아웃, 문의·전환까지 연결되지 않는 흐름이 흔한 문제입니다.",
      "웹은 정보를 나열하는 페이지가 아니라, 방문자가 브랜드를 이해하고 다음 행동으로 이어지게 하는 경험입니다. 구조, 타이포, 여백, CTA, 반응형, SEO가 함께 맞아야 합니다.",
      "WEB DEVELOPMENT는 먼저 사이트의 목적과 방문자 행동을 정의합니다. 그다음 정보 구조와 브랜드에 맞는 UI를 설계하고, 반응형 구현·문의 연결·배포까지 완성도 높은 웹을 전달합니다.",
    ],
    problemsLabel: "PROBLEMS",
    problemsTitle: "이런 상황에서 도움이 됩니다.",
    problems: [
      {
        n: "01",
        t: "NO BRAND PRESENCE",
        d: "사이트는 있지만 브랜드와 서비스가 안 보이는 경우.\n템플릿처럼 보이는 구성을 정리해야 하는 경우.",
      },
      {
        n: "02",
        t: "MOBILE BREAKS",
        d: "모바일에서 깨지고 찾기 어려운 경우.\n반응형 구조와 정보 위계를 다시 잡아야 하는 경우.",
      },
      {
        n: "03",
        t: "NO CONVERSION PATH",
        d: "소개에서 멈추고 문의·신청·탐색으로 이어지지 않는 경우.\n전환 흐름 설계가 필요한 경우.",
      },
      {
        n: "04",
        t: "SCATTERED CONTENT",
        d: "페이지는 많지만 역할과 우선순위가 불명확한 경우.\n정보 구조(IA) 정리가 필요한 경우.",
      },
      {
        n: "05",
        t: "OUTDATED SITE",
        d: "기존 사이트를 유지할 부분과 새로 만들 범위를 나눠야 하는 경우.\n리뉴얼·재구축이 필요한 경우.",
      },
      {
        n: "06",
        t: "LAUNCH BLOCKED",
        d: "디자인은 있지만 구현·배포·도메인 연결이 막힌 경우.\n출시까지 한 파트너가 필요한 경우.",
      },
    ],
    baLabel: "BEFORE / AFTER",
    baTitle: "정보 나열 vs\n브랜드가 읽히는 웹",
    beforeLabel: "BEFORE",
    afterLabel: "AFTER",
    before: [
      "템플릿처럼 보이는 구성과 흔들리는 톤",
      "모바일에서 레이아웃·가독성 문제",
      "페이지마다 다른 버튼·섹션 규칙",
      "문의·전환까지 연결되지 않는 흐름",
    ],
    after: [
      "목적과 방문자 행동을 먼저 정의",
      "브랜드에 맞는 정보 구조와 UI",
      "데스크톱·모바일 모두에서 읽히는 반응형",
      "문의·CTA·SEO·배포까지 연결된 웹",
    ],
    capsLabel: "CAPABILITIES",
    capsTitle: "웹 구축에 필요한 작업을\n한 구조로 진행합니다.",
    caps: [
      {
        t: "GOAL & IA",
        d: "사이트 목적, 페이지 역할, 콘텐츠 우선순위를 정의합니다.\n방문자가 길을 잃지 않는 구조를 만듭니다.",
      },
      {
        t: "UX / UI DESIGN",
        d: "브랜드 톤, 타이포, 여백, 컴포넌트를 맞춥니다.\n템플릿이 아닌 브랜드 사이트로 보이게 합니다.",
      },
      {
        t: "RESPONSIVE BUILD",
        d: "주요 디바이스에서 레이아웃과 가독성이 유지되도록 구현합니다.\n모바일 우선으로 핵심 CTA를 보호합니다.",
      },
      {
        t: "CORE PAGES",
        d: "홈, 소개, 서비스, 문의 등 목적에 필요한 페이지를 완성합니다.\n섹션 구성과 콘텐츠 위계를 맞춥니다.",
      },
      {
        t: "CONVERSION WIRING",
        d: "폼, 메일, 비즈니스 문의 등 실제 다음 행동으로 이어지게 연결합니다.\nCTA와 전환 흐름을 설계합니다.",
      },
      {
        t: "SEO & META",
        d: "제목, 설명, OG 등 기본 검색·공유 설정을 포함합니다.\n페이지별 메타와 구조화를 설정합니다.",
      },
      {
        t: "CMS & OPS",
        d: "필요 시 콘텐츠·문구·이미지 교체가 가능한 구조를 만듭니다.\n운영 방식에 맞춰 CMS 범위를 정합니다.",
      },
      {
        t: "DEPLOY & LAUNCH",
        d: "브라우저·디바이스 점검 후 배포합니다.\n도메인 연결과 운영 안내를 전달합니다.",
      },
    ],
    sourcesLabel: "PROJECT INPUTS",
    sourcesTitle: "프로젝트에 활용하는 정보와 자료를 조합합니다.",
    sourcesNote: "기존 사이트, 준비된 자료, 브랜드 자산에 따라 실제 입력은 프로젝트마다 달라집니다.",
    sources: [
      "브랜드·서비스 설명",
      "기존 사이트·콘텐츠",
      "로고·비주얼 자산",
      "브랜드·UI 가이드",
      "참고 사이트·벤치마크",
      "페이지·메뉴 요구",
      "문의·전환 목표",
      "SEO·키워드 방향",
      "다국어·언어 구조",
      "법·개인정보·약관",
      "호스팅·도메인 환경",
      "향후 확장 계획",
    ],
    useLabel: "USE CASES",
    useTitle: "이런 웹을 만들 수 있습니다.",
    useBadge: "구축 가능 예시",
    useCases: [
      {
        t: "COMPANY / STUDIO SITE",
        d: "무엇을 하는 팀인지, 어떤 방식으로 일하는지 선명하게 보여주는 기업 웹.",
      },
      {
        t: "BRAND SITE",
        d: "제품보다 세계관과 톤이 먼저 전달되어야 하는 브랜드 중심 웹.",
      },
      {
        t: "SERVICE LANDING",
        d: "한 제품·캠페인의 가치와 CTA에 집중한 랜딩 페이지.",
      },
      {
        t: "PORTFOLIO / CASE WEB",
        d: "작업물과 과정을 설득력 있게 보여주는 아카이브형 웹.",
      },
      {
        t: "INQUIRY / HIRING HUB",
        d: "협업 문의, 채용, 파트너십 등 전환 목적의 허브 페이지.",
      },
      {
        t: "PRODUCT WEB",
        d: "제품 기능·가격·문의까지 연결된 서비스 소개 웹.",
      },
      {
        t: "MULTILINGUAL SITE",
        d: "언어 구조와 전환 UX를 포함한 다국어 웹.",
      },
      {
        t: "SITE RENEWAL",
        d: "유지할 페이지와 새로 만들 범위를 나눠 진행하는 리뉴얼.",
      },
    ],
    flowLabel: "EXAMPLE WORKFLOW",
    flowTitle: "구조에서 출시까지",
    flow: [
      {
        n: "01",
        t: "DEFINE",
        d: "브랜드 소개인지, 리드 확보인지, 서비스 설명인지 목표를 먼저 맞춥니다.\n방문자 행동과 성공 기준을 정의합니다.",
        examples: ["목적", "방문자", "CTA", "KPI"],
      },
      {
        n: "02",
        t: "STRUCTURE",
        d: "페이지 맵과 섹션 구성을 잡고 콘텐츠 필요 목록을 정리합니다.\n정보 구조와 네비게이션을 확정합니다.",
        examples: ["Sitemap", "IA", "섹션", "콘텐츠"],
      },
      {
        n: "03",
        t: "DESIGN",
        d: "핵심 화면의 비주얼과 타이포 시스템을 확정합니다.\n브랜드 톤과 컴포넌트 규칙을 맞춥니다.",
        examples: ["UI", "타이포", "컴포넌트", "Review"],
      },
      {
        n: "04",
        t: "BUILD",
        d: "반응형 웹으로 구현하고, 인터랙션과 문의 흐름을 연결합니다.\nSEO·메타 설정을 포함합니다.",
        examples: ["Frontend", "Responsive", "Forms", "SEO"],
      },
      {
        n: "05",
        t: "LAUNCH",
        d: "브라우저·디바이스 점검 후 배포하고 운영에 필요한 안내를 전달합니다.\n도메인 연결을 지원합니다.",
        examples: ["QA", "Deploy", "Domain", "Handoff"],
      },
    ],
    reportLabel: "OUTPUT",
    reportTitle: "결과물은 실제 운영 가능한 웹과 문서로 전달합니다.",
    reportLead: "프로젝트 범위에 따라 구성은 달라집니다. 아래는 자주 포함되는 항목 예시입니다.",
    reportMockStatus: "웹 · 구조",
    reportMockK: "Web Site Spec",
    reportMockT: "페이지·섹션·전환 흐름 요약",
    reportItems: [
      "Site Goals & Audience",
      "Sitemap / IA",
      "Page & Section List",
      "UX / UI Overview",
      "Responsive Breakpoints",
      "Form & CTA Wiring",
      "SEO & Meta Setup",
      "CMS / Ops Notes",
      "QA Checklist",
      "Launch & Handoff Notes",
    ],
    dashTitle: "한 화면에서 사이트 구조와 페이지 범위를 공유할 수 있습니다.",
    dashLead: "페이지·섹션·언어·연동을 함께 정리해 범위 합의와 구현 논의가 빨라집니다.",
    dashNote: "페이지 구성과 기능 범위는 사이트 목적과 예산에 따라 달라집니다.",
    dashMetrics: ["Pages", "Sections", "Languages", "Integrations"],
    dashFilters: ["전체", "Core", "Sub", "Global"],
    aiLabel: "ACCELERATION",
    aiTitle: "반복 업무는 자동화하고,\n설계·구현에 집중합니다.",
    aiLead:
      "콘텐츠 구조화, 섹션 초안, SEO 메타, QA 체크리스트 등 반복 작업은 AI 보조로 속도를 높이고, IA·브랜드 UI·핵심 구현에는 사람이 집중합니다.",
    aiExamples: [
      "페이지·섹션 구조 초안",
      "콘텐츠 위계·문구 방향 정리",
      "SEO 제목·설명 초안",
      "반응형 QA 체크리스트",
      "다국어 구조 정리",
      "운영·인수인계 문서 초안",
    ],
    aiNote: "최종 구조·디자인·품질 판단은 프로젝트 팀과 함께 확정합니다.",
    delLabel: "DELIVERABLES",
    delTitle: "프로젝트 완료 후 제공되는 것",
    delLead: "범위에 따라 아래 항목 중 필요한 결과물을 제공합니다.",
    deliverables: [
      { title: "Sitemap / IA Document", body: "사이트 구조와 페이지 역할을 정리합니다." },
      { title: "Designed Key Screens", body: "핵심 화면의 UX/UI 디자인을 완성합니다." },
      { title: "Responsive Web Build", body: "주요 디바이스에서 읽히는 웹을 구현합니다." },
      { title: "Form & CTA Connections", body: "문의·신청 등 다음 행동으로 연결합니다." },
      { title: "Basic SEO Setup", body: "제목·설명·OG 등 기본 검색 설정을 포함합니다." },
      { title: "UX / UI Design Files", body: "디자인 파일과 주요 컴포넌트를 전달합니다." },
      { title: "Deployed Environment", body: "배포된 사이트와 접속 환경을 제공합니다." },
      { title: "CMS Setup (if scoped)", body: "범위에 포함되면 콘텐츠 수정 구조를 구성합니다." },
      { title: "Launch & Ops Guide", body: "출시 후 운영에 필요한 기본 가이드를 전달합니다." },
    ],
    processLabel: "PROCESS",
    processTitle: "목적 정의부터 출시까지.",
    process: [
      {
        n: "01",
        t: "DISCOVERY",
        d: "사이트 목적, 방문자, 현재 자료, 제약을 확인합니다.\n성공 기준과 전환 목표를 파악합니다.",
        examples: ["목적", "방문자", "자료", "KPI"],
      },
      {
        n: "02",
        t: "STRUCTURE",
        d: "페이지 맵, 섹션, 콘텐츠 필요 목록을 정의합니다.\n정보 구조와 네비게이션을 합의합니다.",
        examples: ["Sitemap", "IA", "섹션", "콘텐츠"],
      },
      {
        n: "03",
        t: "DESIGN",
        d: "핵심 화면, 비주얼, 타이포 시스템을 확정합니다.\n브랜드 톤과 컴포넌트를 맞춥니다.",
        examples: ["UI", "타이포", "컴포넌트", "Review"],
      },
      {
        n: "04",
        t: "BUILD",
        d: "반응형 웹으로 구현하고 문의·CTA를 연결합니다.\nSEO·메타와 인터랙션을 포함합니다.",
        examples: ["Frontend", "Forms", "SEO", "Responsive"],
      },
      {
        n: "05",
        t: "QA",
        d: "브라우저·디바이스별 레이아웃과 흐름을 검수합니다.\n전환 경로와 접근성을 확인합니다.",
        examples: ["Desktop", "Mobile", "Forms", "Fixes"],
      },
      {
        n: "06",
        t: "LAUNCH",
        d: "배포하고 도메인을 연결합니다.\n운영·콘텐츠 교체 안내를 전달합니다.",
        examples: ["Deploy", "Domain", "Access", "Guide"],
      },
      {
        n: "07",
        t: "HANDOFF",
        d: "문서·운영 가이드를 전달합니다.\n향후 페이지·기능 확장 경로를 연결합니다.",
        examples: ["Docs", "CMS", "Support", "Phase 2"],
      },
    ],
    scopeLabel: "SCOPE LEVELS",
    scopeTitle: "웹 프로젝트 복잡도를 이해하기 위한 구분입니다.",
    scopeLead: "고정 패키지가 아닙니다. 페이지 수, 디자인 깊이, 다국어·연동 범위에 맞춰 범위를 정합니다.",
    scopes: [
      {
        t: "SINGLE-PAGE",
        items: [
          "단일 랜딩·캠페인 페이지",
          "핵심 섹션 5–8개",
          "반응형 구현",
          "폼·CTA 연결",
          "기본 SEO·배포",
        ],
      },
      {
        t: "MULTI-PAGE SITE",
        items: [
          "홈·소개·서비스·문의 등 복수 페이지",
          "브랜드 맞춤 UI",
          "정보 구조·네비게이션",
          "문의·전환 연결",
          "SEO·배포·도메인 지원",
        ],
      },
      {
        t: "CUSTOM WEB",
        items: [
          "다국어·CMS·연동 포함",
          "복잡 IA·맞춤 기능",
          "리뉴얼·마이그레이션",
          "확장·Phase 2 설계",
          "별도 협의 범위",
        ],
      },
    ],
    timeLabel: "TIMELINE",
    timeTitle: "범위에 따라 일정이 달라집니다.",
    timeLead: "페이지 수, 디자인 깊이, 콘텐츠 준비 상태, 다국어·연동 포함 여부에 따라 기간이 달라질 수 있습니다.",
    timelines: [
      { t: "Single-page", d: "약 2주" },
      { t: "Multi-page site", d: "약 3–5주" },
      { t: "Custom", d: "별도 협의" },
    ],
    priceLabel: "PROJECT COST",
    priceTitle: "필요한 범위만 견적합니다.",
    priceName: "WEB DEVELOPMENT",
    priceValue: "₩700,000부터",
    priceFactorsLabel: "가격 결정 요소",
    priceFactors: [
      "Scope — 페이지·섹션 수",
      "Design depth — UX/UI 범위",
      "Timeline — 일정·리소스",
      "Content — 콘텐츠 준비 상태",
      "Languages — 다국어 구조",
      "Integration — 폼·CRM·API",
      "CMS — 운영·관리 범위",
      "Renewal — 기존 사이트 마이그레이션",
    ],
    priceNote: "페이지 수, Scope, Design depth, Timeline을 검토한 뒤 견적을 제공합니다. 최종 금액은 범위 확정 후 안내합니다.",
    faqLabel: "FAQ",
    faqTitle: "자주 묻는 질문",
    faqs: [
      {
        q: "콘텐츠(문구·이미지)도 작성해주나요?",
        a: "구조와 초안 방향은 함께 잡을 수 있습니다. 최종 브랜드 문장과 자료는 팀과 협의해 반영합니다.",
      },
      {
        q: "기존 사이트를 리뉴얼할 수도 있나요?",
        a: "가능합니다. 유지할 페이지와 다시 만들 범위를 나눠 진행합니다.",
      },
      {
        q: "CMS나 관리자 페이지도 포함되나요?",
        a: "필요 여부에 따라 다릅니다. 운영 방식에 맞춰 범위를 정합니다.",
      },
      {
        q: "다국어 사이트도 가능한가요?",
        a: "가능합니다. 언어 구조와 전환 UX를 포함해 설계합니다.",
      },
      {
        q: "호스팅은 어떻게 하나요?",
        a: "프로젝트에 맞는 배포 방식을 안내하고 연결을 지원합니다.",
      },
      {
        q: "MVP·랜딩과 어떻게 다른가요?",
        a: "WEB DEVELOPMENT는 브랜드·서비스를 설명하는 완성도 높은 웹 구축에 집중합니다. 동작하는 제품 MVP나 캠페인 단일 랜딩은 각각 MVP·LANDING 서비스가 더 적합할 수 있습니다.",
      },
      {
        q: "기밀 유지는 어떻게 하나요?",
        a: "협의된 범위 내에서만 자료를 사용합니다. NDA가 필요하면 체결 후 진행합니다.",
      },
    ],
    finalLabel: "START A PROJECT",
    finalTitle: "브랜드가 선명한\n웹을 만들어보세요.",
    finalLead:
      "만들고 싶은 사이트 유형과 현재 자료만 알려주셔도 됩니다. 웹 범위와 구조·디자인·구현 방식을 함께 확인합니다.",
    ctaFinalSecondary: "BUILD 전체 보기 →",
    ctaFinalSecondaryHref: "../build/",
  },
  en: {
    seoTitle: "WEB DEVELOPMENT | Newon Business",
    metaDescription:
      "High-finish websites for brands and services — company sites, landings, and product web from structure through design, build, and launch. Newon WEB DEVELOPMENT.",
    crumbBusiness: "BUSINESS",
    crumbServices: "SERVICES",
    crumbBuild: "BUILD",
    crumbHere: "WEB",
    eyebrow: "WEB DEVELOPMENT",
    subEyebrow: "BUILD",
    headline: "Polished web for\nbrands and services.",
    lead: "From brand sites and landing pages to product web and service sites — we design and build digital experiences matched to your goal. Information architecture, UI, responsive implementation, SEO, inquiry connections, and deploy in one continuous path.",
    ctaPrimary: "Website project inquiry →",
    ctaSecondary: "See the scope ↓",
    meta: [
      { k: "SERVICE", v: "Web Development" },
      { k: "BEST FOR", v: "Brand & service web builds" },
      { k: "TIMELINE", v: "Usually 2–5 weeks" },
      { k: "PRICE", v: "From ₩700,000" },
    ],
    overviewLabel: "OVERVIEW",
    overviewTitle: "You have a site.\nThe brand doesn't show.",
    overviewBody: [
      "Many teams have a website, but the brand and offer do not read in one glance. Template-like layouts, broken mobile views, and paths that never reach inquiry or conversion are common.",
      "A website is not a dump of information — it is an experience that helps visitors understand the brand and take the next step. Structure, typography, spacing, CTA, responsive layout, and SEO must work together.",
      "WEB DEVELOPMENT starts by defining the site's purpose and visitor actions. Then we design information architecture and brand-fit UI, and deliver a high-finish site including responsive build, inquiry wiring, and launch.",
    ],
    problemsLabel: "PROBLEMS",
    problemsTitle: "Helpful when you face these situations.",
    problems: [
      {
        n: "01",
        t: "NO BRAND PRESENCE",
        d: "You have a site but the brand and service do not read.\nThe layout feels like a template that needs rebuilding.",
      },
      {
        n: "02",
        t: "MOBILE BREAKS",
        d: "Mobile feels broken or hard to scan.\nResponsive structure and information hierarchy need a reset.",
      },
      {
        n: "03",
        t: "NO CONVERSION PATH",
        d: "The story stops at introduction — visitors never reach inquiry, apply, or explore.\nYou need conversion flow design.",
      },
      {
        n: "04",
        t: "SCATTERED CONTENT",
        d: "Many pages but unclear roles and priority.\nInformation architecture needs organizing.",
      },
      {
        n: "05",
        t: "OUTDATED SITE",
        d: "You need to separate what to keep from what to rebuild.\nRenewal or full rebuild is required.",
      },
      {
        n: "06",
        t: "LAUNCH BLOCKED",
        d: "Design exists but implementation, deploy, or domain connection is stuck.\nYou need one partner through launch.",
      },
    ],
    baLabel: "BEFORE / AFTER",
    baTitle: "Information dump vs\na site where the brand reads",
    beforeLabel: "BEFORE",
    afterLabel: "AFTER",
    before: [
      "Template-like layout and inconsistent tone",
      "Layout and readability issues on mobile",
      "Different button and section rules per page",
      "No path from story to inquiry or conversion",
    ],
    after: [
      "Purpose and visitor actions defined first",
      "Brand-fit information architecture and UI",
      "Responsive layout readable on desktop and mobile",
      "Inquiry, CTA, SEO, and deploy connected",
    ],
    capsLabel: "CAPABILITIES",
    capsTitle: "We run web build\nas one structured engagement.",
    caps: [
      {
        t: "GOAL & IA",
        d: "Define site purpose, page roles, and content priority.\nBuild structure that keeps visitors oriented.",
      },
      {
        t: "UX / UI DESIGN",
        d: "Match brand tone, typography, spacing, and components.\nLook like your brand — not a theme.",
      },
      {
        t: "RESPONSIVE BUILD",
        d: "Implement layouts that hold across primary devices.\nProtect core CTA with mobile-first structure.",
      },
      {
        t: "CORE PAGES",
        d: "Complete home, about, services, inquiry — whatever the goal requires.\nAlign sections and content hierarchy.",
      },
      {
        t: "CONVERSION WIRING",
        d: "Wire forms, email, and business inquiry to real next steps.\nDesign CTA and conversion flows.",
      },
      {
        t: "SEO & META",
        d: "Include basic search and share settings — titles, descriptions, Open Graph.\nSet page-level meta and structure.",
      },
      {
        t: "CMS & OPS",
        d: "When needed, build structures that allow later copy and image updates.\nScope CMS to how you want to operate.",
      },
      {
        t: "DEPLOY & LAUNCH",
        d: "QA across browsers and devices, then deploy.\nDeliver domain connection and operating notes.",
      },
    ],
    sourcesLabel: "PROJECT INPUTS",
    sourcesTitle: "We combine the inputs your project needs.",
    sourcesNote: "Actual inputs vary by existing site, available assets, and brand material.",
    sources: [
      "Brand and service description",
      "Existing site and content",
      "Logo and visual assets",
      "Brand and UI guidelines",
      "Reference sites and benchmarks",
      "Page and menu requirements",
      "Inquiry and conversion goals",
      "SEO and keyword direction",
      "Multilingual structure",
      "Legal, privacy, terms",
      "Hosting and domain environment",
      "Future expansion plans",
    ],
    useLabel: "USE CASES",
    useTitle: "Websites we can build.",
    useBadge: "Example site types",
    useCases: [
      {
        t: "COMPANY / STUDIO SITE",
        d: "A clear corporate web that explains who you are and how you work.",
      },
      {
        t: "BRAND SITE",
        d: "World and tone first — when the brand must lead over product.",
      },
      {
        t: "SERVICE LANDING",
        d: "One offer, one story — focused on value and CTA.",
      },
      {
        t: "PORTFOLIO / CASE WEB",
        d: "Work and process presented with clarity and persuasion.",
      },
      {
        t: "INQUIRY / HIRING HUB",
        d: "Partnership, careers, and conversion-focused hub pages.",
      },
      {
        t: "PRODUCT WEB",
        d: "Service introduction connecting features, pricing, and inquiry.",
      },
      {
        t: "MULTILINGUAL SITE",
        d: "Multilingual web with language structure and switching UX.",
      },
      {
        t: "SITE RENEWAL",
        d: "Renewal separating what to keep from what to rebuild.",
      },
    ],
    flowLabel: "EXAMPLE WORKFLOW",
    flowTitle: "From structure to launch",
    flow: [
      {
        n: "01",
        t: "DEFINE",
        d: "Align on outcome — brand story, lead capture, or product explanation.\nDefine visitor actions and success criteria.",
        examples: ["Goal", "Audience", "CTA", "KPIs"],
      },
      {
        n: "02",
        t: "STRUCTURE",
        d: "Set page map, sections, and content needs.\nConfirm information architecture and navigation.",
        examples: ["Sitemap", "IA", "Sections", "Content"],
      },
      {
        n: "03",
        t: "DESIGN",
        d: "Confirm key screens, visual system, and typography.\nAlign brand tone and component rules.",
        examples: ["UI", "Type", "Components", "Review"],
      },
      {
        n: "04",
        t: "BUILD",
        d: "Implement responsive web with interactions and inquiry flow.\nInclude SEO and meta setup.",
        examples: ["Frontend", "Responsive", "Forms", "SEO"],
      },
      {
        n: "05",
        t: "LAUNCH",
        d: "Device checks, deploy, and operating notes.\nSupport domain connection.",
        examples: ["QA", "Deploy", "Domain", "Handoff"],
      },
    ],
    reportLabel: "OUTPUT",
    reportTitle: "Deliverables are an operable website and supporting docs.",
    reportLead: "Composition varies by project scope. Below are common items.",
    reportMockStatus: "WEB · STRUCTURE",
    reportMockK: "WEB SITE SPEC",
    reportMockT: "Pages, sections, conversion flow",
    reportItems: [
      "Site Goals & Audience",
      "Sitemap / IA",
      "Page & Section List",
      "UX / UI Overview",
      "Responsive Breakpoints",
      "Form & CTA Wiring",
      "SEO & Meta Setup",
      "CMS / Ops Notes",
      "QA Checklist",
      "Launch & Handoff Notes",
    ],
    dashTitle: "Share site structure and page scope in one view.",
    dashLead: "Pages, sections, languages, and integrations together speed scope agreement and build discussions.",
    dashNote: "Page composition and feature range vary by site goal and budget.",
    dashMetrics: ["Pages", "Sections", "Languages", "Integrations"],
    dashFilters: ["All", "Core", "Sub", "Global"],
    aiLabel: "ACCELERATION",
    aiTitle: "Automate repetition.\nFocus on design and build.",
    aiLead:
      "Content structuring, section drafts, SEO meta, and QA checklists can be AI-assisted for speed — while people focus on IA, brand UI, and core implementation.",
    aiExamples: [
      "Draft page and section structure",
      "Organize content hierarchy and copy direction",
      "Draft SEO titles and descriptions",
      "Responsive QA checklists",
      "Multilingual structure organization",
      "Ops and handoff doc drafts",
    ],
    aiNote: "Final structure, design, and quality decisions are confirmed with your project team.",
    delLabel: "DELIVERABLES",
    delTitle: "What you receive when the project completes",
    delLead: "We deliver the items below as needed for your scope.",
    deliverables: [
      { title: "Sitemap / IA Document", body: "Site structure and page roles, clearly mapped." },
      { title: "Designed Key Screens", body: "UX/UI for the pages that matter most." },
      { title: "Responsive Web Build", body: "A build that stays readable across devices." },
      { title: "Form & CTA Connections", body: "Forms and CTAs wired to real next actions." },
      { title: "Basic SEO Setup", body: "Titles, descriptions, and basic share meta." },
      { title: "UX / UI Design Files", body: "Design files and key components." },
      { title: "Deployed Environment", body: "A live deployed site ready to access." },
      { title: "CMS Setup (if scoped)", body: "Content edit structure when included in scope." },
      { title: "Launch & Ops Guide", body: "A short guide for launch and ongoing ops." },
    ],
    processLabel: "PROCESS",
    processTitle: "From goal definition to launch.",
    process: [
      {
        n: "01",
        t: "DISCOVERY",
        d: "Confirm site purpose, visitors, current assets, constraints.\nUnderstand success criteria and conversion goals.",
        examples: ["Goal", "Audience", "Assets", "KPIs"],
      },
      {
        n: "02",
        t: "STRUCTURE",
        d: "Define page map, sections, and content needs.\nAgree information architecture and navigation.",
        examples: ["Sitemap", "IA", "Sections", "Content"],
      },
      {
        n: "03",
        t: "DESIGN",
        d: "Confirm key screens, visual system, typography.\nAlign brand tone and components.",
        examples: ["UI", "Type", "Components", "Review"],
      },
      {
        n: "04",
        t: "BUILD",
        d: "Implement responsive web and wire inquiry and CTA.\nInclude SEO, meta, and interactions.",
        examples: ["Frontend", "Forms", "SEO", "Responsive"],
      },
      {
        n: "05",
        t: "QA",
        d: "Verify layout and flow across browsers and devices.\nCheck conversion paths and accessibility.",
        examples: ["Desktop", "Mobile", "Forms", "Fixes"],
      },
      {
        n: "06",
        t: "LAUNCH",
        d: "Deploy and connect domain.\nDeliver operating and content update guidance.",
        examples: ["Deploy", "Domain", "Access", "Guide"],
      },
      {
        n: "07",
        t: "HANDOFF",
        d: "Deliver docs and operating guide.\nConnect path for future pages and features.",
        examples: ["Docs", "CMS", "Support", "Phase 2"],
      },
    ],
    scopeLabel: "SCOPE LEVELS",
    scopeTitle: "How to think about web project complexity.",
    scopeLead: "Not a fixed package. Scope is set by page count, design depth, and multilingual or integration range.",
    scopes: [
      {
        t: "SINGLE-PAGE",
        items: [
          "Single landing or campaign page",
          "5–8 core sections",
          "Responsive implementation",
          "Form and CTA wiring",
          "Basic SEO and deploy",
        ],
      },
      {
        t: "MULTI-PAGE SITE",
        items: [
          "Home, about, services, inquiry — multiple pages",
          "Brand-fit custom UI",
          "Information architecture and navigation",
          "Inquiry and conversion connections",
          "SEO, deploy, domain support",
        ],
      },
      {
        t: "CUSTOM WEB",
        items: [
          "Multilingual, CMS, integrations",
          "Complex IA and custom features",
          "Renewal and migration",
          "Expansion and Phase 2 design",
          "Scoped separately",
        ],
      },
    ],
    timeLabel: "TIMELINE",
    timeTitle: "Timeline depends on scope.",
    timeLead: "Duration varies by page count, design depth, content readiness, and multilingual or integration inclusion.",
    timelines: [
      { t: "Single-page", d: "About 2 weeks" },
      { t: "Multi-page site", d: "About 3–5 weeks" },
      { t: "Custom", d: "Scoped separately" },
    ],
    priceLabel: "PROJECT COST",
    priceTitle: "We quote only the scope you need.",
    priceName: "WEB DEVELOPMENT",
    priceValue: "From ₩700,000",
    priceFactorsLabel: "Pricing factors",
    priceFactors: [
      "Scope — page and section count",
      "Design depth — UX/UI range",
      "Timeline — schedule and resourcing",
      "Content — readiness of copy and assets",
      "Languages — multilingual structure",
      "Integration — forms, CRM, API",
      "CMS — operations and admin scope",
      "Renewal — existing site migration",
    ],
    priceNote: "We review page count, scope, design depth, and timeline, then provide a quote. Final amount is confirmed after scope lock.",
    faqLabel: "FAQ",
    faqTitle: "Frequently asked questions",
    faqs: [
      {
        q: "Do you write copy and provide images?",
        a: "We help with structure and draft direction. Final brand language and assets are aligned with your team.",
      },
      {
        q: "Can you renew an existing site?",
        a: "Yes. We separate what to keep from what to rebuild.",
      },
      {
        q: "Is a CMS included?",
        a: "Only if needed. We scope to how you want to operate the site.",
      },
      {
        q: "Do you support multilingual sites?",
        a: "Yes. Language structure and switching UX are part of the design.",
      },
      {
        q: "What about hosting?",
        a: "We recommend a fit-for-purpose deploy approach and help connect it.",
      },
      {
        q: "How is this different from MVP or landing?",
        a: "WEB DEVELOPMENT focuses on high-finish brand and service sites. A working product MVP or single campaign landing may fit MVP or LANDING services better.",
      },
      {
        q: "How is confidentiality handled?",
        a: "Materials are used only within agreed scope. NDA available when required.",
      },
    ],
    finalLabel: "START A PROJECT",
    finalTitle: "Build a website\nwhere the brand reads clearly.",
    finalLead:
      "Tell us the site type and what you already have. We will confirm web scope and structure, design, and build approach together.",
    ctaFinalSecondary: "View all BUILD →",
    ctaFinalSecondaryHref: "../build/",
  },
};

export function getWebCopy(lang) {
  return lang === "ko" ? WEB_COPY.ko : WEB_COPY.en;
}
